### ISSUE TITLE
Is it possible to sort except the last column?

### ISSUE THREAD

**Issue by pouu69** [react-tools/react-table#1001]
## Is this a general question about implementation, support, api, or anything else?

STOP WHERE YOU ARE and visit https://spectrum.chat/react-table. Your question has likely already been discussed there. If it hasn't, then please post it there. Github issues are no place for the mundane question. They are to be used only for bug tracking.

If you believe you have indeed uncovered a bug, then please proceed!

## What version of React-Table are you using?
- 6.8.2

Your bug may already be fixed in the latest release. Run `yarn upgrade react-table`!
Place your version here...

## What bug are you experiencing, or what feature are you proposing?
The last column is the column for which the sum total is calculated.
So I would like to exclude it when sorting.
Is it possible to sort except the last column?

**Comment by Jefski14** [comment]
I'm not 100% sure i understand your issue, but you can just set the "sortable" property of the specific column definition to ```false```

Your column definitions yould look something like this: 
```
[
    ...
    {
        Header: "ColumnHeaderNotSortable",
        accessor: "accessorNameOfNotSortableColumn",
        sortable: false,
    },
    {
        Header: "ColumnHeader",
        accessor: "accessorName",
    }
    ...
]
```

**Comment by tannerlinsley** [comment]
You can always fully control the sorting just like @Jefski14 mentioned above by passing a sorting array to the `sorted` prop.
