### ISSUE TITLE
Issue in Pagination in pivoted rows.

### ISSUE THREAD

**Issue by codekika** [react-tools/react-table#1002]
The issue is that when you pivot the columns, the rows come by pagination. If (for example) one pivoted row contains (say) 1000 subrows, then the pagination does not occur when you press on the row (ie) The 1000 subrows render with vertical scroll.

**Comment by tannerlinsley** [comment]
For now this is intended. We have not and don't plan on implementing sub-pagination for expanded rows. You can discuss this more on https://spectrum.chat/react-table. Thanks!
