### ISSUE TITLE
trying to switch the icons if the row is expanded

### ISSUE THREAD

**Issue by hijazikaram** [react-tools/react-table#1004]
I am trying to switch the icons if the row is expanded but its not working. It works if I switch from icons to span.

`Expander: ({ isExpanded, ...rest }) =>
          <div>
            {isExpanded
              ? <i className="far fa-plus-square"></i>
              : <i className="far fa-minus-square"></i>}
          </div>`

**Comment by hijazikaram** [comment]
![screen shot 2018-06-07 at 10 33 49 am](https://user-images.githubusercontent.com/9812037/41107016-59453494-6a3f-11e8-8455-9063b9fa886a.png)

**Comment by hijazikaram** [comment]
![screen shot 2018-06-07 at 11 51 59 am](https://user-images.githubusercontent.com/9812037/41111168-406c8896-6a49-11e8-96bf-360fe32537fa.png)

**Comment by hijazikaram** [comment]
Its being changed its not rerendering.

**Comment by tannerlinsley** [comment]
This is an implementation question and would be better asked on our support forum: https://spectrum.chat/react-table. Thanks!
