### ISSUE TITLE
Cannot Render Basic Demo

### ISSUE THREAD

**Issue by trevorwhealy** [react-tools/react-table#1006]
## Package Versions
- "react": "^16.2.0"
- "react-dom": "^16.2.0"
- "react-table": "^6.8.6"

## What bug are you experiencing, or what feature are you proposing?
App breaks on load:

With this error:
![screen shot 2018-06-07 at 10 28 48 am](https://user-images.githubusercontent.com/14946478/41116574-8c45309c-6a3f-11e8-898a-172fa0b45c1a.png)

On this line:
![screen shot 2018-06-07 at 10 29 26 am](https://user-images.githubusercontent.com/14946478/41116573-8c2dadbe-6a3f-11e8-91ed-aed1ece084ef.png)

Using this code: (utils file is unchanged from examples):
Please include a detailed explanation here...
```js
import React from 'react';
import ReactTable from 'react-table';
import {makeData} from './table-utils';

class App extends React.Component {
  constructor() {
    super();
    this.state = {
      data: makeData(),
    };
  }
  render() {
    const {data} = this.state;
    return (
      <div>
        <ReactTable
          data={data}
          columns={[
            {
              Header: 'Name',
              columns: [
                {
                  Header: 'First Name',
                  accessor: 'firstName',
                },
                {
                  Header: 'Last Name',
                  accessor: 'lastName',
                },
              ],
            },
            {
              Header: 'Info',
              columns: [
                {
                  Header: 'Age',
                  accessor: 'age',
                },
              ],
            },
          ]}
          defaultSorted={[
            {
              id: 'age',
              desc: true,
            },
          ]}
          defaultPageSize={10}
          className="-striped -highlight"
        />
        <br />
      </div>
    );
  }
}

export default App;
```

## What are the steps to reproduce the issue?
- `yarn dev`

### Note: 
- I do not have SSR enabled on my application, and the only thing I can think of is that `react-table` might not play nicely with my slightly older versions of React. There appears to be data populated correctly, but that `resolvedData` is `undefined`.

**Comment by tannerlinsley** [comment]
We are currently using CodeSandbox to maintain examples and demo code. If you having the same issue with those, please reopen this issue, otherwise, problems with the packaged demo code are something you can ignore for now. Thanks!
