### ISSUE TITLE
I would like to keep expander state, can you help me 

### ISSUE THREAD

**Issue by bleedtt** [react-tools/react-table#1010]
i have react table with sub table and when sub table's row click, modal comes up.
this is all working but all expander states erased when modal comes over.
because modal component is not inside of table, I think 
I want to expander states remain when modal pops up, and even when modal closed( want to back to exact same expander state. but also can folded. 
i used row clicked to expand row. 
Can you help me to keep my expander information when modal comes over and closes?

{ ... return onClick ... instance.setState({ expanded ... }
<ReactTable // subtable
....
/>
/>
<Popup .. />

**Comment by GuillaumeJasmin** [comment]
Try this:
```
<ReactTable
   ...
   collapseOnDataChange={false}
/>
```

**Comment by bleedtt** [comment]
you saved me !!
