### ISSUE TITLE
Customize Per Page Options

### ISSUE THREAD

**Issue by caktoy** [react-tools/react-table#1013]
I was searching how to customize per page item in pager section in documentation, but I can't find any example of that case.
How I can customize that section? Only per page options?

![pager](https://user-images.githubusercontent.com/6917446/41245114-51d8686c-6dd1-11e8-9ad8-ba54a24ce47e.PNG)

**Comment by tannerlinsley** [comment]
Search `pageSizeOptions` in the documentation :)
