### ISSUE TITLE
Page is outdated and buggy: https://react-table.js.org/#/story/100k-rows-w-pivoting-sub-components

### ISSUE THREAD

**Issue by bean5** [react-tools/react-table#1016]
## What version of React-Table are you using?
6.5.3

## Expected
Table renders enough pages and rows to display 100k rows.

## Actual
Insufficient rows are created in DOM at https://react-table.js.org/#/story/100k-rows-w-pivoting-sub-components

You can multiply pagination pages by number of rows and you get < 2000. The page is supposed to showcase 100k rows!

## Steps to reproduce
1.  https://react-table.js.org/#/story/100k-rows-w-pivoting-sub-components
2.  run it
3. crunch the numbers

## Possible Reason
1. Version is oudated
2. A bug exists

**Comment by tannerlinsley** [comment]
The rows are pivoted into groups, thus creating less initially visible rows and pages. If all of the pivoted rows were expanded, you would see it is indeed 100k rows.
