### ISSUE TITLE
Change indicator sort table

### ISSUE THREAD

**Issue by erb4f1dotama** [react-tools/react-table#1017]
How can i to change indicator sorted table, arrow up/down??

**Comment by eramit2010** [comment]
You can override style of -sort-asc and -sort-decs and add box-shadow: none to remove existing style and add your own arrow style with ::before.

**Comment by erb4f1dotama** [comment]
can you give me an example please?

**Comment by eramit2010** [comment]
this is what i have done in my code.

`div.-sort-desc {
    padding-right: 20px !important;
    box-shadow: none !important;
    ::before {
      content: "\25B2";
      position: absolute;
      right: 5px;
      top: 5px;
    }
  }`
