### ISSUE TITLE
React Table is not working in IE11

### ISSUE THREAD

**Issue by neerender** [react-tools/react-table#1025]
## What version of React-Table are you using?
6.8.6

## What bug are you experiencing, or what feature are you proposing?
React table is not working in IE 11.
Even the examples given in the site(https://react-table.js.org/#/story/simple-table  ) are not opening in IE11, but Its working fine in Chrome, Edge.

Error: Error: Object doesn't support property or method 'find'

## What are the steps to reproduce the issue?
1.  Open the site (https://react-table.js.org/#/story/simple-table) in IE11
2.  Throws the error "Error: Object doesn't support property or method 'find'" 
3.  Site is not opening.

Even i have the  issue in IE 11 with the SharePoint framework webpart with React Table.
this working fine in Chrome, Edge.

Could you please help me .

**Comment by mikedevita** [comment]
pretty sure you need a shim with IE11, [this](https://github.com/AllenFang/react-bootstrap-table/issues/1404) patch may work...

**Comment by neerender** [comment]
Thanks for your response.
Can you please let me know how to apply this Polyfill for IE 11?
I'm using SharePoint framework, I have installed below ones
- npm install --save babel-polyfill
- npm i @microsoft/sp-polyfills

Its everything is working fine including Chrome, Edge and mobile except IE11
this is stopping me for pushing to production
Could you please explain the steps how to implement the polyfill for my case
Environment:
 - SharePoint framework, React table

**Comment by varzaman** [comment]
You need to make sure you're actually using babel.

Here are the docs.

https://babeljs.io/docs/en/babel-polyfill.html

Babel needs to be the first thing at the entry point of your project.

For example, I'm using webpack, so in my webpack config I have

```
entry: { 'main': ['babel-polyfill', 'react-hot-loader/patch', 'react', 'react-dom', './ClientApp/boot.tsx'] }
```

This will load the babel-polyfill package before everything else, and then continue loading in the above order. Boot.tsx is my main js file that starts the application.

**Comment by neerender** [comment]
The issue has been resolved after importing the below one's
import 'core-js/es6/number';
import 'core-js/es6/array';

The  steps mentioned in the previous thread might need for the typical react app.
In my case its SharePoint framework app created with react framework, seems the babel are loaded already. but not sure babel-polyfil is required for this, its working fine for me without importing babel-polyfill.

so the resolution would be just import the below one's in client side webpart, that  would resolve the issue.

import 'core-js/es6/number';
import 'core-js/es6/array';

Thanks everyone for your support.

**Comment by tannerlinsley** [comment]
This feature/issue has been tagged as one that will likely be fixed or improved in the next major release of React-Table. This release is expected to be completed in the next 6 - 8 months. Please see #1143 for more detail. If you believe this feature can be easily fixed, we invite you to fork the project, attempt the fix, and use it until the latest version is available. If the fix is simple enough, we will also consider it as a PR to the current version.
