### ISSUE TITLE
where is the original css file/source in the folder?

### ISSUE THREAD

**Issue by adamchenwei** [react-tools/react-table#1046]
## What version of React-Table are you using?

latest

## What bug are you experiencing, or what feature are you proposing?

I can only see the css file in a project's node_modules folder, but I can't find css or its source in the repo itself. where is it? I want to customize the whole css myself
## What are the steps to reproduce the issue?

1.  clone the repo
2. see no css file or css source files

**Comment by Meera-Srinivasan** [comment]
yeah, i'd like to know this too.
