### ISSUE TITLE
How to use defaultFilter when we have array of values to filter

### ISSUE THREAD

**Issue by vivek7890** [react-tools/react-table#1052]
Hi,
I need to filter data initially to show the data first time. I can see the issue #355, here we have sent a single key and value to filter data initially. I have an array of key and values for the same column to filter data for initial rendering. How should I do it?
Here is my code -
```
<ReactTable
        data={makeData()}
        columns={columns}
	filterable
	defaultFiltered={[
				    {
					id: 'lastName',
					value: 'fan'
				    },
				    {
					id: 'lastName',
					value: 'babies'
				    }
			        ]}
/>
```

Thanks

**Comment by bogutski** [comment]
Filter data before pass it to React-table
