### ISSUE TITLE
SubComponent Does Not Show Row Data

### ISSUE THREAD

**Issue by skellman** [react-tools/react-table#1079]
## Is this a general question about implementation, support, api, or anything else?

STOP WHERE YOU ARE and visit https://spectrum.chat/react-table. Your question has likely already been discussed there. If it hasn't, then please post it there. Github issues are no place for the mundane question. They are to be used only for bug tracking.

If you believe you have indeed uncovered a bug, then please proceed!

## What version of React-Table are you using?
Latest

Your bug may already be fixed in the latest release. Run `yarn upgrade react-table`!
Just installed today

## What bug are you experiencing, or what feature are you proposing?

Please include a detailed explanation here...

## What are the steps to reproduce the issue?

1.  Go to your examples page (https://react-table.js.org/#/story/sub-components)
2.  Change line 74 to say data={Array.from(row)}
3.  Expand the row

import React from "react";
import { render } from "react-dom";
import { makeData, Logo, Tips } from "./Utils";

// Import React Table
import ReactTable from "react-table";
import "react-table/react-table.css";

const columns = [
  {
    Header: "Name",
    columns: [
      {
        Header: "First Name",
        accessor: "firstName"
      },
      {
        Header: "Last Name",
        id: "lastName",
        accessor: d => d.lastName
      }
    ]
  },
  {
    Header: "Info",
    columns: [
      {
        Header: "Age",
        accessor: "age"
      },
      {
        Header: "Status",
        accessor: "status"
      }
    ]
  },
  {
    Header: "Stats",
    columns: [
      {
        Header: "Visits",
        accessor: "visits"
      }
    ]
  }
];

class App extends React.Component {
  constructor() {
    super();
    this.state = {
      data: makeData()
    };
  }
  render() {
    const { data } = this.state;
    return (
      <div>
        <ReactTable
          data={data}
          columns={columns}
          defaultPageSize={10}
          className="-striped -highlight"
          SubComponent={row => {
            return (
              <div style={{ padding: "20px" }}>
                <em>
                  You can put any component you want here, even another React
                  Table!
                </em>
                <br />
                <br />
                <ReactTable
                  **data={Array.from(row)}**
                  columns={columns}
                  defaultPageSize={3}
                  showPagination={false}
                  SubComponent={row => {
                    return (
                      <div style={{ padding: "20px" }}>
                        Another Sub Component!
                      </div>
                    );
                  }}
                />
              </div>
            );
          }}
        />
        <br />
        <Tips />
        <Logo />
      </div>
    );
  }
}

render(<App />, document.getElementById("root"));

**Comment by tannerlinsley** [comment]
This feature/issue has been tagged as one that will likely be fixed or improved in the next major release of React-Table. This release is expected to be completed in the next 6 - 8 months. Please see #1143 for more detail. If you believe this feature can be easily fixed, we invite you to fork the project, attempt the fix, and use it until the latest version is available. If the fix is simple enough, we will also consider it as a PR to the current version.
