### ISSUE TITLE
Show dummy data when cell has no data.

### ISSUE THREAD

**Issue by alankar-anand** [react-tools/react-table#1080]
When the accessor returns null value, there should be a way to set up a dummy data in the cell.
Something like this:
       { 
          Header: 'Name',
          accessor: 'name' || '----'
        },

**Comment by calebnelson** [comment]
You can make the column something like
```
{
  Header: 'Name',
  accessor: 'name
  Cell: props => {
    return (<span>{props.name || '----' }</span>); 
  },
}
```
in order to implement this.

**Comment by alankar-anand** [comment]
Thanks.
I figured out the change in the code as well.

in file react-table.js line 794:

`row[column.id] = column.accessor(d) || '---';`

This change makes it '---' by default.
