### ISSUE TITLE
Overwritable classes - Adds support for CSS-modules

### ISSUE THREAD

**Issue by jakeclements** [react-tools/react-table#1089]
## The problem
I would like to use react-table but my build tools require locally scoped css-modules with hashed classnames. The react-table component currently relies on global css.

## The solution
Include an optional `classNames` prop that allows the consumer of react-table to overwrite the internal classnames. The classNames prop will be merged with the current classnames to allow this to be a non-breaking change.

### Example
```javascript
<ReactTable
    classNames={{
        // 'ReactTable': '',
        // 'hidden': '',
        // 'rt-expandable': '',
        // 'rt-header-pivot': '',
        // 'rt-pivot': '',
        'rt-resizable-header': 'overwritten-resizable-header-classname',
        // 'rt-resizable-header-content': '',
        // 'rt-resizing': '',
        // '-cursor-pointer': '',
        // '-filters': '',
        // '-header': '',
        // '-headerGroups': '',
        // '-hidden': '',
        // '-padRow': '',
        // '-pagination': '',
        // '-even': '',
        // '-odd': '',
        // '-sort-desc': '',
        // '-sort-asc': '',
    }}
/>
```

After merge the classnames used internally would be;
```javascript
[
    'ReactTable',
    'hidden',
    'rt-expandable',
    'rt-header-pivot',
    'rt-pivot',
    'overwritten-resizable-header-classname',
    'rt-resizable-header-content',
    'rt-resizing',
    '-cursor-pointer',
    '-filters',
    '-header',
    '-headerGroups',
    '-hidden',
    '-padRow',
    '-pagination',
    '-even',
    '-odd',
    '-sort-desc',
    '-sort-asc'
]
```
It would be up to the consumer of react-table to ensure `.overwritten-resizable-header-classname` is a provided style.

## Where's the PR then?
I'd like to gauge interest in this before creating a PR for this feature. At the time of this issue there are a number of PRs failing linting. There's a solution to this in https://github.com/react-tools/react-table/pull/1073 that's been awaiting review for 13 days.

This is not meant to be critical of the codeowners, I understand that OS is a large commitment but while the build is failing adding another non-essential PR for review does little more than add noise.

**Comment by tannerlinsley** [comment]
This feature/issue has been tagged as one that will likely be fixed or improved in the next major release of React-Table. This release is expected to be completed in the next 6 - 8 months. Please see #1143 for more detail. If you believe this feature can be easily fixed, we invite you to fork the project, attempt the fix, and use it until the latest version is available. If the fix is simple enough, we will also consider it as a PR to the current version.
