### ISSUE TITLE
Snapshots are being written differently in OSX and Unix

### ISSUE THREAD

**Issue by shirbr510** [react-tools/react-table#1090]
## What version of React-Table are you using?

6.8.6

## What bug are you experiencing, or what feature are you proposing?

I have a private repo that I'm maintaining that uses react-table.
I am also using jest as my snapshot testing tool.

a few weeks ago, I started getting some failures about an invalid snapshot:

```
Received value does not match stored snapshot "CustomTable renders without crash 1".
15:55:58 
15:55:58     - Snapshot
15:55:58     + Received
15:55:58 
15:55:58     @@ -15,11 +15,11 @@
15:55:58           >
15:55:58             <div
15:55:58               className="rt-tr"
15:55:58             >
15:55:58               <div
15:55:58     -           className=" -cursor-pointer rt-th"
15:55:58     +           className="-cursor-pointer rt-th"
15:55:58                 onClick={[Function]}
15:55:58                 style={
15:55:58                   Object {
15:55:58                     "flex": "100 0 auto",
15:55:58                     "maxWidth": null,
15:55:58     @@ -32,11 +32,11 @@
15:55:58                 >
15:55:58                   Type
15:55:58                 </div>
15:55:58               </div>
15:55:58               <div
15:55:58     -           className=" -cursor-pointer rt-th"
15:55:58     +           className="-cursor-pointer rt-th"
15:55:58                 onClick={[Function]}
15:55:58                 style={
15:55:58                   Object {
15:55:58                     "flex": "100 0 auto",
15:55:58                     "maxWidth": null,
15:55:58 
15:55:58       50 |         );
15:55:58       51 |         let tree = component.toJSON();
15:55:58     > 52 |         expect(tree).toMatchSnapshot();
15:55:58          |                      ^
15:55:58       53 |     });
15:55:58       54 | 
```

this snapshot is invalid due to a tiny whitespace that is added while rendering react table.
apparently, it renders differently on local and CI machines (jenkins on linux servers to be precise).

I have found a similar issue on jest's repository (https://github.com/facebook/jest/issues/6450) but it seems like it is not truly the solution and that something should be done on your end as well.

**Comment by tannerlinsley** [comment]
This feature/issue has been tagged as one that will likely be fixed or improved in the next major release of React-Table. This release is expected to be completed in the next 6 - 8 months. Please see #1143 for more detail. If you believe this feature can be easily fixed, we invite you to fork the project, attempt the fix, and use it until the latest version is available. If the fix is simple enough, we will also consider it as a PR to the current version.
