### ISSUE TITLE
Declare module 'react-table'; for tsx file importing

### ISSUE THREAD

**Issue by gnanaveln** [react-tools/react-table#1091]
Try to use in the below github implementation 07 Form code.

https://github.com/Lemoncode/react-typescript-samples

## What are the steps to reproduce the issue?

1. npm install react-table

2. import ReactTable from "react-table";

getting the below error when import the react table in about.tsx file.

**[ts]
Could not find a declaration file for module 'react-table'. 'd:/Workout/react/react-typescript-samples/07 Form/node_modules/react-table/lib/index.js' implicitly has an 'any' type.
  Try `npm install @types/react-table` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-table';`**

**Comment by gnanaveln** [comment]
'npm install @types/react-table' thru this it is working now,

**Comment by akhilaravind** [comment]
its not working with the latest version as of 2024 Jan
