### ISSUE TITLE
Cannot get rows data

### ISSUE THREAD

**Issue by lazarencomihai** [react-tools/react-table#1095]
I have a objects like this obj = { '[name].[id]' = value} where '[name].[id]' is a string (example [Rick].[40]) . 

Then i try to get the values with the accessors by this string i cannot get the value so i get empty cells but i can get the cells for strings like "Id" and "Order".

**Comment by DamianFekete** [comment]
I guess you're not using a custom accessor. 
Try with
 ```js
accessor: d => d['[Rick].[40]']
```
instead of
```js
accessor: '[Rick].[40]'
```
which I guess will try to access 
```js
d['[Rick]']['[40]']
``` 
I'm not sure if the square brackets have a special meaning, but the dot sure has.

**Comment by tannerlinsley** [comment]
☝️ Yep!
