### ISSUE TITLE
React table hover functionality

### ISSUE THREAD

**Issue by nevetushar** [react-tools/react-table#1101]
I've react-table which contains some information on rows. 
I want to implement the functionality like when I hover over any row then it should display the floating delete button. (so that when clicks on the button row would be deleted and delete button only show when I hover on the table row)

Is there any way to achieve this using react-table or any code sample of above problem?

Thanks, in advance.

**Comment by lomo009** [comment]
+1

**Comment by nicolasletoublon** [comment]
+ 1 
We do need a way to act on the components in the row if the row is hovered. So doing it only by hiding/ showing a button is not enough :/

**Comment by AshotN** [comment]
You could do this with CSS

**Comment by tannerlinsley** [comment]
This feature/issue has been tagged as one that will likely be fixed or improved in the next major release of React-Table. This release is expected to be completed in the next 6 - 8 months. Please see #1143 for more detail. If you believe this feature can be easily fixed, we invite you to fork the project, attempt the fix, and use it until the latest version is available. If the fix is simple enough, we will also consider it as a PR to the current version.

**Comment by PaulRBerg** [comment]
FWIW, this now seems to be available if you set the class name of the React Table to `-highlight`.

**Comment by francoisihry** [comment]
Hi, 

I am currently looking for that functionality. I could not find an example though.

Do you have a sample code example on how to achieve it please ?

**Comment by vadimyen** [comment]
Any updates?

**Comment by samnoyes** [comment]
Can't really close this as completed until its actually completed... which it seems that it is not.

**Comment by KevinVandy** [comment]
> Can't really close this as completed until its actually completed... which it seems that it is not, five years later.

This kind of functionality is not really core to TanStack Table right now and won't be a built in feature, but it's still easy enough to add your own state and mouse enter events alongside TanStack Table.

**Comment by igalklebanov** [comment]
If anyone's interested in a programmatic (not CSS) approach to this.. 🤷 
https://github.com/igalklebanov/tanstack-table-hovering
