### ISSUE TITLE
Allow `defaultSorted` to use data properties, not just row properties

### ISSUE THREAD

**Issue by fastfedora** [react-tools/react-table#1104]
I'm using react-table v6.8.6.

What I'd like to do is have the table sorted by default using a property in my data that I don't want to show in the table. Specifically in this case `createdAt`, though I have another use case where I'll be doing something similar with `viewOrder`. 

Adding `defaultSorted={[ { id: 'createdAt', desc: true } ]}` only works when I have a column defined with an ID of `createdAt`. If I remove the column definition, the sort function is passed undefined values. From what I gather, the sort `id` is the name of the property from the row, not the original data.

If there was a way to reference the original data row in the sort expression, that would be ideal. 

For instance, something like `defaultSorted={[ { id: 'original.createdAt', desc: true } ]}`. To avoid conflict with existing properties, the `original` property could be prefixed: `.original.createdAt` or `@original.createdAt`, for example.

Or an additional property could be added to the sort options that would specify the data property instead of the row property: `defaultSorted={[ { dataId: 'createdAt', desc: true } ]}`.

For now, I'm pre-sorting the data before I pass it into `react-table`, but this splits the logic of where my sorting is occurring, and makes it more confusing what's going on in the code.

**Comment by panuhorsmalahti** [comment]
I agree. The `sortMethod` is called with formatted/accessed values, not the original row, which can make sorting really difficult. For example, if the table shows localized values, I would have to un-localize the parameters and then sort them.

A work-around is to have the `accessor` return a `JSX.Element` and then use the `props` property in the `sortMethod`. This is clearly not ideal.

**Comment by tannerlinsley** [comment]
This feature/issue has been tagged as one that will likely be fixed or improved in the next major release of React-Table. This release is expected to be completed in the next 6 - 8 months. Please see #1143 for more detail. If you believe this feature can be easily fixed, we invite you to fork the project, attempt the fix, and use it until the latest version is available. If the fix is simple enough, we will also consider it as a PR to the current version.
