### ISSUE TITLE
Override 'No rows found' message with a custom message

### ISSUE THREAD

**Issue by monarajhans** [react-tools/react-table#1115]
When there are no rows in the dataset to generate a table, it shows the message 'No rows found'. How can I override this message to be a custom message? 

![screen shot 2018-09-04 at 4 27 14 pm](https://user-images.githubusercontent.com/12970128/45062782-6785be00-b05f-11e8-9e94-e4567ea62bfa.png)

**Comment by monarajhans** [comment]
Closing this as I found it in the documentation :)

**Comment by The-Code-Monkey** [comment]
where was it in the docs

**Comment by monarajhans** [comment]
@The-Code-Monkey Check "noDataText" attribute in the [docs](https://github.com/react-tools/react-table). It is just a string which is set to a value. You can pass whatever custom string value in here.

**Comment by UtkarshSapiens** [comment]
was this attribute of noDataText removed in recent versions?
