### ISSUE TITLE
Expanded state based on row data

### ISSUE THREAD

**Issue by cipacda** [react-tools/react-table#1119]
It would be nice to be able to store expanded rows based on row data (ideally a row id if such exists). This would be really helpful if we want to store user preferences on expanded rows or dynamically expand a row based on a pivot value.

At the moment it seems that expanded state is stored based on row indices, but these are not unique to the rows and they change as the sorting changes in the table for example. 

Would such an improvement be possible? 

Using React 16.4.6
Using react-table 6.7.11

-------
We could add a new prop, a function returning a string from the row value and if this is set we should change this code (line 466 in index.js) to use that accessor instead of the row index?

```
const rowInfo = {
        original: row[originalKey],
        row,
        index: row[indexKey],
        viewIndex: (rowIndex += 1),
        pageSize,
        page,
        level: path.length,
        **nestingPath: path.concat([i]),**
        aggregated: row[aggregatedKey],
        groupedByPivot: row[groupedByPivotKey],
        subRows: row[subRowsKey],
      }
```

**Comment by tannerlinsley** [comment]
This feature/issue has been tagged as one that will likely be fixed or improved in the next major release of React-Table. This release is expected to be completed in the next 6 - 8 months. Please see #1143 for more detail. If you believe this feature can be easily fixed, we invite you to fork the project, attempt the fix, and use it until the latest version is available. If the fix is simple enough, we will also consider it as a PR to the current version.

**Comment by cobyrne09** [comment]
@tannerlinsley what is the best solution for this in v6?

**Comment by gajus** [comment]
@tannerlinsley Hi, can you please advise what is the solution in v6 if any and if this is addressed in v7?

**Comment by tannerlinsley** [comment]
v6 I'll admit was very difficult to do this and honestly I wouldn't even advise attempting it. v7 on the other hand, is built to handle this easily. You can read the documentation in the readme for the `useExpanded` hook , or look at the [Expanding - Client Side Example](https://codesandbox.io/s/github/tannerlinsley/react-table/tree/master/examples/expanding-client-side)

**Comment by gajus** [comment]
Off-topic to this conversation, but it would be nice if v7 came with v6 theme. Lack built-in/ available ready-made styles is the primary reason for not migrating at the moment.

**Comment by tannerlinsley** [comment]
It's on my list for sure.
