### ISSUE TITLE
Is this repo dead?

### ISSUE THREAD

**Issue by ljmerza** [react-tools/react-table#1124]
No merges have been made since May and the build fails.  I don't see any announcements.

**Comment by tannerlinsley** [comment]
I have. Concerning v7 and that it is actively being developed.

**Comment by ljmerza** [comment]
Where? Adding this to the readme would help.

**Comment by tannerlinsley** [comment]
It was only a few days ago via twitter (the code isn’t even located in git yet). When the code is ready for contributions, I’ll make a v7 branch and add a link to it in the master readme.

**Comment by ljmerza** [comment]
Okay. It's a great library so thank you for the time you put into it.
