### ISSUE TITLE
Odd vs. Even striped rows option.

### ISSUE THREAD

**Issue by caravinci** [react-tools/react-table#1134]
## Is this a general question about implementation, support, api, or anything else?

No, it is a feature request, I guess. Definitely not a bug.

## What version of React-Table are you using?

6.8.6

## What bug are you experiencing, or what feature are you proposing?

Adding `-striped` alternates the background colouring of rows, greying out odd ones.
There could be `-evenly-striped` vs. `-oddly-striped`  classes, that let the users easily choose which rows to grey out. I may be able to open a PR later for this, but perhaps this is an easy add for someone better versed on the inner workings of the module.

**Comment by simjoh** [comment]
This could be done by styling instead of adding unnecessary props.

**Comment by tannerlinsley** [comment]
We will not be adding props for this feature. Please see #1143
