### ISSUE TITLE
Resize Columns not working in a new window

### ISSUE THREAD

**Issue by GoChartingAdmin** [react-tools/react-table#1144]
**Describe the bug**
The resize column feature works perfectly in the parent window.  However the same feature does not work properly when the table is rendered in  child window

**To Reproduce**
1. Go to https://dev.gocharting.com/terminal/IN/CRYPTO/BTC%7CUSD/Coinbase
2. Click on "Show Me All Markets" button in the first tab of the left hand navigation panel 
3. A dock will appear from right and you can see a react table.  The resize column feature works beautifully 
4. Now click on the small popout window icon on the top right corner of the dock.  A new window will open with the react table in it.  Now the resize column feature does not work

**Expected behavior**
The resize column feature should work when the table is rendered in a child window

**Screenshots**
Click on the "Show Me All Markets" GREEN button on the left
![image](https://user-images.githubusercontent.com/20324844/46521710-ba31e000-c880-11e8-81ac-e7de0c9c32c2.png)

Resize Column Working Fine in Parent Window
![image](https://user-images.githubusercontent.com/20324844/46521683-a25a5c00-c880-11e8-8a4d-b36cb1a19ea1.png)

Now click on the popout icon and the new table in a new window will appear.  Resize column does not work in this new window

![image](https://user-images.githubusercontent.com/20324844/46521738-d7ff4500-c880-11e8-9289-d6dfa1bde47c.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Browser [e.g. chrome, safari]  Chrome

And thank you for the library

**Comment by GoChartingAdmin** [comment]
I will try and share a codesandbox soon

**Comment by tannerlinsley** [comment]
Please reopen with the link to the sandbox :)
