### ISSUE TITLE
Trying to access the cell CSS style conditionally.

### ISSUE THREAD

**Issue by Ashish1857** [react-tools/react-table#1145]
### I have declared the column as:

 const columns = [
      {
        Header: (
          <span>
            {" "}
            {"Supplier Name"}
            {this.props.supplierNameRequired ? (
              <span className="requiredAsterisk">{" *"}</span>
            ) : (
              ""
            )}
          </span>
        ),
        accessor: "name",
        id: "cellT01",
        className: "cellT01",
        headerClassName: "cellH01",
        Cell: this.renderEditable,
        sortable: true,
        style: {
          color: "#42b4ee",
          align: "left",
          maxwidth: "100%"
        }
      },
      {
        Header: (
          <span>
            {" "}
            {"CDA/NDA In Place?"}
            {this.props.cdaNdaRequired ? (
              <span className="requiredAsterisk">{" *"}</span>
            ) : (
              ""
            )}
          </span>
        ),
        Id: "CDA/NDA In Place?",
        //accessor: "inputData",
        Cell: this.renderCDA_NDAEditable,
        className: "cellT03",
        sortable: false,
        headerClassName: "cellH03",
      },
      {
        Header: (
          <span>
            {" "}
            {"CDA/NDA Signature Date"}
            {this.props.signatureDateRequired ? (
              <span className="requiredAsterisk">{" *"}</span>
            ) : (
              ""
            )}
          </span>
        ),
        Id: "CDA/NDA Signature Date",
        //accessor: "dateData",
        sortable: false,
        Cell: this.CDA_NDASignatureDate,
        className: "cellT04",
        headerClassName: "cellH04"
      },
      {
        Header: (
          <span>
            {" "}
            {"CDA/NDA Termination Date"}
            {this.props.terminationDateRequired ? (
              <span className="requiredAsterisk">{" *"}</span>
            ) : (
              ""
            )}
          </span>
        ),
        Id: "CDA/NDA Termination Date",
        //accessor: "terminationDate",
        sortable: false,
        Cell: this.CDA_NDATerminationDate,
        className: "cellT05",
        headerClassName: "cellH05"
      },
      {
        Header: (
          <span>
            {" "}
            {"Supplier Financial Review"}
            {this.props.financialReviewRequired ? (
              <span className="requiredAsterisk">{" *"}</span>
            ) : (
              ""
            )}
          </span>
        ),
        Id: "Supplier Financial Review",
        //  accessor: "review",
        sortable: false,
        Cell: this.supplierFinancialReview,
        className: "cellT06",
        headerClassName: "cellH06"
      }
    ];

Now Taking example of column 2:    {"CDA/NDA In Place?"}
this is the cell render function:
  renderCDA_NDAEditable = cellInfo => {
    let supplier = this.props.supplierData;
    return (
      <div>
        <Select
          options={this.props.cda_ndaOptions}
          searchable={false}
          onChange={e => this.cda_ndaOnChange(e, cellInfo)}
          value={supplier[cellInfo.index].cda_nda}
          placeholder={this.props.cda_ndaPlaceholder}
        />
      </div>
    );
  };
  cda_ndaOnChange = (selectedOption, cell) => {
    if (selectedOption != null) {
      let supplierData = this.props.supplierData;
      supplierData[cell.index].cda_nda = selectedOption;
      this.setState({
        supplierData
      });
    }
  };

so this will generate the specified column for each supplier,
The issue is , I have to access the particular cell's css conditionally, let's say if i have no value in this particular column for 3rd row.Then when i call my save button it will look into the supplier object if the particular supplier has no nda/cda value selected then the border of that cell will become red.

please help as i am stuck in middle of my work.

**Comment by simjoh** [comment]
I don't think I fully underastand the problem but regarding conditionally rendering you can do. 

```
                    Cell:row=>{if(row.WHATEVER==SOMETHINGELSE){ 
                                           return<p style={{}}>row.id</p>
                                       }
                                       else{
                                            return <p>Something</p>}
                                       }

```
And the lack of formatting makes the code impossible to read.
