### ISSUE TITLE
Resizability

### ISSUE THREAD

**Issue by gnir-work** [react-tools/react-table#1146]
Hey, 
I happened to stumble upon an interesting use case.
What if i want to change the size of my table?
For example at first my data contained only 2 items and after some kind of user interaction it changed to 30 items. 
I would like it if the table could change its size (By size I mean number of rows).
I can open a PR with this functionality if you would like.

I have read the discussion about the future of `react-table` however i think that this is part of the logically part and not the UI.

What do you guys think?

**Comment by tannerlinsley** [comment]
I'm not sure I understand. You can already change the number of rows being
displayed with the current API, no?

**Comment by tannerlinsley** [comment]
No worries! Hey to help. And thanks!
