### ISSUE TITLE
React-Table crashes browser/devtools with dynamic columns

### ISSUE THREAD

**Issue by anthonychung14** [react-tools/react-table#1147]
**Describe the bug**
This is more of a performance question that I have already raised in the forums.
In tables of more than 300 rows and 13 columns, React-Table will
1. Crash React dev tools (if it is open)
2. Take a 3-4 second lag to show/hide columns
3. UI is unresponsive in the meantime

https://spectrum.chat/?t=80a7dd6a-715d-41f4-9e9a-aedcc1ce3fa2

I am highlighting this as a bug to the creators for visibility and because your understanding of the library will be helpful in either
- Making the performance bearable
- Providing feedback about the scalability of the tool

**To Reproduce**
1. Create a table with the aforementioned dimensions (300 x 13)
2. Implement Show/Hide in the following manner
- Event handler for show/hide in header-cell
- Parent component's state toggles: `showColumn: true`
- React-Table recalculates column props
- React-Table ALSO recalculates data-prop

**Expected behavior**
I expect React-Table to leave the `data` prop unchanged since no values have changed

As I write this, it has occurred to me that React (and React-Table) will consider the new and old data props to be different object references (without doing an equality check).

If this is true, do the creators have any recommendations around how to work around this issue?

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: Chrome
 - Version: 6.8.6

**Comment by anthonychung14** [comment]
To add: our designer is against pagination. Another idea I have is using `react-list` to virtualize the rows so less are being rendered to the UI

**Comment by tannerlinsley** [comment]
The `data` prop is not designed to be an inline array, but instead an immutable one (usually cached and updated via component state, or through some other immutable library). If the `data` prop changes, it kicks off a rather tedious process of updating the internal data model, sorting, filtering, layout, and ultimately the rendering of the table. 

Another thing to note is that react-table was intentionally designed to be used with pagination. If you require long lists of rows, you should look into virtualizing the rows in a scrollable viewport, or simply using a different tool that is meant for that altogether.
