### ISSUE TITLE
Custom pagination

### ISSUE THREAD

**Issue by mellis481** [react-tools/react-table#1150]
I didn't see the ability to control the appearance of the pager.  I'm more interested in a Bootstrap-style pager.  Eg.

![image](https://user-images.githubusercontent.com/39313898/46763078-dda4c280-cca6-11e8-97f7-298188dd2070.png)

Is that something currently do-able with react-table?

**Comment by alexkindel** [comment]
You can customize the Pagination using Component Overrides, here's a quick example:

```javascript
<ReactTable
  ...
  PaginationComponent={Pagination}
/>
```

```javascript
class Pagination extends React.Component {
  render = () => {
    return (
      <div>
        You are on page {this.props.page + 1} of {this.props.pages}.
      </div>
    );
  };
}
```

**Comment by mellis481** [comment]
@alexkindel Awesome. Thanks!  I'm using Typescript.  What is the type of `props` the Pagination Component uses?

**Comment by ankitkadali** [comment]
I am passing the customPagination in the same manner as above; but i am facing a warning message of Failed prop type: Invalid prop `PaginationComponent` supplied to `ReactTable`.
Any idea what can be the cause
