### ISSUE TITLE
filterValue doesn't work in IE

### ISSUE THREAD

**Issue by Arpitha18** [react-tools/react-table#1156]
**Describe the bug**
filterValue internally is depended on `startwith` implementation which is not available in IE
**To Reproduce**

const data = [
  {
    firstName: "Vernell",
    lastName: "Feher",
    visits: 1,
    employee: "true"
  },
  {
    firstName: "Meridith",
    lastName: "Westerlund",
    visits: 2,
    employee: "true"
  },
  {
    firstName: "Vada",
    lastName: "Rabideau",
    visits: 1,
    employee: "true"
  }
];

const columns = [
  {
    header: "First Name",
    accessor: "firstName",
    filterValue: "Mer"
  },
  {
    header: "Last Name",
    accessor: "lastName"
  },
  {
    header: "Visits",
    accessor: "visits"
  },
  {
    header: "Permanent",
    accessor: "employee"
  }
];

**Expected behavior**
filter value is dependent of `startWith` api , which is only available in IE
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/startsWith
**Codesandbox!**
Use a new [react-table codesandbox](codesandbox.io/s/X6npLXPRW) to reproduce the issue.

**Screenshots**
Table with filterValue property doesn't work

**Desktop (please complete the following information):**
 - IE 11

**Additional context**
Adding polyfill for startsWith will help in achieving it.

**Comment by tannerlinsley** [comment]
Please use a polyfill for non-modern browser support.
