### ISSUE TITLE
How can I do the sum of multiple accessors?

### ISSUE THREAD

**Issue by mantegnous** [react-tools/react-table#1157]
{
            Header:'Title',
            accessor: 'SCADU_TOTA1P'+ 'RIMES_ASCA1P'+'PORFO_ASCA1P'
        }

This method not works!

**Comment by sam-jaguar** [comment]
If you do 
`
{
  Header: 'Title',
  Cell: props => <span>{props.original.SCADU_TOTA1P + props.original.RIMES_ASCA1P + props.original.PORFO_ASCA1P}</span>
}
`
it should work out for you.

**Comment by tannerlinsley** [comment]
Github issues is no place for general support. We encourage you to use our public support forum at https://spectrum.chat/react-table.

NOTE: If a support/help/question issue is opened, it will be closed immediately and be redirected to the forum. Thanks for helping us keep our issues clean and productive!
