### ISSUE TITLE
Sorting function gives incorrect/unreliable results

### ISSUE THREAD

**Issue by jmitchell33** [react-tools/react-table#1160]
There is an issue with sorting numbers I've come across that returns an incorrect ordering - for example a column in the table that has the numbers [0.00, 5.00 12.65, 15.00, 20.00, 21.00, 23.00, 23.00, 25.00] should return the numbers in this order.  However when I am clicking the column header to sort, I will receive either [5.00, 25.00, 23.00, 23.00, 21.00, 20.00, 15.00, 12.65, 0.00] or [0.00, 12.65, 15.00, 20.00, 21.00, 23.00, 23.00, 25.00, 5.00].  

The picture below is a different column that has results all over the place when I click the "Total" column.
![sorting function](https://user-images.githubusercontent.com/2698727/47251235-58ee3d00-d43a-11e8-9f34-d988e0db51c6.png)

It doesn't seem to be happening for all columns with similar data formats, but for specific columns in my table it always occurs.

**Comment by Mulli** [comment]
I guess you are using string sort instead of numeric sort.
In string sorting 5 > 2.5 since the shorter (string) the greater

**Comment by jmitchell33** [comment]
I didn't realize there was a parameter for that.

**Comment by tannerlinsley** [comment]
Make sure you are passing a number to your accessor, not a string. Then the column will be sorted correctly.
