### ISSUE TITLE
Page prop with custom handlePagination is wrong

### ISSUE THREAD

**Issue by gyulakiraly** [react-tools/react-table#1163]
**Describe the bug**
I am implementing in my codebase a paginated fetch data for which i have to send the server the active page of the table. For this React-Table needs the `page` prop to be populated with the active page and the onPageChange function populated with the custom pagination function. When this happens, on render the current page shows `page+1`. This might be because of the code in React-Table's pagination.js line 99 and 109 that make the {page + 1}.
Does anyone know a workaround for this bug?

**To Reproduce**
```javascript
const TeamAdmin = ({
  teamAdminList,
  activePage,
  teamAdminListTotal,
  handlePageChange,
  isFetching,
}) => {
  console.log(activePage)

  return (
    <Row>
      <Col md={{ size: 12 }}>
        <ReactTable
          columns={[
            {
              Header: "Name",
              id: "name",
              accessor: d => {
                const name = d.name;
                return (
                  <span onClick={() => console.log('')}>{name}</span>
              )},
            },
            {
              Header: "Days Off Available",
              id: "daysOffAvailable",
              accessor: d => {
                const daysOffAvailable = d.totalDays - d.takenDays;
                return (
                  <span>{daysOffAvailable}</span>
              )},
            },
          ]}
          manual // Forces table not to paginate or sort automatically, so we can handle it server-side
          data={teamAdminList}
          page={activePage}
          pages={Math.ceil(teamAdminListTotal / teamAdminList.length)}
          loading={isFetching} // Display the loading overlay when we need it
          defaultPageSize={10}
          className="-striped -highlight"
          showPageSizeOptions={false}
          showPageJump={false}
          onPageChange={handlePageChange}
        />
      </Col>
    </Row>
  );
};

export default TeamAdmin;
```

TeamAdmin is rendered in a different component from which i pass through the active page and handlePagination .... the pagination works ok, as it returns the correct data and activePage ... the problem is on the table render that shows the current page, as i pass on `1` and it shows `2`

**Comment by gyulakiraly** [comment]
Found a workaround for this for the moment:  you must have a custom pager that starts from 0 on front-end yet when you do the API calls to fetch the data you have to make a `page + 1` to get the correct data. Can't this be changed in a next version so the front-end pager starts from 1 not 0 as it should be ?

**Comment by tannerlinsley** [comment]
This feature/issue has been tagged as one that will likely be fixed or improved in the next major release of React-Table. This release is expected to be completed in the next 6 - 8 months. Please see #1143 for more detail. If you believe this feature can be easily fixed, we invite you to fork the project, attempt the fix, and use it until the latest version is available. If the fix is simple enough, we will also consider it as a PR to the current version.
