### ISSUE TITLE
Some of the data is AWOL after refresh

### ISSUE THREAD

**Issue by briannons** [react-tools/react-table#1164]
**Describe the bug**
When I reload the page and refetch the data, I hand off the data from my component to react-table, but react-table only renders 1/2 of the data pieces, but a correct sum. I don't know what's happening to the 2nd piece of data. It's there in the props of react-table, and 2 trComponents are being generated, but the data seems to be put in an object making it display as ' ' so I'm reaching out to you guys.

<img width="1501" alt="screen shot 2018-10-23 at 13 49 54" src="https://user-images.githubusercontent.com/13250500/47397790-b528b980-d6e5-11e8-9239-fb2c949a6028.png">

![screen shot 2018-10-22 at 16 39 33](https://user-images.githubusercontent.com/13250500/47397873-35e7b580-d6e6-11e8-97cc-7cab396f3cf3.png)

**To Reproduce**
1. Visit page.
2. Click 'refresh' button to call the fetch method & make the network calls to get the data
3. Data gets passed in to the new component successfully as per the React developer tools
4. UI generated has 2 lines, 1 blank, and a correct total line.

**Expected behavior**
Both lines with their data are there, and the total remains correct.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS Sierra
 - Browser: Chrome and Firefox
 - Version: Chrome 69.0.3497.100, FF 62.0.3

**Additional context**
It seems to be pretty specific to having reloaded the page but I cannot for the life of me figure out what's different in how the data is being retrieved or passed in.

**Comment by briannons** [comment]
@tannerlinsley can I arrange a Skype or something? I'm having trouble reproducing it in a sandbox.

**Comment by briannons** [comment]
I figured out the problem. React-Table doesn't like it when part of its data is still arriving, so when I started waiting for all my data to be loaded before rendering the table, it worked. I might file this as a feature request.

**Comment by tannerlinsley** [comment]
How are you requesting your data?

**Comment by briannons** [comment]
Redux fetches. We 1st get a list of them, then request the details for each item in the list, compile that as a prop & pass it to react-table. When I check the dev tools all the items are there, but the table will only be showing 1. I got it fixed by not rendering the table until all the items had been fetched.
