### ISSUE TITLE
How to reset react-table props? 

### ISSUE THREAD

**Issue by Aaron-Lei** [react-tools/react-table#1166]
### **Purpose**

Implement the filter, sorting and pagination from the server-side.
I want to add a button to each row,and when click it, the props of React-Table should be reset.

### **Code Snippet**
**ReactTable props**
```
<ReactTable
       ...
       data={data}
       columns=[{
              {...},
              {
                 Header: 'Action',
                 filterable: false,
                 sortable: false,
                 Cell: row => (
                        <div> 
                               <button onClick={(e) => { this.handleDelete(e, row.original) }}>Delete</button>
                         </div>
                 )
                }]
        }
        manual
        filterable
        pages={this.state.pages}
        loading={this.state.loading}
        onFetchData={this.fetchData}
        defaultPageSize={20}
        className="-striped -highlight react-table"
/>
```
**Function Snippet**
```
fetchData(state, instance) {
        ...
        let url = baseUrl + '?page=' + state.page + "&pageSize=" + state.pageSize +...(sorted & filter params);
        fetch(url).then(res => res.json()).then(data => {
                this.setState({
                         loading: false,
                         data: data.data,
                         pages: Math.ceil(data.recordsTotal / pageSize)
                 })
         })
}

// this function is to delete current row data and then refresh the react table, reset the all props(but didn't yet)
handleDelete(e, row) {
        this.deleteCurRowAndRefresh(row.id);
    }
```

**Question**
with the code above, when changing the pages, pageSize, filter, sorted, all goes well, but when click the 'delete' button of each row, url with the correct params posted, and data are correct, but the filter,sorted,currentPage,cureentPageSize are still the previous one, not reset.

**Comment by tannerlinsley** [comment]
Github issues is no place for general support. We encourage you to use our public support forum at https://spectrum.chat/react-table.

NOTE: If a support/help/question issue is opened, it will be closed immediately and be redirected to the forum. Thanks for helping us keep our issues clean and productive!
