### ISSUE TITLE
Vertical scrollbar hiding last column data   

### ISSUE THREAD

**Issue by Mukesh-Bhootra** [react-tools/react-table#1167]
**Describe the bug**
Vertical scrollbar hiding last column data if we have horizontal bar too and last column width is reduced.
 
**To Reproduce**
Any react table with 3 or more columns, increase the width of middle column and reduce the width of last column , when you scroll right to end you will find one or two characters are hiding under vertical scroll bar. 

**Expected behavior**
Vertical scrollbar should be post last column width should not hide the details showing in last column

**Codesandbox!**
you can use https://codesandbox.io/s/o5np5p0nrz codesand box and increase width of columns adding screen shot too.

**Screenshots**
![image](https://user-images.githubusercontent.com/28565938/47445214-667f2c00-d786-11e8-8a70-e32db5231974.png)

**Desktop (please complete the following information):**
Windows / Crome
 - Browser - chrome 
 - Version 68.0.3440.106

**Comment by tannerlinsley** [comment]
RT wasn't designed for inline-scrolling, hence the pagination, so unfortunately, there is no official support for this use-case. You're more than welcome to explore and ask in the forum though! https://spectrum.chat/react-table

**Comment by Mukesh-Bhootra** [comment]
@Mulli can you suggest how to do ? looking for few workarounds
