### ISSUE TITLE
Table slowdown on multiple rows / columns

### ISSUE THREAD

**Issue by HtmlRanger** [react-tools/react-table#1169]
A table with 40 columns and 200 rows is very slow. This can be seen if you highlight the line by click. After clicking on the lines, it takes 1-2 seconds before it is highlighted. Is this because the table is completely redrawn for the sake of a single row? Very noticeable in IE, in Chrome less.

**Comment by tannerlinsley** [comment]
I would accept a PR to add/update/fix this functionality, or you can wait for v7 (a month or two). Thanks for the input!
