### ISSUE TITLE
advancedExpandTableHOC is missing from react-table 6.8.6

### ISSUE THREAD

**Issue by JacobTheEvans** [react-tools/react-table#1170]
**Describe the bug**
advancedExpandTableHO is missing from the npm install of react-table

I also notice the import statement is missing from the docs. Is this intentional? Is the expect behavior for someone to copy the src code from the github repo in order to use the advancedExpandTableHO component?

**To Reproduce**
1. Init new project using ```yarn init```
2. Install react-table using ```yarn add react-table@6.8.6```
3. Try to import advancedExpandTableHO using ```import advancedExpandTableHO from 'react-table/lib/hoc/advancedExpandTableHO'``` in a file within the project
4. Watch import fail

or

1. Init new project using ```yarn init```
2. Install react-table using ```yarn add react-table@6.8.6```
3. Open node_modules folder
4. Go to react-table/lib/hoc
6. See that the advancedExpandTableHO folder is missing

**Expected behavior**
advancedExpandTableHO folder should be in npm package

**Desktop (please complete the following information):**
 - OS: fedora 28

**Comment by mdeividas** [comment]
Having the same problem. Any update regarding this issue?

**Comment by JacobTheEvans** [comment]
Unfortunately not I have seen. I dont believe its a priority with the library being refactored to use react hooks. Im currently copying the HOC folder into my react project when I use react-table.

**Comment by tannerlinsley** [comment]
I would accept a PR to add/update/fix this functionality, or you can wait for v7 (a month or two). Thanks for the input!
