### ISSUE TITLE
advancedExpandTableHOC demo uses react-table@6.5.3

### ISSUE THREAD

**Issue by JacobTheEvans** [react-tools/react-table#1171]
**Describe the bug**
advancedExpandTableHOC demo located https://react-table.js.org/#/story/advanced-expand-table-hoc
and https://codesandbox.io/s/y2m39jz8v1?from-embed is not using the latest version of react-table

**To Reproduce**
Go to https://react-table.js.org/#/story/advanced-expand-table-hoc
or https://codesandbox.io/s/y2m39jz8v1?from-embed

**Expected behavior**
Should be using the latest version of react-table or mark the documentation site with a warning that it uses an older version

**Additional context**
I would be willing to update after #1170 has been addressed

**Comment by tannerlinsley** [comment]
I would accept a PR to add/update/fix this functionality, or you can wait for v7 (a month or two). Thanks for the input!
