### ISSUE TITLE
Last column partially hidden on horizontal scroll

### ISSUE THREAD

**Issue by bg87** [react-tools/react-table#1172]
**Describe the bug**
On a table with horizontal scroll: Every now and then when scrolled all the way over the last column isn't fully visible.

**To Reproduce**
I can't reliably reproduce it, it only happens intermittently and not very often.

**Expected behavior**
The user should be able see all columns.

**Desktop (please complete the following information):**
 - OS: macOs
 - Browser: chrome
 - Version: latest

**Comment by karlbloedorn** [comment]
On your last column, you could try   style: {textAlign: 'right', paddingRight: 15}, but it sounds like your issue might be more than that if it is intermittent.

**Comment by tannerlinsley** [comment]
I would accept a PR to add/update/fix this functionality, or you can wait for v7 (a month or two). Thanks for the input!
