### ISSUE TITLE
FoldableTableHOC is missing from 6.8.6

### ISSUE THREAD

**Issue by usergit** [react-tools/react-table#1173]
**Describe the bug**
FoldableTableHOC is missing from 6.8.6

**To Reproduce**
1. Go to 'node_modules/react-table/lib/hoc'

**Expected behavior**
FoldableTableHOC is missing from the list of HOC's

**Comment by usergit** [comment]
I just saw https://github.com/react-tools/react-table/issues/1039 maybe it should be removed from the examples page till it gets released

**Comment by baoduy** [comment]
I will review and add the samples back today. Sorry for delay as really busy with a project recently.

**Comment by baoduy** [comment]
I already submit a new pull request to fix the sandbox issue. However, the folder foldable table is missing in the 6.8.6 npm package even it is there in the lib folder when running `npm run build` command.

**Comment by tannerlinsley** [comment]
I would accept a PR to add/update/fix this functionality, or you can wait for v7 (a month or two). Thanks for the input!

**Comment by bellsenawat** [comment]
sorry I can't found FoldableTableHOC on current version @baoduy @tannerlinsley
