### ISSUE TITLE
Hide number row selection dropdown

### ISSUE THREAD

**Issue by yjadhav** [react-tools/react-table#1175]
Hello,

How i can hide dropdown which is used to select number of rows to display in the table.

![image](https://user-images.githubusercontent.com/18395667/47601837-ab5bca80-d9f3-11e8-9d57-5f70f4dd6b09.png)

**Comment by JacobTheEvans** [comment]
If you are just trying to remove the pagination from the bottom then you need to disable the pagination for the table. 

```javascript
<ReactTable
  data={data}
  columns={columns}
  showPagination={false}
/>
```

If you want pagination but dont want the row selection then your left with two options.

1. Either pass in a custom component for pagination

```javascript
<ReactTable
  data={data}
  columns={columns}
  PaginationComponent={CustomPagination}
/>

function CustomPagination () {
 // look at docs for how to build custom component
  return false
}
```

2. You can just set the amount of rows manually and hide the rows with CSS.

```javascript
<ReactTable
  data={data}
  columns={columns}
  defaultPageSize={20}
/>
```

```css
.-pageSizeOptions {
 display: none;
}
```

**Comment by kyawkyawsoezhu** [comment]
`showPageSizeOptions: false`

**Comment by Qamar-Ascend** [comment]
> `showPageSizeOptions: false`
its good solution thanks
