### ISSUE TITLE
Pagination Arrows aren't working

### ISSUE THREAD

**Issue by jmitchell33** [react-tools/react-table#1177]
When using pagination, I noticed an issue when clicking the up/down arrows in the input for Page Number.  This is occuring for me even on the simple table demo:

https://react-table.js.org/#/story/simple-table

When you click the up/down arrow to change the page, and then click in the number input field for page and hit enter - it works properly, which makes me think there is an issue in the plumbing for the event tied to the up/down arrows.

**Comment by tannerlinsley** [comment]
The types for RT are definitely out of date. I will accept a PR to add/update this functionality, or you can wait for v7 (a month or two). Thanks for the input!

**Comment by tannerlinsley** [comment]
I will accept a PR to add/update this functionality, or you can wait for v7 (a month or two). Thanks for the input!
