### ISSUE TITLE
Unable to use React class for custom header / cell renderer

### ISSUE THREAD

**Issue by electricsam** [react-tools/react-table#1178]
**Describe the bug**
I am trying to use a custom header and cell.  These cells use a ref, and as such cannot be a stateless functional component.  According to the documentation:

> Renderers
> React Table supports very flexible renderers for just about everything:
>
> Cell - Renders a standard cell
> Header - Renders a column header or column group header
> Footer - Renders a column footer
> Filter - Renders a column's filter UI
> Aggregated - Renders an aggregated cell
> Pivot - Renders a pivoted cell (by default, will utilize Expander and PivotValue renderers)
> PivotValue - Renders the value inside a Pivot renderer
> Expander - Renders the Expander used in both the default Pivot renderer and any expander-designated column
> 
> Any of these renderers can be one of the following:
>
> A React Class
> JSX or any rendered react component
> Stateless functional component
> Function that returns any primitive

However, when I use a react class, I get the following error:

> main.js:116313 Uncaught TypeError: Cannot call a class as a function
>    at _classCallCheck (main.js:116313)
>    at DeleteIcon (DeleteIcon.jsx:7)
>    at Object.normalizeComponent (utils.js:224)
>    at makeHeader (index.js:336)
>    at Array.map (<anonymous>)
>    at makeHeaders (index.js:362)
>    at makeTable (index.js:758)
>    at ReactTable.render (index.js:790)
>    at finishClassComponent (react-dom.development.js:13727)
>    at updateClassComponent (react-dom.development.js:13690)

**To Reproduce**

I am trying to use a React class to accomplish this. For example:

```
import React from 'react';

export class DeleteIcon extends React.Component {

  render() {
    return (<div>foo</div>);
  }

}
```

In my class using ReactTable:

```
        <ReactTable
          className="-striped -highlight"
          defaultSorted={[{ id: 'id', desc: false }]}
          loading={!fetched}
          columns={[
            {
              Header: DeleteIcon,
              id: 'delete',
              accessor: 'id',
              className: 'text-center',
              minWidth: 35,
              resizable: false,
              filterable: false,
              sortable: false,
              Cell: DeleteIcon,
            },
          ]}
          data={data}
        />
      </div>
```

If I try to wrap my real implementation of DeleteIcon (with ref) in a functional component, I get the following warning, which results in a error in the component:

>Warning: Function components cannot be given refs. Attempts to access this ref will fail.

**Expected behavior**
I should be able to use a React class for a custom header / cell without wrapping in a functional component.

**Comment by dclark27** [comment]
This is also an issue on our system. Cell actually works just fine with this:

 columns={[
            {
              Header: DeleteIcon,
              id: 'delete',
              accessor: 'id',
              className: 'text-center',
              minWidth: 35,
              resizable: false,
              filterable: false,
              sortable: false,
              Cell: (row) => {
                 return <SomeReactComponent {...row} />
               },
            },
          ]}

**Comment by tannerlinsley** [comment]
I would accept a PR to add/update/fix this functionality, or you can wait for v7 (a month or two). Thanks for the input!
