### ISSUE TITLE
Table sorting doesn't work properly when column has the same value for each row

### ISSUE THREAD

**Issue by jeffcardoso** [react-tools/react-table#1179]
**Describe the bug**
When I switch the sort order of one column with the same value for each row, then the order becomes reversed.

**To Reproduce**
1. Go to https://codesandbox.io/s/kmjw832rkr;
2. Click the "Age" column header to sort ascending by age;
3. Click the "Age" column header to sort descending by age;
4. The order of rows becomes reversed although the age is the same for each row.

**Expected behavior**
The rows order should remain the same.

Thanks in advance!

**Comment by hichamnaimi** [comment]
Hi facing the same problem as @jeffcardoso said !!

**Comment by tannerlinsley** [comment]
This is called stable sorting. It uses the original row index from your data as a fallback for equal values. This is intended for a large majority of use cases too, but if you want to override the sortBy or orderBy functions, React Table supports it.
