### ISSUE TITLE
Filter does not work when you are on any page except page 1 and the number of filtered record returned is 1.

### ISSUE THREAD

**Issue by dhruvmbhatt** [react-tools/react-table#1180]
If you are on any page except page 1 and you try to filter for a single record out of many records(say 100000) and page size of 10, then it does not show that record and just shows page 1 in footer.
When you click the footer page 1 pagination item,  only then the record is visible.

So I assume that there needs to be a fix wherein whenever a user tries to filter for any value the current Page should be set to the first page.

**Comment by tannerlinsley** [comment]
I would accept a PR to add/update/fix this functionality, or you can wait for v7 (a month or two). Thanks for the input!
