### ISSUE TITLE
Column header and cell shifting when overflow is visible

### ISSUE THREAD

**Issue by jkeruzec** [react-tools/react-table#1185]
**Describe the bug**
With fixed height, column header and cell are shifting a bit when overflow is visible on the right side of screen

**To Reproduce**
Apply max height on React Table to have a visible overflow
```
<ReactTable
                loading={this.loading}
                data={this.formatData} // Transform mobx observable to simple array 
                columns={columns}
                sorted={[{ // the sorting model for the table
                    id: 'category'
                  }, {
                    id: 'process'
                }]}
                pageSize={5}
                pivotBy={["category"]}
                style={{fontSize: '0.8em', maxHeight: 400}}
                className="-striped -highlight"
                />
```

**Expected behavior**
Column headers and cells are aligned

**Screenshots**
![image](https://user-images.githubusercontent.com/3499632/48003418-b0fd9280-e10e-11e8-9f53-df9aecfd59b4.png)

**Comment by jkeruzec** [comment]
Using the proposed css in example is not very good either because when there are no scrolling on main table, a shift is created.

I think this options must be dynamic according to scrolability of table : 
```css
.ReactTable .rt-thead {
  overflow-y: scroll;
}
```

**Comment by tannerlinsley** [comment]
@jkeruzec 👍
