### ISSUE TITLE
Styles break when table overflows horizontally as well as vertically

### ISSUE THREAD

**Issue by Billy-** [react-tools/react-table#1187]
**Describe the bug**
When configuring a table with a fixed height (for sticky headers), which also needs horizontal scrolling due to too many columns / not enough horizontal space, the table's styles break.

**To Reproduce**
1. Go to https://codesandbox.io/s/o7ynj9kn0z
2. Drag the preview window so that it is narrow enough to cause horizontal scrolling
3. Observe the following issues:
  i. Table headers have scrollbars (both vertical and horizontal - should not have either)
  ii. The table body seems to have ~10px of horizontal scrolling going on (in addition to the main table's horizontal scrollbar, which is working as expected)
  iii. The vertical scrollbar for the table body is hidden until you scroll horizontally all the way to the right

**Expected behavior**
The above issues do not occur

**Codesandbox!**
https://codesandbox.io/s/o7ynj9kn0z - Forked from the "Fixed Header + Vertical Scroll" codesandbox

**Screenshots**
![image](https://user-images.githubusercontent.com/4316168/48197457-b1d03780-e34d-11e8-98e5-c9d425a04b6f.png)

**Desktop:**
 - OS: Ubuntu 18.04
 - Browser Chrome
 - Version 69.0.3497.100 (Official Build) (64-bit)

**Additional context**
Horizontal scrolling works on it's own, and sticky headers/vertical scrolling seems to work on it's own, but both at once is what causes this.

**Comment by Billy-** [comment]
Update:
https://codesandbox.io/s/jnj5z20jqv

By removing the `overflow-y: 'scroll'` style on the `rt-thead` selector in styles.css fixes the headers having overflow - not sure why this was added to this codesandbox example?

I also added a style which hides the x overflow on `rt-tbody` - this fixes the strange horizontal scroll on the body.

The only remaining issue is that the vertical scrollbar is hidden until the body is horizontally scrolled all the way to the right. I can't see any way of fixing this issue, hopefully someone else may have an idea.

**Comment by tannerlinsley** [comment]
I would accept a PR to add/update/fix this functionality, or you can wait for v7 (a month or two). Thanks for the input!

**Comment by danielkrich** [comment]
Happens to me as well. Is there a fix?
![image](https://user-images.githubusercontent.com/15924758/58789878-d9436600-85f7-11e9-9c58-82fad0ec6b88.png)

Note how the scroll-bar on the right shifts all cells. This also creates a weird horizontal scrolling behaviour...

**Comment by danielkrich** [comment]
> Happens to me as well. Is there a fix?
> ![image](https://user-images.githubusercontent.com/15924758/58789878-d9436600-85f7-11e9-9c58-82fad0ec6b88.png)
> 
> Note how the scroll-bar on the right shifts all cells. This also creates a weird horizontal scrolling behaviour...

OK, this fixed it for me:
` overflowY: 'scroll', overflowX: 'hidden' ` on `Tbody`
