### ISSUE TITLE
Editing cells when the column is sorted causes multiple edits

### ISSUE THREAD

**Issue by TobyAbel** [react-tools/react-table#1188]
**Describe the bug**
When sorting by a column, if you edit a cell in that column in such a way as to re-order it, both the cell in the position that you edited, and the cell in the new position that it now occupies appear to have the new value.

**To Reproduce**
1. Go to https://react-table.js.org/#/story/editable-table
2. Copy steps from this video: http://recordit.co/YuuL1lrYqI

**Expected behavior**
The value in the cell in the position that you edited should change to the value of that column in the row that now occupies that position.

**Codesandbox!**
https://react-table.js.org/#/story/editable-table

**Screenshots**
http://recordit.co/YuuL1lrYqI

**Desktop (please complete the following information):**
 - OS: e.g. iOS
 - Browser: chrome
 - Version: 70

**Additional context**
Note the combined name is *not* changing in this example, so it's likely a visual issue, not a data issue (i.e. the cell's text is not updating to match the data model). However, if you then click on the incorrect cell, the data model is immediately updated without you having typed anything, and the issue propagates to the data model.

**Comment by tannerlinsley** [comment]
I would accept a PR to add/update/fix this functionality, or you can wait for v7 (a month or two). Thanks for the input!
