### ISSUE TITLE
Custom id keys for filter and sort column params.

### ISSUE THREAD

**Issue by tommyalvarez** [react-tools/react-table#1189]
**Is your feature request related to a problem? Please describe.**
Currently, when using server-side filtering or sorting, the object that is created consist of an id and a value. The value for id, is the id specified for each column like this:

```
{
      Header: I18n.t('attributes.product.abbr.presentation'),
      id: 'product_presentation',
      accessor: 'product.presentation',
      filterable: true,
      sortable: true,
      Filter: (props) => (<InputFilter {...props} placeholder={I18n.t('placeholders.product.filter.presentation')} />)
    }
``` 

The problem is that i need a different value for the id prop for sorting and filtering, due to backend limitations that needs to receive it in a specific way and since the Component where i'm using the react-table is very reusable, i can't be manual tampering with the filter or sort object generated by this library. I need to send it almost 'as is' to the backend. This issue is similar to #9 except that the solution there isn't enough for having a different id for both filter and sort

**Describe the solution you'd like**
I would like to be able to specify _filterKey_ and _sortKey_ for each column and if none is supplied, just take it from the _id_ prop as usual.

**Describe alternatives you've considered**
I can't think of an alternative solution other than tampering with the **onSortedChange** function, and manually tweaking the argument received and changing by hand the id param. That would break the reusability of the component where that _onSortedChange_ function resides. 

**Additional context**
Nothing to add

**Comment by tannerlinsley** [comment]
I would accept a PR to add/update/fix this functionality, or you can wait for v7 (a month or two). Thanks for the input!

**Comment by Migggz** [comment]
As I'm using Version `^7.7.0` and still don't find a solution for this problem, I did a workaround to get over this problem using these helper functions:

```js
const SEPARATOR = "__SEPARATOR__";
export const getColumnFilterKey = id => !id.includes(SEPARATOR) ? id : id.split(SEPARATOR)[0];
export const getColumnSortKey = id => !id.includes(SEPARATOR) ? id : id.split(SEPARATOR)[1];
export const setColumnFilterAndSortKey = (filterKey, sortKey) => filterKey + SEPARATOR + sortKey;
```
and specifying each column id using `setColumnFilterAndSortKey` like this:
```tsx
{
    Header: "First Name",
    accessor: 'firstname',
    id: setColumnFilterAndSortKey('firstname', 'members.firstname'),
    Filter: (props: FilterProps<object>) => (
      <DefaultInputFilter
        {...props}
        inputProps={{
          placeholder: "Find user by first name",
        }}
      />
    ),
  },
```
In the table component retrieve keys using `getColumnFilterKey` & `getColumnSortKey` like this :
```tsx
useEffect(() => {
    const structuredFilters = {
      ...filters.reduce((acc: {}, curr) => {
        return {
          ...acc,
          [getColumnFilterKey(curr.id)]: curr.value,
        };
      }, {}),
      ...sortBy.reduce((acc, curr) => {
        return {
          sortField: getColumnSortKey(curr.id),
          sortDirection: curr.desc ? 'desc' : 'asc',
        };
      }, {}),
    };
    fetchData({ structuredFilters });
  }, [sortBy, fetchData, filters]);
```

I hope this helps anyone facing the same problem.

**Comment by dnquang1996vn** [comment]
@Migggz thanks for your solution. It can be a workaround.
I hope in the new react table version, we can have sortKey and filterKey column props

**Comment by reinos** [comment]
@tannerlinsley it seems that this feature is still not available in version 8.x. Can you give us an update on this one?

**Comment by tamal-sen** [comment]
I have also run into this issue. @tannerlinsley, I would really appreciate it if you could provide an update.
