### ISSUE TITLE
Warnings in react-table when using React's strict mode

### ISSUE THREAD

**Issue by edmorley** [react-tools/react-table#1193]
**Describe the bug**
Hi!

React 16.3 added a new strict mode, which highlights potential issues in an app (such as those that will cause problems when using the upcoming async mode):
https://reactjs.org/docs/strict-mode.html

Enabling it for our app resulted in errors coming from `react-table`:

```
Warning: Unsafe lifecycle methods were found within a strict-mode tree:
    in StrictMode (at intermittent-failures/index.jsx:12)

componentWillMount: Please update the following components to use
componentDidMount instead: ReactTable

componentWillReceiveProps: Please update the following components to use
static getDerivedStateFromProps instead: ReactTable, ReactTablePagination
```

**To Reproduce**
1. Inspect react-table source for usage of deprecated lifecycle methods:
  https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html#migrating-from-legacy-lifecycles

**Expected behavior**
No usages of deprecated lifecycle methods.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox Nightly
 - Version `react-table@6.8.6`

**Additional context**

React docs on migrating:
https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html#migrating-from-legacy-lifecycles
https://reactjs.org/docs/react-component.html#unsafe_componentwillmount
https://reactjs.org/docs/react-component.html#unsafe_componentwillreceiveprops

The offending usages are here:
https://github.com/react-tools/react-table/blob/f55ce620411c619855a2fe2f081407e4f82727b9/src/lifecycle.js#L3-L5
https://github.com/react-tools/react-table/blob/474244ce419ebcb825d8e7927289631ef7696af8/src/pagination.js#L23-L27
https://github.com/react-tools/react-table/blob/f55ce620411c619855a2fe2f081407e4f82727b9/src/lifecycle.js#L11-L49
https://github.com/react-tools/react-table/blob/02e65b4388fa583690ec7b8ebd70ce27dc4e320f/src/hoc/foldableTable/index.js#L44-L48
https://github.com/react-tools/react-table/blob/9048835bcc69d7110a3c8b126d683085769b11c0/src/hoc/advancedExpandTable/index.js#L69-L73

**Comment by tannerlinsley** [comment]
React Table is currently under a rewrite for a next major version. It's a heavy undertaking that will take months to accomplish. Be patient, fork and fix if you must on the current version. Thanks

**Comment by edmorley** [comment]
Hi! The `componentWillMount` and `componentWillReceiveProps` usages linked above still exist on `master`. It sounds like this will be resolved as part of the future re-write, but I think it would be best to leave this issue open until it is? It will make it easier for others to find and save them spending time writing up another issue.
