### ISSUE TITLE
Footer can has props?

### ISSUE THREAD

**Issue by tz310200** [react-tools/react-table#1194]
**Is your feature request related to a problem? Please describe.**

In my project, I encapsulated the react-table.columns and my server data are not in the same component. I want to get the react-table props in the Footer.

**Describe the solution you'd like**

https://codesandbox.io/s/qxk9120l6q

**Additional context**
![image](https://user-images.githubusercontent.com/29906873/48389532-d2770380-e738-11e8-8899-fed084f711bf.png)

![image](https://user-images.githubusercontent.com/29906873/48389526-cb4ff580-e738-11e8-940d-85bb1991ec92.png)

**Comment by tannerlinsley** [comment]
I would accept a PR to add/update/fix this functionality, or you can wait for v7 (a month or two). Thanks for the input!
