### ISSUE TITLE
Not re-rendering properly when add or delete row from data

### ISSUE THREAD

**Issue by jberry4** [react-tools/react-table#1196]
I am currently using react-table and have/want the ability to add or delete rows from the table.
The control for this adding or deleting is in the final column in the table which has either an add or delete button and I am using 'Cell' within that column in order to render this button
The onclick function updates the local state which is passed back in to the table as the 'data' prop
Some of the other columns in the table contain inputs where you can update the value and this is updated in the local state and this works without fault.

The issue is that when I add or delete a row I get strange behaviour to do with how it is rendered/displayed. For example when you delete a row the number of rows reduces by one but the data from the deleted row is still shown in the inputs at the deleted parts index even though the data in state is correct.

More strangely when adding a new row the values that are added should always be '--' and this is what should be displayed in the input (type selected) in the relevant column but instead I am getting a value from a different cell displayed in that rows inputs. (I am not using default values in the input)

The data in state is correct and I have tried using 'resolveData' prop without this improving the situation

**Additional context**
Interestingly I also have a use case where the table is in a modal. When the modal is closed and reopened the data is not changed in any way when this toggling occurs but the table displays correctly in the modal when reopened

**Comment by Alphablackwolf** [comment]
I am also having this issue. I implemented a custom filter that sits outside the grid and searches all fields and manually filters the data displayed. When I use the 'Cell' in the column options to give it a react component it fails to render the correct data, even though all internal states show the correct data. If I change it from a react component to straight html, it works fine. code sandbox example is [here](https://codepen.io/anon/pen/qQzxGm/?editors=0010): to test it out simply search 'sting,' it will display 'a king agency' and not 'a sting agency.' However, if you remove the component and replace it's render directly into the Cell in the column definition, it will work as expected.

**Comment by Alphablackwolf** [comment]
Aaaand I found the problem. For me, adding a key fixed it. If you are rendering a react component, you will need to add key={someUniqueIdentifierOrIndex} to the component.

**Comment by tannerlinsley** [comment]
@Alphablackwolf is correct. For v6, this is the recommended solution. I would accept a PR to add/update/fix this functionality, or you can wait for v7 (a month or two). Thanks for the input!

**Comment by Aouiti-bilel** [comment]
Hello, I t'ill have a similar issue. I am using React-table v7

**Comment by Kuzirashi** [comment]
In my case adding `data` array to `columns` memoization helped. Thanks to this answer: https://stackoverflow.com/a/61810099/2166409

**Comment by Eosis** [comment]
I can confirm as @Aouiti-bilel has that this issue persists in v7.

The same suggested fix (ensuring that the rendered cell component has a key set) works.
