### ISSUE TITLE
Row heights are not resizing for inner content.

### ISSUE THREAD

**Issue by jkreish** [react-tools/react-table#1197]
**Describe the bug**
No matter what I put in the Cell property, I can't get the rows to resize based on the content inside the cell. 

**To Reproduce**
In the following code snippet, I can see "TestTop", but not "TestBottom"
```
<ReactTable
            columns={[
              {
                id: 'flagInfo',
                Header: ' ',
                accessor: 'flagReason',
                Cell: row => (
                  <div >
                    <p> TestTop </p>
                    <br />
                    <br />
                    <br />
                    <br />
                    <p> TestBottom </p>
                  </div>
                )
              }
            ]}
            manual
            data={flags}
            pages={1}
            showPaginationBottom={false}
            loading={loading} 
            filterable={false}
            defaultPageSize={flags.length}
            className="-striped -highlight"
            getTdProps={(state, rowInfo, column, instance) => {
              return {
                onClick: (e, handleOriginal) => {
                  if (handleOriginal) {
                    handleOriginal();
                  }
                }
              };
            }}
          />
```

**Expected behavior**
I expect the row to resize to show all content in the cell. 

**Screenshots**
![screen shot 2018-11-14 at 1 24 17 pm](https://user-images.githubusercontent.com/22059594/48503663-b777c280-e810-11e8-8718-2017810b3fd8.png)

**Desktop (please complete the following information):**
 - Browser: Chrome

**Versions:**
react-table: "^6.8.6",
react: "^16.3.1",

**Comment by jkreish** [comment]
Found the issue. The row height can be set in CSS: 
```
.rt-tr {
      text-align: left;
      height: 3.2em;
}
```
If you want variable height that adjusts to the inner content, just remove the height property above.

**Comment by maboutin81** [comment]
I have the same issue and I don't have this "height: 3.2em;" anywhere.
