### ISSUE TITLE
change to a single row causes render of whole table (external data store)

### ISSUE THREAD

**Issue by abolognino** [react-tools/react-table#1199]
**Describe the bug**
I have a table with 100 rows, the data is fed from an external store (redux), when a single row is modified the whole table is re-rendered, which is extremely slow.

**To Reproduce**
The suggested [codesandbox](https://codesandbox.io/s/r5q81w4wwq) for redux already displays this behaviour, just run it locally, enable react profiler with highlight updates enabled, then click on Update Last Record.

The whole table is highlighted

**Expected behavior**
I would expect only the modified row to be re-rendered

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Chrome
 - Version 70

react-table 6.8.6

**Comment by tannerlinsley** [comment]
Right now all rows are unfortunately rerendered and yes this sucks. I would accept a PR to add/update/fix this functionality in v6, or you can wait for v7 (a month or two) where we have fixed the issue. Thanks for the input!

**Comment by beccarif** [comment]
Good morning, this issue has been fixed in version 7?
I have the same issue with Redux as external source...
Thank you
