### ISSUE TITLE
The IE11-related `flex: auto 1` CSS for `rt-table` is invalid

### ISSUE THREAD

**Issue by vdh** [react-tools/react-table#1200]
**Describe the bug**
[Commit 56b721](https://github.com/react-tools/react-table/commit/56b721c185c75d430a1d8ec3a8213a3f1de406d6) added an invalid property to the default styles.

`auto 1` is not a valid value for the `flex` property. it's a shorthand property for:
- `flex-grow`
- `flex-shrink`
- `flex-basis`

`auto` is only valid for `flex-basis`, or on the whole property as a shorthand for `1 1 auto`.

**To Reproduce**
The error is present in the compiled CSS assets.

**Expected behavior**
The value should be either changed to `auto`, revered back to `1`, or some other valid `flex` value. If that invalid `auto 1` value is *really* necessary for IE 11, then it should be behind a CSS hack, such as:
```css
_:-ms-fullscreen, :root .ReactTable .rt-table{ flex:auto 1; }
```

**Comment by tannerlinsley** [comment]
I would accept a PR to add/update/fix this functionality, or you can wait for v7 (a month or two). Thanks for the input!
