### ISSUE TITLE
onExpandedChange handler is not passed complete row information

### ISSUE THREAD

**Issue by Olivercomputing** [react-tools/react-table#1201]
The function signature for the onExpandedChange handler is, evidently:
    (expanded:any, viewIndex:number, e:any)

where currently, and as described earlier in a bug report, 'e' is useless. 

The problem I'm having is that the index value passed in the second parameter is the *view* index. This evidently equals the actual data index when there's no filtering (and sorting, come to think of it, though I haven't tried that yet.)

This is a big problem if the function needs to have access to the underlying table data for the expanded row. By contrast, the SubComponent prop in ReactTable passes a row object to the handler which *does* include both the actual data index and the view index. 

Arguably the second parameter should be the actual data index and not the view index. I'm not sure offhand what value the view index has to the onExpandedChange handler. Alternatively, if the actual data row object were passed to the handler, as it is with the SubComponent handler, the problem would be solved. I could see two backwards compatible solutions to this. One would be to add a fourth parameter to the onExpandedChange handler which would be the row object. Another would be to add a new prop, named say onExpandedChangeRow, with a signature of:

  (expanded:any, row:any, e:any)

A non-backwards compatible change would be to change the existing second parameter so that it was the actual data index, not the view index. This is inferior IMO to passing in the row object because it requires accessing a source for the table data that's separate from the ReactTable's copy of it.

**Comment by tannerlinsley** [comment]
I would accept a PR to add/update/fix this functionality, or you can wait for v7 (a month or two). Thanks for the input!

**Comment by mike391** [comment]
Done: https://github.com/tannerlinsley/react-table/pull/1299
