### ISSUE TITLE
Tree table scroll horizontal issue

### ISSUE THREAD

**Issue by leenint** [react-tools/react-table#1202]
Hi,

Version: "react-table": "6.8.6"

When i use treetable in small div element, it will has 2 horizontal scroll bar.
- if I scroll first bar -> body scroll but header do not.
- if I scroll second bar -> header scroll but body do not.

This is my sample code:
[https://codesandbox.io/s/0zo67k77w](url)

Please help me fix this issue.

**Comment by JonPugsley** [comment]
Your link is going to the wrong place (https://github.com/react-tools/react-table/issues/url)

Here's a clickable one: https://codesandbox.io/s/0zo67k77w.

I've seen this before too, though I'm not positive exactly what causes it.  It definitely seems to be related to the size of the ReactTable component vs the size of the container.

**Comment by tannerlinsley** [comment]
I would accept a PR to add/update/fix this functionality, or you can wait for v7 (a month or two). Thanks for the input!
