### ISSUE TITLE
Prevent unmounting of Subcomponent when not expanded

### ISSUE THREAD

**Issue by marjan2k** [react-tools/react-table#1203]
It will be easier to add react-transition-group transitions to subcomponent if it is not unmounted.

We can use the "in" prop of transition group show hide the subcomponent.

Currently I can only animate when the subcomponent appears but cannot animate subcomponent exit/hide since its unmounted

**Comment by tannerlinsley** [comment]
This will be possible in v7 (a month or two). Thanks for the input!

**Comment by vtni** [comment]
Are there any news about this?
