### ISSUE TITLE
Failing ESLint react/prop-types using arrow function in Cell of columns

### ISSUE THREAD

**Issue by ailionx** [react-tools/react-table#1207]
**Describe the bug**
When using an arrow function as `Cell` value in `columns` config, the props are failing ESLint react/prop-types rule.

**To Reproduce**
This is part of the `columns` value:
```
    const columns = [
        {
            id: 'completedDate',
            Header: 'Date Completed',
            accessor: record => moment(record.published_date, 'YYYY-MM-DDTHH:mm:ss')
                .format('YYYY-MM-DD hh:mm:ss a'),
            Cell: ({ value }) => (
                <div className="text-center">
                    <span style={{ lineHeight: '57px' }}>{value}</span>
                </div>
            ),
        }
```

This is my ESLint config:
```
{
  "extends": "airbnb",
  "env": {
    "browser": true
  },
  "parser": "babel-eslint",
  "plugins": [
    "babel",
    "jsx-a11y"
  ],
  "rules": {
    "indent": [
      "error",
      4
    ],
    "no-underscore-dangle": [
      "off"
    ],
    "babel/semi": 1,
    "react/jsx-indent": [
      "error",
      4
    ],
    "react/jsx-indent-props": [
      "error",
      4
    ],
    "jsx-a11y/label-has-for": "off",
    "jsx-a11y/label-has-associated-control": ["error", {
      "assert": "either"
    }]
  }
}
```
The `value` in `columns.Cell` arrow function is getting `ESLint: 'value' is missing in props validation. (react/prop-types)`. The app works great. Just it doesn't pass ESLint.

**Expected behavior**
This is the way to use it as in the official website examples. It should pass the ESLint.

**Comment by asheba** [comment]
Any update on this issue?

**Comment by Margoot** [comment]
Any update please ...?

**Comment by shermify** [comment]
If your eslint config requires prop types for all react components, then you need to add prop types to your react component that you are using for custom cell rendering.  This is not a bug with react-table.

**Comment by tannerlinsley** [comment]
I will accept a PR to add/update this functionality, or you can wait for v7 (a month or two). Thanks for the input!

**Comment by ErikAGriffin** [comment]
This seems to still be an issue.  Any updates @tannerlinsley? 

Also it's not for lack of props validation on a custom component: if you are rendering a simple `<span>` element the error still appears, immediately following the `Cell:` property for the function arguments

![image](https://user-images.githubusercontent.com/10357979/81347355-31d97980-9079-11ea-8ac1-df765d7a921f.png)

**Comment by amaljosea** [comment]
This works https://github.com/yannickcr/eslint-plugin-react/issues/2404#issuecomment-529227876

**Comment by serhanekicii** [comment]
![pic-selected-221227-1855-43](https://user-images.githubusercontent.com/52760200/209690694-ee8bcd5b-3c1a-4b5b-909e-21b21f987f78.png)
Still on v8.

**Comment by dca123** [comment]
Was happening to me with `material-react-table`, it's a configuration issue since eslint expects a definition for the props when a component is written.

Updating my eslint config to this fixed the issue 

```  
"react/prop-types": ["error", {
            "skipUndeclared": true
        }]  
```

**Comment by hodovani** [comment]
You can use `useRowState` to pass additional data. [docs](https://github.com/TanStack/table/blob/v7/docs/src/pages/docs/api/useRowState.md)

**Comment by razzeee** [comment]
I'm also seeing this with `material-react-table` @dca123 

are you still suppressing the error, not sure I like that solution
