### ISSUE TITLE
Editable rows in dynamic table 

### ISSUE THREAD

**Issue by brunaaleixo** [react-tools/react-table#1209]
I have a table in which 2 of the columns are editable. When dynamically adding a new row to a table, the new row's columns are not editable. This is recent to version 6.8.6 - in version 6.8.5 the table's columns are editable, as expected.

**Comment by tannerlinsley** [comment]
I would accept a PR to add/update/fix this functionality, or you can wait for v7 (a month or two). Thanks for the input!
