### ISSUE TITLE
Setting  defaultPageSize to a value 0-9 or 11-19 strangely sets the paging dropdown to "5 rows"

### ISSUE THREAD

**Issue by Jared-Nielsen** [react-tools/react-table#1210]
**Describe the bug**
In the demos at: https://react-table.js.org/#/story/simple-table the code on the left allows you to change the defaultPageSize.  If you set it to a number from 1-9 or 11-19 it only shows "5 rows" on the paging drop down in the right hand panel.  My code also reflects the same problem.  The grid renders with the specified number of rows... it just doesn't reflect on the paging drop down.

**To Reproduce**
1. Go to https://react-table.js.org/#/story/simple-table
2. Change the code to be: defaultPageSize={9}
3. View the pane on the right to see the number of rows change to "5 rows" (bug)
4. Change the code to be: defaultPageSize={10}
5. View the pane on the right to see the number of rows change to "10 rows" (expected)
6. Change the code to be: defaultPageSize={13}
7. View the pane on the right to see the number of rows change to "5 rows" (bug)
8. Change the code to be: defaultPageSize={20}
9. View the pane on the right to see the number of rows change to "20 rows" (expected)

**Expected behavior**
See above outcomes

**Codesandbox!**
This works on your current demo sandboxes

**Screenshots**

**Desktop (please complete the following information):**
 - OS: PC or Mac
 - Chrome
 - 70.0.3538.110 (Official Build) (64-bit)

**Comment by LaurieSReynolds** [comment]
Seeing the same thing when we set the default page size to 1000. 

The number of rows that are displayed is correct and the# of pages is correct, just the number of rows is incorrect.

Code sandbox based on the simple table example w/ 
          defaultPageSize={1000}

https://codesandbox.io/s/8zmx6kkrlj


![image](https://user-images.githubusercontent.com/18370991/49396076-17b1a400-f6ed-11e8-9ce4-204f1b66f3b1.png)

**Comment by tannerlinsley** [comment]
@jeppe-style is correct. I will accept a PR to add/update this functionality, or you can wait for v7 (a month or two). Thanks for the input!
