### ISSUE TITLE
When the field name has ".", the data will not be rendered.

### ISSUE THREAD

**Issue by hi-wendy** [react-tools/react-table#1211]
**Describe the bug**
When the field name has ".", the data will not be rendered.

**To Reproduce**
`columns=[{"Header":"1 + d.id","maxWidth":96,"accessor":"1 + d.id"}];
data=[{"1 + d.id":2,"key":0},{"1 + d.id":3,"key":1},{"1 + d.id":4,"key":2},{"1 + d.id":5,"key":3},{"1 + d.id":6,"key":4},{"1 + d.id":7,"key":5},{"1 + d.id":8,"key":6},{"1 + d.id":9,"key":7},{"1 + d.id":10,"key":8},{"1 + d.id":12,"key":9},{"1 + d.id":14,"key":10},{"1 + d.id":15,"key":11},{"1 + d.id":16,"key":12},{"1 + d.id":17,"key":13},{"1 + d.id":18,"key":14},{"1 + d.id":19,"key":15},{"1 + d.id":20,"key":16},{"1 + d.id":21,"key":17},{"1 + d.id":22,"key":18},{"1 + d.id":23,"key":19},{"1 + d.id":24,"key":20},{"1 + d.id":25,"key":21},{"1 + d.id":26,"key":22},{"1 + d.id":29,"key":23},{"1 + d.id":40,"key":24},{"1 + d.id":42,"key":25},{"1 + d.id":91,"key":26},{"1 + d.id":92,"key":27},{"1 + d.id":93,"key":28},{"1 + d.id":94,"key":29},{"1 + d.id":519,"key":30},{"1 + d.id":520,"key":31},{"1 + d.id":521,"key":32},{"1 + d.id":522,"key":33},{"1 + d.id":523,"key":34},{"1 + d.id":524,"key":35},{"1 + d.id":525,"key":36},{"1 + d.id":526,"key":37},{"1 + d.id":527,"key":38},{"1 + d.id":528,"key":39},{"1 + d.id":529,"key":40},{"1 + d.id":530,"key":41},{"1 + d.id":531,"key":42},{"1 + d.id":532,"key":43},{"1 + d.id":533,"key":44},{"1 + d.id":534,"key":45},{"1 + d.id":535,"key":46},{"1 + d.id":536,"key":47},{"1 + d.id":537,"key":48},{"1 + d.id":538,"key":49},{"1 + d.id":539,"key":50},{"1 + d.id":540,"key":51},{"1 + d.id":541,"key":52},{"1 + d.id":542,"key":53},{"1 + d.id":543,"key":54},{"1 + d.id":544,"key":55},{"1 + d.id":545,"key":56},{"1 + d.id":546,"key":57},{"1 + d.id":547,"key":58}]
`

**Expected behavior**
'1 + d.id' should show,but it wasn't show

**Codesandbox!**
`columns=[{"Header":"1 + d.id","maxWidth":96,"accessor":"1 + d.id"}];
data=[{"1 + d.id":2,"key":0},{"1 + d.id":3,"key":1},{"1 + d.id":4,"key":2},{"1 + d.id":5,"key":3},{"1 + d.id":6,"key":4},{"1 + d.id":7,"key":5},{"1 + d.id":8,"key":6},{"1 + d.id":9,"key":7},{"1 + d.id":10,"key":8},{"1 + d.id":12,"key":9},{"1 + d.id":14,"key":10},{"1 + d.id":15,"key":11},{"1 + d.id":16,"key":12},{"1 + d.id":17,"key":13},{"1 + d.id":18,"key":14},{"1 + d.id":19,"key":15},{"1 + d.id":20,"key":16},{"1 + d.id":21,"key":17},{"1 + d.id":22,"key":18},{"1 + d.id":23,"key":19},{"1 + d.id":24,"key":20},{"1 + d.id":25,"key":21},{"1 + d.id":26,"key":22},{"1 + d.id":29,"key":23},{"1 + d.id":40,"key":24},{"1 + d.id":42,"key":25},{"1 + d.id":91,"key":26},{"1 + d.id":92,"key":27},{"1 + d.id":93,"key":28},{"1 + d.id":94,"key":29},{"1 + d.id":519,"key":30},{"1 + d.id":520,"key":31},{"1 + d.id":521,"key":32},{"1 + d.id":522,"key":33},{"1 + d.id":523,"key":34},{"1 + d.id":524,"key":35},{"1 + d.id":525,"key":36},{"1 + d.id":526,"key":37},{"1 + d.id":527,"key":38},{"1 + d.id":528,"key":39},{"1 + d.id":529,"key":40},{"1 + d.id":530,"key":41},{"1 + d.id":531,"key":42},{"1 + d.id":532,"key":43},{"1 + d.id":533,"key":44},{"1 + d.id":534,"key":45},{"1 + d.id":535,"key":46},{"1 + d.id":536,"key":47},{"1 + d.id":537,"key":48},{"1 + d.id":538,"key":49},{"1 + d.id":539,"key":50},{"1 + d.id":540,"key":51},{"1 + d.id":541,"key":52},{"1 + d.id":542,"key":53},{"1 + d.id":543,"key":54},{"1 + d.id":544,"key":55},{"1 + d.id":545,"key":56},{"1 + d.id":546,"key":57},{"1 + d.id":547,"key":58}]
`

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by nigel-stewart** [comment]
I believe I am also experiencing this issue, if I understand correctly: 

When trying to access object properties with dot syntax (i.e. `accessor: "person.name"`), the field does not render.

**Comment by hi-wendy** [comment]
> I believe I am also experiencing this issue, if I understand correctly:
> 
> When trying to access object properties with dot syntax (i.e. `accessor: "person.name"`), the field does not render.

I came up with a temporary solution. Use regular expressions to replace the "." of accessor in columns with other characters and the key names in data with the same characters. My English is poor, I don't know if you can understand it.

**Comment by hi-wendy** [comment]
`
accessor: item.replace(/\./g,'#')


for(var i = 0;i<data.length;i++){
for (const key in data[i]) {
          if (/\./.test(key)) {
            data[i][key.replace(/\./g,'#')] = data[i][key];
          }
        }
}`

**Comment by tannerlinsley** [comment]
You must either use a functional accessor like `accessor: row => row['my.column.name']` or remove the periods and brackets from your property name. I would recommend the latter regardless, since it is never a good idea to have any type of object notation in a string property.
