### ISSUE TITLE
Pagination page input focus lost on backspace in Firefox

### ISSUE THREAD

**Issue by matejstrasek** [react-tools/react-table#1213]
**Describe the bug**
When clearing the page number in pagination, focus of the input is lost. Only after clicking again on the input, value of the page can be changed.

**To Reproduce**
1. https://react-table.js.org/#/story/simple-table
2. Click on input to change page number
3. Press 'backspace'
4. Focus of the input is lost

**Expected behavior**
When you remove page number, you should be able to type new value without clicking on the input again.

**Codesandbox!**
https://react-table.js.org/#/story/simple-table

**Screenshots**
<img width="173" alt="screenshot 2018-12-10 at 13 24 05" src="https://user-images.githubusercontent.com/9976413/49733022-c0797980-fc80-11e8-9424-46579f23013a.png">
<img width="162" alt="screenshot 2018-12-10 at 13 24 10" src="https://user-images.githubusercontent.com/9976413/49733024-c0797980-fc80-11e8-8269-64c08bcd22d1.png">

**Desktop:**
 - OS: macOS
 - Browser Firefox
 - Version 63.0.3

**Comment by tannerlinsley** [comment]
I would accept a PR to add/update/fix this functionality, or you can wait for v7 (a month or two). Thanks for the input!
