### ISSUE TITLE
Clear Single Filter

### ISSUE THREAD

**Issue by andrewnessinjim** [react-tools/react-table#1215]
**Is your feature request related to a problem? Please describe.**
I am trying to clear a single column filter on the click of a button.

**Describe the solution you'd like**
Using `<input type="search"/>` instead of `<input type="text"/>` for inputs that appear just below the header. This is just easy and accessible than implementing an own solution.

**Comment by tannerlinsley** [comment]
I would accept a PR to add/update/fix this functionality, or you can wait for v7 (a month or two). Thanks for the input!
