### ISSUE TITLE
Optimize Performance of Row Sorting with Key

### ISSUE THREAD

**Issue by janewang** [react-tools/react-table#1217]
**Enable Unique Key on Page Row**
The table currently recreates rows when user sorts the table which is not optimal.

`makePageRow` returns the following row with the key defined as below:
`<TrGroupComponent key={rowInfo.nestingPath.join('_')} {...trGroupProps}>`. 

nestingPath is `path.concat([i])`, where path is an empty array and i the index. We are unable to pass in a unique array for path due to the way makePageRow is being called. 

`makePageRow(d, i)` is called without allowing an optional parameter path: https://github.com/react-tools/react-table/blob/master/src/index.js#L848

**To Reproduce**
Sorting the table causes all rows to be recreated due to the lack of a unique key. Currently the key is based only idx. There is no option to pass in the path due to how makePathRow is called: https://github.com/react-tools/react-table/blob/master/src/index.js#L848

**Expected Behavior**
Each row should have a unique key such that sorting would not cause the creation of the rows again.

**Solution**
Update: 
`<TrGroupComponent key={ userDefinedData || rowInfo.nestingPath.join('_')} {...trGroupProps}>`.

**Comment by tannerlinsley** [comment]
I would accept a PR to add/update/fix this functionality, or you can wait for v7 (a month or two). Thanks for the input!

**Comment by mike391** [comment]
@janewang  have you written any code to improve this? Im also curious if this will help speed up my implementation

**Comment by tannerlinsley** [comment]
This is fixed in v7. You can try the alpha now (sandbox link in the Readme). You're in full control of row keys now. They are automatically created for you as a prop, but ultimately, you can use whatever key for a row you'd like, since you control all of the markup now.

**Comment by bsell93** [comment]
If I or someone else comes across this same issue (again in my case 😅) I would like to add you can use `getTrGroupProps` to set the `key` prop on the `TrGroupComponent` that will allow for better uniqueness across rows.


```
const getTrGroupProps = (tableState, row: {original: {...rowDataHere}}) => {
    const propsToReturn: { key?: string } = {};
    if (row?.original?.entity?.uniqueId) {
        propsToReturn.key = row.original.entity.uniqueId;
    }
    return propsToReturn;
};
```
