### ISSUE TITLE
Remove rightmost column - max-width buggard.

### ISSUE THREAD

**Issue by JumpinJackFlash** [react-tools/react-table#1218]
Thank you Tanner for a very well laid out react component.  

I think I have found an issue.  I have a multi-column table.  When disabling the rightmost (n) column from view, the max-width property for what will become the rightmost (n-1) column does not get recomputed.  The column size itself expands as one would expect but the text within does not subsequently grow to fill all available space thus leaving text cut-off.

This may be browser dependent however.  The error exhibits on Firefox.  Under Chrome, the 2nd column gets resized and the error is not apparent.

1. Use Firefox
2. Have a multi-column table for which you can dynamically enable/disable the displaying of selected columns.
3. Hide the rightmost column.
4. Observe that the new rightmost column does not expand the displayed text properly.
5. Disabling the max-width css property for the cell causes the text to fill all available space.

**Expected behavior**
Text should expand to fill the fully displayed column width.

**Codesandbox!**
Too much code required to reproduce....

**Screenshots**

[Screenshot-1 - the column that will exhibit the error is the 'Keyword-List'](https://cdn-eval.asteriondb.com/streaming/stream_object?Y24LX5GSEDB3HDX5YD0ZBDLUIOPVL01E)

[Screenshot-2 - after disabling the displaying of the 'view' column, you can see how the 'Keyword List' column has grown in size but the text within does not expand to fill the available space.
](https://cdn-eval.asteriondb.com/streaming/stream_object?17FEJ9RG127L4FEUG51BEV0ZBTN4KF2M)

**Desktop (please complete the following information):**
 - OS: Fedora
 - Browser Firefox
 - Version: Firefox 64 - Fedora 27

**Comment by tannerlinsley** [comment]
My guess is that you have either a `width` or `maxWidth` set on the column that is holding it back from filling the space.

Reopen if you find otherwise or need more help.
