### ISSUE TITLE
For a specific row merge two columns or for a specific column merge two cells.

### ISSUE THREAD

**Issue by sireeshav** [react-tools/react-table#1219]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by tannerlinsley** [comment]
I would accept a PR to add/update/fix this functionality, or you can wait for v7 (a month or two). Thanks for the input!

**Comment by AmareshB** [comment]
Is there a such a feature present now?
