### ISSUE TITLE
Table height at 100% of window

### ISSUE THREAD

**Issue by burtonator** [react-tools/react-table#1222]
First, LOVE react-table....

We use it in Polar:

https://getpolarized.io/

If you want to link to us in a "powered by" section we'd be honored !

Anyway.  I'd like the ability to set the number of items variable and computed based on the page height.

here's a screenshot below.  This way I could resize the window and the height would just adjust along with the footer.  Then I could paginate directly.

Even better, some type of 'scroll window' such that I can paginate through large numbers of records by just using a scroll bar (virtual scrolling I think it's called)

![image](https://user-images.githubusercontent.com/45447/50368605-5ba30680-053f-11e9-9fcd-b9491644ea51.png)

**Comment by tannerlinsley** [comment]
In the next major version (v7) you'll be able to do custom rendering and pagination control very easy. Stay tuned :)

**Comment by GeorgeCodeHub** [comment]
Hello there. Is this issue covered or did you focus on another direction? I'm asking because I can't seem to find a working example.
