### ISSUE TITLE
Sorting gives empty lines/empty results on the top

### ISSUE THREAD

**Issue by PranavBhatia** [react-tools/react-table#1224]
As shown in the image below, it returns the empty cells first, and then the ones with data.

<img width="360" alt="screen shot 2018-12-25 at 8 48 18 am" src="https://user-images.githubusercontent.com/30525912/50423335-ed519300-0821-11e9-80f3-21e09812fa80.png">

**Comment by tannerlinsley** [comment]
You can override the sorting function if you'd like, or I would accept a PR to add/update this functionality, or you can wait for v7 (a month or two). Thanks for the input!
