### ISSUE TITLE
Keyboard navigation... 

### ISSUE THREAD

**Issue by burtonator** [react-tools/react-table#1226]
It would be nice if react-table had support for keyboard navigation - or at least an example on how to set it up.

I looked at getTdProps and getTrProps and those don't work with onKeyDown.

**Comment by tannerlinsley** [comment]
I would accept a PR to add/update this functionality, or you can wait for v7 (a month or two). Thanks for the input!

**Comment by t3db0t** [comment]
Did anyone ever take a stab at this?

**Comment by GuptaSiddhant** [comment]
This can add basic keyboard navigation. More cases can be added to switch for row selection, expansion and click.
https://github.com/tannerlinsley/react-table/discussions/2752#discussioncomment-192558
