### ISSUE TITLE
IE11 display issues 

### ISSUE THREAD

**Issue by paigeflourin** [react-tools/react-table#1227]
i get this extra space below my table on IE: but it does not happen on any other browsers:

![image](https://user-images.githubusercontent.com/6951524/50634843-cebe6b00-0f8a-11e9-9390-55db64787d65.png)

```
<ReactTable 
                  data={this.state.qnaActionHistory } 
                  PaginationComponent={Pagination}
                  columns={[.......]}
                  pageSize={pgSize}
                  className="-striped -highlight"
                />
```

**Comment by whitesnow9291** [comment]
Hi @paigeflourin 
I got exactly same issue in IE11.
How did you solve it?

Thanks
