### ISSUE TITLE
How to use the styles prop of column object?

### ISSUE THREAD

**Issue by snehjogani** [react-tools/react-table#1228]
i passed an object to the styles prop to the column i want to apply this style to as follows:

```
styles: { lineHeight: '20px' }
```
but it doesn't seem to work.

**Comment by snehjogani** [comment]
figured it out.
It was a mistake on my part.
apologies!

**Comment by nickwild-999** [comment]
@snehjogani What was that mistake? I have a similar error and cannot find out why
Thanks
