### ISSUE TITLE
[Question] Freeze first row, it should always remain first 

### ISSUE THREAD

**Issue by AEDmitriev** [react-tools/react-table#1235]
Hello,
I'm trying to use ReactTable, 
Wonder if there is any way to freeze first row of a table,

Example from Webix and it requires pro version :(
https://snippet.webix.com/42ce62fa

In my application server replies with array of data to be displayed.
First row is arrgegated row, it contains %, strings, numbers and arrays.
Filtering, sorting should be disabled for that row, it should be always displayed right after headers.

Is there any complete solution for me?
sorry for any mistakes :)

Thanks in advance

**Comment by tannerlinsley** [comment]
I will accept a PR to add/update this functionality, or you can wait for v7 (a month or two). Thanks for the input!
