### ISSUE TITLE
After using the pivot By. Cell property can't able to change the display value. Even it has no effect on Cell

### ISSUE THREAD

**Issue by rakibulalam** [react-tools/react-table#1237]
```
pivotBy={['parent_id', 'id']}
columns={[
	{
		accessor: 'parent_id',
		Cell:(...props)=>'Value Define'						
	},
	{
		accessor: 'id',						
	},
	
]}

```

**Comment by tannerlinsley** [comment]
It uses the `Pivot` and `PivotValue` renderers instead of `Cell`. Please refer to their usage in the docs. I will accept a PR to add/update this functionality, or you can wait for v7 (a month or two). Thanks for the input!
