### ISSUE TITLE
[Future-Issue] Problem with React concurrent mode

### ISSUE THREAD

**Issue by darkxeno** [react-tools/react-table#1238]
The state property currentlyResizing doesn't not return to a false value after a column resizing when using React in concurrent mode.

I have created a codesandbox where the issue can be reproduced by resizing one column:

https://codesandbox.io/s/ox81r862z6

Probably is not the only problem happening, i will update the issue if i encounter more connected side effects.

The issue can no be reproduced outside of the React concurrent mode.

Let me know if you need more info about this.

**Comment by tannerlinsley** [comment]
I will accept a PR to add/update this functionality, or you can wait for v7 (a month or two). Thanks for the input!
