### ISSUE TITLE
Shouldn't ReactTable.ref be Instance<T> ?

### ISSUE THREAD

**Issue by JoshMcCullough** [react-tools/react-table#1239]
**Describe the bug**
I believe the typings may not be correct for the `ref` property of a `ReactTable` component.

**To Reproduce**
1. using Typescript, add a `ReactTable` component and set the `ref` property similar to:

```
refReactTable: ReactTable

render() {
 return <ReactTable ref={instance => refReactTable = instance} />;
}
```

2.  attempt to call `refReactTable.fireFetchData` and you'll see that `fireFetchData` does not exist on `ReactTable` (it exists on `Instance` instead)

**Expected behavior**
`fireFetchData` should be defined on the `ref`.

**Comment by JoshMcCullough** [comment]
Note that to get around this issue, you can do ...

```
<ReactTable ref={instance => {
    this.refReactTable = instance as ReactTableInstance<Project>;
}} />
```

**Comment by tannerlinsley** [comment]
The types for RT are definitely out of date. I will accept a PR to add/update this functionality, or you can wait for v7 (a month or two). Thanks for the input!
