### ISSUE TITLE
Accept forwardRef as component prop

### ISSUE THREAD

**Issue by nnishimura** [react-tools/react-table#1240]
**Describe the feature**
Getting a warning on component props (e.g. TableComponent) when a styled component is passed. Can reproduce with styled component v4+ or emotion v10+.
This is because it's wrapped with forwardRef.

**Describe the solution you'd like**
Add custom prop-type for forwardRef. Something like this: https://github.com/aragon/aragon-ui/pull/296

**Additional context**
Prop-type does not have a support for forwardRef right now: https://github.com/facebook/prop-types/issues/200

**Comment by tannerlinsley** [comment]
I will accept a PR for this functionality, or you can wait for v7 (a month or two). Thanks for the input!
