### ISSUE TITLE
Contextmenu support

### ISSUE THREAD

**Issue by fearintino** [react-tools/react-table#416]
## Adding contextmenu support

Can you **explain the best way** to add contextmenu support to rows? I think it is **wrap row component with handler**. If i think right, please explain **how i can manualy render row with some wrapper** in right way

I want try to [use this library](https://github.com/vkbansal/react-contextmenu)

Thank you!

**Comment by tannerlinsley** [comment]
Please ask this question in the slack channel :) https://react-chat-signup.herokuapp.com/

**Comment by gewesp** [comment]
Has this been answered or support added?  The link in the reply from August 8, 2017 is broken.

**Comment by gewesp** [comment]
Test
