### ISSUE TITLE
onFetchData(state) doesn't seem to hold target state

### ISSUE THREAD

**Issue by alessbelli** [react-tools/react-table#418]
## Problem Description
I am using react-table 6.0.2, and using redux to hold a single state across my app.
I have a connected component which maps part of the state to props (most of the parameters I need to control the table), and passes those down to a component which only holds the react-table, and the functions that I have defined in order to work with it.
I have an onFetchData which seems to take as parameters the (target?) state and which allows me to query an api for new data.

For now I am only interested in pagination, so I expect that coming from the first page, when I call onFetchData from a click on the 'next' button, the target state will hold the second page (actually, page # 1 instead of 0), so that I can call my api action getData({ page: 1, pageSize: 5}).
Instead, the state passed in props to onFetchData contains page=0, so have basically no way of knowing what action to take.

By the way I have also tried something simiilar with changing page size, but the same behavior happens (no target pageSize) so I don't know how I can change the pageSize. The action does fire, but it takes as parameters the 'current' state, so obviously the result stays the same.

Am I doing something wrong here? 

## Steps to Reproduce
not sure if necessary to go all the way but:
1. Set up actions/reducers to have a fetchData action change data in the redux store
2. build a component which gets called by its  container with all the right props from the state
3. inside this component, have a ReactTable component with onFetchData that calls a function to trigger the fetchData action, or console.log(state) inside onFetchData
4. try to change page

**Comment by tannerlinsley** [comment]
Please update to the latest release and try again

**Comment by alessbelli** [comment]
I have updated, and the issue was still there.
However, I have explored the entire props, and it seems that onFetchData(state, instance) does hold the target state, but it is inside the instance object under instance.state. I'm not sure therefore if it is expected behavior, but simply changing my call to take page data from instance.state instead of state solved the issue for me. It probably does to under 6.x, I just haven't tried downgrading the package again.

I'm not sure if the documented example inside react story would work - maybe it does because of the bound state - but maybe you could do it without binding states and simply taking target state from the instance prop as I did, and it would work however the component is written.

Thank you very much nonetheless, this library is amazing!

**Comment by tannerlinsley** [comment]
I'll improve the docs. Thanks!
