### ISSUE TITLE
text overflow should.... something? 

### ISSUE THREAD

**Issue by gregglind** [react-tools/react-table#419]
## Problem Description

For long text fields and such, it would be nice to say "give this as much vertical room as it needs"

Maybe this is already configurable and I just haven't found it!

**Comment by tannerlinsley** [comment]
This is possible, and should be possible with one style change.  Cell styles are set to `whitespace: no-wrap` by default. However, if you change it to `whitespace: normal`, you will see the text wrap inside of the cell width. :)

**Comment by mnieber** [comment]
I needed this solution, works great! I would put this trick into the main documentation (or make it a cell property)
