### ISSUE TITLE
How to access to a row ref?

### ISSUE THREAD

**Issue by Kimel1** [react-tools/react-table#420]
I'm trying to access like that 
in   `getTrProps={(params, rowInfo) => {}}`
```
                onClick: () => {
                  this.someFunction(rowInfo, params.TableComponent);  // or params.TableComponent() or blabla
                }
```
and got different errors. 
I need to get tr ref in  onClick and pass it. (I want to release "scroll to row" functionality) 
so I need ref to call scrollIntoView()

**Comment by Kimel1** [comment]
I'v found very rough "solution"

in return set id: 'someId' and then in function use document.getElementById('someId') to get node. 

But I still looking to more react-style solution

**Comment by tannerlinsley** [comment]
Yeah, I'm not sure exactly how this would work. We would probably need to build in the capability to use a `ref` in getProps somehow. For now your solution is probably the best way to go about it.

**Comment by DiegoAlbertoTorres** [comment]
Just wanted to +1 this, I have the exact same use case as @Kimel1. Thanks for the workaround @Kimel1 !

**Comment by joeellis** [comment]
We also ran into this issue - +1 for a non-`document` related fix if it's possible.

**Comment by nuno-ferrao** [comment]
Would also like to see a solution for this ! Need to implement a similar use case.

**Comment by lukasvice** [comment]
Here's my approach. I created a new table feature to store the refs of the rows and cells inside the `row` and `cell` objects of TanStack Table. The refs have to be set when the table is rendered. Then you can access the tr/td elements wherever you have the `row` and `cell` object.

Check out this CodeSandbox: https://codesandbox.io/p/sandbox/nervous-bush-dkv4n5
