### ISSUE TITLE
Accessing a record id to pass as props to an href in another column

### ISSUE THREAD

**Issue by j0mueller** [react-tools/react-table#422]
## Problem Description
I'm using react-table with a Ruby on Rails backend. I've set up the table without a record ID column. But I'd like to access the id to use to set params in a link on another column. I'm not sure how to grab it and feed it into the link.

## Code Snippet(s) or Codepen (http://codepen.io/tannerlinsley/pen/QpeZBa?editors=0010)
```
  const columns = [{
        Header: 'Name',
        accessor: 'name',
        minWidth: 150,
        Cell: props => <a href={`/hikes/id`}>{props.value}</a>
}, { ...
```
I've tried setting the id placeholder above as props.id and this.state.hikes.id, but those are not defined. An alternative would be to have the whole row be clickable with a link to another page, but I'm not sure how to do that either.

Thanks for your help!

## System Information
* **Chrome v59.0.3071.115**
* **Node 7.10.0**
* **OS 10.11.6**
* **NPM 5.3.0**
* **Yarn 0.27.5**

**Comment by tannerlinsley** [comment]
You can access the original row in a renderer via the `props.original` property.  Example: https://codepen.io/tannerlinsley/pen/yobpxq?editors=0010
