### ISSUE TITLE
Clicking the next or previous button renders the table twice?

### ISSUE THREAD

**Issue by JHRms** [react-tools/react-table#423]
When I click 'next' on the table, the table renders and the page size and page index changes. But then it renders again and the page size and index reset. Any idea why this happens and a fix I could? I need these values to stay rather than reset.

**Comment by tannerlinsley** [comment]
Please post your code

**Comment by JHRms** [comment]
`<ReactTable`
      
`columns={ columns }`
     ` data={ documents }`
      `manual`
      `pages={ store.geState().pages }`
      `page={ store.geState().page }`
      `onFetchData={(state, instance) => {`
        `    DocumentActions.fetchDocs(state.pageSize, instance.state.page, state.sorted, state.filtered);
      }}`
`    />`

**Comment by tannerlinsley** [comment]
@JHRms, you are using the `page` prop, but never updating it.  If you use the `page` prop, you should almost always accompany it with `onPageChange={newPage => this.setState({page: newPage}}` (or similar way of updating your external state). I would suggest removing the `page` prop altogether for your example.

Note: If you have more questions about implementation, please join the slack channel at https://react-chat-signup.herokuapp.com. Post your code in a question, and you will receive ample help :). We try our best to reserve github issues for bug reports and feature requests.
