### ISSUE TITLE
Saving filtered rows instance

### ISSUE THREAD

**Issue by snirlugassy** [react-tools/react-table#424]
Hey All!
How can I access the currently visible rows?
I have another component that is responsible to export the visible rows.
In previous version i used "onChange", but on version 6 for some reason it is not working.
Thanks.

**Comment by tannerlinsley** [comment]
At any moment, you can use a react `ref` on `<ReactTable/>` to get the table instance. Then use `ref.getResolvedState()`, which will return the entire table state for your own maniacal plans :)

Note: If you have more questions about implementation, please join the slack channel at https://react-chat-signup.herokuapp.com. Post your code in a question, and you will receive ample help :). We try our best to reserve github issues for bug reports and feature requests.

**Comment by snirlugassy** [comment]
Hey Tanner,How can I join the slack?

Regards,
Snir Lugassy



On Wednesday, August 9, 2017, 6:02:18 PM GMT+3, Tanner Linsley <notifications@github.com> wrote:


Closed #424.
