### ISSUE TITLE
Filter on hidden column

### ISSUE THREAD

**Issue by amoghpalnitkar** [react-tools/react-table#425]
## Problem Description
This might be a niche requirement, but I want to filter on a column which has property show:false. I am applying a custom filter to the column since my filter dropdown is outside of the React Table component.

Is there anyway I can achieve this?

Thanks!

**Comment by tannerlinsley** [comment]
Since this is more of an implementation question and not an issue or bug,
we suggest you use our [slack channel](https://react-chat-signup.herokuapp.com/) to ask for more assistance. Thanks!
