### ISSUE TITLE
onFetchData

### ISSUE THREAD

**Issue by JHRms** [react-tools/react-table#428]
In the onFetchData prop, what is the difference between `state` and `instance.state`?

**Comment by tannerlinsley** [comment]
@JHRms, if you have questions about the api, please join the slack channel and ask there. Only create issues if you have found unexpected behavior after following the documentation. If you have questions about implementation or need help achieving something that isn't outlined in the docs, use the slack organization to ask for help.

Short answer, there is no difference.
