### ISSUE TITLE
How to insert a column "More actions"

### ISSUE THREAD

**Issue by be-next-hotdog** [react-tools/react-table#431]
Hello, folks,
Just a simple, I wonder how to compose a column which consist merely customized data (a string or a 'more action' button for example) ? 

Thx a lot. :)

**Comment by pwhipp** [comment]
You can annotate your columns, adding new ones for any purpose. Here's a snippet adding a column to add a selection checkbox:

```
selectedColumn = {
        id: '_selected',
        Header: <input type="checkbox"
                       checked={allSelected()}
                       onChange={() => setAllSelected()}
                       ref={input => {if (input) input.indeterminate = someSelected()}} />,
        sortable: false,
        filterable: false,
        resizable: false,
        width: 30,
        Cell: ({original}) => (original) ?
            <input type="checkbox"
                   checked={isSelected(original)}
                   onChange={() => setSelected(original)} /> :
            <span />}
columns = [selectedColumn, ...columns];
```

**Comment by tannerlinsley** [comment]
Since this is more of an implementation question and not an issue or bug,
we suggest you use our [slack channel](https://react-chat-signup.herokuapp.com/) to ask for more assistance. Thanks!
