### ISSUE TITLE
Hide or remove Page number and  Number of Rows

### ISSUE THREAD

**Issue by masagarino** [react-tools/react-table#434]
## What version of React-Table are you using?
Your bug may already be fixed in the latest release. Run `yarn upgrade react-table`!
Place your version here...
Version 6 
## What bug are you experiencing, or what feature are you proposing?
Please include a detailed explanation here...

I have some concern if there is some point we can hide or remove the Page number or the Number of rows below?

**Comment by tannerlinsley** [comment]
You can remove or override the pagination component very easily. Since this is more of an implementation question and not an issue or bug,
I suggest you join our [slack channel](https://react-chat-signup.herokuapp.com/) to ask for more assistance. Thanks!
