### ISSUE TITLE
Set custom search term value programmatically

### ISSUE THREAD

**Issue by Drillan767** [react-tools/react-table#435]
Hello, i'm currently finishing some last features in my React-Table, and managed to make a tag system work. However, I'd like to be able to set the search box equal to what the user just clicked on. Here is my code:

``` javascript
{
    Header: 'Tags',
    accessor: 'tags',
    id: 'tags',
    Cell: row => {
        let tags = row.value.replace(/[^a-zA-Z0-9\s]/g, "");
        let tag = [];

        // Sets the tag in a <span> element, and adds a 'onClick' function with the value as a key
        tags.split(' ').map(function(value) {
            tag.push(
                <span 
                    onClick={(e)=>setFilter(e, value)} 
                    className="tag-name" 
                    key={value}
                >
                    {value}
                </span>);
        });
        // On click, gets the current event and the tag's key , then set it as search item
        function setFilter(e, value) {
            console.log(value); // return tag's value
        }

        // Ads '<br />' every three tags
        for(let i = 0; i <= tag.length; i++){
            if(i % 3 === 0 && i !== 0) {
                tag.splice(i, 0, <br key={i*i} />);
            }
        }

        return <div style={{lineHeight: '30px'}}>{tag}</div>;

    },

    filterMethod: (filter, row) => {
        const tags = row[filter.id].replace(/[^a-zA-Z0-9\s]/g, "");
        let tag = [];
        tags.split(' ').map(function(value) {
            tag.push(value);
        });

        // Allows getting results while starting to type a tag's name
        return tag.some(
            function(v){
                return v.indexOf(filter.value)>=0
            }
        )
    }
} 
```
So I'd like to allow the user to, by clicking on a tag, set it as a search element and get results from this search.

I've been testing your filterMethod function enough to understand that `filter.value` contains what the user is looking for, so I'm looking for a way to customize it just enough to allow me to set is as I want.

Is there a way to do so?

Thank you in advance

**Comment by tannerlinsley** [comment]
There are plenty of ways to do this (including entirely replacing the filter component with your own). 
Since this is more of an implementation question and not an issue or bug,
I'd suggest you join our [slack channel](https://react-chat-signup.herokuapp.com/) to ask for more assistance. Thanks!
