### ISSUE TITLE
Features:Request 

### ISSUE THREAD

**Issue by kamarajuPrathi** [react-tools/react-table#436]
1.Row span and Column Span ? 
2.Dragging Rows ?
3.Copy data and paste in a column ?
4.Import and Export Csv/excel data 
5. Custom styling themes (predefined)

Please let me know if these can be supported ?

**Comment by tannerlinsley** [comment]
First, read the Readme. It will answer most of those questions. Second, you should visit our [slack channel](https://react-chat-signup.herokuapp.com/) to ask for more assistance on any remaining questions you have. Thanks!

**Comment by kamarajuPrathi** [comment]
This was posted before I asked in slack . Thanks

**Comment by tannerlinsley** [comment]
👍
