### ISSUE TITLE
Add event listener to cell

### ISSUE THREAD

**Issue by joelrorseth** [react-tools/react-table#437]
Hey guys, I'm trying to implement a feature where the user can long-press any cell in the row and it will change the background color for every cell in that row. I will also need to set the text in a predetermined column in such a row whenever this occurs.

Is there any equivalent to adding an event listener directly when rendering the cell? Working with the DOM to obtain the cells has proven to be difficult. I am currently setting the *className* using the *index* so I may be able to change all cells in the row at once? This is my cell rendering code eventually passed to *columns*:

```
renderEditable (cellInfo) {

    var cellClass = "checklist-row-" + cellInfo.index;
    var col;
    var verified = cellInfo.original.VERIFIED;

    if (verified == "YES") { col = '#baffbe';}
    else if (verified == "NO") { col = '#ff5e59'; }
    else { col = '#f9ff87'; }

    return (<div className={cellClass} style={
      {
        backgroundColor: col,
        color: 'black',
        width: "100%",
        height: "28px",
        fontSize: "12px",
        padding: "6px",
        borderStyle: "solid",
        margin: "0px",
        transition: 'all .2s ease-out',
        overflow: "hidden"
      }
    } contentEditable suppressContentEditableWarning onBlur={(e) => {

      // Extract new value, row and column accessor id of changed cell
      var row = cellInfo.index
      var column = cellInfo.column.id
      var newValue = e.target.textContent;

      this.updateChecklistAttribute(row, column, newValue);

    }}>{this.state.data[cellInfo.index][cellInfo.column.id]}</div>)
  }
```
Thanks in advance for your help.

**Comment by s7dhansh** [comment]
Why not add an event on the `div.{cellClass}` itself?

**Comment by tannerlinsley** [comment]
Since this is more of an implementation question and not an issue or bug,
we suggest you use our [slack channel](https://react-chat-signup.herokuapp.com/) to ask for more assistance. Thanks!
