### ISSUE TITLE
is it possible to create a crosstable using react-table

### ISSUE THREAD

**Issue by christoph88** [react-tools/react-table#439]
Sorry about this not being a bug request but I was wondering if it is possible to create a crosstable using react-table? Could you perhaps give a few pointers to get me started.

I was looking at your pivot table option but the problem here is I cannot really display data side-by-side and if I want to see the differences I need to expand the rows which is not really useful in my use case.

**Comment by tannerlinsley** [comment]
I'm not entirely sure what you're referring to, but my guess would be know. 

Since this is more of an implementation question and not an issue or bug,
I suggest you use our [slack channel](https://react-chat-signup.herokuapp.com/) to ask for more information on this. Sounds cool! Thanks!
