### ISSUE TITLE
Freeze/Collapse failures?

### ISSUE THREAD

**Issue by Crpt774** [react-tools/react-table#441]
Version: 6.5.3
Use of freezeWhenExpanded and collapseOnPageChange are failing when combined with: (
```
data: this.state.data,
                    columns: columns,
                    defaultPageSize: Object.keys(parsedTradeData).length > 25 ? 25 : Object.keys(parsedTradeData).length,
                    showPagination: true,
                    freezeWhenExpanded: true,
                    className: '-striped -highlight table',
                    collapseOnDataChange: false,
                    collapseOnPageChange: true,
                    collapseOnSortingChange: true,
                    defaultSorted: [{
                        id: 'strategy',
                        desc: false
                    }],
```
) and custom subcomponents. 

as such, I was wondering if there were any known failures for these settings, or if I was even correct in my  thoughts on their use (couldn't see them in the docs beyond in default settings)? 

My assumed uses:
freezeWhenExpanded should prevent pagination when a subcomponent is open
collapseOnPageChange should auto close the subcomponent when the page is changed

I mainly asked as I'm aware that collapseOnSortingChange actually resets the table to page one on sort, which seems somewhat counter intuitive to me.

the data is sourced from a Websocket, and we have had to add a delay on opening to ensure the data actually shows. could that be causing this, or was I wrong in my interpretation of the settings use?

Thanks,

Jack.

**Comment by tannerlinsley** [comment]
Are you still having this issue Jack?

**Comment by Crpt774** [comment]
I'm afraid so,

Should also mention that we are now using a local version rather than the CDN after a number of issues with a few smaller CDNs recently, but I can update as needed, and we are running the latest version. 

and yeah, every time I switch the sorting, it works, and ends up breaking because that data was never requested (the data has to be requested only when required as some tables have 1000s of rows, and the WS server cannot handle it.)

**Comment by tannerlinsley** [comment]
This should be fixed in the latest version.
