### ISSUE TITLE
How to customize sort icon in header cell?

### ISSUE THREAD

**Issue by prettyGIT** [react-tools/react-table#444]
I am wondering if it is possible to custom sort icon

Currently sort icon is defined as below
.ReactTable .rt-thead .rt-th.-sort-asc, .ReactTable .rt-thead .rt-td.-sort-asc {
    -webkit-box-shadow: inset 0 3px 0 0 rgba(0,0,0,0.6);
    box-shadow: inset 0 3px 0 0 rgba(0,0,0,0.6);
}

I want to change it into arrow up/down icon corresponding to the sort order

**Comment by tomcohen** [comment]
`.ReactTable{
    .rt-thead{
       .rt-th {
            &.-cursor-pointer {
              > div {
                &:first-child {
                  &:after {
                    display: inline-block;
                    content: ' ';
                    position: relative;
                    left: 6px;
                    top: 2px;
                    width: 14px;
                    height: 12px;
                    background-image: url('../img/Sort_arrow.svg');
                    background-repeat: no-repeat;
                  }
                }
              }
            }
            &.-sort-asc{
              box-shadow: none;
              >div {
                &:first-child {
                  &:after {
                    background-image: url('../img/Sort_arrow_az.svg');
                  }
                }
              }
            }
            &.-sort-desc{
              box-shadow: none;
              >div {
                &:first-child {
                  &:after {
                    background-image: url('../img/Sort_arrow_za.svg');
                  }
                }
              }
            }
          }
    }
   }`


'../img/Sort_arrow_za.svg' - sorting desc arrow image
'../img/Sort_arrow_az.svg' - sorting asc arrow image
'../img/Sort_arrow.svg' - not sorted column image

**Comment by tannerlinsley** [comment]
Since this is more of an implementation question and not an issue or bug,
we suggest you use our [slack channel](https://react-chat-signup.herokuapp.com/) to ask for more assistance. Thanks!

**Comment by kasarlavinaysrivastav** [comment]
was a solution for this? I am looking for one to build.. Please let me know if you have accomplished changing sort icons to arrows. thanks

**Comment by andrewaxelrod-ist** [comment]
A CSS Solution if you want to use a sort up/down icon. This solution is for resizable columns enabled. 

`.ReactTable .rt-resizable-header {
    padding: 6px 24px !important;
    -webkit-box-shadow: none !important;
    box-shadow: none !important;
}
 
.ReactTable .rt-resizer:before {
    display: inline-block;
    position: absolute;
    right: 25px;
    top: 3px;
    height: 18px;
    width: 18px;
    color: transparent;
    content: '.';
    background-size: 18px 18px;
    background-repeat: no-repeat; 
    opacity: 0.87;
}

.ReactTable  .rt-resizable-header-content:after {
    position: absolute;
    right: 8px;
    top: 3px;
    height: 18px;
    width: 18px;
    z-index: 120;
    color: transparent;
    content: '.';
}

.ReactTable .rt-th.-sort-asc .rt-resizer:before {
    background-image: url(data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTgiIGhlaWdodD0iMTgiIHZpZXdCb3g9IjAgMCAxOCAxOCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMTAgMTVWNmw0IDQgMS0xLTYtNi02IDYgMSAxIDQtNHY5eiIgZmlsbD0iIzMzMyIvPjwvc3ZnPg==);
}

.ReactTable .rt-th.-sort-desc .rt-resizer:before {
    background-image: url(data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTgiIGhlaWdodD0iMTgiIHZpZXdCb3g9IjAgMCAxOCAxOCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNOCAzdjkuMTNMNCA4IDMgOWw2IDYgNi02LTEtMS00IDQuMTNWM3oiIGZpbGw9IiMzMzMiLz48L3N2Zz4=);
}
`

**Comment by andrewaxelrod** [comment]
A CSS Solution if you want to use a sorting up/down icon. This solution is for resizable columns enabled. 

```
.ReactTable .rt-resizable-header {
    padding: 6px 24px !important;
    -webkit-box-shadow: none !important;
    box-shadow: none !important;
}
 
.ReactTable .rt-resizer:before {
    display: inline-block;
    position: absolute;
    right: 25px;
    top: 3px;
    height: 18px;
    width: 18px;
    color: transparent;
    content: '.';
    background-size: 18px 18px;
    background-repeat: no-repeat; 
    opacity: 0.87;
}

.ReactTable  .rt-resizable-header-content:after {
    position: absolute;
    right: 8px;
    top: 3px;
    height: 18px;
    width: 18px;
    z-index: 120;
    color: transparent;
    content: '.';
}

.ReactTable .rt-th.-sort-asc .rt-resizer:before {
    background-image: url(data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTgiIGhlaWdodD0iMTgiIHZpZXdCb3g9IjAgMCAxOCAxOCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMTAgMTVWNmw0IDQgMS0xLTYtNi02IDYgMSAxIDQtNHY5eiIgZmlsbD0iIzMzMyIvPjwvc3ZnPg==);
}

.ReactTable .rt-th.-sort-desc .rt-resizer:before {
    background-image: url(data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTgiIGhlaWdodD0iMTgiIHZpZXdCb3g9IjAgMCAxOCAxOCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNOCAzdjkuMTNMNCA4IDMgOWw2IDYgNi02LTEtMS00IDQuMTNWM3oiIGZpbGw9IiMzMzMiLz48L3N2Zz4=);
}
```

**Comment by Aaron-Lei** [comment]
@andrewaxelrod  please tell me the steps on how to override the default react-table sorting css with the CSS solution you provided? Thanks

**Comment by andrewaxelrod-ist** [comment]
@Aaron-Lei You can place it anywhere and it should work.

**Comment by nmaties** [comment]
```.MyReactTableClass {
  .-sort-desc {
    box-shadow: none !important;
    &:before {
      content: "▼";
      float: right;
    }
  }

  .-sort-asc {
    box-shadow: none !important;
    &:before {
      content: "▲";
      float: right;
    }
  }
}```

**Comment by SimonVuong** [comment]
for a pure js way, you can do

```
import find from 'lodash/find';

const getTheadThProps = (table, row, col) => {
  const sortedCol = find(table.sorted, { id: col.id });
  const boxShadow =
    sortedCol ? `inset 0px ${sortedCol.desc ? -3 : 3}px 0px 0px ${colors.lightBlue}` : '';
  return {
    style: {
      ..._styles.thead,
      boxShadow,
    },
  };
};

      <ReactTable
        data={data}
        columns={columns}
        getTheadThProps={getTheadThProps}
      />
```

**Comment by binglinglanyun** [comment]
@SimonVuong got _styles and colors not found, what's these two variables?

**Comment by fekajin** [comment]
you can give it like  

<BaseTable
    components={components}
    fixed
/>

and 

const components = {
      SortIndicator:  customSortComponent,
   // ...other components
    };

after that you can define your custom sort icon 

CustomSort = (props) => {
    return (
      <div>
     {
     props.sortOrder === 'desc' ? ':)' : ':('
     }
      </div>
    );
  }

**Comment by whitesnow9291** [comment]
How to show both up, down arrow for only sortable enabled columns? so user can know those are sortable column.
For columns sortable=false should has no icon, only sortable columns will show default sort icon.

**Comment by manisha-planetrics** [comment]
@whitesnow9291 Did you find any solution?

**Comment by Lullabyq** [comment]
@manisha-planetrics, @whitesnow9291
you can use default option for column [disableSortBy](https://github.com/TanStack/table/blob/v7/docs/src/pages/docs/api/useSortBy.md#column-options)
