### ISSUE TITLE
.rt-resizer class z-index

### ISSUE THREAD

**Issue by stearm** [react-tools/react-table#448]
## What version of React-Table are you using?
6.0.5

## What bug are you experiencing, or what feature are you proposing?
Why `.rt-resizer` class in style.css has `z-index` setted to 10? 
I cannot click on the element which goes above the resizer (for example a datepicker).

**Comment by tannerlinsley** [comment]
Good point. We'll look at this.

**Comment by stearm** [comment]
@tannerlinsley any news about?

**Comment by rseningen** [comment]
@stearm I am having this issue as well.  I can't click on dates in a DatePicker because of the resizer.  Were you able to find a solution?

**Comment by stearm** [comment]
@rseningen just override z-index :)
