### ISSUE TITLE
Is there a way to define the next column to be sorted?

### ISSUE THREAD

**Issue by daniloprates** [react-tools/react-table#449]
For now the next column is the one on the left. I would like to sort the right one.

E.G.

* How it's now:

| COL A | COL B ▲ | COL C |
|-------|---------|-------|
| ***AAA***   | AAA     | BBB   |
| ***BBB***   | AAA     | AAA   |
| ***CCC***   | AAA     | CCC   |
| ZZZ   | BBB     | MMM   |
| YYY   | CCC     | NNN   |

* How I'd like to have it:

| COL A | COL B ▲ | COL C |
|-------|---------|-------|
| BBB   | AAA     | ***AAA***   |
| AAA   | AAA     | ***BBB***   |
| CCC   | AAA     | ***CCC***   |
| ZZZ   | BBB     | MMM   |
| YYY   | CCC     | NNN   |

**Comment by tannerlinsley** [comment]
You can easily override the sorting algorithm for the entire table, specific columns, and even use `sorted` as a controlled prop for multi-sort. 

For more help on this subject we suggest you use our [slack channel](https://react-chat-signup.herokuapp.com/) to ask for more assistance. Thanks!
