### ISSUE TITLE
Provide sorted data to components?

### ISSUE THREAD

**Issue by wmertens** [react-tools/react-table#457]
## What version of React-Table are you using?

None yet, evaluating

## What bug are you experiencing, or what feature are you proposing?

I would like to render a detail view when a row is clicked, replacing the table view, and in the view have prev/next buttons that go through the data in table-sorted order.

It seems to me that in order to get this data, I have to do the sorting myself and provide the sorted data to react-table? Would it instead be possible to provide the sorted data and the sort index to row components?

**Comment by tannerlinsley** [comment]
Yes it would

**Comment by gary-menzel** [comment]
This looks like it is related to #485.

**Comment by gary-menzel** [comment]
I have recently read this request again and think it should be done completely outside of ReactTable.  The description of this "form" based view is a completely different component.  So, it should be built as such and then the state in the parent component can manipulate the detail form.

I am regularly doing something similar (although, I am opening a side column with the detail view).

Not part of the design of react-table. Closing.

**Comment by gary-menzel** [comment]
NOTE: it is not the idea of passing the sorted data - it is just that the use-case described isn't enough to warrant making the changes.
