### ISSUE TITLE
how to get original data index? getting per page index only in "cell"

### ISSUE THREAD

**Issue by surenfeb14** [react-tools/react-table#463]
here, getting index value is same as per page pagination index

Cell: ({ original, row, index}) => {

## What version of React-Table are you using?
Your bug may already be fixed in the latest release. Run `yarn upgrade react-table`!
Place your version here...

## What bug are you experiencing, or what feature are you proposing?
Please include a detailed explanation here...

## Use https://codesandbox.io/s/X6npLXPRW (by clicking the "Fork" button) to reproduce the issue.
Then paste a link to your newly forked codesandbox here...

## What are the steps to reproduce the issue?
1. list the steps
2. to reproduce
3. the issue

**Comment by corymainwaring** [comment]
That is the way it works. If you want a unique ID across page boundaries, you should make the objects you send to ReactTable via the `data` prop have a unique id, and use that. In the cell renderer, you can use `original['<id field goes here>']' to access that id.

**Comment by tannerlinsley** [comment]
Since this is more of an implementation question and not an issue or bug,
we suggest you use our [slack channel](https://react-chat-signup.herokuapp.com/) to ask for more assistance. Thanks!
