### ISSUE TITLE
Creating custom cell components that use several row properties

### ISSUE THREAD

**Issue by softweave** [react-tools/react-table#468]
## What version of React-Table are you using?
6.5.3

## What feature are you proposing?
Clarify how to access several row properties in a custom column component.

I want to access several row properties in a custom cell component to render a link. Currently, my custom component looks like this:
```
                    columns={[
                        {
                            Header: "Name",
                            accessor: "name",
                            Cell: row => (
                                <Link className="scenarioDetailLink"
                                      to={row.linkDestination}
                                      id={row.linkName}>{row.name}</Link>
                            )
                        },
```
The generated elements look like:
<img width="425" alt="td" src="https://user-images.githubusercontent.com/2711933/29890387-6d074fc6-8d95-11e7-8db8-94565601b8ae.png">

What am I doing wrong?

**Comment by softweave** [comment]
After digging into the react-table source code, I changed my custom component to be:
```
                    columns={[
                        {
                            Header: "Name",
                            accessor: "name",
                            Cell: cellInfo => (
                                <Link className="scenarioDetailLink"
                                      to={cellInfo.row.linkDestination}
                                      id={cellInfo.row.linkName}>{cellInfo.row.name}</Link>
                            )
                        },
```

Now, the generated elements look like:
<img width="419" alt="td-2" src="https://user-images.githubusercontent.com/2711933/29891641-d1d99bee-8d99-11e7-8541-3c5be2a08df7.png">

I don't know where to go from here.

**Comment by softweave** [comment]
Replacing the Link component with html markup had no effect:
```
                        {
                            Header: "Name",
                            accessor: "name",
                            Cell: cellInfo => (
                                <a className="scenarioDetailLink"
                                   href={cellInfo.row.linkDestination}
                                   id={cellInfo.row.linkName}>{cellInfo.row.name}</a>
                            )
                        },
```

The generated anchor elements are missing id and href properties.

**Comment by softweave** [comment]
I got around link issues by adding:
```
getTdProps={(state, rowInfo, column, instance) => {
	return {
	    onClick: (e, handleOriginal) => {
	        if (column.id === "name") {
	            console.log("go to:", rowInfo.original.linkDestination);
	            this.props.router.push(rowInfo.original.linkDestination);
	        } else if (handleOriginal) {
	            handleOriginal()
	        }
	    }
	}
```

Can values other than the cell's accessor be used to render a custom cell component?

**Comment by tannerlinsley** [comment]
Since this is more of an implementation question and not an issue or bug,
we suggest you use our [slack channel](https://react-chat-signup.herokuapp.com/) to ask for more assistance. Thanks!

**Comment by danieltendaj** [comment]
Try this way:
`{
	Header: "Name",
	accessor: "name",
	Cell: cellInfo => (
		<a href={cellInfo.original.linkDestination}>
		{cellInfo.original.linkName}
		</a>
	)
}`
