### ISSUE TITLE
Can I pivot by matching both two columns

### ISSUE THREAD

**Issue by dinhtungdu** [react-tools/react-table#469]
## What version of React-Table are you using?
6.5.3

## What bug are you experiencing, or what feature are you proposing?
As the title, how can I do that? For example in the codesandbox I put later on this issue: How can I pivot by both Name and Subject? I want to see the mean score for every Subject of student name Tim. And by matching like that, I also can filter by Subject name. Any help is very appriciated. Thank in advanced!

## Reproduce the issue.
https://codesandbox.io/s/k932noo06v

**Comment by tannerlinsley** [comment]
Since this is more of an implementation question and not an issue or bug,
we suggest you use our [slack channel](https://react-chat-signup.herokuapp.com/) to ask for more assistance. Thanks!
