### ISSUE TITLE
Need one example of the following...

### ISSUE THREAD

**Issue by jkathir** [react-tools/react-table#473]
Need an html file with react-table with static json or html data with following

1. Read only grid as above without edit, delete and save option.
2. The grid with many export options - pdf, csv, excel, word etc.,
3. When the pagination is enabled - goto page option to navigate to particular page
4. Copy to clipboard and print option
5. Support quickest rendering for alteast 5,000 rows with page size as 10, 100, 500, 1000, 5000
6. Search all columns or individual columns
7. Export selected or all columns

Example grid
--------------
http://institut-de-genomique.github.io/Ultimate-DataTable/
https://w3lessons.info/2015/07/13/export-html-table-to-excel-csv-json-pdf-png-using-jquery/

Reference
-----------
1. http://2.bp.blogspot.com/-yTiytux2848/Vcj-b5FjyUI/AAAAAAAAdQk/8rzPAsyU4Dw/s1600/jQuery%2Bdatatables%2Bexport%2Bto%2Bpdf.png
2 . https://www.phpflow.com/wp-content/uploads/2015/09/export-table-data-toexcel-png-pdf.png
3. https://i.stack.imgur.com/XeCzz.png
4. https://stackoverflow.com/questions/45901407/static-data-grid-10k-records-with-search-pagination-export-options
5. https://datatables.net/extensions/scroller/examples/initialisation/large_js_source.html

**Comment by tannerlinsley** [comment]
This is not an issue or bug with the. we suggest you use our slack channel to ask for more examples and assistance. Thanks!
