### ISSUE TITLE
Table renders blank rows if data does not exist

### ISSUE THREAD

**Issue by tilomitra** [react-tools/react-table#474]
## What version of React-Table are you using?
v6.5.3 (latest as of writing this).

## What bug are you experiencing, or what feature are you proposing?
When rendering a table with pageSize > number-of-rows-in-table, additional blank rows are rendered.

## Use https://codesandbox.io/s/10j8k608l3 to reproduce the issue. 
Total data = 5 rows, but table renders 5 blank rows.  I would expect the table to render the `min(NumData, pageSize)`

## What are the steps to reproduce the issue?
1. Set total data < number of rows in table
2. View blank rows.

**Comment by tilomitra** [comment]
Btw, I really appreciate you creating this component. It has helped us a lot. 👍 Great work!

**Comment by hyanmandian** [comment]
I think that this #191  issue solve your problem

**Comment by tannerlinsley** [comment]
Indeed :)

**Comment by tilomitra** [comment]
Thanks a lot!
