### ISSUE TITLE
Props callback crashes on non-true return

### ISSUE THREAD

**Issue by C-Higgins** [react-tools/react-table#475]
## What version of React-Table are you using?
6.5.3

## What bug are you experiencing, or what feature are you proposing?
getTrProps and probably all the other get props callbacks will crash the component if returning a falsey value. This is not intuitive or documented. See example below

## Example
https://codesandbox.io/s/50lprj46mx
Intuitively you would think to just return nothing here if the row is undefined, but you must return something truthy.

## What are the steps to reproduce the issue?
Return void or falsey value from get props callback

**Comment by tannerlinsley** [comment]
On the next refactor I will normalize propCallbacks to not require this. For now, it is newly documented.
