### ISSUE TITLE
Custom sorting that depends on direction

### ISSUE THREAD

**Issue by nicodjimenez** [react-tools/react-table#476]
## What version of React-Table are you using?
6.5.3

## What bug are you experiencing, or what feature are you proposing?
I want to put all the rows with undefined values at the bottom, regardless of the sorting direction.  Is this feature supported? 

Thanks for the lovely library!

**Comment by tannerlinsley** [comment]
Yes it is. You can override the sorting function for both individual
columns and the entire table

**Comment by nicodjimenez** [comment]
Ok I get that, what I'm asking is how to override the sorting function for both ascending order as well as descending order, regardless of whether that's for a single column or the entire table.  The purpose being putting null elements on the bottom regardless of if you're sorting in ascending order or in descending order.

**Comment by flood4life** [comment]
It looks like it is possible for filtering via `filterAll` but not possible for sorting. @tannerlinsley is there any particular reason a similar option is not available for sorting? Perhaps a PR adding it would be welcome?

**Comment by bloomt** [comment]
I am looking for this exact same feature. Any updates?

**Comment by nicodjimenez** [comment]
@tannerlinsley I'm happy to make a PR for this if you're OK with that, also a few pointers before I dig into the code would be welcome.

**Comment by gary-menzel** [comment]
There's a problem I can see with changing how react-table works right now. At present, the "order" is not provided as react-table itself determines how to treat the return value from the sort function based on the internal order state. Providing the order in the call and then changing the algorithm to suit would then confuse the code inside react-table. For those of us who are relying on that default behaviour, it would break things.

**Comment by tannerlinsley** [comment]
Gary is correct. You can override the default sorting method for both the entire table and individual columns. This should suffice.

**Comment by flood4life** [comment]
@tannerlinsley I'm afraid you're missing the point here. It is impossible to define a relation between two objects that would make some group of objects (e.g., `null` objects) either greater or lesser than any other object depending on the direction (because sorting method doesn't know anything about direction). Hence, it is impossible to always place `null` objects at the top (or the bottom) of the sorted result. 
So, overriding default sorting method doesn't suffice.

**Comment by simon-bond** [comment]
This is an issue for me too. It's a very small change to the code to pass the sort direction, and it doesn't change the default behaviour.

**Comment by simon-bond** [comment]
Example usage that always sorts 0 to the bottom:

```javascript
sortMethod: (a, b, desc) => {
  a = (a === 0) ? (desc ? -Infinity : Infinity) : a;
  b = (b === 0) ? (desc ? -Infinity : Infinity) : b;
  if (a > b) { return 1; }
  if (a < b) { return -1; }
  return 0;
}
```

**Comment by flood4life** [comment]
@simon-bond I've already submitted an identical PR (https://github.com/react-tools/react-table/pull/383), but it was rejected (though I'm not sure why exactly).

**Comment by simon-bond** [comment]
So you did. I don't follow the explanation for its rejection either.
