### ISSUE TITLE
Make an API for react-table (request)

### ISSUE THREAD

**Issue by nzhtrtlc** [react-tools/react-table#477]
Hi @tannerlinsley and other contributers;

Can you make an API for the reac-table ?

I tried to filter my table in custom text input. But changing table data array is not fast as native filter function.
If you can provide an api it'll be very good for me and other users. At least add api for filter.
Example;

import ReacTable from 'react-table';

const reactTable = ReactTable.getInstance();

onFilter(val){
reactTable.filter(val); 
// this line can run the filterMethod that we define in component otherwise run as default.
}

I need something like that.

Thanks.

**Comment by tannerlinsley** [comment]
You can do this already. Use a ref to acquire the instance. Then use the instance programmatically.
