### ISSUE TITLE
Custom filter not working in example at react-table.js.org

### ISSUE THREAD

**Issue by jtlindsey** [react-tools/react-table#479]
## What version of React-Table are you using?
Repo example default from:
[https://react-table.js.org/#/story/custom-filtering](https://react-table.js.org/#/story/custom-filtering)

## What bug are you experiencing, or what feature are you proposing?
Learning about this react-table. So i went to the example site and tried out the custom-filtering.
[https://react-table.js.org/#/story/custom-filtering](https://react-table.js.org/#/story/custom-filtering)

## Use https://codesandbox.io/s/X6npLXPRW (by clicking the "Fork" button) to reproduce the issue.
https://react-table.js.org/#/story/custom-filtering

## What are the steps to reproduce the issue?
1. Go to [https://react-table.js.org/#/story/custom-filtering](https://react-table.js.org/#/story/custom-filtering)
2. Try to filter by first name or last name, enter one letter at a time and see it does not react as expected.

**Comment by tannerlinsley** [comment]
If you inspect the code, it is indeed working. It is `custom` because the `firstName` column is filtering if the name begins *and ends* with the letter. The second column filters using the `match-sorter` library, which is a fuzzy finder library.

**Comment by jtlindsey** [comment]
Here is a visual recording of what happens. See how typing d filters, and thien typing i clears the screen even though diamond is a valid result.

![record1](https://user-images.githubusercontent.com/7409277/30139625-f854971c-933c-11e7-91dc-cec34e0ffec1.gif)

**Comment by jtlindsey** [comment]
...i see
