### ISSUE TITLE
Resize column (except fist column) has a strange parallel behavior

### ISSUE THREAD

**Issue by othke** [react-tools/react-table#482]
version: 6.5.3

When column is resized for the first time (not the first one on the left), there is a strange parallel resize.
[
![resize_parallel](https://user-images.githubusercontent.com/7658882/30262593-d150ccce-96d1-11e7-929e-e20cadda827a.gif)
](url)

The behavior disappear after the first column was resized. Maybe this is due to the flexbox ?

**Comment by ldstein** [comment]
That's flexbox at work.

If a column has an undefined width, it will try and fill up all the available space. After manually resizing a column, it then has a defined width and it's width will no longer be dynamic.

**Comment by othke** [comment]
Sur, but we are not suppose to know the table is driving by flexbox. I will try look if this is possible to determine all the column width when the first is reiszed

**Comment by ldstein** [comment]
If you haven't already, have a look at #94 for some ideas.

You'll find you can pretty much override the default resize mechanism through a mixture of custom components and `getTrProps`/`getTdProps`

**Comment by tnrich** [comment]
@othke any luck with fixing this in user land? @ldstein can this be fixed by default?

**Comment by ldstein** [comment]
A simple solution is to specify widths for all your columns, except for one column where you leave the width undefined. The column with no fixed width will then expand to fill up the remaining space.

I feel React-Table made the right move by keeping it's column resizing algorithm light and in the CSS domain. I've tried too many other JS datagrids which had more fully featured resizing algorithms which never worked quite as well (complex DOM width calculations, resize detection, etc).

**Comment by mnieber** [comment]
@othke I ran into the same problem and it sufficed to give a width to the first column:

```
    const columns = [
      {
        Header: 'First',
        accessor: 'first',
        width: 400
      },
      {
        Header: 'Second',
        // etc, etc
```

**Comment by Pavel-Ropakov** [comment]
For me setting width only for first column didn't work.

**Comment by demptis82** [comment]
Make sure your columns have unique ID's and you wont run into this
