### ISSUE TITLE
"Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of `ReactTable`."

### ISSUE THREAD

**Issue by miguelmota** [react-tools/react-table#484]
```
proxyConsole.js:56 Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of `ReactTable`. See https://fb.me/react-warning-keys for more information.
```

getting warning about ReactTable

**Comment by Muedgar** [comment]
I get the same error but it's not working, I even tried this  "https://github.com/ubilabs/react-geosuggest/issues/328" but it still doesn't work for me maybe you can give it a try.

**Comment by gary-menzel** [comment]
ReactTable is very flex. Out of the box, this error does not happen. But, if you are overriding one of the many rendering options (Rows, Columns, even the whole table using functional rendering) it may be some code you have injected into ReactTable that is the "closest" trackable React component that it can report against.

**Comment by gary-menzel** [comment]
If you believe it to be a real issue with ReactTable code you should put up a codesandbox here so it can be duplicated.

**Comment by miguelmota** [comment]
ah you're right, it was a nested element causing the error message
