### ISSUE TITLE
ShouldComponentUpdate blocks the opening/closing of SubComponent

### ISSUE THREAD

**Issue by K-Sutton** [react-tools/react-table#486]
Hello,
I'm using shouldComponentUpdate to prevent the table from unnecessarily updating when there's nothing to update. However, when I check this, after some random time interval it'll lock the SubComponent so I can no longer update or open any other items.

Here's what I'm checking (I'm unable to put it into codesandbox as some of the dependencies is sent from the server):
`value: function shouldComponentUpdate(nextProps, nextState) {
if(!_.isEqual(this.props.data, nextProps.data)) {
                        return true;
                    }
                    if(!_.isEqual(this.state.data, nextState.data)) {
                        return true;
                    }
                    return false;
                }`

Thanks

**Comment by gary-menzel** [comment]
Well, opening and closing of the sub-component relies on a component update. You'll need to take that into account in some way. Are you totally convinced your need to manage shouldComponentUpdate ? It can get you into a lot of trouble. If you do, then maybe you should do in a high-up component (wrap react-table and allow it "always" update when it needs to) and hoist the update management to a higher component.
