### ISSUE TITLE
Only able to access data inside cell through row._original

### ISSUE THREAD

**Issue by DaveyEdwards** [react-tools/react-table#488]
## What version of React-Table are you using?
6.5.3

## What bug are you experiencing, or what feature are you proposing?
The only way I am able to access the data I need inside a table cell is row._original
This works, I am just concerned there may be something I am doing wrong or could have a potential future problem. 

```js
      { 
        Header: 'Name',
        id: 'name',
        accessor: s => s.name,
        Cell: props => <a onClick={() => {
          this.onStudyClicked(props.row._original)
        }
        }>{props.value}</a>,
      },
```

**Comment by tannerlinsley** [comment]
Use props.original

**Comment by DaveyEdwards** [comment]
Damn I thought that was one of the first things I had tried!  Don't think I waited long enough for the compile.  Thank you!

**Comment by KBiswas98** [comment]
const data = React.useMemo(() => _data, []);
