### ISSUE TITLE
How to implement filtering logic in React table?

### ISSUE THREAD

**Issue by shanky101** [react-tools/react-table#489]
Im using React Table to display data I receive from an API call. Currently I save the state locally and the table displays the data. I have added filtering of column values for two columns. My filtering logic is as follows:
```

<ReactTable
  data={tableData}
  noDataText="Loading.."
  filterable
  defaultFilterMethod={(filter, row) =>
    String(row[filter.id]) === filter.value}
    };
  }}
  columns={[
    {
      columns: [
        {
          Header: 'Name',
          accessor: 'Name',
          id: 'Name',
          Cell: ({ value }) => (value === 'group1' ? 
          'group1' : 'group2'),
          filterMethod: (filter, row) => {
            if (filter.value === 'all') {
              return true;
            }
            if (filter.value === 'group1') {
              return row[filter.id] === 'group1';
            }
            if (filter.value === 'group2') {
              return row[filter.id] === 'group2';
            }
          },
          Filter: ({ filter, onChange }) =>
            <select
              onChange={event => onChange(event.target.value)}
              style={{ width: '100%' }}
              value={filter ? filter.value : 'all'}
            >
              <option value="all">All</option>
              <option value="group1">Group1</option>
              <option value="group2">Group2</option>
            </select>,
        },
   }
```

As of now, the filtering rule is hard coded between two values. How to implement the filter logic so that the filtering is dynamic?(If there are 3 or 7 different values in a particular column, the dropdown should display all 7 values and filter should work based on any of the value selected).

**Comment by gary-menzel** [comment]
This is really not an "issue" for react-table. You seem to have the logic right in your Filter and filterMethod you just need to decide how to specify what the different options are and then use some type of switch statement in your filterMethod (or some type of reducer).

Your filterMethod has:
```
           if (filter.value === 'group1') {
              return row[filter.id] === 'group1';
            }
```
Why not just make it:
```
return row[filter.id] === filter.value;
```
That way your Filter component can have as many values as you like.
