### ISSUE TITLE
How I can filtering by hidden columns

### ISSUE THREAD

**Issue by arazumoff** [react-tools/react-table#491]
Hello anyway!

I need to do a filter for the table by hidden columns. I've found a method with changing the source code. How can I do that without any changes in the code?

**Comment by gary-menzel** [comment]
At this point in time, the only way I could find to do it was to "hack" the "hidden" column by not hiding it and just making the width be 0px and then disabling resizing and also removing the filter input box (so it is not accidentally clicked on).

**Comment by AAraozBAS** [comment]
was implemented this feature? I has 6.10 version and didn't work.

**Comment by philippemellenger** [comment]
It would be great to have this feature, it seems something very common.

**Comment by philippemellenger** [comment]
It would be great to have this feature. I feel like it is a common usecase, I found lots of issues talking about this but actually not solution.

**Comment by tannerlinsley** [comment]
v8 supports this as filters are not calculated using only visible columns, but any columns that have active filters in the filter state.

**Comment by jeg924** [comment]
@tannerlinsley How do I restrict the filter to only visible columns in v8?

**Comment by jeg924** [comment]
Right now I'm checking the row each time the function is called to check if the column is visible. But maybe there's a built in way that's more efficient?

```typescript
export const globalFilter: FilterFn<VSDataTableValue> = (
  row,
  columnId,
  filterValue,
  addMeta
): boolean => {
  const visibleCell = row
    .getVisibleCells()
    .find((cell) => cell.column.id === columnId);

  // Don't filter on invisible columns.
  if (visibleCell === undefined) {
    return false;
  } else {
    const search = filterValue.toLowerCase();

    const value = convertValueToString(visibleCell.getValue());

    const result = sequentialSearch(value ?? '', search);

    addMeta({ label: result.label });

    return result.valid;
  }
};
```
