### ISSUE TITLE
Disable pivot expand.

### ISSUE THREAD

**Issue by Romyeo** [react-tools/react-table#492]
How can i disable expand in pivot?
I used the "expander: false" but it didn't work.

**Comment by sedroar** [comment]
You have to set the Expander property of the column to null. Take this piece of code as a reference
`column.Expander = () => { return null; };`

**Comment by Romyeo** [comment]
Didn't seem to work, I was still able to expand the row

**Comment by sedroar** [comment]
Well, in that case, you should do what I did at last: I had to implement the handler for onExpandedChange event of React Table, to avoid expand in the corresponding case.

**Comment by I3igI3uilder** [comment]
This thread led me make this example:
[https://codesandbox.io/s/z2v5p0w6rp](https://codesandbox.io/s/z2v5p0w6rp)
