### ISSUE TITLE
How to obtain "the resolved width of this cell"?

### ISSUE THREAD

**Issue by mnieber** [react-tools/react-table#498]
The docs suggest that it's possible to obtain the resolved cell width:

```
All of these formats receive the following props:
width: '', // the resolved width of this cell
```

Unfortunately, I cannot figure how to get this value (also because I don't understand the bit about a `format` receiving a prop). Can someone give a short example?

**Comment by gary-menzel** [comment]
Well, the component itself does not store the resolved width of a cell as it uses flexbox to determine this. But, it does store the width of a cell if you size it with the resizer. Those values are already available in the react-table state (obtainable by various methods - I prefer calling getResolvedState on a ref instance of the component). Another way is to manage the resize state by passing an onResizedChange callback and then passing the resized value back into the component - you can siphon off the information in your callback to do something with the column size.

**Comment by mnieber** [comment]
Thanks for your reply, I was hoping that the width would somehow "just be available", without needing some extra tricks to get to it. But in any case, as it happens I don't need this information any more, so I will close the issue.
