### ISSUE TITLE
Sorting a column with a object containing strings and integers

### ISSUE THREAD

**Issue by JorisPhilipsen** [react-tools/react-table#501]
I'm currently using version 6.5.3 of the library. 

I've got a issue with the following: I've got a array of objects containing a person object which always has a age but not always a name. The name is a string and the age is a integer. 

`{
          id: 'person',
          Header: 'Person',
          accessor: a => a.person.name ? a.person.name : a.person.age,
   }`

I want to sort by name first (a-z) then sort by age (0-99). 

Here is a example: https://codesandbox.io/s/k28w4jqwm7

Here is a example with sortMethod: https://codesandbox.io/s/ymv48y6x31

Here is example where I turn the 'age' into a string https://codesandbox.io/s/ol87ypympz which proves sorting strings work.

What am I doing wrong?

**Comment by gary-menzel** [comment]
You should be splitting `person` into two columns and sorting them separately. You can create an accessor with dot notation. So you could have two columns: 1) with `accessor: 'person.name'`; and 2) with `accessor:'person.age'`. If you wanted, you could also have a group header above those and call it "Person". There are examples in the doco. I think trying to sort on both numbers and strings in the same column will just complicate things (you could do it with specialised sort routines though).

**Comment by JorisPhilipsen** [comment]
@gary-menzel the issue is that I have limited space for the table which is why I want to display the two field as one field. Do you have a example of a  specialised sort routine and what should I use as a id?

**Comment by gary-menzel** [comment]
Well - I think you already have everything you need in your examples. You need to decide what to display in the column based on if it is the Age or the Name. You need to do the same thing in the sort method before you decide how to sort.  If you have Age then sort by that as a number. If you have Name and Age then sort by a Name/Age combination (you could compose a string with name and age in both and compare those or you could first decided the -1,0,1 of the string and then decide the same for Age.

This is not really a react-table question or an issue with the code.

**Comment by JorisPhilipsen** [comment]
Thanks for clearing this up!
