### ISSUE TITLE
Issue when trying to expand a group of a second level pivot

### ISSUE THREAD

**Issue by sedroar** [react-tools/react-table#505]
## What version of React-Table are you using?
Your bug may already be fixed in the latest release. Run `yarn upgrade react-table`!
6.5.3

## What bug are you experiencing, or what feature are you proposing?
Nested pivoting is not working. When you assign an array of columns to pivot, you are able to expand the first level, but not the deeper ones.

I found that the problem is in the set method, of utils
`function set() {
  var obj = arguments.length > 0 && arguments[0] !== undefined ? arguments[0] : {};
  var path = arguments[1];
  var value = arguments[2];

  var keys = makePathArray(path);
  var keyPart = void 0;
  var cursor = obj;
  while ((keyPart = keys.shift()) && keys.length) {
    if (!cursor[keyPart]) {
      cursor[keyPart] = {};
    }
    cursor = cursor[keyPart];
  }
  **cursor[keyPart] = value;**
  return obj;
}`

When trying to assign value, cursor[keyPart], the cursor[keyPart] is true, instead of an object.

## What are the steps to reproduce the issue?
1. Have a React Table with an array of valid columns assigned to Pivot
2. Expand a group of the first pivot level. This works well
3. Try to expand a group of the second pivot leve. This doesn't work

**Comment by tannerlinsley** [comment]
Please refer to this working example. https://react-table.js.org/#/story/pivoting-aggregation
