### ISSUE TITLE
Support React 16

### ISSUE THREAD

**Issue by tobiaslins** [react-tools/react-table#511]
## What version of React-Table are you using?
6.5.3

## What bug are you experiencing, or what feature are you proposing?
If you are upgrading to the new react version (16.0.0) it will still install the peer dependency react 15.4.2. The application will crash.
You already fixed the issue in your master branch by adding `"react": "^15.x.x || ^16.x.x"` in `package.json`

It would be great if you can release a new NPM version with this change that we can migrate to the new react version!

Thank you

**Comment by kailaskore** [comment]
+1

**Comment by tannerlinsley** [comment]
Fixed

**Comment by pawarvijay** [comment]
trying to Use it with react 16 i got this error , am i missing any thing

```
tom-Macbook:myapp tom$ npm install react react-dom react-table --save
frontend-b2c@0.1.1 /Users/tom/myapp
├── UNMET PEER DEPENDENCY eslint-config-react-tools@^1.0.10
├── react@16.0.0
├── react-dom@16.0.0
└── react-table@6.7.4

npm WARN react-table@6.7.4 requires a peer of eslint-config-react-tools@^1.0.10 but none was installed.
tom-Macbook:myapp tom$
```

**Comment by gary-menzel** [comment]
@pawarvijay You can ignore that. It is really only a dev dependency (as linting only happens during the development build). It is only a warning but will probably be addressed in a later release.

**Comment by bugzpodder** [comment]
please do address this in a later release as any warnings will break npm shrinkwrap.  Thanks.

npm shrinkwrap
npm ERR! peer invalid: eslint-config-react-tools@^1.0.10, required by react-table@6.7.4
