### ISSUE TITLE
Fixed width on column spoils the table.

### ISSUE THREAD

**Issue by smoleniuch** [react-tools/react-table#512]
## What version of React-Table are you using?
Latest

## What bug are you experiencing, or what feature are you proposing?
Can someone explain to me why setting fixed width on **First Name** column spoils the table?
Other columns appear after resizing by mouse.How can i set fixed width without disturbing the table?

https://codesandbox.io/s/o7pzjqqpv5
## What are the steps to reproduce the issue?
1. list the steps
2. to reproduce
3. the issue

**Comment by smoleniuch** [comment]
Its due to value type.It must be an integer instead of string.

**Comment by tannerlinsley** [comment]
Correct. You must provide a numeric width
