### ISSUE TITLE
Hide empty rows.

### ISSUE THREAD

**Issue by kishorcse** [react-tools/react-table#514]
include react table.
give some data. minimum pages should be 2 pages of data.
suppose records in data are 15.
pageSizeOptions=[10].
now in second page only 5 rows will show the data. remaining empty rows should not be rendered. they should be hidden and tables height should be reduced to fit only rendered rows.

**Comment by kishorcse** [comment]
![empty rows](https://user-images.githubusercontent.com/3874757/30935205-9488e064-a3ed-11e7-8e78-d4e8048fd509.PNG)

**Comment by kishorcse** [comment]
![empty rows](https://user-images.githubusercontent.com/3874757/30935359-0e4d9a70-a3ee-11e7-8f03-6e7dbb06be3d.PNG)


this is how it looks. i want  to hide those empty rows

**Comment by afoliveira** [comment]
minRows = {0}
This is a solution

**Comment by kishorcse** [comment]
Thanks @afoliveira it works

**Comment by OndeVai** [comment]
This seems like a bad default to me. I would think minRows={0} would be the default.

**Comment by tannerlinsley** [comment]
The idea behind a paginated table is to keep the UI predictable. Pagination buttons should not jump around. That is why the default minRows is set to the pageSize. Of course, you can change this if you don't like that, and that's the beauty of it!

**Comment by AfzalAhshan** [comment]
use emptyRowsWhenPaging: false, in options

**Comment by MDziurakh** [comment]
@arabaykaa https://github.com/TanStack/table/discussions/2109, looks like this is deprecated
