### ISSUE TITLE
Number.isNaN not supported in IE

### ISSUE THREAD

**Issue by Fanneyyy** [react-tools/react-table#516]
Not sure about how compatible this package is with IE but I got this error when running my app on IE 11:
`Object doesn't support property or method 'isNaN'`

Noticed that the function `src/utils.js/asPx` is using the `Number.isNaN` method (Not supported in IE).
Wondering if it could be switched out with something like
```javascript
function isNumeric(n) {
  return !isNaN(parseFloat(n)) && isFinite(n);
}
```
Many thanks for an awesome table :)

**Comment by Fanneyyy** [comment]
https://github.com/react-tools/react-table/pull/517
Made the changes I believe should solve the problem without affecting other funtionality, if you’re interested :)

**Comment by tannerlinsley** [comment]
Yeah we suggest using an es6 polyfill when using ie. We would like to keep any browser specific code out of the library as much as possible.
