### ISSUE TITLE
Infinite Scrolling with Table

### ISSUE THREAD

**Issue by ryanvanbelkum** [react-tools/react-table#522]
## What version of React-Table are you using?
Your bug may already be fixed in the latest release. Run `yarn upgrade react-table`!
6.5.3

## What bug are you experiencing, or what feature are you proposing?
With a table of 1000+ rows, sorting/filtering becomes quite slow. This is alleviated with pagination, but we would prefer not to go that route. Doing some JS profiling it looks like an expensive part of the filtering/sorting process is row regeneration. Is it possible to do some sort of lazy loading (infinite scrolling) with this table? That way on sort/filter the table would only have to generate x number of rows instead of 1000+.

## What are the steps to reproduce the issue?
1. create a table with over 1000 items
2. sort the list by one of the columns
3. clear sort and then filter list by one of the columns
4. notice the lag

**Comment by zusamann** [comment]
Why don't you do server side sort/filter, rather than doing it on the client. There is not much this library can do if you're dealing with large amounts of data. It's the job of a database to handle such queries.

**Comment by ryanvanbelkum** [comment]
@zusamann while I agree with you in some aspects, why would I want to make a call to the api -> database, then back to the client each time i want to change the sort. I feel like that would take the same amount of time, or more.

**Comment by ryanvanbelkum** [comment]
also note that sorting/filtering on the server would not solve this issue. The sort/filter functions only take ms. The slow down is regenerating all the rows in the list, done by react-table

**Comment by tannerlinsley** [comment]
Infinite scrolling is not in the roadmap for React Table. You would be better suited using a different library if it is a feature you deem necessary. For react table, we believe less scrolling provides a better user experience for the majority use case.
