### ISSUE TITLE
defaultSortMethod force rows to bottom regardless of sort direction

### ISSUE THREAD

**Issue by K-Sutton** [react-tools/react-table#527]
Hello,
I'm wanting to force the "Total" row to the bottom of the table via the defaultSortMethod, this will need to ignore the sort direction and always be forced to the bottom.

Here's my defaultSortMethod:
```
defaultSortMethod: function(a, b) {
                    if(a === 'Total' || b === 'Total') {
                        return 0;
                    }

                    a = a === null || a === undefined ? '' : a;
                    b = b === null || b === undefined ? '' : b;

                    a = isNaN(a) ? a.toLowerCase() : parseFloat(a);
                    b = isNaN(b) ? b.toLowerCase() : parseFloat(b);

                    if (a > b) {
                        return 1;
                    }
                    if (a < b) {
                        return -1;
                    }
                }
```
As you can see, I've just taken the actual default method, and changed it to check if the column is "Total", if it is, then force to the bottom. I tried `return -1;` but that caused the sorting to break, only `return 0;` worked.

**Comment by gary-menzel** [comment]
You should consider implementing a custom footer (check `Footer` in the docs). The sorting mechanism is not a viable way to accomplish this.
