### ISSUE TITLE
Checkbox bug in pagination

### ISSUE THREAD

**Issue by bitbleach** [react-tools/react-table#531]
## What version of React-Table are you using?
Your bug may already be fixed in the latest release. Run `yarn upgrade react-table`!
Place your version here...

react-table@6.6.0

## What bug are you experiencing, or what feature are you proposing?
Please include a detailed explanation here...
There seems to be a bug with pagination and checkboxes in rows, see my stackoverflow post.
 
https://stackoverflow.com/questions/46551810/adding-dynamically-generated-checkboxes-to-react-table-and-capturing-row-data?noredirect=1#comment80058450_46551810

## Use https://codesandbox.io/s/X6npLXPRW (by clicking the "Fork" button) to reproduce the issue.
Then paste a link to your newly forked codesandbox here...
https://codesandbox.io/s/j39zk4x4v3
## What are the steps to reproduce the issue?

1.) Add input to Cell: 
`Cell: row => (<input type="checkbox" />)`

2.) See how checkbox stays even on next pages

**Comment by gary-menzel** [comment]
Closing this issue. Advice provided in the #slack channel. This is an implementation question and not an issue with react-table.
