### ISSUE TITLE
sortedData issue

### ISSUE THREAD

**Issue by yezhi780625** [react-tools/react-table#535]
## What version of React-Table are you using?
Your bug may already be fixed in the latest release. Run `yarn upgrade react-table`!
`react-table": "^6.6.0"`

## What bug are you experiencing, or what feature are you proposing?
I am trying to get sortedData in onFetchData handler.
After shift-clicking the header 3 times, state.sorted got became an empty array ( [] ) , however state.sortedData remains the same state as after shift-clicking 2 times .
Is it correct? If it is, how could I recover the initial data after shift-clicking the header 3 times ?
What's more, when I am filtering, it will recover the initial data after shift-clicking the header 3 times.
If I shift-clicking the header 3 times before filtering, the above will not work.

## Use https://codesandbox.io/s/X6npLXPRW (by clicking the "Fork" button) to reproduce the issue.
https://codesandbox.io/s/54r9wqrljp

**Comment by gary-menzel** [comment]
You have misunderstood the purpose of `onFetchData`. It is not for react-table to send you the data it is for when you want to fetch data from the server and control all the sorting and filtering yourself.

If you need to obtain the sortedData from react-table then you should have a quick look at the FAQ in the Wiki (there's only one item there right now but it explains how to get at the internally sorted data).

https://github.com/react-tools/react-table/wiki/FAQ

**Comment by yezhi780625** [comment]
@gary-menzel Thank you for the information. I had fixed the code https://codesandbox.io/s/54r9wqrljp. However the result is the same.

1. After shift-clicking the header 3 times, `sorted `got became an empty array ( [] ) , however `sortedData `remains the same state as after shift-clicking 2 times .
2. What's more, when I am filtering, it will recover the initial data after shift-clicking the header 3 times.
3. If I shift-clicking the header 3 times before filtering, 2. will not work.

**Comment by gary-menzel** [comment]
`sortedData` is what represents the sorted **and** filtered state of the table.

I've run your codesandbox - shift-clicked multiple times and checked `sortedData` using your button and still don't understand what the issue is. When I filter the data so there are only a few rows, I see those rows in `sortedData` and then when I sort, the data gets moved in array as I would expect. Similarly, if I then clear out the filter, the `sortedData` looks correct.

**Comment by yezhi780625** [comment]
@gary-menzel I am sorry for my poor expression.
I mean that the `sortedData `should be unsorted when I shift-clicked header the third times, but it is not.
When I typing something into the filter, it worked well. However, I shift-click multiple times before I typed something into the filter, it will be failed.

**Comment by gary-menzel** [comment]
shift-click the third time (as far as I know) just no longer includes that field in the sort (it doesn't "unsort" it). The idea of shift-click is actually to allow you to select multiple columns. If you select more than one column and the shift-click the third time, the sorting will change slightly (but if you just use one column there is nothing to resort).

I don't think it is broken - I think this is the intended behaviour. It probably depends on how you interpret the documentation when it says "will clear the multi-sort and replace it with the single sort of that column". I take that to mean it will turn the sorting off and leave you with whatever the sort state was for that column.
