### ISSUE TITLE
Is there any sample code that can show us on how to select specified row by the radio button?

### ISSUE THREAD

**Issue by chancein007** [react-tools/react-table#541]
Hello, Team,

Is there any sample code that can show us on how to select specified row by the radio button in the first column? If so, how to get the selected row data in the method?

Is there any way to hidden one column to record the id (business data) of each row?

Thanks in advance

**Comment by gary-menzel** [comment]
All of this is possible bit you need to implement for your own use case.  As this is an implementation question. Please feel free to join the #react-table Slack channel and ask there (there are a wider range of people there to help).

**Comment by tommyalvarez** [comment]
@gary-menzel I end up here also looking for an example of this. I think the use case is not pretty common but for example, it's useful for selecting a winner from a group of rows (single winner). I can simulate it with checkbox, but radio's would be better.
How do i get in into the slack channel ? @chancein007 any chance you end up implementing your own HOC and be kind to share it ?
