### ISSUE TITLE
Custom sorting UI

### ISSUE THREAD

**Issue by Firenze11** [react-tools/react-table#544]
Not sure if this functionality exist already, but if would be nice to enable a custom sorting UI, say, I need to use an up-arrow / down-arrow to indicate whether this column is sorted increasingly or decreasingly. 
Currently, my question is (so that I could implement a similar logic myself) whether there is a way to access the sorting state (ascending or descending) of a column?

**Comment by gary-menzel** [comment]
Firstly, to access the internal state of react-table, check this FAQ:

https://github.com/react-tools/react-table/wiki/FAQ#how-do-i-get-at-the-internal-data-so-i-can-do-things-like-exporting-to-a-file

Then, if you don't want the existing bars you need to override the CSS.

Here is a codesandbox of something that I put together in the past.

https://codesandbox.io/s/k2nk6q5vv5

As this is an implementation issue, please feel free to join the Slack #react-table channel as there is a broader range of people there to help with such questions.

**Comment by Firenze11** [comment]
Thanks @gary-menzel ! Which workspace is that #react-table channel in? Do you mind sending me an invitation? Thanks.

**Comment by gary-menzel** [comment]
There is an invite button on the react-table documentation page but here it is again....

https://react-chat-signup.herokuapp.com/

**Comment by Firenze11** [comment]
Thanks!
