### ISSUE TITLE
Update doc for using props.orderByMethod

### ISSUE THREAD

**Issue by jfroffice** [react-tools/react-table#545]
Can we use __lodash/sortBy__ instead of the default __lodash/orderBy__ that you have redefined in the utils file?

**Comment by gary-menzel** [comment]
You could try to replace it (the first two parameters are the same). But the react-table orderBy utility is richer than the lodash sortBy function (specifically an extra parameter for the direction of the sort, and another additional parameter that provides the index of the row to assist in tiebreak between rows that contain the same data - which the lodash routine would ignore).

Fork one of the sample sandboxes and just try it.

You should also consider what your use-case is for this as there is already very rich functionality exposed in event hooks and replacement props to externalise sorting.

For further help you should join the #react-table channel on Slack as this question is likely to quickly become an implementation question (despite the doco on the prop not be up-to-date).

**Comment by gary-menzel** [comment]
There is nothing to implement for react-table. Closing.
