### ISSUE TITLE
Typescript type definition v6 misses `onFetchData`

### ISSUE THREAD

**Issue by rewop** [react-tools/react-table#546]
## What version of React-Table are you using?
Version 6.6.0

## What bug are you experiencing, or what feature are you proposing?
In typescript the type definition of react-table does not include the new `onFetchData` parameter, but it still has the old `onChange` parameter.

## Sandbox issue
https://codesandbox.io/s/4lx75rrpkw

## What are the steps to reproduce the issue?
1. Render a react table component in typescrypt with property onFetchData

**Comment by thangchung** [comment]
@rewop I have got the same issue like this. So do you have any way to work-around this?

**Comment by rewop** [comment]
@thangchung  I have wrapped in `ReactTable` in  my custom component that accept the same definition, and extended react table props: 

```
import ReactTable, { ReactTableFunction, TableProps } from 'react-table';

interface AdvancedTableProps extends TableProps {
  onFetchData: ReactTableFunction;
}

class AdvancedTable extends React.Component<Partial<AdvancedTableProps>> {
  render() {
    return <ReactTable {...this.props} />;
  }
}
```

Mind that despite this is a workaround that works to solve the type error, `AdvancedTableProps` is no the correct type, because the component still accepts `onChange` prop which would be never called. 

On a side note, I also found out that a lot of the braking changes introduced in [version 6](https://github.com/react-tools/react-table/blob/master/CHANGELOG.md#600) are not up to date in the [type definition](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-table).

**Comment by thangchung** [comment]
@rewop Got it. Thank you for your help 👍

**Comment by gary-menzel** [comment]
The .ts  for react-table is not maintained by the react-table developers and is not part of the package. You'd need to check npm for whichever .ts package you are using and contact the developers directly for an update.

**Comment by rewop** [comment]
@gary-menzel thanks. This means that `react-table` doesn't offer typescript type definition support? 

The npm module I use is `@types/react-table` from https://github.com/DefinitelyTyped/DefinitelyTyped.  I will move this issue there in this case.

**Comment by gary-menzel** [comment]
There is no support in the code for .ts - that is correct.  The NPM  page from that version (@types/react-table) explains it was provided by someone else.
