### ISSUE TITLE
Row styles failing on expansion after sorting

### ISSUE THREAD

**Issue by dysfunc** [react-tools/react-table#547]
## What version of React-Table are you using?
`"react-table": "^6.6.0"`

## What bug are you experiencing, or what feature are you proposing?
Trying to use `getTrProps` to apply styles to an expanded row after sort appears to have index mapping issues. I'd love for this to be user error :) 

## Live Demo
https://codesandbox.io/s/04v151l12p

## What are the steps to reproduce the issue?
1. Expand any row
2. Sort any column
3. Expand any row in the list

You'll notice the bold highlighting is reflected in the original row vs the newly sorted row index

**Comment by gary-menzel** [comment]
The keys used for expanded rows are local to the page (e.g. rows 1-10). As the page is sorted, the indexes are applied to different rows (they still represent row 1, row 2, etc.). To accomplish something like you have shown you will need to relate the index back to a specific row key (like an _id) in your data and record that in your wrapping components state.

This is part of the design of react-table to keep it data agnostic (i.e. it knows nothing about your data - only what you describe in the configurations).  However, there is a `freezeWhenExpanded` prop that you can set to `true`. That may be a quick answer to your situation but may also end up being a restriction (as they will have to close the expanded row(s) before they can re-sort).

If you need further help in implementing this, then you should join the #react-table channel on Slack. Thanks.

**Comment by dysfunc** [comment]
I must be missing something. I don't need it to know anything about my data. This is your internal mapping of expanded rows. The demo I provided is using the component state to apply the styling to expanded row. After sort, I'd expect two things (based on config): 1.) Expanded rows would be remapped with the new sorted index, 2: Blows away expanded state entirely. If the expanded state has been reset, it should still apply the styling to tr using the trprops method as setup in my demo. No? 

I understand I can control expanded state via local component state. However, not modifying the default value of `collapseOnSortingChange` would imply that sorting will reset expanded state after sort? If that's a true statement, shouldn't the demo work properly since it's just looking for - is row N expanded yes|no?

**Comment by gary-menzel** [comment]
You are using `rowInfo.index` which is related to the whole data set and does not change. You need to use `rowInfo.viewIndex` which is relative to the view.

As previously suggested, bringing this type of issue to the #react-table Slack channel might resolve it quicker as a lot of other users are there at various times across different time zones.

**Comment by codevanaco** [comment]
Thanks @gary-menzel  -  changing from 'rowInfo.index' to 'rowInfo.viewIndex' took care of my issues.
