### ISSUE TITLE
Add PropTypes to React-Table

### ISSUE THREAD

**Issue by frankolson** [react-tools/react-table#549]
## What version of React-Table are you using?
6.6.0

## What bug are you experiencing, or what feature are you proposing?
I want to propose adding the `prop-types` library to React-Table. Since there are a significant amount potential props, this would help give developers useful feedback as they are developing.

It shouldn't be too difficult to track down all the needed definitions as there is already a file containing all the `defaultProps`.

**Comment by gary-menzel** [comment]
@frankolson I think you have sent through a few other PRs so I don't see anyone complaining if you do this.  It may get tricky when you get to some of the nested (i.e. the `column`) props.

**Comment by frankolson** [comment]
Yah, if we create a small [jest](https://github.com/facebook/jest) suite we might be able to test the compatibility.

**Comment by gary-menzel** [comment]
This should be addressed in V 6.7.4
