### ISSUE TITLE
The example of custom filtering is not working

### ISSUE THREAD

**Issue by arimourao** [react-tools/react-table#553]
The sample code for "Custom Filtering" is not working as it should for the column "First Name". All other columns seems to be working fine.

https://react-table.js.org/#/story/custom-filtering

**Comment by gary-menzel** [comment]
Confirmed. The && should be a || in the `filterMethod` for `firstName`. Low priority change due to it being in the examples.

**Comment by piyuesh-dev** [comment]
I'll do it.

**Comment by piyuesh-dev** [comment]
Submitted PR 739.

**Comment by tannerlinsley** [comment]
Closing due to issue age. If you think this issue needs to be reopened, please check the latest version of React-Table for the issue once more and reopen if appropriate. Thanks!
