### ISSUE TITLE
Freez Column Issue

### ISSUE THREAD

**Issue by sanjeev-iitr-uk** [react-tools/react-table#556]
I want to freez first 2 columns on horizontal scroll, i have given css as {positon: 'fixed'}  to the first column but it doesn't work and second column overlaps the first. please give a solution to freez some columns from the left.

**Comment by gary-menzel** [comment]
Column freezing is not supported.

**Comment by gary-menzel** [comment]
There have been several requests made to add this as a feature but, as of now, this is not likely to happen too soon.
