### ISSUE TITLE
sortMethod has limitation

### ISSUE THREAD

**Issue by Younger-Peng** [react-tools/react-table#560]
Let's say I want to sort a array [10, 12, 23, 11, 20, 5] by asc;
But I want the first item's position to stay unchanged:[10, 5, 11, 12, 20, 23];
using sortMethod can only accept the adjacent two items, Can we let the sortMethod accept the whole column?In this we, We can customize the sortMethod totally

**Comment by gary-menzel** [comment]
I am not sure what you mean by "accept the whole column". The sorting is row based and uses a traditional A/B sorting approach and allows any sort function to be plugged in.

Is the array you mentioned a specific set of numbers and do you know that "10" should always be at the top? If so, you can do that with the existing sort method by just writing your return values to ensure that "10" always stays at the top. If that number (10) is not always in the data, it is not clear how you would determine what should sort at the top above everything else.

This is more of an implementation issue and you should consider asking in the #react-table Slack channel (there is a badge at the top of the doco) as other people have done some complicated sorts. Thanks.

**Comment by gary-menzel** [comment]
Closing as this is not compatible with the feature set of react-table.
