### ISSUE TITLE
How to disable sorting?

### ISSUE THREAD

**Issue by robert-zaremba** [react-tools/react-table#561]
## What version of React-Table are you using?

```v6.6.0```

## What bug are you experiencing, or what feature are you proposing?

Feature: add ability to disable sorting (no click on header)
(or update documentation if it already exists)

**Comment by robert-zaremba** [comment]
It's in the `ReactTable` props:

      sortable={false}

**Comment by sbimochan** [comment]
> It's in the `ReactTable` props:
> 
> ```
>   sortable={false}
> ```

That will disable for all columns. What about selective columns sortable?

**Comment by hillcjames** [comment]
> > It's in the `ReactTable` props:
> > ```
> >   sortable={false}
> > ```
> 
> That will disable for all columns. What about selective columns sortable?
See #336 - describes disabling filtering and sorting on individual columns.

**Comment by sbimochan** [comment]
> > > It's in the `ReactTable` props:
> > > ```
> > >   sortable={false}
> > > ```
> > 
> > 
> > That will disable for all columns. What about selective columns sortable?
> 
> See #336 - describes disabling filtering and sorting on individual columns.

Solved. thanks
