### ISSUE TITLE
[Question] Is it possible for the pivot to expand upwards?

### ISSUE THREAD

**Issue by hdwatts** [react-tools/react-table#563]
Our table is looking and working great, however a client would prefer if our aggregates we're below the data and that the pivots expand upwards.  Is this possible, and if so what would the best way of implementing it?

**Comment by gary-menzel** [comment]
At present, the addition of the rows is internal to the table (with no overrides) and they are always added below. There is no way to directly control how these rows are rendered. I am not even sure you could control it indirectly.

[Comment: A pivot is a fairly well defined mechanism. I don't think I have ever seen a pivot go "up" as you describe.]

**Comment by gary-menzel** [comment]
As this is not a very common (I have not even seen pivot work this way), the issue will be closed.
