### ISSUE TITLE
Rows don't render in IE11

### ISSUE THREAD

**Issue by mikedevita** [react-tools/react-table#564]
## What version of React-Table are you using?
6.5.3

## What bug are you experiencing, or what feature are you proposing?
Rows are not visible, but they exist in DOM

## Use https://codesandbox.io/s/X6npLXPRW (by clicking the "Fork" button) to reproduce the issue.
https://codesandbox.io/embed/gLwmmjzA3?autoresize=1&hidenavigation=1&view=split

## What are the steps to reproduce the issue?
1. load sandbox in IE11
2. table rows are not visible

 
![image](https://user-images.githubusercontent.com/2991640/31845528-796db914-b5b6-11e7-8b75-97fd83bdb1db.png)
![image](https://user-images.githubusercontent.com/2991640/31845529-7ed95e30-b5b6-11e7-89e5-1051a901ae84.png)

**Comment by gary-menzel** [comment]
I have done a check on this (although I don't use IE very much). It appears that using `flex: auto 1` in the `.ReactTable .rt-table` css (instead of `flex: 1`) fixes this problem. However, while I tested it also in Chrome, I am not sure if it will be compatible with all browsers.

**Comment by mikedevita** [comment]
thanks Gary I'll test this on my app on Monday to see if it's a viable work around.

**Comment by mikedevita** [comment]
@gary-menzel I can confirm that adding the following css resolves the issue, is this going to be planned to push into the next release?

```css
.ReactTable .rt-table {
  flex: auto 1;
}
```

**Comment by gary-menzel** [comment]
Really up to @tannerlinsley. It would still need to be tested across all the currently supported browsers.  But, as overriding CSS is fairly simple, it is likely to have low priority. I will definitely add an FAQ to the github Wiki.

Thanks for the confirmation.

**Comment by mikedevita** [comment]
yeah thats totally fine, i am in no rush to get a fix pushed so its up to @tannerlinsley entirely I'd say. Plus with a viable workaround there really no rush at all for any of my other projects.

**Comment by jepz** [comment]
Does the problem that IE 11 doesn't support property or method of find have anything to do with it?

**Comment by maxdarque** [comment]
Is this low priority? I understand there is an easy fix for this with the CSS override. Having said that, the product is fundamentally broken in a major use case...IE 11....

**Comment by mikedevita** [comment]
there's already a PR for it. it's just waiting to be tested and merged. it's up to the core maintainers I think now.

**Comment by gary-menzel** [comment]
Mike is correct.

For clarity, I have added a section to the FAQ that describes the triage levels.

https://github.com/react-tools/react-table/wiki/FAQ#what-is-the-criteria-for-assessing-issue-priority

**Comment by gary-menzel** [comment]
#573

**Comment by maxdarque** [comment]
Thank you for taking the time to clarify this for me!

**Comment by gary-menzel** [comment]
This should be addressed in V 6.7.4
