### ISSUE TITLE
Add the possibility to specify default values for column options on table level

### ISSUE THREAD

**Issue by kremuwa** [react-tools/react-table#565]
## What version of React-Table are you using?
6.6.0

## What bug are you experiencing, or what feature are you proposing?
I would like to propose a feature of setting a default value for column options on a table level. For example, I wanted to use fuzzy matching in all the columns except one and currently I have to specify the filterAll option on each of the columns. Also, I wanted to change the HTML markup of text inputs used for filtering and right now I can see no option but using identical value of `Cell` option for each of the columns.

**Comment by gary-menzel** [comment]
You could create your own default column and use destructuring to get the "defaults".....

e.g.
```
function myDefaultCell(/* normal parms here */)
{
  return 'Something'; // render whatever you like
}

function doSomethingDifferent(/*...*/)
{
  return 'Something Different';
}

const defaultColumn = 
{
  Cell: myDefaultCell,
  Header: 'No Column Header',
}

const columns =
[
  {
    ...defaultColumn, 
    accessor: 'col1',
    Header: 'Column One',
  }
  {
    ...defaultColumn, 
    id:'col2',
    accessor: (d)=>d.someValue,
    Cell: doSomethingDifferent,
  }
]
```
And you can use that same approach for just about any of the column properties (obviously not the ones that need to be unique like `id` but definitely for things like the `get...Props` set of properties (for styling purposes).

You may also like to consider joining the #react-table Slack channel (if you haven't already) as most of the current users gather there and tend to not read the issues on github as much as they follow the discussion on Slack. There is a badge in the doco for joining.

**Comment by gary-menzel** [comment]
Closing - mechanism does exist for "default" values in columns using destructuring as per the example above.

**Comment by kremuwa** [comment]
I like the smartness of your idea a lot, mostly because it shows how flexible React/JS-ES6 is, but I think this is still cumbersome compared to a built-in feature. A desire to add additional class to HTML code of the filter fields (e.g. a Bootstrap `form-control` class, so that they look like other form fields on the website) sounds like a pretty common desire to me. I think, however, that I may move this discussion to the Slack channel indeed, as you suggested. Thanks a lot for everything!

**Comment by kremuwa** [comment]
I just found out that the feature I proposed already exists. On supported props list we can see:

`  // Global Column Defaults
  column: {
    // Renderers
    Cell: undefined,
    Header: undefined,
    Footer: undefined,
    Aggregated: undefined,
    Pivot: undefined,
    PivotValue: undefined,
    Expander: undefined,
    Filter: undefined,
    // Standard options
    sortable: undefined, // use table default
    resizable: undefined, // use table default
    filterable: undefined, // use table default
    show: true,
    minWidth: 100,
    // Cells only
    className: '',
    style: {},
    getProps: () => ({}),
    // Headers only
    headerClassName: '',
    headerStyle: {},
    getHeaderProps: () => ({})
    // Footers only
    footerClassName: '',
    footerStyle: {},
    getFooterProps: () => ({}),
    filterAll: false,
    filterMethod: undefined,
    sortMethod: undefined,
    defaultSortDesc: undefined,
  },`

It's a bit tricky to use, see:
https://github.com/react-tools/react-table/issues/394
to get some advice about it.
