### ISSUE TITLE
Custom CSS usage

### ISSUE THREAD

**Issue by Coolpeace5** [react-tools/react-table#566]
Hello,

I was wondering how the CSS customization of react-table works. At this moment I am unable to change the react table via CSS. I am using the react-table that is used inside the plot.ly data-table experiments. I have hosted a custom CSS at:
https://codepen.io/Stuart_Kerkhof/pen/OxGVmy.css
Where I copied some of the react-table default CSS from:
https://unpkg.com/react-table@6.6.0/react-table.css

Then I applied changes to this, but they don't seem to work.
Can someone maybe give an example of a working custom CSS for react-table?

kind regards,

Stuart

**Comment by gary-menzel** [comment]
You can't really customize the ReactTable CSS in that way. A lot of the CSS in the files is required to provide the layout by using flexgrid and messing with it can break the layout. To override various styles you need to look at the `get...Props` set of callbacks in the docs and examples.

This is more of an implementation issue than any problem with the code.  The best place to ask about this type of thing is on the #react-table Slack channel. You can find a badge to join at the top of the documentation.

**Comment by Coolpeace5** [comment]
@gary-menzel 
Thank you for your reaction. I will try that!

**Comment by avremel** [comment]
@gary-menzel can you please provide a basic example of how to use component decorator to manipulate css?
