### ISSUE TITLE
Property defaultSorted is called defaultSorting in d.ts

### ISSUE THREAD

**Issue by mvladic** [react-tools/react-table#568]
## What version of React-Table are you using?
6.6

## What bug are you experiencing?

Property `defaultSorted` is called `defaultSorting` in Typescript definition file. Similarly, `defaultFiltered` is called `defaultFiltering` in d.ts.

**Comment by gary-menzel** [comment]
The .ts  for react-table is not maintained by the react-table developers and is not part of the package. You'd need to check npm for whichever .ts package you are using and contact the developers directly for an update.
