### ISSUE TITLE
Empty noDataText leaves white box on page

### ISSUE THREAD

**Issue by dclark27** [react-tools/react-table#572]
## What version of React-Table are you using?
6.6.0

## What bug are you experiencing, or what feature are you proposing?
When clearing the noDataText prop, the space for the text remains on the page and looks off. If there is no text, I'd like that box to go away. 

## Use https://codesandbox.io/s/X6npLXPRW (by clicking the "Fork" button) to reproduce the issue.
https://codesandbox.io/s/p2w0rwnpjx

**Comment by gary-menzel** [comment]
You could dynamically control your `defaultPageSize` when there is no data and set it to 0 or 1. To be honest, even that looks a little bit strange when react-table is designed to be a fixed height table.

No-one has asked for this specific change so it is unlikely to make it into the development pipeline.

**Comment by gary-menzel** [comment]
There is an option to resolve this in the current release.... Override the `NoDataComponent` - make it return a `null`.

Closing now.
