### ISSUE TITLE
 add data from 2 cells 

### ISSUE THREAD

**Issue by soyJSus** [react-tools/react-table#574]
Hi friend, good afternoon, I'm trying to amount data from 2 cells but it tells me that it is not defined

 { Header: "Aciertos",  accessor: "point", id: "point",   Cell: ({ state, column, props, value }) => (value)},

**Comment by gary-menzel** [comment]
While possible, this is an implementation question and should be asked in the #react-table Slack channel (badge at the top of the doco). 

In any case, the mix of parameters in the `Cell` function also contain the visible row and the original row (`row`, `original`) - that way you can access other data in the row.

**Comment by soyJSus** [comment]
I add correctly, however there are fields that do not exist because the user does not believe it, as it could be valid if it exists to add it otherwise it omit it, use conditional but it does not workTypeError: row.questForo is undefined

**Comment by soyJSus** [comment]
@gary-menzel hello you cant help me please ?

**Comment by gary-menzel** [comment]
Not here - please join the #react-table channel on Slack. The github issues aren't for general help. Thanks.
