### ISSUE TITLE
uuid is dropped in data row?

### ISSUE THREAD

**Issue by theigor** [react-tools/react-table#576]
## What version of React-Table are you using?
"react-table": "^6.6.0",

## What bug are you experiencing, or what feature are you proposing?
This is really weird but it looks like the `uuid` property is being dropped inside `SubComponent`. See screenshot. `this.state.Endpoints` is the data for the top level react table. It is an array of objects with `uuid` as a property. Inside `SubComponent = row =>`, you can see that the `original` object has `uuid` and if I do `row.row`, even that has `uuid` in `_original` but for some reason `uuid` is not a property of `row.row` and I can't access `row.original` (in a type-safe way) because it is of type `RowInfo` and `.original` is not exposed (maybe that's a separate bug?). I can get around it by doing `const r = (row as any).original;` but I don't think this is the right way to go about it.

![image](https://user-images.githubusercontent.com/6673707/32009115-170c8dc6-b97c-11e7-8111-da2f316969eb.png)

I haven't found any references to `uuid` in `node_modules/react-table` so I don't really know what could be causing this behavior.

Thanks!

**Comment by gary-menzel** [comment]
I think there may just be some confusion.

`row` is the visual row generated based on your column definitions and will only contain uuid if you expose it as part of your column array.  However, `row` always contains `_original`.

`original` or `_original` is the row as it exists in the data you passed to the `data` prop.

The use of the underscore helps avoid namespace conflicts.

The `SubComponent` parameter is a "rowInfo" object that contains `row` and `original` along with metadata related to the display of the row (such as the `viewIndex`. So, as it is currently coded in your example, the parameter named `row` in your `SubComponent` is actually a `rowInfo` object.

So you can either grab the whole parameter as an object or use destructuring to split out the pieces you want - e.g. `SubComponent: (rowInfo)...` or `SubComponent: ({row,original})...`.

I'm using SubComponent regularly and realise this can cause a bit of confusion but eventually makes sense.  By way of confirmation, here is the code where SubComponent is triggered...

```
          {SubComponent &&
            !rowInfo.subRows &&
            isExpanded &&
            SubComponent(rowInfo)}
```
