### ISSUE TITLE
Nested data

### ISSUE THREAD

**Issue by hundsim** [react-tools/react-table#579]
Can the data passed to ReactTable be nested? 

If so, how would I set the car model in the below example to an accessor?

```
[
	{
	  "name":"John",
	  "age":30,
	  "car": {
	    "model":"Ford",
	    "color":"green",
	  }
	},
	{
	  "name":"Jane",
	  "age":34,
	  "car": {
	    "model":"Volvo",
	    "color":"blue",
	  }
	}
]
```

**Comment by gary-menzel** [comment]
Please check the documentation on `accessor` and the samples. This is all available there. Otherwise, it is best to ask this in the #react-table Slack channel (badge in the doco).

Short answer, all possible with `accessor` and/or `Cell`.

**Comment by hundsim** [comment]
It's funny. I've been trying to get my head around this for hours. Reading every single code sample. Trying to grasp the terminology and concept for react-table. Thinking that this MUST be the easiest thing.

Wrong buddy, wrong.

Nested data is an edge case. And I should stop do edgy things.

**Comment by lakshajit** [comment]
Hi Gary,

I am using React Table and setting columns dynamically, by mapping first object of my response for column names and creating array of object like react table requires.

So, if I take @hundsim data example, and if we add parts info array object, how do I set accessor for it. I tried a lot. console showing values but, cant able to see data which comes in 3rd level nest.

Could you please help to understand it.

Thanks,
Ajit

**Comment by Royalza** [comment]
> Hi Gary,
> 
> I am using React Table and setting columns dynamically, by mapping first object of my response for column names and creating array of object like react table requires.
> 
> So, if I take @hundsim data example, and if we add parts info array object, how do I set accessor for it. I tried a lot. console showing values but, cant able to see data which comes in 3rd level nest.
> 
> Could you please help to understand it.
> 
> Thanks,
> Ajit

Hi.

I've managed to show 2nd level nested objects. 3rd level objects causes an error "object child components cannot be rendered". Did you manage to solve this?

**Comment by cristianounix** [comment]
Same problem

**Comment by aminul007bd** [comment]
I am also facing the issue the looping through the nested objects and showing the value. Is there any example for this?

**Comment by Akiriki** [comment]
I spent some time looking for a code example for this, but I could not find any. The documentation for the accessor does not include calling properties of nested objects.

Since i am using typescript, the simple solution did not work for me:
```javascript
    accessor: 'car.color'
```
Instead after some reasearch I found this solution :
```javascript
    accessor: (originalRow, rowIndex) => {
                return originalRow.car.color;
            },
```
Hopefully that will save someone else some time ;)

**Comment by Gilbertelnino** [comment]
> I spent some time looking for a code example for this, but I could not find any. The documentation for the accessor does not include calling properties of nested objects.
> 
> Since i am using typescript, the simple solution did not work for me:
> 
> ```js
>     accessor: 'car.color'
> ```
> 
> Instead after some reasearch I found this solution :
> 
> ```js
>     accessor: (originalRow) => {
>                 return originalRow.car.color;
>             },
> ```
> 
> Hopefully that will save someone else some time ;)

I can't believe your solution unstuck me after 2 hours of trying to figure out what is going on

**Comment by saebalam** [comment]
console the nested object and check by expanding elements. eg. cars.suv[0].price

**Comment by SeamusY** [comment]
Question @gary-menzel 

Regarding to nested, is it possible to also handle the sort of nested data specifically one key? How would you approach the method?

**Comment by its-monotype** [comment]
@SeamusY Also interested in that. And how to deal with column filters if I have a ManyToOne relation? For example, I want to get the original object in Combobox to display to the user the image and title of the nested entity and only the title in a cell. And If there is no two-way relation and I need to fetch that nested entity from the server?

**Comment by Jervx** [comment]
UPDATE

@tanstack/react-table 8.10.6


my data 
```
const data = [
    {
        "id": 1,
        "packageName": "Christmas Promo",
        "displayPrice": 1507.5,
        "discount": 25,
        "createdAt": "2023-11-03T05:13:50.703Z",
        "deleted": false,
        "_count": {
            "Services": 2
        }
    }
]
```


this works fine
```js

    {
        accessorKey: "_count.Services",
        header: ({ column }) => (
            <DataTableColHeader column={column} title="services" />
        ),
        cell: ({ row }) => (<div className="capitalize">{row.original._count.Services}</div>),
        enableHiding: false,
    }, 

```

**Comment by SeamusY** [comment]
> @SeamusY Also interested in that. And how to deal with column filters if I have a ManyToOne relation? For example, I want to get the original object in Combobox to display to the user the image and title of the nested entity and only the title in a cell. And If there is no two-way relation and I need to fetch that nested entity from the server?

Unfortunately at the end i had to remap the entire object to a flat or as flat as possible.

**Comment by sajadmh** [comment]
This is how to access a nested object to capture the correct id "value" in order to use it in the filterFn. No flattening necessary:

Example data structure `console.log({ row });`

```
{
    "row": {
        "id": "4",
        "index": 4,
        "original": {
            "id": "d0cb238d-034f-434f-aacd-c3078fa10ea0",
            "title": "Fake Title",
            "location": {
                "id": "fcbd914a-98ba-45b1-9a29-31b3325a9185",
                "name": "San Francisco, CA",
            },
        },
        "depth": 0,
        "_valuesCache": {
            "location": "fcbd914a-98ba-45b1-9a29-31b3325a9185",
            "title": "Fake Title"
        },
    },
}
``` 


**Solution:**

Create the column and define the key normally, but create an `accessorFn` that goes through the `row` in order to get the nested value for your `filterFn` or any other purpose:

```
  {
    accessorKey: "location",
    accessorFn: (row) => {
      return row.location.id;
    },

    filterFn: (row, id, value) => {
      return value.includes(row.getValue(id));
    },
  },
```

**Comment by ppaul** [comment]
nothing about sort using nested values? why isn't anyone talking about it?

**Comment by TresorRw** [comment]
> nothing about sort using nested values? why isn't anyone talking about it?

I have not seen it too

**Comment by nsharmaRndc** [comment]
nothing works

**Comment by MichaelDimmitt** [comment]
Unfortunately @TresorRw , you have to have both for sorting to work.
So if you are trying to get rid of the warning caused from:
```typescript
accessorKey: 'ref_visit_status_reason.visit_rsn_cd_pk',
```

Now you need both and your accessorFn needs to handle its own partials for each level of nesting might have undefined.
I confirmed sorting was working on my end after making these changes. But I will probably submit some config driven pr sometime this week just to get the discussion started, because this is a lot of boiler plate just to avoid a warning.
```typescript
accessorKey: 'originalRow.car.color',
accessorFn: (originalRow) => originalRow.car?.color,
```
