### ISSUE TITLE
Freezing columns

### ISSUE THREAD

**Issue by balintpeak** [react-tools/react-table#580]
Is there a way to freeze some columns on the left hand side?
For example facebook data table has this feature (https://facebook.github.io/fixed-data-table/api-columngroup.html) but lacks a lot of the other ones react-table has.

Thanks.

**Comment by gary-menzel** [comment]
No, there is no ability to freeze columns at this point as it is a difficult exercise based on the currently design - including the desire to keep the code lightweight for performance reasons.

**Comment by gary-menzel** [comment]
Please see #556, #507 and specifically the earlier #167.

Closing.

**Comment by balintpeak** [comment]
@gary-menzel thank you very much for the quick response!
