### ISSUE TITLE
ESLint Plugin Should Move to DevDependencies

### ISSUE THREAD

**Issue by skipjack** [react-tools/react-table#582]
## What version of React-Table are you using?
Your bug may already be fixed in the latest release. Run `yarn upgrade react-table`!
__v6.7.0__

## What bug are you experiencing, or what feature are you proposing?
It seems the `eslint-config-react-tools` was accidentally added to the main `dependencies` field instead of `devDependencies`. I noticed this after installing `react-table` as the `eslint-config-react-tools` flags for `peerDependencies` that don't seem like they should be necessary.

See [this line](https://github.com/react-tools/react-table/blob/master/package.json#L42) in the `package.json` for reference.

## Use https://codesandbox.io/s/X6npLXPRW (by clicking the "Fork" button) to reproduce the issue.
N/A

## What are the steps to reproduce the issue?
1. Install `react-table`
2. See that it includes `eslint-config-react-tools` as a normal dependency

Should be a pretty simple fix... I'd be happy to submit a PR if we're all in agreement that this dependency was incorrectly placed.

**Comment by skipjack** [comment]
Love the package btw, thanks so much for your work on this component and its documentation!

**Comment by skipjack** [comment]
Also seeing some odd `PropTypes` warnings for props that I'm not passing. You can see the same errors if you open the console in your examples (e.g. [this one](https://codesandbox.io/s/X6npLXPRW)).

**Comment by gary-menzel** [comment]
V 6.7.4 seems to resolve all the propTypes issues.

**Comment by onpaws** [comment]
@skipjack I'm experiencing the same issue on v6.7.4
@tannerlinsley is this deliberate?
