### ISSUE TITLE
Inject non-data rows at an interval into tbody

### ISSUE THREAD

**Issue by timkelty** [react-tools/react-table#585]
## What version of React-Table are you using?
react-table@6.7.4

I'm looking for a way to intersperse rows at an interval throughout by table. The particular application is to display a "promo" every so often rows.

Currently, I've achieved this in a rather hacky way by hijacking the `SubComponent`/expanded functionality.

I'm hiding the expanders, making everything expanded by default, and rendering the subcomponent content on the interval I want. Here's a demo: https://codesandbox.io/s/7mxonnlwq1

I'm wondering if there is a more elegant solution, or if it might be a case for a feature request. [`react-data-grid`](https://github.com/adazzle/react-data-grid), for example, has a `rowRenderer` prop where I could push my promo row onto the rows at my interval.

**Comment by gary-menzel** [comment]
This is really an implementation issue and a very specific use case. Given the design goals and architecture of react-table, it seems like you have probably already got the best approach to this. Also, it is possible to replace the `TrComponent` (equivalent to a row renderer).

You could also add a flag to your original data so that expander knows to automatically expand or close the sub-component.

Given it is possible to put anything in a sub-component and programmatically control the expansion (and other ways to accomplish this) there's no real need to add a feature like this.

**Comment by timkelty** [comment]
Thanks for the reply @gary-menzel. Agreed it is pretty specific.

If I want to go another route, I'll look into overriding `TrComponent` or `TbodyComponent`

> You could also add a flag to your original data so that expander knows to automatically expand or close the sub-component.

Could you elaborate on that at all?

**Comment by gary-menzel** [comment]
Well, a lot of the time, I compose the data for react-table (from whatever the data source was) using <array>.map(...) and add anything to mapped record I want. In your case, for example, you could add flag in (and any other data - maybe it is an object) that has the promo in it. Then, you could built out your overrides to look for that on the record and cause state changes to show the sub-component.

**Comment by gary-menzel** [comment]
With component overrides, you don't even necessarily have to render a different component... You could just use it for the side-effect of getting access to state (say to the rows that are in the current view) and use the information to update your own state (and cause a redraw).

react-table is very lightweight but provides a lot of override capability to make it do lots of tricks.  Not like an "all features" table but often more flexible.

**Comment by timkelty** [comment]
Thanks for the clarification.

> react-table is very lightweight but provides a lot of override capability to make it do lots of tricks. Not like an "all features" table but often more flexible.

Indeed - loving that I can override any components and/or props!
