### ISSUE TITLE
Passing more data to the subcomponent

### ISSUE THREAD

**Issue by dilipSundar** [react-tools/react-table#586]
## What version of React-Table are you using?
    "react-table": "6.6.0"

## What bug are you experiencing, or what feature are you proposing?
I would like to pass more data than just row to my subcomponent.
Precisely, I would like to send the function also in addition to data to my subcomponent. Is there a way to achieve this ?

```
const xyzTable = ({routes, onButtonClick}) => {
  return (
    <ReactTable
      data={routes}
      columns={columns}
      SubComponent={SubTable}
      className="-striped -highlight"
    />
  )
}

```
In the above snippet, I would like to pass the onButtonClick also to my subcomponent. How can I achieve it ?

## Use https://codesandbox.io/s/X6npLXPRW (by clicking the "Fork" button) to reproduce the issue.
Then paste a link to your newly forked codesandbox here...

## What are the steps to reproduce the issue?
1. list the steps
2. to reproduce
3. the issue

**Comment by njdaniel** [comment]
I'm having this same issue, was this solved?

**Comment by amit-mb** [comment]
How about something like this?
```js
      SubComponent={row => (
        <MyComponent
          rowProps={row}
          someOtherProp={props.handleMyEvent}
        />
      )}
```

**Comment by NathanCH** [comment]
It's strange that `row` doesn't contain the same keys as when it's called from a column via `Cell` or `Expander`.

For example, if you extend `ReactTableDefaults.column`, the methods you add are available in `Cell` but not in the `SubComponent` callback.
