### ISSUE TITLE
Cusom header sort style 

### ISSUE THREAD

**Issue by TuanDSE62171** [react-tools/react-table#588]
## What version of React-Table are you using?
`"react-table": "^6.5.3"`

## What bug are you experiencing, or what feature are you proposing?
I want to apply a certain style to header cell if users click sort, like adding a icon to indicate rather than the inset

I've tried getTheadProps and get the className of the cell but it would get previous className not the current name, e.g: user clicks sort asc (I will get none), user clicks desc (I will get 'asc'), etc..

Thank you

**Comment by gary-menzel** [comment]
This is an implementation question and is best asked on the #react-table Slack channel (badge at the top of the doco). 

Here is a sample on codesandbox.io that does it by manipulating the Header and headerStyle.....

https://codesandbox.io/s/k2nk6q5vv5


Any other questions - ask on #react-table Slack as suggested.

**Comment by TuanDSE62171** [comment]
Thank you sire, you are a life saver
