### ISSUE TITLE
Can't use external data source

### ISSUE THREAD

**Issue by GlenHughes** [react-tools/react-table#591]
## What version of React-Table are you using?
6.7.4

## What bug are you experiencing, or what feature are you proposing?
I am trying to create a React table  using an external data source and I keep getting this error: `invariant.js:42 Uncaught Error: Objects are not valid as a React child (found: object with keys {title, description}). If you meant to render a collection of children, use an array instead.`

My code: 
`
import React from 'react';
import ReactDOM from 'react-dom';
import axios from 'axios';
import ReactTable from 'react-table';

const COLUMNS = [
    {
        Header: '',
        accessor: ''
    },
    {
        Header: 'Report Name',
        accessor: 'name'
    },
    {
        Header: 'Report Description',
        accessor: 'description'
    }
];

export class SelectReport extends React.Component {

    constructor(props) {
        super(props);
        this.state = {
            data: [],
            loading: false
        };
    }

    render() {
        return (
            <div>
            <ReactTable
                data={this.state.data}
                columns={COLUMNS}
                loading={this.state.loading}
                onFetchData={(state, instance) => {
                    this.setState({loading: true});
                    axios.get('/custom-reports/types', {
                        page: state.page,
                        pageSize: state.pageSize,
                        sorted: state.sorted,
                        filtered: state.filtered
                    })
                    .then((response) => {
                        console.log(response.data);
                        this.setState({
                              // data: response.data,
                              data: [
                                  {
                                      "title": "Title value",
                                      "description": "Description value"
                                  }
                              ],
                              loading: false
                          })
                      })
                      .catch((error) => {
                          console.log(error);
                      });
                  }}
              />
              </div>
          )
      }
  }

  ReactDOM.render(
      <SelectReport />,
      document.getElementById('custom-report-types-table')
  );
`

## What are the steps to reproduce the issue?
1. Try and run my code within a React Component

**Comment by GlenHughes** [comment]
I'm guessing my JSON needs to be formatted some other way then I have shown? I have tried for testing `data: ['test', '123']` which stopped the error but it ended up including each array as its own row rather then column.

**Comment by gary-menzel** [comment]
In your code you have the following as a single example:
```
                          data: [
                              {
                                  "title": "Title value",
                                  "description": "Description value"
                              }
                          ],
```
If that is how your data looks, then your COLUMNS need to be (most basic):
```
const COLUMNS =
[
  { Header: 'Title', accessor:'title' },
  { Header:'Description, accessors: 'description' },
];
```
I am not sure why you have a blank column record (empty Header and empty accessor) or why the column names don't seem to line up with your data.

In any case, this is an implementation question and should be asked over on the #react-table Slack channel (badge in the doco). The github issues are for bugs and feature requests.

**Comment by GlenHughes** [comment]
Ahh, I can't believe that was why!! Thank you and sorry for posting in the wrong place. How do I get on to the Slack channel?

**Comment by mikedevita** [comment]
you click the slack channel button on the README.
