### ISSUE TITLE
Option to export data

### ISSUE THREAD

**Issue by SalmaanP** [react-tools/react-table#592]
I really like this library, an option to export the data as csv would be great. Exporting all the data in the table can be done without any problems but while using filters it should only export the current filtered data.

Is this already implemented?

**Comment by gary-menzel** [comment]
You can get a the filtered/sorted data in the `state` of the component. Check the FAQ in the github wiki.

**Comment by gary-menzel** [comment]
https://github.com/react-tools/react-table/wiki/FAQ#how-do-i-get-at-the-internal-data-so-i-can-do-things-like-exporting-to-a-file
