### ISSUE TITLE
Drag and Drop table rows

### ISSUE THREAD

**Issue by odedgottesman** [react-tools/react-table#593]
Hey, not exactly an issue but more of a question. I am using react table in my react-redux app, and I have tables in which data order matters. I would like to enable drag and drop for rows, to change their order. Is there anything built in that might help me, or I have to use an external library such as react-dnd? Or maybe just html DND is enough in this simple case? Any tips will be appreciated, Thanks for this great library!

**Comment by gary-menzel** [comment]
Nothing in the box for DnD. You would have to implement it externally. Depending on the library you may need to override one of the *Component overrides to enable the correct `div`. The other consideration would be that react-table is (basically) a paged system. So if your ordering needs to spread across pages it may be a challenge. You may have to forego the paging and set up the props so the table is always showing all the rows.

**Comment by gary-menzel** [comment]
As this is an implementation issue, please take the discussion to the #react-table Slack channel (badge at the top of the readme doco page). Thanks.
