### ISSUE TITLE
Q: How do you change event type of filter trigger?

### ISSUE THREAD

**Issue by justduy** [react-tools/react-table#595]
Can I change it to on enter press or something like that?

**Comment by gary-menzel** [comment]
There is nothing in the component for doing this specifically. You need to override the filter component itself directly and replace the input field with your own.

For further help on this it is suggested that you join the #react-table channel on Slack as this is related to implementation. There is a badge at the top of the readme. Thanks.

**Comment by fabioespinosa** [comment]
https://github.com/react-tools/react-table/issues/1109
