### ISSUE TITLE
Header has collapsed with upgrade to 6.7.4

### ISSUE THREAD

**Issue by aikidoshi** [react-tools/react-table#597]
I have a project that has 3 tables in it, and when I upgraded to 6.7.4 the headers all collapsed down to a couple of pixels in height.

Reverting to 5.6.0 fixed the problem but leaves me running an older version.

Any ideas please?

Regards,

Steve Bond

**Comment by gary-menzel** [comment]
No-one else has reported such a problem. I've upgraded to 6.7.4 and it worked perfectly fine.

- from 5 to 6 is a breaking change (semver standards) so a lot may have changed
- Which browser is this happening on? It may be related to some of the issues reported in the github Wiki FAQ if it is IE.
- Are you overriding any components?
- can you provide a codesandbox.io demonstrating the behaviour ?

**Comment by gary-menzel** [comment]
Closing unless this can be reproduced on 6.7.4.

**Comment by aikidoshi** [comment]
Hi Gary,
Sorry I'm under pressure from production deadlines right now. All I can tell you is that I reverted to the previous version and the headers came back.
Regards,
Steve
________________________________

**Comment by gary-menzel** [comment]
That's OK - @tannerlinsley is pretty strict with semver. I was not a user of the package prior to version 6 so I am not really aware of what techniques were being used back then. I suspect, with the major version change, that the architecture may have changed completely.

Probably best to stick with the version that is working until you have time to look at 6.7.* (probably best to fire up a separate spike to give it a run through - codesandbox.io is a great tool for doing that if you don't want to scaffold up another project - you could even start with a fork of one of the samples from the react-table,js.org site).
