### ISSUE TITLE
Basic code renders headers but not data

### ISSUE THREAD

**Issue by HenrikBechmann** [react-tools/react-table#602]
## What version of React-Table are you using?
6.7.4

## What bug are you experiencing, or what feature are you proposing?

The following code renders the column headers, but not the data:
```

    <ReactTable 
        data = {[['one',1],['two',2]]} 
        columns = {[{Header:'One'},{Header:'Two'}]}
    />
```

**Comment by gary-menzel** [comment]
Try
```
    <ReactTable 
        data = {[{one:1},{two:2}]} 
        columns = {[{Header:'One',accessor:'one'},{Header:'Two',accessor:'two'}]}
    />
```
and check out the documentation on react-table.js.org - react-table deals with an array of objects as the data (not nested arrays) and each column requires an `accessor`. You should also consider joining the #react-table channel on Slack (badge at the top of the readme in the doco). The github issues are for bug fixes, ideas and feature requests rather than implementation questions. Thanks.

**Comment by HenrikBechmann** [comment]
Thanks, what threw me is the statement: "Simply pass the data prop anything that resembles an array or object"; doesn't say it needs to be an array of objects. I tried signing up for slack and got a heroku error; works now.

Sorry to intrude.

**Comment by gary-menzel** [comment]
It is probably worth looking through the sample code and looking at how the sample data is composed. It is very flexible (and can handle some pretty strange data constructs) but that take a lot more understanding. Best to get the basics down first.

**Comment by HenrikBechmann** [comment]
I just didn't see a statement anywhere that said (default) data needs to be an array of objects, nor that accessor is a required property. I agree about basics. Some documentation citing basic requirements would be _very_ helpful. Even just the statement you made above! (maybe I just missed it in the docs)

Looks like a good product, but it's been hard to get started. (no I'm not a neophyte) The examples don't rule out an array of arrays, which surely is a basic data structure for tables! IAC I've joined your slack channel now, so I'll take it over there :-)

An array of arrays is suitable for a table display where download as csv is an option, btw. One would think it would be common.

In the meantime I'm pre-processing the nested arrays as objects:
[{0:value1},{1:value2}...]
