### ISSUE TITLE
generated filtered parameter results in infinite render loop

### ISSUE THREAD

**Issue by twheys** [react-tools/react-table#603]
## What version of React-Table are you using?
Bug appears in version 6.0.4 and still exists in the master branch

## What bug are you experiencing, or what feature are you proposing?
Generating the `filtered` parameter in the render function leads to an infinite render loop due to this condition https://github.com/react-tools/react-table/blob/master/src/lifecycle.js#L49

Since the array is evaluated with strict equality, having pointers to different arrays with the same values causes the condition to always evaluate to true. In my case, I am manually loading data, so `onFetchData` function is called which triggers a state update and my component re-renders, generating a new array.

## Use https://codesandbox.io/s/X6npLXPRW (by clicking the "Fork" button) to reproduce the issue.
Unable to reproduce it with the codesandbox code because it requires a way to update the component props after fetchData is called.

This sample should get you started. The fetchData function will need to do something that triggers a prop update for App.
https://codesandbox.io/s/nnkywzknol

## What are the steps to reproduce the issue?
1. Look at the sample I've provided, it requires a table with `filtered`, `manual`, and `fetchData` props
2. The filtered prop must be generated every render cycle (Cannot share the same pointer to value used in previous render)
3. The fetchData function must trigger a prop update for the component containing the react table so that the filtered prop is re-generated

## Suggested solution

In lifecycle.js, strict equality cannot be used to compare array values that come from props. There are several occurrences using the `sorted` and `filtered` props.

**Comment by gary-menzel** [comment]
I think it best to take this over to the #react-table Slack channel is it is implementation related (i.e. how to accomplish a particular use-case). There is a badge at the top of the react-table data for the Slack channel. Thanks.

[PS: You should be able to replicate any real-world actions in codesandbox - so I am not sure why the conditions can't be replicated there. Also not exactly sure why the filtered prop needs to be generated eery render cycle.  Maybe further explanation or questions are required.]

**Comment by twheys** [comment]
Ok, I'll take this to the discussions.  I am trying to implement a react-table where the filters and sort order is driven by query parameters, so the render function reads them.
