### ISSUE TITLE
Real-time data

### ISSUE THREAD

**Issue by redlock** [react-tools/react-table#604]
What is the proper way to update the table with streaming real-time data? Currently re-rendering the whole table just because a cell value changed is not practical and causing perf issues. Any suggestions?

**Comment by gary-menzel** [comment]
Well, this is the "React" way of doing things.  The cells and rows are properly keyed to allow React to only re-render what has changed. If it is causing performance issues then you may need to consider a different package.

However, this question is probably better asked over on the #react-table Slack channel as the github issues are not monitored by a wide range of people for implementation questions.

**Comment by redlock** [comment]
Thanks for the quick reply.
