### ISSUE TITLE
Disable sorting on a column header

### ISSUE THREAD

**Issue by navaneethr** [react-tools/react-table#605]
Is there a way to disable sorting on a specific header column?

**Comment by navaneethr** [comment]
Alright, this issue was addressed here.
https://github.com/react-tools/react-table/issues/336

**Comment by Dhirajbhujbal** [comment]
put sortable:false in column props

**Comment by corysimmons** [comment]
@Dhirajbhujbal `sortable: false` didn't work for me but `disableSortBy: true` did.

**Comment by jaiho8816** [comment]
Yes, you can disables sortby in specific columns
`const columns = [
]`

**Comment by bhavinzwt** [comment]
It is not working in react 17

**Comment by benjaminmerchin** [comment]
with TanStack v8,  you have `enableSorting: false,` now in the columnHelper.accessor

**Comment by bnabet08** [comment]
> with TanStack v8, you have `enableSorting: false,` now in the columnHelper.accessor

And for those who would also like to hide filters in v8, use `enableColumnFilter: false`

https://tanstack.com/table/v8/docs/api/features/filters#enablecolumnfilter
https://tanstack.com/table/v8/docs/api/features/sorting#enablesorting

**Comment by ipavlyk-startupsoft** [comment]
`enableSorting: false + accessorFn` or `accessorFn: null`

**Comment by toto1384** [comment]
This doesn't work well with typescript.

**Comment by BenjaOliva** [comment]
> This doesn't work well with typescript.

Did you found a solution ? Thought that `meta` can do the trick, but no luck yet. Still getting TS issues when trying to access it on component rendering logic
