### ISSUE TITLE
Column width

### ISSUE THREAD

**Issue by JeffWScott** [react-tools/react-table#607]
Two questions:
1. Can the columns be set to expand to their contents by default?
2. I'm trying to create buttons that will disable columns (ie. the user can click a button to remove a column.), but I can't quite figure out how.  My initial through was to feed in a columns object but that doesn't seem to be working.  Any ideas?

**Comment by JeffWScott** [comment]
for #2 what I'm trying to do is create the columns obj dynamically based on choices made by the user.  Then i will pass it in to the ReactTable's columns prop.  I believe this is the correct way to do it.

Where I'm failing is the "Cell" property.  I do not seem to be able to pass in my JSX like your example.  I can't come up with the correct way to do this.  

```
var testobj = [
    {
        Header: "Market",
        columns: [{
            Header: "Market Name",
            accessor: "MarketName",
            Cell: row => (<div><Button> {row.value}</Button></div>)
        }]
    },
    {
        Header: "Changes",
        columns: [{
            Header: "1min",
            accessor: "Percent1min.PercentPrice",
        }]
    }
]

**Comment by gary-menzel** [comment]
1. No it does not auto size to the content. I believe some people have used some CSS tricks to get that to happen but I am not sure what they are as I don't have that requirement (and I let my users just size the columns themselves and I store the column sizing in my DB).
2. Your code looks correct.

You should join the #react-table Slack channel (badge at the top of the readme in the doco). That is where most implementation questions get asked.

**Comment by JeffWScott** [comment]
Thanks Gary, will do.
