### ISSUE TITLE
Sorting is broken for immutable data

### ISSUE THREAD

**Issue by venkateswararao** [react-tools/react-table#611]
I am using react-table using immutable.js but sorting is broken let me know how to fix ?

**Comment by SyedSaifAli** [comment]
@venkateswararao Can you show what exactly are you doing for an illustration.

**Comment by gary-menzel** [comment]
This is an implementation question. Please take it over to the #react-table Slack channel (badge at the top of the readme in the docs).  We don't want to clutter the issues with implementation questions. Thanks.
