### ISSUE TITLE
ExpandedComponent prop does not accept ES6 classes

### ISSUE THREAD

**Issue by nbob** [react-tools/react-table#615]
## What version of React-Table are you using?
v6.7.4

## What bug are you experiencing, or what feature are you proposing?
It is not possible to use React component in ExpandedComponent prop.
Raised an error on ES6 classes.

## Use https://codesandbox.io/s/X6npLXPRW (by clicking the "Fork" button) to reproduce the issue.
https://codesandbox.io/s/qqwk8xz6q6

**Comment by gary-menzel** [comment]
The code expects a function-based component. Search the code in `defaultProps.js` for `ExpanderComponent` (and others) to see examples. Essentially, they are meant to be pure components. If you wanted to use a class-based component you'd still have to wrap it as an arrow function so you could pass in the props - e.g. - `ExpanderComponent={(props)=><YourComponent {...props} />`

This is not actually a bug but intended behaviour. If you'd like to discuss how to use class-based components with react-table in more detail then I suggest you head over to #react-table on Slack (badge in the readme in the doco).

**Comment by nbob** [comment]
I've tried to do the same thing with ThComponent prop.
https://codesandbox.io/s/qqwk8xz6q6

And i found that it works fine with class-based and function-based React Component.

**Comment by gary-menzel** [comment]
`ThComponent` is used directly as a component in the source (`<ThComponent .... />`) whereas the ExpandedComponent is used as a function.
