### ISSUE TITLE
Uncontrolled table

### ISSUE THREAD

**Issue by nbob** [react-tools/react-table#616]
## What version of React-Table are you using?
6.7.4

## What bug are you experiencing, or what feature are you proposing?
I am trying to use uncontrolled react-table component. So, it collapse all expanded rows after render calling.

## Use https://codesandbox.io/s/X6npLXPRW (by clicking the "Fork" button) to reproduce the issue.
https://codesandbox.io/s/m428k3v54y

## What are the steps to reproduce the issue?
1. Expand some row in table
2. wait for setInterval callback calling
3. All rows are collapsed now

**Comment by gary-menzel** [comment]
You should consider one or more of the following flags/props:
```
  collapseOnSortingChange: true,
  collapseOnPageChange: true,
  collapseOnDataChange: true, // specifically this one
  freezeWhenExpanded: false,
```
But, essentially, you may have to resort to using a controlled table depending on what you want to do.  I also suggest you take some more time to understand how ReactTable works as it is a bit different to a lot of other solutions out there and the behaviour may not be what you expect and there is a lot of doco to consume.
