### ISSUE TITLE
Passing data from firebase firestore

### ISSUE THREAD

**Issue by fsolar** [react-tools/react-table#618]
## What version of React-Table are you using?
15.6.2 (create-react-app)

## What bug are you experiencing, or what feature are you proposing?
pass external data from firestore database

Hi guys, I need to pass information to the table from firestore (new firebase data base), it's easy to pass the data through the .map function to an <li></li> or another jsx element, but I do not know how to pass the information from the database to the data={} prop of React Table.

Any help will be well recieved 👍

**Comment by gary-menzel** [comment]
I know nothing about Firebase but ReactTable just takes an array of data.

**Comment by gary-menzel** [comment]
This appears to be an implementation question and is better asked over on the #react-table Slack channel (badge at the top of the readme doco). There are a wider range of developers there who may have had experience with your particular stack. Thanks.
