### ISSUE TITLE
Get filtered data

### ISSUE THREAD

**Issue by gjvpaet** [react-tools/react-table#620]
Is there a way to get the filtered data from the table?

**Comment by gary-menzel** [comment]
There's a wiki FAQ....
https://github.com/react-tools/react-table/wiki/FAQ#how-do-i-get-at-the-internal-data-so-i-can-do-things-like-exporting-to-a-file

**Comment by MortimerMarsyja** [comment]
> There's a wiki FAQ.... https://github.com/react-tools/react-table/wiki/FAQ#how-do-i-get-at-the-internal-data-so-i-can-do-things-like-exporting-to-a-file

not working anymore

**Comment by ArthurPedroti** [comment]
@MortimerMarsyja e for anyone who wants to know, you can access the filtered data from the property `table.getFilteredRowModel().rows`

**Comment by Yuta4u** [comment]
thank you @ArthurPedroti
