### ISSUE TITLE
Possible hiding first level column in pivot rows?

### ISSUE THREAD

**Issue by mrshawn191** [react-tools/react-table#624]
<img width="1131" alt="react tables" src="https://user-images.githubusercontent.com/5851638/32919508-66f37e7e-cb26-11e7-9b4b-5518200d7b7f.png">

Hi just wanted to know if it is possible to hide the data on first level before collapsing the row?

**Comment by gary-menzel** [comment]
I have produced a HOC that makes the pivot work more like a Tree Table (and accomplishes what you have asked for every generated row in the pivot).  It is in the process of getting into the core code base but here is an example on codesandbox.io .... 

https://codesandbox.io/s/lxmr4wynzq

*NOTE: it does not (yet) support aggregation for those columns that have an aggregate value*

**Comment by mrshawn191** [comment]
Thank you works like a charm, btw do you know how to add color pivoted cells?

**Comment by mrshawn191** [comment]
also could you might answer, what is the preferred way to display large amount of text in cells? Should it display all on hover?

**Comment by gary-menzel** [comment]
The additional questions are more related to general implementation.  Please head over to the #react-table Slack channel for this.  There is a badge at the top of the README in the doco. Thanks.
