### ISSUE TITLE
Don't work getResizerProps for SubComponents react-table

### ISSUE THREAD

**Issue by temonich** [react-tools/react-table#627]
This is example: https://codesandbox.io/s/ry2zznnr5n

I create ReactTable with another ReactTable as SubComponents.
When I want  catch onResize event on inner table, but work only for parent table.

its need for me, for synchronize all inner column size in subcomponents.

**Comment by gary-menzel** [comment]
This is an implementation question. Please head over to the #react-table Slack channel for implementation questions. There is a badge at the top of the README in the doco. Thanks.

However, you were using an ALPHA version of react-table in your codesandbox. The following codesandbox is updated to the latest version and uses a more appropriate mechanism for testing the `onResizedChaged` and seems to work correctly on the inner table.

If you want it to sync with the outer table, you'll need to trap the information in the resized parameter and push that back into the outer table using your component state and passing as props.

https://codesandbox.io/s/9ly50720pw

**Comment by mike391** [comment]
@gary-menzel you wouldnt happen to still have that code sandbox snippet somewhere still?
