### ISSUE TITLE
Multi Level Header

### ISSUE THREAD

**Issue by Vineeth-Mohan** [react-tools/react-table#629]
We are trying to build a pivot table out of react-table  but then there is just one thing that is missing - Multi level headers. At this point , we can only have a maximum of 2 level of header. Not anything beyond that. Kindly add provision to accept multiple level of headers. We can follow the same format where we can keep on adding columns inside each column.

Reference - orb.js has multiple level of headers - http://orbjs.net/

**Comment by gary-menzel** [comment]
Are you aware that you can replace the `TheadComponent` (and most of the other components) ?

In fact, you can replace everything in the rendering if you use functional rendering.

Please also feel free to submit a PR for the changes you have suggested and they can be considered.

**Comment by gary-menzel** [comment]
If you plan to submit a PR it will be reviewed and considered for inclusion. In the meantime, this issue will be closed.

**Comment by michaelcohen716** [comment]
The TheadComponent solution isn't working for me...is there a new approach to hiding the top header?
