### ISSUE TITLE
Failed prop type: Invalid prop `noDataText` supplied to `ReactTable`, expected a ReactNode.

### ISSUE THREAD

**Issue by Alex-Innomn** [react-tools/react-table#630]
## What version of React-Table are you using?
v 6.7.4

## What bug are you experiencing, or what feature are you proposing?
In v5.6.0, I used successfully to render "customized" noDataText with markups as follows:
`noDataText = {() => (
                        <span>This project has no jobs. Please add new jobs using the <FontAwesome name="plus" style={{ color: '#01a982' }} /> button.</span>
                    )}`
With the latest version 6.7.4,  I am getting "Failed prop type: Invalid prop `noDataText` supplied to `ReactTable`, expected a ReactNode." warning. The closed issue  #583 had solved similar issues for different props.

If I give string value to noDataText prop, it works as expected.

**Comment by gary-menzel** [comment]
This is likely due to the inclusion of props validation.  However, you should be able to remove the arrow function and just use the `<span ... />` directly - e.g. - `noDataText={<span>...</span>}`. Let us know if that works or not.

@frankolson Related to the props validation?

**Comment by Alex-Innomn** [comment]
Thanks @gary-menzel !
No warning once I removed the arrow function.
