### ISSUE TITLE
Update Changelog.md

### ISSUE THREAD

**Issue by alexmarles** [react-tools/react-table#632]
Hi everyone,

I open this to ask the maintainers and collaborators to keep the Changelog file up to date. The last table release of the package seems to be ```v6.7.4``` but the Changelog file only keeps track up to version ```v6.5.0```

Thanks

**Comment by gary-menzel** [comment]
I'm going to look into recreating the CHANGELOG from the Release tags. Just not sure when I will get to it.

**Comment by gary-menzel** [comment]
The CHANGELOG is mostly up-to-date now. So closing this issue.
