### ISSUE TITLE
Material Theme

### ISSUE THREAD

**Issue by davidgit75** [react-tools/react-table#633]
## What version of React-Table are you using?
Last version

## What bug are you experiencing, or what feature are you proposing?
Isn't an error, is only that I want to get the table with a material style, so we need use a material table that allow us resize columns, so we have tried to use react-md (datatable) and add resize styles but really is very ugly. Exist some material theme for reacttable?

Thanks

**Comment by gary-menzel** [comment]
react-table is not theme-based so there is no simple way to create a theme for a particular CSS approach. You have the following options to style react-table:

- style, headerStyle, footerStyle on columns
- getProps and getHeaderProps on columns
- a function override (get...Props) for pretty much every component
- completely replacing the sample CSS provided with the package (or selectively for various pieces)
