### ISSUE TITLE
Custom sorting/filtering 

### ISSUE THREAD

**Issue by philipp-sorin** [react-tools/react-table#635]
## What version of React-Table are you using?
lastest
6.7.4
## What bug are you experiencing, or what feature are you proposing?
Hello, I've just started use React-Table and have a little question, which I didn't find in a documentation.
So, I have a UI where filter/sorting/column title placed in header. But I can't manipulate sorting/filtering from header. How can I resolve it?

**Comment by gary-menzel** [comment]
This is an implementation question and is best asked on the #react-table Slack channel (there is a badge at the top of the README doco). The github issues are really for bug fixes or feature requests. Thanks.

In any case, you should read the the documentation again. There is a section about "Fully Controlled Component" and look at the `filtered`, `sorted`, `onFilteredChange` and `onSortedChange` props.
