### ISSUE TITLE
Mysterious, Magical minRows

### ISSUE THREAD

**Issue by spacedarcy** [react-tools/react-table#636]
## What bug are you experiencing, or what feature are you proposing?
I'd like to see additional documentation and an example demonstrating the use of `minRows` to better highlight and explain its use to developers new to react-table. Personally, my users languished for _months_ waiting for me to implement a way to take the empty rows out of tables, only for me to discover the feature had been there for quite a long time. (`minRows` appeared in react-table a mere two weeks after I was originally asked about it. 😞) What finally drove me to make this feature request was seeing this issue: https://github.com/react-tools/react-table/issues/555 This request indicates that I'm not unique in failing to notice the amazing `minRows` in the docs, and therefore there's work to be done in surfacing this extremely useful setting.

**Comment by gary-menzel** [comment]
There are a lot of things to "fix" in ReactTable - doco is probably not as high on the list as some of the other technical pieces. But happy for you to submit a PR.

**Comment by spacedarcy** [comment]
I'm treating this feature request largely as a todo for myself. And well, you never know if someone else will randomly have the time.

**Comment by gary-menzel** [comment]
So, I have never used that prop: if you set it to "zero" then any "pad rows" on the final page are not shown?
[I looked at the code and that appears to be what would happen - although I don't have a use case and would have to run up a purpose-built test]

**Comment by spacedarcy** [comment]
@gary-menzel That's correct. It's very handy for cutting down whitespace on a page. 

Although to be honest, the only use I can think of for setting it to a non-zero value would be to provide enough padding for the No Rows Found message to display nicely inside the body of the table. That only applies in situations where the number of returned results is less than the page size though.

**Comment by gary-menzel** [comment]
Which I had thought was the original intention - so this other use may be an side effect.  I'll have a look at it when I am next in the code and add something into the doco (which I fully expect a lot of people won't read - :) - present company excepted).

**Comment by gary-menzel** [comment]
@spacedarcy I am adding some notes to the doco on `minRows` (but no example). I am also putting a note in that indicates setting it 0 when there are no rows in the data may cause the table formatting to look strange.  Having played with it a little, I doubt I would ever use it as my users like the table page to stay the same size and the pagination buttons to not move.

I can't yet say when the doco updates (yours is only one of a couple) will be released but it will get in with the next actual push to npm.  It didn't make the cut for 6.7.5 that went up today.

**Comment by spacedarcy** [comment]
Awesome, thanks. And yes, it does look a little strange with the default no rows styling when minRows is at 0. I have the opposite use case: my users don't paginate very often and the table sizes can be highly variable. So having the buttons be a 'moving target' isn't as big a priority as optimizing screen space when many tables are displayed at once. If they decide it's a problem in the future, I guess I can always use the option to have pagination controls on top!

**Comment by tannerlinsley** [comment]
Closing due to issue age. If you think this issue needs to be reopened, please check the latest version of React-Table for the issue once more and reopen if appropriate. Thanks!
