### ISSUE TITLE
would react table work with arrays in a JSON? I have an array in a JSON and would like to display the details as a table

### ISSUE THREAD

**Issue by sarat34408** [react-tools/react-table#637]
## What version of React-Table are you using?
Your bug may already be fixed in the latest release. Run `yarn upgrade react-table`!
Place your version here...

## What bug are you experiencing, or what feature are you proposing?
Please include a detailed explanation here...

## Use https://codesandbox.io/s/X6npLXPRW (by clicking the "Fork" button) to reproduce the issue.
Then paste a link to your newly forked codesandbox here...

## What are the steps to reproduce the issue?
1. list the steps
2. to reproduce
3. the issue

**Comment by hansena** [comment]
Yes

**Comment by sarat34408** [comment]
@hansena any examples? Here is how my data looks like.
 name:{
        age:,
        gender:,
        education:{
          highschool:xxx,
          university:yyyy,
        }
        hobbies:[{name: swimming, timings: 3-4PM},{name:running,timings: 8-9PM}]
       }

**Comment by gary-menzel** [comment]
This is an implementation question and is better asked and answered on the #react-table Slack channel (there is a badge at the top of the README in the doc).  The github issues is predominantly for bugs and new feature requests and is only monitored by a handful of active developers. 

[FWIW: your data appears to be a combination of objects and nested arrays - ReactTable is not a "tree" table and you would need to use the SubComponent mechanism to display the nested data or you would need to consider flattening out the data and using the pivot functionality. Another possibility would be to create a Cell renderer for the nested array data and just iterate over the array elements output a `<div>` or `<ul>/<li>`.]
