### ISSUE TITLE
Is there any way to highlight selected row.

### ISSUE THREAD

**Issue by wmaiouiru** [react-tools/react-table#638]
I am trying to add a border or highlight the entire row in react-table. I was wondering if there is any way to intercept the style in rows? Something like 

(d) => {
   // do something with the row data
   return style
}

**Comment by gary-menzel** [comment]
`getTrProp`, `getTdProps`, `get...Props` - there are a whole bunch of them in the doco and an example of how to change the style. You could also consider a CSS override by including another CSS file after the core CSS.  The structure of the CSS is easy to follow as it is "table"-based nomenclature.

**Comment by tesicg** [comment]
How to use CSS override to get the selected row highlighted? I've overridden the original CSS for hover event: .rt-tr:hover. What event is handling row selection?
