### ISSUE TITLE
Render react table as standard html table instead of divs

### ISSUE THREAD

**Issue by Goatfried** [react-tools/react-table#639]
## What version of React-Table are you using?
6.7.4

## What bug are you experiencing, or what feature are you proposing?
In my project, I'm using [Bulma.io](https://bulma.io) as a css Framework.  I'd like to use it for table styling as well, but it requires a standard html table structure with table > thead > tr > th and table > tbody > tr >td.
This doesn't work with the default react-table behavior, since tables are rendered as nested div components.
I know I can use the Renderer definitions to override the render of table content (cell, footer, header, ...), but is it possible to modify it, so that it generates a standard html table instead?

**Comment by gary-menzel** [comment]
This is highly unlikely. You may as well just build your own table. The problems will arise when you try and do the grouped columns, SubComponent and Pivot expansion, etc. as there are additional wrappers (`<div>s`) used that just aren't available in a normal `table` set of tags.

Furthermore, if you just try to replace certain portions, you are going to be fighting against the `flexbox` that your framework uses compared to what ReactTable is using.

You can use functional rendering to render anything you like - but then you'd probably only really be using the filtering/sorting and would still have to render all of that UI functionality anyway.

It's probably a better idea to see if someone has built a table component for that framework - it looks like they already have the styling for one there.

**Comment by Goatfried** [comment]
Okay, I understand that.
Well, it's only about appearance anyway, so I should probably just copy and modify the relevant part of the stylesheets

**Comment by Goatfried** [comment]
For anyone wandering here: I dropped the approach, but I could have achived what I wanted via component override in theory.
