### ISSUE TITLE
Clear filters

### ISSUE THREAD

**Issue by Krakof** [react-tools/react-table#640]
Hi,
Found this issue   #540 and just want to know if am I right using such way to clear all filters:
```
<ReactTable
                className={'-striped -highlight '}
                data={data}
                columns={columns}
                showPagination = {data.length > 100}
                defaultPageSize = {100}
                minRows = {1}
            >
                {(state, makeTable, instance) => {
                    return (
                        <div className='table-wrap'>
                            <button
                                className="reset-filters"
                                onClick={() => {
                                      ##instance.setState({
                                        filtered:[],
                                        sortedData: instance.state.data
                                    })
                                }}
                            >Reset filters</button>
                            {makeTable()}
                        </div>
                    )
                }}
            </ReactTable>
```
I'll be grateful for any advice. Thanks
Version 6.7.4

**Comment by danielmariz** [comment]
I'm not sure about this children approach, I've never seen a example like that but if your children component works I'd say that you need to manage your state in the React Table parent (wrapper) than you can access and clear all filters.

Something like that

```

export default class TableWrapper extends React.Component {
    constructor(){
        super();
        // start your state
        this.state = {
            filtered: []
        }
    }
    render () {
        return <ReactTable
                className={'-striped -highlight '}
                data={data}
                columns={columns}
                showPagination = {data.length > 100}
                defaultPageSize = {100}
                minRows = {1}
                //add filtered prop
                filtered={this.state.filtered}
            >
                {(state, makeTable, instance) => {
                    return (
                        <div className='table-wrap'>
                            <button
                                className="reset-filters"
                                onClick={() => {
                                    //find a way to access the ReactTable Wrapper
                                      TableWrapper.setState({
                                        filtered:[],
                                    })
                                }}
                            >Reset filters</button>
                            {makeTable()}
                        </div>
                    )
                }}
            </ReactTable>
    }
}
```

But those question is easier solved if you ask on slack chat

**Comment by gary-menzel** [comment]
I would not recommend setting the state directly on the ReactTable instance.  You should treat the internals of ReactTable as "read only" and not set anything directly (as you may be bypassing some critical code required to maintain the overall state).

The "safest" way to "clear" the filters or the sorting is to capture the `onSortedChange` and `onFilteredChange` and store those in your own state to pass back into your ReactTable instance as props.

Also, it is very unusual to use the functional rendering for the purpose of setting those properties.  You should only consider using functional rendering when you want to completely replace the way that ReactTable renders the data.

**Comment by Krakof** [comment]
Thanks for all your suggestions.
So the main idea is: if I want to use 'Reset filters' button I should pass filtered options into ReactTable as Daniel solution at  #540 . Am I right?

**Comment by gary-menzel** [comment]
Yes - Daniel's solution is the most basic solution and is very tidy.
