### ISSUE TITLE
Cannot use React classes as custom renderer

### ISSUE THREAD

**Issue by adrfoong** [react-tools/react-table#642]
## What version of React-Table are you using?
6.7.4

## What bug are you experiencing, or what feature are you proposing?
1. Cannot use react class as custom renderer
2. JSX renderers don't seem to work

## Use https://codesandbox.io/s/X6npLXPRW (by clicking the "Fork" button) to reproduce the issue.
https://codesandbox.io/s/p35n0z027

## What are the steps to reproduce the issue?
As you can see in the sandbox, I've created a simple React class and passed it in as a custom cell renderer. This breaks because  in `src/utils`, we have: 

```
function normalizeComponent (Comp, params = {}, fallback = Comp) {
  return typeof Comp === 'function'
    ? Object.getPrototypeOf(Comp).isReactComponent
      ? <Comp {...params} />
      : Comp(params)
    : fallback
}
```

If `Comp` is a React class, `Object.getPrototypeOf(Comp).isReactComponent` returns undefined. `Comp.prototype.isReactComponent` returns `{}`, which is what I think we're really expecting.

In addition, passing in `<CustomRenderer />` instead of `CustomRenderer` does not break anything, but also does not actually use the custom renderer. This is true for both functional components and classes.

I also haven't been able to find any examples using a React class or JSX, so I might be doing this wrong, but these seem to be fairly normal use cases to me.

**Comment by gary-menzel** [comment]
The doco is most likely out of date or the code has broken since become React 16 compatible.  A Cell renderer is best done as a function as it takes a varied set of parameters. You can break those parameters down and return JSX which will render as per the examples on codesandbox.io.  So, for example, something like this will work (or a variation with a more complex function:
```
Cell: () => <YourComponent>
```

**Comment by adrfoong** [comment]
Thanks for the reply. While I don't mind doing what you suggested, I think it's inconsistent with what's in the docs:

>Any of these renderers can be one of the following:
>
>- A React Class
>- JSX or any rendered react component
>- Stateless functional component
>- Function that returns any primitive

**Comment by gary-menzel** [comment]
Yes - I did mention that the doco appears to be out of date.  However, there are also changes with React that have not been incorporated into the code.  The list of fully conversant maintainers is quite small at present.

**Comment by gary-menzel** [comment]
While there may be a consistency issue with the doco or the code, this issue will be closed as there is a suitable workaround.  However, any PR to address the discussion will be reviewed and actioned accordingly.
