### ISSUE TITLE
Add right border to last column

### ISSUE THREAD

**Issue by SirWinn3r** [react-tools/react-table#646]
Hi,

I'm using the version 6.7.4 (last one to this day), and I'd find useful to actually see the right border of the last column.
 
If you look at this example code:
https://codesandbox.io/s/qxqlvl62qq

If I want to resize the last column, I have to find the last column's right border, which is not convenient due to this border not being visible.

**Comment by gary-menzel** [comment]
You can change any of the CSS or styles on the column objects. I added this to my CSS change all the border styles as I wanted all my tables to look the same and the lighter grey borders were just a little hard to see....
```
.ReactTable .rt-tbody .rt-td,
.ReactTable .rt-tbody .rt-td:last-child,
.ReactTable .rt-thead .rt-th,
.ReactTable .rt-thead.-filters .rt-th,
.ReactTable .rt-thead .rt-th:last-child, 
.ReactTable .rt-thead .rt-td:last-child,
.ReactTable .rt-tfoot .rt-td,
.ReactTable .rt-tfoot .rt-td:last-child
{
  border-right: 1px solid rgba(0, 0, 0, 0.2);
}
```
Please also consider joining the #react-table Slack channel (badge in the README In the doco) as the github issues are bugs and feature requests. Thanks.

**Comment by SirWinn3r** [comment]
Hi,
Thanks for this.
This was actually a feature request, I'm proposing to change the default behavior.

**Comment by gary-menzel** [comment]
This is unlikely to make it into the core as it is possible to override the functionality (which is largely what the architecture of ReactTable is about rather than fine-tuning the library).

**Comment by SirWinn3r** [comment]
Alright, thanks again.
