### ISSUE TITLE
horizontal scroll

### ISSUE THREAD

**Issue by danmolitor** [react-tools/react-table#647]
Hi there,

I've looked through the props and issues, and I could just be missing something. Is there a way to set a width and overflow for the table so that the table can be scrollable horizontally, or will I have to do that with CSS?

Thanks.

**Comment by gary-menzel** [comment]
The columns autosize to fit the width. If you size the columns beyond what can fit, the horizontal scroll will automatically be enabled. The table is designed to be "responsive" and does not support setting a horizontal width.  However, each column allows for a `width` property - which you could set to various amounts that would cause the scroll to kick in.

Please also consider joining the #react-table Slack channel (badge in the README in the doco) as the github issues are for broken code or feature requests. Thanks.

**Comment by AntonDeXy** [comment]
I have the same problem and spent a lot of time doing it. So I just wrapped a table to a div and set for div `max-width: 100%;
    overflow-x: auto;`
I think it’s not actually for you now, but maybe somebody will have the same question

**Comment by SomnathKadam** [comment]
Thanks @AntonDeXy ,

```
<div style={{ maxWidth: '100%', overflowX: 'auto' }}>
              <table {...getTableProps()}> ........  </table>
</div>
```

**Comment by anish-sarvadhi** [comment]
However, when we attempted to use that, no dropdown menu opened. How can we fix this?
