### ISSUE TITLE
how to know page index is next or previous   `

### ISSUE THREAD

**Issue by amiiy** [react-tools/react-table#650]
## What version of React-Table are you using?
6.7.4
I have a table with server-side rendering. I use loadMoreentries() function of graphql for page pagination. here :  
```
<ReactTable
        manual
        data={tableData}
        columns={columns}
        loading={loading}
        onPageChange={pageIndex => loadMoreEntries({ pageIndex: pageIndex })}
        onFetchData={state => {
          const options = { where: JSON.stringify(state.filtered) };
          refetch(options);
        }}
      />
```
how i can know what was previouse page index?

**Comment by gary-menzel** [comment]
You have to manage that in your own `state` (by collecting it in your `onPageChange` handler and storing it in store by you load the data)

**Comment by mschipperheyn** [comment]
Hmm, what I think the functionality should be is that if you set the page attribute to x, when you click next it should be page +1 and when you click previous it should be page - 1. State management should not be required. I consider it a bug that this is not the case.
