### ISSUE TITLE
Clicking an individual cell opens a subcomponent with data relevant to the cell that was clicked

### ISSUE THREAD

**Issue by michaelangeliu** [react-tools/react-table#652]
This library has been amazing! Getting it to handle our data has been incredibly straightforward.

I do have a question, is there a trigger that I can call to open the subComponent and pass new data to that subComponent?

Say for example, we're measuring sales by various people. In the cell, we have 10 sales. We'd like to click on the 10 and have the subComponent be displayed and show that the 10 sales were made to these 10 people. Or that these 4 salespeople made 1, 2, 3, 4 sales respectively.

I'd be happy to explain in more detail as needed!

Thanks!

**Comment by gary-menzel** [comment]
`SubComponent` can get data from anywhere available to it in the scope of where the component is defined or the props that are passed to it.  As far as opening it programmatically - you need to do that via the `expanded` prop on ReactTable.

However, this is really an implementation question and should be taken over to the #react-table channel on Slack (badge at the top of the README on the doco site). Thanks.
