### ISSUE TITLE
[QUESTION] How can I provide custom component to aggregated row?

### ISSUE THREAD

**Issue by buddythumbs** [react-tools/react-table#653]
## What version of React-Table are you using?
Your bug may already be fixed in the latest release. Run `yarn upgrade react-table`!
Place your version here...
`"react-table": "^6.7.4",`
## What bug are you experiencing, or what feature are you proposing?
Not an issue but a question really.

Not sure where this code would go (as the base unit seems to be column) - but would it be possible to provide a custom renderer for aggregated rows?

Great great library by the way!

**Comment by gary-menzel** [comment]
Do you mean the whole row?  There are component overrides for this in the doco.

Or do you mean to a specific cell - there is an `AggregatedComponent' override.

This is probably better taken over to #react-table on Slack (badge in the README from the doco). Thanks.

**Comment by buddythumbs** [comment]
Hi @gary - yes the entire row - sorry I missed the example in the documentation.

**Comment by gary-menzel** [comment]
It's probably not 'easy' as replacing the entire row will have challenges and you'd probably need to use a couple of different component overrides.
