### ISSUE TITLE
[Request] show title or add custom 

### ISSUE THREAD

**Issue by ThatBrianDude** [react-tools/react-table#654]
HTML elements have the `title` attribute which pops up nicely when you hover over them.

(Try it out on the fork or start button)

A great addition to cells would be allowing titles.
You could then add two props to columns: 

showTitle: boolean
title: string

If showTitle is set to true but no title is provided you default to the column header text. 

(Since the header text in the cells title is kind of redundant I would recommend showTitle to default to false)

**Comment by gary-menzel** [comment]
Are you aware you can build an visual rendering you like with the `Cell` component?

There is a general rule with ReactTable that it is very lightweight so the user can do whatever they like (it is not about abstracting all the rendering options as this would start to bloat the code).

**Comment by ThatBrianDude** [comment]
Oh sure, I just thought this is something that might be quite common.

Upon closer inspection though I just realised that there arent any features yet that arent purely functional so forget my suggestion I overlooked that

**Comment by gary-menzel** [comment]
There is quite a lot that can be changed with function overrides.  In fact, I think there is only one other package that ReactTable depends on (everything else is just pure functions).

I'll close this now and hope to see you over at #react-table on Slack (badge in the README doco). Thanks.
