### ISSUE TITLE
Accessor+ Cell doesn't play well together

### ISSUE THREAD

**Issue by rotilho** [react-tools/react-table#655]
## What version of React-Table are you using?
6.7.4

## What bug are you experiencing, or what feature are you proposing?
I have a custom accessor which display emails breaking lines like:

1@mail.mail
2@mail.mail
3@mail.mail

It works fine until add a custom editor. After that the accessor stops to work and the results are displayed with coma:

1@mail.mail,2@mail.mail,3@mail.mail

This is my column:
```
{
            id: "emails",
            Header: "Emails",
            accessor: route => <MailFormatter emails={route.emails}/>,
            Cell: this.renderEditable.bind(this)
}
```

## Use https://codesandbox.io/s/X6npLXPRW (by clicking the "Fork" button) to reproduce the issue.
https://codesandbox.io/s/m7y83zlk0j

## What are the steps to reproduce the issue?
1. Create a custom acessor
2. Add a Cell configuration

**Comment by gary-menzel** [comment]
NOTE: the `accessor` is design to accept some type of textual or basic data as a return value as it uses that for filtering and sorting - it is not the primary way to display data unless what goes in is what you want to come out.  Returning a "component" will not work with the `accessor`

The `Cell` is the correct place to render data. If you want a component of editable and some other type of visualisation - this is where you should put a component.
