### ISSUE TITLE
Small corrections to documentation

### ISSUE THREAD

**Issue by DavidIMcIntosh** [react-tools/react-table#656]
## What version of React-Table are you using?
Your bug may already be fixed in the latest release. Run `yarn upgrade react-table`!
6.7.4

## What bug are you experiencing, or what feature are you proposing?
One small definite error, one small potential error in documentation:
1) In your section entitled "Custom Cell, Header and Footer Rendering", the first two items in your list are:
  *  row - Original row from your data
  *  row - The post-accessed values from the original row
The first is a typo - it should be
  *  original - Original row from your data
  *  row - The post-accessed values from the original row
2) In your list of props passed to the renderers - in particular, the props that are passed to the `Cell` renderer (and maybe others), it seems the props also include a `column` property that contains the entry from the`Columns` array for that column.  I think some of your examples use this prop, and I seem to be using it successfully in my code.  It contains much useful information, such as `props.column.id`, which is indispensable for callbacks.  This should be included in the documentation, unless I am misunderstanding something.

## What are the steps to reproduce the issue?
    export const Cell = (cellInfo) => {
        let colInfo = cellInfo.column;
        let colId = colInfo.id;
        ....

**Comment by gary-menzel** [comment]
There are lots of issues with the doco that need to fixed - they are on the radar (including the 'row/original' one).

**Comment by tannerlinsley** [comment]
Closing due to issue age. If you think this issue needs to be reopened, please check the latest version of React-Table for the issue once more and reopen if appropriate. Thanks!
