### ISSUE TITLE
Custom pageSize gets the table confused

### ISSUE THREAD

**Issue by DavidIMcIntosh** [react-tools/react-table#657]
## What version of React-Table are you using?
Your bug may already be fixed in the latest release. Run `yarn upgrade react-table`!
6.7.4

## What bug are you experiencing, or what feature are you proposing?
Setting `pageSize={someCustomPageSize}` where `someCustomPageSize` is a value not contained in the `pageSizeOptions` (for example `pageSize={30}` where `pageSizeOptions` is not set, and thus has the defaulted values `[5, 10, 20, 25, 50, 100]`) gets the table react-tbel conponent confused, especially when changing sizes with the automatically-provided page-size-changer option at the bottom.  Page counts are incorrect, page selection does not work correctly, rendering can get confused, there are multiple issues.

## What are the steps to reproduce the issue?
1. If this is not easily reproducable, I will try to find some time to work up a simple example from my code.

**Comment by gary-menzel** [comment]
You definitely need to sync your possibly page sizes and the selection list. You might also want to see if `defaultPageSize` resolves the problem you were having.

If you are new to ReactTable it is probably better to ask these things on the #react-table Slack channel (badge at the top of the README in the doco) as the github issues are reserved for bugs that have no workaround or new feature requests.  Thanks.
