### ISSUE TITLE
Separate theme and functional css

### ISSUE THREAD

**Issue by mikecentiq** [react-tools/react-table#660]
Please consider separating the functional and stylistic CSS into separate files. I am currently trying to style my table and I'm having to perform actions like removing box shadows and borders etc. It would be nice if I could just include the functional CSS so I have a working table, and then apply all of my styling/theming on top. Adding new styles rather than having to remove ones that I don't want. Things like color, padding, borders, border radius, box shadows, font weight etc belong in a separate theme file which you can optionally include.

**Comment by JedWatson** [comment]
We've implemented custom styling comprehensively in v2: https://deploy-preview-2289--react-select.netlify.com/styled

This doesn't implement specifically what you want, but I think we could work it a bit more to implement "base" styles and various "themes" that people can opt into (similar to how we've done the `Animated` components)

I'm working to finalise the API at the moment so let me know if you've got any feedback - if nothing else, it should make it much easier to remove "presentation" styles that are applied by default.

**Comment by JedWatson** [comment]
**edit** sorry for anyone who just got a notification from me on this, I typed a reply into the wrong window...

**Comment by tannerlinsley** [comment]
Great request. I'll work on this.

**Comment by digitalmaster** [comment]
Is there a clean-ish way to remove all the theme related styles?

**Comment by tannerlinsley** [comment]
Closing due to issue age. If you think this issue needs to be reopened or if it should be turned into a pull-request, please check the latest version of React-Table for the issue or feature once more and reopen or create a PR if appropriate. Thanks!
