### ISSUE TITLE
Updating the columns prop doesn't cause a re-render

### ISSUE THREAD

**Issue by jontansey** [react-tools/react-table#662]
## What version of React-Table are you using?
6.6.0

## What bug are you experiencing, or what feature are you proposing?
Updating the columns prop doesn't cause a re-render

## example
https://codesandbox.io/s/2j0kz92y6j

2 buttons have been added to (naively) demonstrate the issue:

Button 1 doesn't work but should, Button 2 forces a re-render by adding an int key prop and incrementing when changing the columns. 

##
suggested fix is to make the componentWillReceiveProps comparison of old columns vs new columns a deep comparison. (I'll create a pull request with a fix shortly).

**Comment by tannerlinsley** [comment]
Please refer to this example on how to correctly update a state variable in the way you are demonstrating: https://codesandbox.io/s/o4q0lqqwxy
