### ISSUE TITLE
Checkbox Table Uncaught ReferenceError: regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by s-wynter** [react-tools/react-table#664]
## What version of React-Table are you using?
6.7.4

## What bug are you experiencing, or what feature are you proposing?
I have copied checkboxHOC.js and index.js from react-table/docs/src/examples/checkbox/, and it compiles okay, but the error I get in console is 'Uncaught ReferenceError: regeneratorRuntime is not defined'. The error mentions bootstrap, but after taking bootstrap out of my package.json the error persists. This might be really obvious to the more experienced, and I apologize if that is the case.

## Use https://codesandbox.io/s/X6npLXPRW (by clicking the "Fork" button) to reproduce the issue.
https://z2r4jyx0yx.codesandbox.io/ Weirdly I can't re-create the error, as in codesandbox I don't get any errors but nothing renders.

## What are the steps to reproduce the issue?
1. Copy checkboxHOC.js and index.js from react-table/docs/src/examples/checkbox/ into your code editor
2. make sure you're importing the component from the right place (in my case that's "cols_for_table.js")
3. npm start

**Comment by gary-menzel** [comment]
Firstly, you should probably look at the current source on GitHub as this has been incorporated into the main src tree under `selectTableHOC` and the code has probably changed slightly.

Secondly, I have no idea what `regeneratorRuntime` is. I built the `selectTableHOC` code and this term is unfamiliar to me.

**Comment by s-wynter** [comment]
Thanks for your answer, I've gotten the updated code, and now I'm getting the same result as codesandbox; compiles okay but renders nothing with no errors. Should I close this issue and raise a new one?

**Comment by gary-menzel** [comment]
This is not a problem with the code as it works in a number of environments. This is better taken to the #react-table Slack channel (badge in the README in the doco). As I previously said though, I have absolutely no idea what `regeneratorRuntime` is - it is not part of the `selectTableHOC` code and I have never seen that reported in any React code that I have built.

According to this: 
https://stackoverflow.com/questions/33527653/babel-6-regeneratorruntime-is-not-defined

It is a babel related thing and not related to #react-table.
