### ISSUE TITLE
[Question] Use custom css styles opposed to jsx properties

### ISSUE THREAD

**Issue by jordenstuder** [react-tools/react-table#665]
## What version of React-Table are you using?
6.7.4

## What bug are you experiencing, or what feature are you proposing?
From the examples I am seeing that you can set the midWidth/width properties through jsx properties when you are creating the ReactTable column property. Is there a way to specify a className for the column in order to be able to do custom css on an individual column width to keep it out of the code and put it into the styles?

**Comment by mikedevita** [comment]
yes, its literally in the README.md in the [columns](https://github.com/react-tools/react-table#columns) section.

```
// ...
  className: '', // Set the classname of the `td` element of the column
// ...
```

**Comment by jordenstuder** [comment]
Guess I completely missed that. Multi-tasking failure.

Thank you.
