### ISSUE TITLE
Add column to getResizerProps cb

### ISSUE THREAD

**Issue by Thimey** [react-tools/react-table#666]
Currently the column argument for `getResizerProps` is passed as `undefined` : https://github.com/react-tools/react-table/blob/1e849df9992b5b9035c0c0a4f5c942d9d76bbac1/src/index.js#L202

It would be really handy if the column for the resizer was passed through (I believe it would be the column to the left of the resizer component)

My use case is an expand to fullwidth on `onDoubleClick` (similar to the behaviour in Excel)

I have forked, made the change but not sure how to see my changes locally. If you could let me know how, I can test and submit a PR.

Cheers

**Comment by gary-menzel** [comment]
The "how to see my changes locally" does not have a "simple" answer at the moment. The samples were moved to codesandbox to make them more accessible for experimentation but it means they are no longer part of the source.  You can, however, follow the README directions and fir up the docs server along side watching source changes and add in some test components (but it would be best to remove them before submitting the PR).

The other question I have (without seeing the changes) is what/where the change would be.

**Comment by Thimey** [comment]
Hi Gary, thanks for the reply.

Re the changes - please see PR (https://github.com/react-tools/react-table/pull/667)

In the mean time I have found another solution - just use the `getTheadThProps` instead. Therefore, this is not critical.

**Comment by gary-menzel** [comment]
@Thimey This should have been released in 6.7.5 (just a few minutes ago as of writing this). I'll close for now - reopen if there is an further issue.
