### ISSUE TITLE
Fully controlled component manual fetch preventing when pass props to it via attributes

### ISSUE THREAD

**Issue by WebdevMerlion** [react-tools/react-table#668]
React-Table 6.7.4 

How can i prevent fireFetchData() if i change props of component by its parent (simply to pass via attributes), since last changes in [8792bd95a](https://github.com/react-tools/react-table/commit/8792bd95a0a2c6ecf24ef717e09cdcd7d7667a9e) fired it every once props has changed
And its still fired with old state.

**Comment by gary-menzel** [comment]
This is desired behavior.

If any of `page`, `pageSize`, `sorted` or `filtered` change as a result of creating the new internal state then a request for an update of the data is required. The purpose of `fireFetchData` is to trigger the `onFetchData` callback - which is to allow the user to control and get new data from a back end or some type of data store.

If your requirement has conditions around any of those 4 properties (where you would sometimes not update with any new data), you need to manage that in your `onFetchData` as ReactTable can't be aware of special cases.

NOTE: the whole operation of React itself is based on detecting changes in props/attributes and causing a render based on that change.

**Comment by WebdevMerlion** [comment]
Its all clear. But will be good, if when newData, coming from parent != oldData, wich still in the table state, we do not fire fetching. Even if those 4 params is changed to at the same time. Cause table component is already will got new data, and re-rendering wich is in React paradigm, and then i'll got fireFetchingEvent, caused by any of 4 params change, that make unnesessary request.

And yes, its resolving now in onFetchData, but i got old state in it.

**Comment by gary-menzel** [comment]
Please submit a codesandbox.io example of what you are experiencing.

**Comment by WebdevMerlion** [comment]
Fine. Don't need it. This is my experience. Just wrote shouldComponentUpdate of parent, to prevent double render. Thanks anyway.
