### ISSUE TITLE
Apply Custom filters (dropdown) using pivot(grouping of rows)

### ISSUE THREAD

**Issue by nqDev01** [react-tools/react-table#669]
Hello All
I am little bit confused regarding custom filtering with custom filtering 

https://codesandbox.io/s/x7w0q5mj8w

**Comment by gary-menzel** [comment]
Please take this question over to the #react-table Slack channel (badge at the top of the README in the doco).  The github issues are for bugs and feature requests. Thanks.

[Also, you will probably need a more specific question for people to be able to provide advice or help.]

**Comment by ivaqmo123** [comment]
Hi @gary-menzel , I think this is indeed an issue/bug in react-table since it doesn't allow to filter pivoted table as is shown in this code: https://codesandbox.io/s/x7w0q5mj8w 
Please, would you check it and confirm this is an actual issue?

Thanks
Ivan
