### ISSUE TITLE
Accessing row information in pivoted cell

### ISSUE THREAD

**Issue by ericmcgregor** [react-tools/react-table#671]
## What version of React-Table are you using?
latest

When pivoting a table of data by a column, it's difficult to understand from the documentation how to work with the resulting rows.  

Let's say I am trying to pivot by "category", and in the resulting rows i'd like to wrap the "title" cell in a link which has the row's "id" in it.  The pivot and aggregation fields on the column don't provide you with any usable information about the rest of the row.  there is a subRow field, and a bunch of other fields, but all you can really use is row.value.  row.original or a reference to the rest of the data doesn't exist.

I'm sorry if i'm missing something, but i've spent hours on this and i just don't understand it.  It seems like it would just be easier to aggregate the information on my own, and use nested components.  Is there better or more clear documetnation on pivoting?

**Comment by pairwinter** [comment]
I think you can overwrite the getTdProps or getTrProps by injecting what you need. 
like this:
`getTrGroupProps: (finalState, rowInfo) => {
        var index = rowInfo && rowInfo.index || 0
        var getSortIndex = finalState.getSortIndex
        if (getSortIndex && rowInfo) {
          index = getSortIndex(rowInfo.original)
        }
        return {
          index: index,
          row: rowInfo
        }
      },`
`getTdProps: ({data, store, sorted, filtered},
                   rowInfo, column) => {
        return {data, store, sorted, filtered, rowInfo, column}
      },`
And then you can get the return value in your td or tr components

**Comment by ericmcgregor** [comment]
i'll give this a shot.  it just seems like you should always get row info in a cell render method.

**Comment by gary-menzel** [comment]
So, here's the thing with the pivot implementation....

The "rows" that provide the summarised data are "phantom" or "ghost" rows.  They are not associated with any real "row" as that may be nested several levels below the phantom rows. You just need to detect if the subrows are present and take appropriate action (i.e. you can't really access a `row` or `original` until the leaf node is reached.

**Comment by gary-menzel** [comment]
While I am not saying it is "easy" to deal with the nested structure of the pivot implementation, it is not a "bug" or "feature" request and is best discussed over on the #react-table Slack channel (badge at the top of the README in the doco) and supported with various codesandbox examples (i.e. is does not qualify as a "issue" for react-table).

So, this issue will be closed so it can continue on the Slack channel. Thanks.
