### ISSUE TITLE
Sorting by date problem

### ISSUE THREAD

**Issue by fsolar** [react-tools/react-table#674]
Hi, i have a column with dates in the format dd/mm/yyyy, the table must be default sorted by this column in desc way but im getting an error because it order by the highest day without consider the month.

Any idea how to solve it? I try with the custom sort example code but i get a weird outupt.

`sortMethod: (a, b) => {
                    if (a === b) {
                      return 0;
                    }
                    const aReverse = a.split("").reverse().join("");
                    const bReverse = b.split("").reverse().join("");
                    return aReverse > bReverse ? 1 : -1;
                  }`

**Comment by SyedSaifAli** [comment]
You can always convert the date format into ts and then try sorting it.
