### ISSUE TITLE
Have table respect max-width

### ISSUE THREAD

**Issue by kyleknighted** [react-tools/react-table#675]
## What version of React-Table are you using?
6.7.4

## What bug are you experiencing, or what feature are you proposing?
On occasion I will need the table to be able to horizontally scroll, but in most instances I will want the table to be restricted to the width of the page.

I noticed that you're adjusting the `flex-grow` value on the fly which doesn't have a great way to be contained. So I instead set the flex-grow and flex-shrink to both be 1 and allow the flex-basis to adjust on the fly. This will allow the table to respect a `max-width` in the styles.

## Use https://codesandbox.io/s/X6npLXPRW (by clicking the "Fork" button) to reproduce the issue.

Didn't for the sandbox, but I do have this change at https://github.com/kyleknighted/react-table/blob/max-width/src/index.js

## What are the steps to reproduce the ~issue~ solution?
1. Set your package.json to pull from the above repo/branch
2. Update your packages to use the new repo
3. Give your base `.ReactTable` element a max-width in your local styles that you're comfortable with
  a. I used `calc(100vw - 300px)` to account for my sidebar and padding, but it's irrelevant
4. Refresh your page and now you can adjust columns without having to worry about horizontal scroll.
5. If you still would like horizontal scroll, just don't set the max-width and the table will allow for infinite width

## Request

I would love some feedback from the devs/contributors to see if this is a PR that makes sense to contribute or if I am better off using my own feature branch for this ability

**Comment by gary-menzel** [comment]
I'll see if we can get a discussion going regarding this. I think your suggestion of "use it or not" (depending on requirements) makes sense.  It will probably have to be explained clearly in the doco though.

**Comment by gary-menzel** [comment]
So @kyleknighted, are you able to submit a PR on this along with an updated README on how to use it?

Can the default style can remain as it is now and that people wanting to use it will just update or override their own styles?

Have you tested this on a range of browsers to ensure it doesn't break (specifically IE - as I suspect the others will probably be fine)?

**Comment by kyleknighted** [comment]
@gary-menzel I can work on putting one together and doing some tests. 
I haven't seen any "works in XYZ browsers". Do you know what browsers & versions this library supports?

**Comment by gary-menzel** [comment]
At least the main 4 as backwards compatible (version-wise) as possible: Chrome, Firefox, Safari and IE.

The main reason being that the solution is CSS-based (and that is where a lot of the discrepancies still exist - especially with IE).

**Comment by kyleknighted** [comment]
@gary-menzel sounds good - currently swamped with work at the moment but I'm tinkering with my needs in a fork in hopes that I can accomplish a PR while actually finalizing some development. It may be a week or so before i'm able to put up a proper PR with documentation. But, I found a few flaws in my first implementation.

Random question though, in the columns array the user can pass a `minWidth` to the cell, but it's a proptype number. My issue is that max-width either needs to be a string (because i may want to pass `max-content` or `calc(100vw - 306px)` etc. Or... I can make the prop a boolean and they user passes `hasMaxWidth` and then they would be responsible for setting the max-width in their own CSS (which is my preferred method). Any thoughts?

**Comment by gary-menzel** [comment]
@kyleknighted If you are up to tinkering with the propTypes to accept both a string and a number, that seems reasonable.  Another contributor added them but it was only based on a "best guess" scenario. We shouldn't try to make the prop into something "different" than what HTML would expect. So, we should evolve them as required.

[PS: I understand the "swamped with work"]

**Comment by tannerlinsley** [comment]
Closing due to issue age. If you think this issue needs to be reopened, please check the latest version of React-Table for the issue once more and reopen if appropriate. Thanks!
