### ISSUE TITLE
Add defaultPage prop

### ISSUE THREAD

**Issue by yudeikisorta** [react-tools/react-table#676]
## What version of React-Table are you using?
react-table@6.6.0

## What bug are you experiencing, or what feature are you proposing?
Add property defaultPage

## What are the steps to reproduce the issue?
There are several default properties already defined like defaultPageSize or defaultFiltered, but what I need is a defaultPage prop, it is an small change to your library
I'm working with redux and I need to save the table state in redux and load it when the component is mounted again. All the default props works fine, but the table is always initialised in page 1, and not in the page stored in redux
The change is in `lib/index.js` line 76 
instead of
`page: 0,`
it should be 
`page:  props.defaultPage,`

**Comment by gary-menzel** [comment]
There is a `page` prop for ReactTable - is that not working for you? Check the doco by searching the page for `Controlled State Overrides`.

**Comment by yudeikisorta** [comment]
I dont want to control page changes, I just need the defaultPage prop, similar to defaultPageSize and  defaultFiltered, so it is initialised in the page stored in redux, but controlled by this library

**Comment by gary-menzel** [comment]
Oh - sorry - I see what you mean now.

Yes - it is a small change - but there is also a very small team working on the code now (and a bunch of PRs queued up) - so I don't know how long it will take to get the change in (as simple as it is).

**Comment by gary-menzel** [comment]
This is still on the radar but another use case has come up that has highlighted that a change in the props (specifically the proposed `defaultPage`) would need to be detected and reapplied to the actual `page` in the component state.
