### ISSUE TITLE
How to get arrow keys working for row select

### ISSUE THREAD

**Issue by kimwykoff** [react-tools/react-table#677]
## What version of React-Table are you using?
6.7.4

## What bug are you experiencing, or what feature are you proposing?
I want to know how to listen for keyDown events. I've tried adding an onKeyDown listener to the getProps, the getTableProps, but they never fire. I suppose it's because the react-table doesn't have focus, so I tried to get the focus on the react-table in componentDidMount, like this:

    import * as React from 'react'
    import ReactDOM from 'react-dom'
    import ReactTable, {Column as RTColumn} from 'react-table'
    export class Grid<Record, S extends keyof Record> extends React.PureComponent<GridProps<Record, S>> {
        private grid = null

        componentDidMount() {
            this.focusTable()
        }

        private focusTable() {
            ReactDOM.findDOMNode(this.grid).focus();
        }

        private setGrid = (grid) => {
            this.grid = grid
        }
        private readonly getTableProps = (state, rowInfo, column) => {
            return {
                onKeyDown: (e, key) => {
                    console.log("TableProps: onKeyDown: e = ", e)
                }
            }
        }
        private readonly getProps = (state, rowInfo, column) => {
            return {
                onKeyDown: (e, key) => {
                    console.log("Props: onKeyDown: e = ", e)
                }
            }
        }

        render() {
            return (
                <ReactTable
                    style={{
                        maxHeight: '100%',
                        overflowX: 'auto',
                        width: '100%'
                    }}
                    className={className}
                    page={0}
                    pageSize={this.props.data.length}
                    showPagination={false}
                    data={this.props.data}
                    columns={columns}
                    getTableProps={this.getTableProps}
                    getProps={this.getProps}
                    ref={this.setGrid}
                />
            )
        }
    }
## Use https://codesandbox.io/s/X6npLXPRW (by clicking the "Fork" button) to reproduce the issue.
https://codesandbox.io/s/0m47zkpk8w

In the sandbox, I can't seem to use ReactDOM - it doesn't seem to recognize that and says it's undefined.

In my code, it's recognized and I can actually follow it down the call stack, but focus() doesn't seem to do anything. When I hit the up and down arrow keys, nothing happens.

Could you help me get the navigation buttons working? Thanks.

**Comment by gary-menzel** [comment]
This is really an implementation question and should be asked over on the #react-table Slack channel (badge at the top of the README in the doco). The github issues are for bugs and feature requests. Thanks.

In regard to ReactDOM on codesandbox.io you need to ensure the package has been included as a dependency (and this code will be much easier to provide advice on if you can get it over to codesandbox).
