### ISSUE TITLE
Missing HOCs from package

### ISSUE THREAD

**Issue by nlucero** [react-tools/react-table#678]
I've installed `react-table` through `npm`. As I see on the [docs](https://react-table.js.org/#/story/hoc-readme), the correct way to include the provided HOCs is:

```
import treeTableHOC from 'react-table/lib/hoc/treeTable'
```

But there is no `lib/hoc` under my installation, so the above import fails.

Am I doing something wrong? Are the HOCs available as part of an independent package?

I'm using this version of `react-table`:

```
"dependencies": {
    "react-table": "^6.7.4",
    ...
  },
```

Thanks!

**Comment by gary-menzel** [comment]
There is a new release about to land 6.7.5 that will have the HOCs in the npm package. I'll close this for now - reopen again if there are any other issues.

**Comment by nlucero** [comment]
Great! Any ETA on this?

**Comment by gary-menzel** [comment]
It is on npm now.
