### ISSUE TITLE
React-table sub components

### ISSUE THREAD

**Issue by abaruah12** [react-tools/react-table#681]
## What version of React-Table are you using?
react-table 6.7.4
react: 16.2.0

## What bug are you experiencing, or what feature are you proposing?
I am trying to use subRows property for Cell to set rows which will be shown when cell is expanded but its not working. The SubComponent functionality also doesn't allow me to set content specific to each row. 

So say my data looks like such:
[
{id: 1, expand: {'some data 1'}}
{id: 2, expand: {'some data 2'}}
]

I would like for the SubComponent (or any other functionality) to show the value stored in the expand property of each object in the data array. Please let me know if anyone was able to display sub components like I am trying to do.

**Comment by gary-menzel** [comment]
Many people are doing this. This is an implementation issue that you should take over to the #react-table Slack channel (badge at the top of the README in the doco). The github issues are for bug reports and feature requests. You should also prepare a codesandbox.io example of what you are trying to do so it is easier for people to provide advice. Thanks.
