### ISSUE TITLE
className='-striped -highlight' not working with a fresh create-react-app APP.

### ISSUE THREAD

**Issue by loudking** [react-tools/react-table#682]
## What version of React-Table are you using?
Your bug may already be fixed in the latest release. Run `yarn upgrade react-table`!
Place your version here...

6.7.5

## What bug are you experiencing, or what feature are you proposing?
Please include a detailed explanation here...

With create-react-app and default CSS, react-table v6.7.5 cannot see the effect of '-striped' or '-highlight'

## Use https://codesandbox.io/s/X6npLXPRW (by clicking the "Fork" button) to reproduce the issue.
Then paste a link to your newly forked codesandbox here...

## What are the steps to reproduce the issue?
1. npm install -g create-react-app
2. Add 'react-table@6.7.5' to package.json.
2. replace src/App.js with following code
```
import React, { Component } from 'react';
import logo from './logo.svg';
import './App.css';
import ReactTable from 'react-table';
import 'react-table/react-table.css';

class App extends Component {
  constructor() {
    super();
  }
  render() {
    const data = [
            {
                "location":"01-01",
                "amount":150
            },
            {
                "location":"01-02",
                "amount":3000
            },
            {
                "location":"01-03",
                "amount":1201
            }
    ];

    const columns = [
      {
        Header: "Location",
        accessor: "location"
      },
      {
        Header: "Amount",
        accessor: "amount",
        Cell: props => <span className='number'>{props.value}</span>
      }
    ];

    return (
      <div className="App">
        <header className="App-header">
          <img src={logo} className="App-logo" alt="logo" />
          <h1 className="App-title">Welcome to React</h1>
        </header>
        <p className="App-intro">
          To get started, edit <code>src/App.js</code> and save to reload.
        </p>
        <ReactTable
          data={data}
          columns={columns}
          classsName='-striped -highlight'
        />
      </div>
    );
  }
}

export default App;

```

3. npm start.

**Comment by gary-menzel** [comment]
I've just run up a quick codesandbox (which uses create-react-app under the hood) and ReactTable 6.7.5 plus the sample data and columns you provided - the `-striped` and `-highlight` seem to be working there. They are also working in my production application.

https://codesandbox.io/s/5knzrn8qmk

[the table is in a separate package called `mytable.js` and the component is a "pure" component - but that should not make any difference]

**Comment by oim5nu** [comment]
@gary-menzel 
I tried the sandbox there. The header clicked would get blue-outlined, whose width is wider than the column width. I tried it in my project, and found the outline wraps the div with class 'rt-resizer'. The previous versions do not have it.

Is it deliberately added in or not? Thanks.

![image](https://user-images.githubusercontent.com/15712107/33991627-70314116-e123-11e7-889b-789fd3b0a117.png)

**Comment by gary-menzel** [comment]
I don't think that is deliberate. That looks like an issue.

However, have you resolved your `-striped -highlight` issue ?

**Comment by oim5nu** [comment]
oh, btw, className='-striped -highlight' works okay for me. Thanks.

**Comment by gary-menzel** [comment]
I am looking at the focus issue - and trying to find where that may have slipped in (previously, none of the ReactTable divs could accept focus)

**Comment by gary-menzel** [comment]
From what I can tell - it's appearing in a range of browsers.  In Chrome this is triggering:
```
:focus {
    outline: -webkit-focus-ring-color auto 5px;
}
```
That is on the "user agent stylesheet". I'll have to go back through the recent PRs to see if I can identify any changes that contributors may have made that would cause this.

**Comment by oim5nu** [comment]
In Safari, this focus issue is also there. : (

**Comment by gary-menzel** [comment]
Yes - it behaves differently in different browsers (it's there in them all).

I have tracked it down to all the work that was done around fixing the linter errors (introduced bug where a `tabIndex` was introduced.  I've referred it back to the contributor to confirm it was only for linting purposes and that there wasn't some other reason (which I can't imagine there would be).

Unfortunately, there is no workaround (due to the order in which the internal code applied user classes/styles and component required styles.  It will have to have another PR and a release.

**Comment by gary-menzel** [comment]
However, I'd like to close this issue and have you open a different one for this "focus" problem - issues shouldn't cover two different things.

Please refer to this issue when opening the other.

**Comment by oim5nu** [comment]
Thanks a lot @gary-menzel

**Comment by gary-menzel** [comment]
I'll close this now and track the focus issue on #685

**Comment by loudking** [comment]
Hi Gary, sorry for the late reply but this problem persists on my side. I tried two different PCs and all have the same effect - '-stript -highlight' not working. Sccreenshot can be found below:

![react-table](https://user-images.githubusercontent.com/11624509/34069471-0beed1da-e28d-11e7-9d94-f65a0afc9cb7.png)

 I have created a GITHUB public project and can you please take a look at it?

URL: https://github.com/loudking/react-table-test

**Comment by rlking1985** [comment]
I know this closed but wanted to point out that the original bug was just an issue with the code.

The original code had an incorrect name for className (three s')

```
        <ReactTable
          data={data}
          columns={columns}
          classsName='-striped -highlight' // className not classsName
        />
```

**Comment by Werewoof** [comment]
Just noticed that too. :upside_down_face: Those mistakes get me all the time. Haha
