### ISSUE TITLE
Server-side filtering not working correctly after some actions

### ISSUE THREAD

**Issue by maxkordiyak** [react-tools/react-table#683]
I'm using server-side pagination, filtering, sorting, and rows selection. When I try to retrieve an element from the table initially (which is not necessarily on the current display list) it works. But after switching a page or two further, or applying rows filter, the filtering method cannot reach specified element. Is there a way to reset the table view after some actions applied to its initial state so that the element can be found?

**Comment by gary-menzel** [comment]
This is an implementation question and should be taken over to the #react-table Slack channel (badge at the top of the README in the doco).  You should also put together a codesandbox to demonstrate the issue and/or explain further what you advice you require.

I realise that server-side adds a complication putting an example together but you can probably abstract that and just build something that doesn't actually do a server call but mocks that process in a reliable way.

**Comment by maxkordiyak** [comment]
The table was resetting its page automatically, I had to set index: 1 on my filter change       (onFilteredChange)
