### ISSUE TITLE
Callbacks not working

### ISSUE THREAD

**Issue by ttessarolo** [react-tools/react-table#684]
Hi I'm using react-table v.6.7.5
Everything is working perfectly, excepts callbacks are not invoked.

Just a simple example:

```
onSortedChange={(newSorted, column, additive) => {
          console.log(newSorted, column, additive)
 }}
```

is not printing out nothing...

**Comment by gary-menzel** [comment]
I've just updated the following codesandbox to use 6.7.5 and dropped in your snippet above (with only a minor change to make the output a little more readable) and it seems to work (in both the codesandbox console and the browser console):

https://codesandbox.io/s/m4lj24j5z9

Please provide a codesandbox that includes any callbacks you are unable to get working.

**Comment by ttessarolo** [comment]
it still doesn't works. Everything else is working. It seams that the callback functions are not invoked. I want to go deeper in the source code do understand why. Probably is some special React/Events condition that prevent callback to be fired...

**Comment by gary-menzel** [comment]
I don't quite understand.  The sample I provided works for me - did you check that?.  Are you saying that sample is not working?  If so, please provide a codesandbox that demonstrates the problem (as requested and and expected when reporting bugs by the bug template).

**Comment by ttessarolo** [comment]
Your code is working. On the Sandbox.
But inside my App I've tried everything but the callbacks ara not invoked... 
Even the resizing of column is not working.

**Comment by gary-menzel** [comment]
Standard debug approach - you'll have to cut it back so it is just ReactTable. It's too difficult for someone to remotely debug a whole stack.  All we can do is prove that it behave properly when tested.  Given it is working in codesandbox other people's apps there must be some code in your app that is causing this.

**Comment by ttessarolo** [comment]
Hey this is the code:
https://codesandbox.io/s/n3vp4kwnv4

But as I said int he sandbox works, but it doesn't produce any console.log in my App.

**Comment by gary-menzel** [comment]
As I said - I don't know. As you said, it works in there - so React is definitely calling the function. It must be something else in your App that is causing it.

**Comment by ttessarolo** [comment]
It seams to fail here:

<img width="1167" alt="1" src="https://user-images.githubusercontent.com/4814632/34041401-3eb8dc0a-e198-11e7-9a35-2dd961f0eb39.png">

it seams that React@16.2.0 doesn't call the cb().

Even if the cb() is correctly defined here:

![2](https://user-images.githubusercontent.com/4814632/34041455-5a790e42-e198-11e7-9385-3f62b25d3a9a.png)

and it is correctly passed as props from the container:

```
onSortedChange={(newSorted, column, additive) => {
              console.log({newSorted, column, additive})
        }}
```

**Comment by gary-menzel** [comment]
But you said it calls other callbacks ?

[There's nothing wrong with that code from what I can see - even ignoring the fact that it is working for other people.]

What browser are you using? Are you using server-side rendering?

I am really at a loss to provide any more advice because it just can't be replicated outside of your environment.

**Comment by gary-menzel** [comment]
I don't believe this is an issue with ReactTable and is something to do with your implementation. Best to take this over to the #react-table Slack channel (badge at the top of the README in the doco) as there are more people there that may have experienced something like this. I'm there as well but I just can't really see what else I can contribute at this point. I still believe there is some subtle thing you are doing that will only be apparently in looking at all the code around the ReactTable instance.

The github issues are for bugs and feature requests.  Sack is for implementation advice and assistance.

**Comment by ttessarolo** [comment]
Thanks!
