### ISSUE TITLE
Demos not working

### ISSUE THREAD

**Issue by gilesbutler** [react-tools/react-table#688]
Hey guys, 

Do you know that none of your demos are working? 

I get the following on every demo at https://react-table.js.org/#/story/simple-table

<img width="1723" alt="screen shot 2017-12-18 at 10 53 20" src="https://user-images.githubusercontent.com/790734/34088022-c6fe4550-e3e1-11e7-8325-b0be9093df5a.png">

**Comment by gary-menzel** [comment]
Yes - this is due to some change in codesandbox. The demos are not part of the main code base so it is going to take a while for those to be looked at.  It is in the data generation - for some reason they are putting a hard limit on loop iterations.

**Comment by gary-menzel** [comment]
This issue was resolved by the people at codesandbox.io.

**Comment by gilesbutler** [comment]
Awesome, thanks @gary-menzel - all working here now 👍
