### ISSUE TITLE
Changes on codesandbox are causing data generation in the samples to fail

### ISSUE THREAD

**Issue by gary-menzel** [react-tools/react-table#691]
This is a more specific version of these issues: (#688 and #689).

The issue appears to be that there is a hard limit on the number of iterations that codesandbox is allowing (the error reads "exceeded 5000 iterations").

Most of the codesandbox samples use a function called `makeData` that defaults to creating over 5000 dummy records.  You can pass a prop to `makeData` to tell it to generate only (say) 500 records.

This will take a while to resolve as the codesandbox examples are not under source control and the specific function is included directly in the files that make up each example.

**Comment by gary-menzel** [comment]
This issue was resolved by the people at codesandbox.io.

**Comment by emyarod** [comment]
Unfortunately this issue seems to persist on examples like the [100k Rows w/ Pivoting & Sub Components](https://react-table.js.org/#/100k-rows-w-pivoting-sub-components) demonstration
