### ISSUE TITLE
Export filtred list

### ISSUE THREAD

**Issue by MekMed** [react-tools/react-table#693]
Thank you a lot for your component. It is really great.

I have a request. Actually, the filtered list (what we see in the rendered lines) is not exported. It is possible to have the applied filters to filter the data. But, with a custom filters it is not so easy.

So, my request is to export the filtered list.

Thx,

**Comment by ayxos** [comment]
I have solved it like this:

            <ReactTable
                data={this.props.rows}
                pageSize={10} // the number of rows per page to be displayed
                filterable
                defaultFilterMethod={(filter, row) => String(row[filter.id]).indexOf(filter.value) > -1}
                onFilteredChange={function(filtered) {
                    const filter = filtered.length ? filtered[0].value : '';
                    if (self.props.filter) self.props.filter(filter);
                    return self.setState({ dataToCsv: filter ? filtering(filter, self.props.rows) : self.props.rows})}
                }
                columns={columns}
            />

**Comment by gary-menzel** [comment]
@ayxos I don't think he was asking how to create a custom filter (although your solution would work if that were the case).

@MekMed 
Please check the FAQ in the Wiki as it describes how to get at the filtered data in the ReactTable internal state.  You can then iterate over the `sortedData` (which is also the filtered data) and run any type of export functionality you require.

https://github.com/react-tools/react-table/wiki/FAQ#how-do-i-get-at-the-internal-data-so-i-can-do-things-like-exporting-to-a-file

**Comment by MekMed** [comment]
Thank for your responses.

@gary-menzel 
Using ref and internal state will work, but, for me, it wont be the best solution. The best will be some thing like for filtered or onFilteredChange to either access to the sortedData directly or be notified if changed.

Thx,

**Comment by gary-menzel** [comment]
`filtered` is just the criteria for telling ReactTable what to filter.

`onFilteredChange` is called with the criteria the user supplied for the filter.

`sortedData` is not passed to `onFilteredChange`.

I would have expected that "exporting" the data would be done as a result of the user pressing a button.  The method I have indicated is the best way to access the sortedData in a reliable way.

**Comment by MekMed** [comment]
Thank you for your answer.
I'll do so !

**Comment by mnai01** [comment]
> @ayxos I don't think he was asking how to create a custom filter (although your solution would work if that were the case).
> 
> @MekMed Please check the FAQ in the Wiki as it describes how to get at the filtered data in the ReactTable internal state. You can then iterate over the `sortedData` (which is also the filtered data) and run any type of export functionality you require.
> 
> https://github.com/react-tools/react-table/wiki/FAQ#how-do-i-get-at-the-internal-data-so-i-can-do-things-like-exporting-to-a-file

Is there an updated link you can provide? This one doesnt bring you to anything in regards to exporting.

**Comment by mnai01** [comment]
Extract 'rows' from the destructured values and that will give you all the row data that has been filtered. This is all I needed.

```js
const {
    getTableProps,
    headerGroups,
    prepareRow,
    page,
    gotoPage,
    setPageSize,
    rows, // <-------------
    state: { pageIndex, pageSize, filters }
  } = useTable(
    { data, columns, autoResetHiddenColumns: false },
    useFilters,
    useGlobalFilter,
    useSortBy,
    usePagination,
    useRowSelect
  );
  ```

**Comment by MortimerMarsyja** [comment]
> 

rows is not defined
