### ISSUE TITLE
Controlled-Component invokes fetchData twice on sort

### ISSUE THREAD

**Issue by daveschikora** [react-tools/react-table#695]
## What version of React-Table are you using?
6.7.5

## What bug are you experiencing, or what feature are you proposing?
I am using a controlled component version of the table, managing sort and filter state. (similar to here: https://react-table.js.org/#/story/controlled-component) 
Now when I combine this with a remote Server supplying data (using the fetchData callback), the callback is triggered twice on each sort. I have provided a very simple sandbox example showing the bahvior here:
https://codesandbox.io/s/r5qz71onwq

The fetchData function does nothing, but alert "fetch data". On each sort this is executed twice. Am I missing something fundamental here or is this a bug? 

The work-around i found is to not use the fetchData callback at all but manage it completely through the sort callbacks etc., however I find this very inconvenient. 

## Use https://codesandbox.io/s/X6npLXPRW (by clicking the "Fork" button) to reproduce the issue.
https://codesandbox.io/s/r5qz71onwq

## What are the steps to reproduce the issue?
1. Sort a column

**Comment by daveschikora** [comment]
update: removing the 
sorted={this.state.sorted}
code fixes the issue. Doesnt feel quite right though to only set the callback without the binding..

**Comment by gary-menzel** [comment]
As we discussed over on the Slack #react-table channel, they are actually independent. You can also set `sorted` without passing in `onSelectedChange` to tell the table how to sort the data it has.

I'll close this for now.  Maybe this will figure in a future major version rewrite or the issue may go away entirely if the whole API changes.
