### ISSUE TITLE
Setting `loading: false` and overriding LoadingComponent renders loader

### ISSUE THREAD

**Issue by iamvanja** [react-tools/react-table#698]
## What version of React-Table are you using?
6.7.5

## What bug are you experiencing, or what feature are you proposing?
Setting `loading: false` and overriding LoadingComponent still renders loader despite the false loading prop. When loading is set to false, loader should not be rendered.

## Use https://codesandbox.io/s/X6npLXPRW (by clicking the "Fork" button) to reproduce the issue.
https://codesandbox.io/s/zxy6vwwrk4

## What are the steps to reproduce the issue?
1. Set `loading` prop to `false`
2. Verify that the default loader is not shown
3. Now set `LoadingComponent` prop to a custom component
3. Custom loader renders despite the `loading={false}` prop

**Comment by gary-menzel** [comment]
This the designed/desired behavior. When you override a component in ReactTable you are completely responsible for the implementation.  Here is the default component (and you can see it is built to show or hide based on parameter passed)....
```
  LoadingComponent: ({ className, loading, loadingText, ...rest }) => (
    <div
      className={classnames('-loading', { '-active': loading }, className)}
      {...rest}
    >
      <div className="-loading-inner">
        {loadingText}
      </div>
    </div>
  ),
```

**Comment by iamvanja** [comment]
Thanks for the response. Always rendering and hiding/showing using CSS is an interesting decision. I think more "React way" is to let the parent component decide whether a child component would be rendered or not.

**Comment by gary-menzel** [comment]
The usage here is not so much a child component as a render callback pattern (like a mini HOC passed as a prop).  This gives all the control back to the parent (your wrapper) as to what should be done. It may not necessarily be the best choice in this particular part of the code but it is consistent with every other component override in the package.

The doco clearly states that overriding an of the `*Component` props places all responsibility on the developer to replicate the default functionality.

I'll close this one off now.

**Comment by iamvanja** [comment]
Thanks for the extra clarification, Gary.
Yes, this is resolved. Happy holidays!
