### ISSUE TITLE
How to use external Table component?

### ISSUE THREAD

**Issue by loudking** [react-tools/react-table#699]
## What version of React-Table are you using?
Your bug may already be fixed in the latest release. Run `yarn upgrade react-table`!
Place your version here...
6.7.4

## What bug are you experiencing, or what feature are you proposing?
Please include a detailed explanation here...

I was planning to use an external Table component. It has properties 'striped' and 'hover' which corresponds to react-table's className='-striped -highlight', but the color is much better than react-table's own color. In addition its 'th' is by default bold.

I tried following code:

```
import { Table } from 'reactstrap';

return (
            <ReactTable data={data}
                        columns={columns}
                        TableComponent={ Table }
            />);
```

The table is shown but its 'th' is not bold.

If I change to following code:

```
            <ReactTable data={props.leases}
                        columns={columns}
                        className='-striped -highlight'
                        getTheadThProps={() => ({ className: 'font-weight-bold'})}
                        TableComponent={ Table }
             />
```

I can see 'th' is bold but it is because I manually set it with getTheadThProps. And className '-striped -highlight' is working because it is manually being passed.

so my questions are:

1. Is my way of using external Table Component correct?
2. How to pass some properties to external component, like 'striped hover'?

**Comment by gary-menzel** [comment]
You probably need to re-read the ReactTable documentation again as well as review the ReactTable CSS.

ReactTable is a complete standalone table component which does NOT use the default HTML table elements (like table, tbody, thead, tr, td - etc). So there is really no simple way to use the `Table` component from `reactstrap`. You need to build up your own CSS based on the ReactTable css.
