### ISSUE TITLE
Missing 'defaultPage' option

### ISSUE THREAD

**Issue by andcl** [react-tools/react-table#701]
Well, I can't find this apparently obvious option in the documentation of react-table, and I can't figure out why is not implemented. Is there any reason? Just proposing its addition here :)

In one of my tables, I need to start showing the last page independently of its number of rows, but then let the user paginate all over (so the fully controlled option through 'page' is not valid for me).

I think it could be achieved with a 'defaultPage' option (like the existing 'defaultPageSize' for pageSize).
In the meantime... could you suggest me any workaround to face this issue?

Thank you very much.

**Comment by gary-menzel** [comment]
There is no workaround. There is a feature request in for this already: #676

**Comment by andcl** [comment]
Ok, I will keep an eye on this.
Thanks for such a great library.

**Comment by tannerlinsley** [comment]
Should be fixed!

**Comment by nzhtrtlc** [comment]
May i ask if there will be any development about defaultPage ?

**Comment by timkrins** [comment]
Is this fix going to be in a tagged release anytime?
