### ISSUE TITLE
onFetchData not triggered at pagination

### ISSUE THREAD

**Issue by sstruct** [react-tools/react-table#704]
## What version of React-Table are you using?

6.7.6

## What bug are you experiencing, or what feature are you proposing?

When I try to wrap react-table as a customized component(called CReactTable) in my own components library, I imported this component in another repo and use the server-side data feature, onFetchData event has only been triggered once at `componentDidMount`. Pagination can change the page index, but can't trigger onFetchData nor onPageChange event.

```
        <ReactTable
          data={this.state.data} // should default to []
          pages={10}
          columns={[{ Header: "title", accessor: "title" }]}
          pageSize={50}
          manual // informs React Table that you'll be handling sorting and pagination server-side
          onPageChange={(pageIndex) => {
            // when I click next page, nothing happens here
            console.info('debug pageIndex', pageIndex)
          }}
          onFetchData={(state, instance) => {
            // console.info('debug state, instance', state, instance)
            // when I click next page, nothing happens here
            // show the loading overlay
            this.setState({ loading: true });
            // fetch your data
            Axios.get("https://jsonplaceholder.typicode.com/posts").then(
              res => {
                // Update react-table
                this.setState({
                  data: res.data,
                  loading: false
                });
              }
            );
          }}
        />
```

```
// another repo
import { CReactTable } from 'my-ui-lib'

const Test = () => {
    return <CReactTable />
}
```

## What are the steps to reproduce the issue?

```
// my-ui-lib
yarn run watch
yarn link

// another repo
yarn link my-ui-lib

import { CReactTable } from 'my-ui-lib'

const Test = () => {
    return <CReactTable />
}
```
FYI: 

```
// my babel config
  "scripts": {
    "watch":
      "BABEL_ENV=development babel --watch src --out-dir dist --source-maps --copy-files --ignore '**/*.test.js'",
  },
    "babel-cli": "6.26.0",
    "babel-core": "6.26.0",
    "babel-eslint": "8.0.3",
    "babel-jest": "21.2.0",
    "babel-loader": "7.1.2",
    "babel-plugin-transform-es2015-modules-commonjs": "6.26.0",
    "babel-preset-react": "6.24.1",
    "babel-preset-react-app": "3.1.0",
    "babel-preset-stage-1": "6.24.1",
 ```
```
// .babelrc
{
  "plugins": ["transform-es2015-modules-commonjs"],
  "presets": ["stage-1", "react"]
}
```

**Comment by gary-menzel** [comment]
`onPageChange` is not a notification - it is an override that allows you to control the page changing yourself and then you need to push the `page` back in as a prop (the changing page prop will then trigger the `onFetchData`. So there is not much use in combining `onFetchData` and `onPageChange` because `onFetchData` will be called when a page changes - but by providing the `onPageChange` you are short-circuiting the paging mechanism.

Remove `onPageChange` and, if you need the page number, get the page information from the `state` prop passed to `onFetchData`.

As far as your external component  is concerned - it may also be causing a problem but it would have to be provided in a codesandbox to provide any further advice.

**Comment by sstruct** [comment]
Thanks for your apply. I added the `onPageChange` just to show this event is not triggered. After I removed the `onPageChange` and this problem is still there.

I forked the [codesandbox](https://codesandbox.io/s/klr7k1yr5), and it works fine within it.
Also, I tried to move the `CReactTable` to the repo needs to use it. It works fine too.

So I guess this problem results from `babel` or `yarn link`. Another situation is that other simpler components line `Input, Button, etc.` are not effected. So It really make it hard to find out where the bug is.

Sorry for it seems that `codesandbox` doesn't support `yarn(npm) link`, so I can't reproduce it online.

**Comment by gary-menzel** [comment]
Unfortunately, build environments vary greatly and if your component logic works in a well structured and maintained build environment (e.g. codesandbox) then it's difficult to provide any additional advice. I doubt it is related to yarn specifically (but could be related to how you are creating the symbolic link).  However, that is going to be so specific to your environment the only thing for it is to do the research and see if anyone else has had a similar problem (not specifically with React Table - just generically).

But, many people are using React Table - both just "as is" as well as build a wrapping component around it - that I doubt it is an issue with React Table.

It is still probably best to ask on the #react-table Slack channel - in case anyone has experienced issues with their build environment.
