### ISSUE TITLE
pagination-bottom div takes all available space in some circumstances

### ISSUE THREAD

**Issue by RoboPhred** [react-tools/react-table#705]
## What version of React-Table are you using?
0.4.7

Browsers:
Chrome  63.0.3239.84 (Official Build) (64-bit)
Edge

## What bug are you experiencing, or what feature are you proposing?
The paginator (div .pagination-bottom) gets its height calculated to extreme values and squashes the .rt-table div to nothing.

The environment where I first notice this has a specific use case that requires the site to be built up in an iframe using document.write.  When the table runs in this env, the pagination div takes the entire height of the table, and rt-table has a height of 0.

I don't have too much experience with flex, but as far as I can tell is the prev/next button's "height: 100%" should (and often does) make pagination-bottom want to take up as much space as possible, which is factored in by flex.  This element has a flex-grow of 0 and flex-shrink of 1, causing it to shrink to its minimum viable height, as rt-table is allowed to expand and contains the size to do so.

However, in uncertain conditions (see below), it seems that pagination-bottom is getting a baseline flex size of the outer .ReactTable div, causing it to crush rt-table into height 0.
On closer inspection, it seems the culprit is ultimately the prev and next buttons.  Setting their height to auto will cause the issue to go away.

An interesting behavior to check for is to set min-height on pagination-bottom to 0, causing flex to allow it to shrink indefinitely.  The result is rt-table takes half of the space, pagination-bottom takes the other half, but pagination-bottom's children continue to take the full .ReactTable div height and overflow.

##  What are the steps to reproduce the issue?
Unknown, but somehow related to how or when the html content of the table is loaded.

I have copied out the .ReactTable element from my prod site, and set up a few jsfiddles with the react-table.css content.

Element and style-tag contained css: working
https://jsfiddle.net/2ht0nw56/
![fiddle-working](https://user-images.githubusercontent.com/6816874/34367116-b4a849c2-ea63-11e7-916f-67a09dd4d81b.png)

document.write with identical content to the above: broken
https://jsfiddle.net/vkb4rzyc/
![fiddle-broken](https://user-images.githubusercontent.com/6816874/34367118-b59326c2-ea63-11e7-9fdf-e0f0b5c081b6.png)

.html file on the local fs with document.write: broken
[doc-write.html.txt](https://github.com/react-tools/react-table/files/1588077/doc-write.html.txt)

.html file with the same content as the first / working jsfiddle: broken
[element.html.txt](https://github.com/react-tools/react-table/files/1588078/element.html.txt)

I have yet to find any real pattern to this, but I have a few things it is not:
iframe: Happens in local html, does not happen in the jsfiddle (which uses an iframe for its output).
document.write: This causes it in jsfiddle, but the issue happens on the html file.
invalid flex-grow default: Checked this, the expanded pagination-bottom always has a computed flex-grow of 0

At first I suspect a browser bug, and given that the results differ based on the means of writing html there might still be one involved.  However, both chrome and edge are doing this, and the fact that it happens with static html / css is making me start to doubt this.

Unfortunately, I do not know flexbox to any great detail, so I am nearing the edge of how far I can push this.  I am going to attempt to reproduce the behavior by trimming out as much of the table content as possible and making the minimum content that can reproduce this.

## Workaround
I have been able to hack around the issue by disabling the "height: 100%" on the prev/next buttons with:
```
.ReactTable .-pagination .-btn {
    height: auto !important;
}
```

I understand that my use case is on the edge of sanity, so thank you for any help that anyone can contribute.  The workaround works, so I am more interest in solving this as a puzzle / contribution / learning exercise than as an actual usage blocker.

**Comment by gary-menzel** [comment]
Please ensure your doctype is correct - https://github.com/react-tools/react-table/wiki/FAQ#my-reacttable-doesnt-seem-to-display-properly-on-browser-x---help

**Comment by RoboPhred** [comment]
Ah!  Adding this fixed all of my local tests.

I do have a correct doctype in my project, which runs fine locally.  However, upon inspecting the iframe of component hosting my content, it seems to be rewriting my doctype to
```<!DOCTYPE html[]>```

Thanks for the support!  This is probably the cause; I will try to get this fixed, and re-open if the problem continues.
