### ISSUE TITLE
Bottom of table height issue

### ISSUE THREAD

**Issue by dahudson88** [react-tools/react-table#707]
## What version of React-Table are you using?
Your bug may already be fixed in the latest release. Run `yarn upgrade react-table`!
Place your version here...

"react-table": "^6.7.6",

## What bug are you experiencing, or what feature are you proposing?
Please include a detailed explanation here...

I am using the basic table example as follows:
 <ReactTable
                    data={data}
                    columns={columns}
                    defaultPageSize={this.state.vals.length + 1}
                    className="-striped -highlight"
                />
The data is displayed the table as expected, but the bottom portion that has the "previousText", "nextText", "Page 1 of 1", "5 rows" has height that is very large.  Is there a way to specify the height of just that section?

I have looked at the following tutorial and there did not appear to be any changes needed:
[https://react-table.js.org/#/story/simple-table ](url) 

**Is there a way to customize the height of that bottom section?  Below is an image of the issue I am seeing...**
![screen shot 2017-12-27 at 1 37 04 pm](https://user-images.githubusercontent.com/31221472/34390033-17f981ba-eb0b-11e7-8546-bda5672d46c3.png)

I am suspecting that there is another style that I may have that may be causing this. Because on a clean app using creaet-react-app this issue is not there.

**Comment by gary-menzel** [comment]
Please ensure your doctype is set correctly as per this FAQ....

https://github.com/react-tools/react-table/wiki/FAQ#my-reacttable-doesnt-seem-to-display-properly-on-browser-x---help

**Comment by dahudson88** [comment]
Thank you that fixed it.
