### ISSUE TITLE
Add support for explicit control for "active view" (page rows) range.

### ISSUE THREAD

**Issue by lukaswelinder** [react-tools/react-table#713]
## What version of React-Table are you using?

`6.7.4`

### Problem

I'm working on a virtualized/infinite scroll HOC for `react-table` and am running into performance complexity due to the way the "current view" is handled only via pagination.

Beyond about 2k rows (even though only about 40 are mounted to the DOM at any time) update times climb upwards of 200ms, beyond 10k updates take over 1s. I'm assuming that this is due to react attempting to reconcile all rows, but I'll be doing some further digging...

I have tested my virtual scroll implementation independently with an average of 15-30ms update time for 10k rows (nearly 50x faster).

### Solution

Allow the current view to be defined by some `view` prop representing the range of rows `[start, end]` that are on the "page". This also opens up a lot of flexibility to implement more advanced paging controls for `react-table`.

I'll be diving into this tonight with hopes of:

1. Add support for explicit view-range.
1. Investigating root cause(s) of performance hangups and identifying potential improvements.

**Comment by gary-menzel** [comment]
I have a log collection in MongoDB that has over 10's of 1000's of lines and I simple just load a page worth using `onFetchData` as there is very little need to actually load all of the lines.  Theoretically, you could take the current `page` and `pageSize` and compose a "virtual" view range from those numbers (telling your back end to load records either side and only going back to get the "difference" each time).  I am just not sure what value that would add.

You could potentially code that as a HOC without changing the base code.

However... I suggest you upgrade to 6.7.6 before starting any coding with an intent to supply a PR.  Any PR in the current major version would need to be backwards compatible.

You should also be aware that there is a complete redesign on the (virtual) drawing board that is likely to see a lot more of the functionality being pushed out into replaceable components.

Should you end up delivering a PR for progressive/virtual updating (nothing is truly "infinite") we'd be happy to consider merging it.

[Branch from MASTER and submit the PR from the branch]

**Comment by lukaswelinder** [comment]
@gary-menzel Thanks for the quick response.

> Theoretically, you could take the current page and pageSize and compose a "virtual" view range from those numbers (telling your back end to load records either side and only going back to get the "difference" each time). I am just not sure what value that would add.

This is what I was thinking would solve the view range problem; I hadn't realized/considered that `page` did not have to be an integer. I think that this issue can be closed; thanks.

> You should also be aware that there is a complete redesign on the (virtual) drawing board that is likely to see a lot more of the functionality being pushed out into replaceable components.

Interesting, would be cool to see. Anywhere I can read more or contribute to what you have in mind?

> Should you end up delivering a PR for progressive/virtual updating (nothing is truly "infinite") we'd be happy to consider merging it.

Will probably hold off for now; the virtual scroll HOC is a bit tied to our apps codebase at the moment, so I'd rather wait to see what changes you guys are planning before implementing a standalone solution.
