### ISSUE TITLE
Select Table selects rows from other pages

### ISSUE THREAD

**Issue by eklam** [react-tools/react-table#716]
## What version of React-Table are you using?

6.7.5

## What bug are you experiencing, or what feature are you proposing?

In the toggleAll function the getResolvedState().sortedData is used. It's stated that it returns only the currently visible rows. That's it not the case:

https://codesandbox.io/s/7yq5ylw09j?from-embed

## What are the steps to reproduce the issue?
1. Click on the header checkbox
2. Click Log Selection
3. Check the console and observe that more than 10 rows are logged

**Comment by gary-menzel** [comment]
The comment states:

"So, to that end, access to the internals of ReactTable are required to get what is
currently visible in the table **(either on the current page or any other page).**"

In the example, the header check box is meant to select ALL of the records (based on what the user has filtered). The `sortedData` returns everything that has been filtered (in the sorted order).

There is actually no internal state for the "visible" rows. It is calculated from the pageSize and the current page.

In any case, the responsibility for `toggleSelection` and `selectAll` are up to the developer to implement (so they can do anything to record the selection state).

The example is working as it was designed (and described) to do.

**Comment by eklam** [comment]
Got you. Since the example does no use filters, I assumed that it meant paging. Still, I think the comment should be changed:

"So, to that end, access to the internals of ReactTable are required to get _the filtered and sorted rows from the table_ ~~what is currently visible~~ in the table (either on the current page or any other page)."

The records in the second page are not currently visible. 

Kind of a bummer that we have to re-implement the filtering/sorting and paging on our own to have access to the current page visible rows. Any ideas how to do that in a nice way?

**Comment by gary-menzel** [comment]
You don't have to re-implement the sorting and filtering.  Use the `page` and `pageSize` to calculate the indexes in `sortedData` that constitute the current page (as I said in an earlier comment).
