### ISSUE TITLE
Is react-tools.js compatible with "create react app"?

### ISSUE THREAD

**Issue by dberhane** [react-tools/react-table#717]
Is react-tools.js compatible with "create react app"?  The Component decorators do not work with "create react app". I've tried to use getProps with the following code snippet below generates the error message, "TypeError: Cannot read property 'row' of undefined". I could view with console.log that the rowInfo object does have the attribute row but when I enter rowInfo.row it causes TypeError message:

  getProps: (state, rowInfo, column) => {
    console.log(rowInfo.row)
 }

Full error message from the console:

allbmj.js:117 Uncaught TypeError: Cannot read property 'row' of undefined
    at Object.getProps (allbmj.js:117)
    at makePadColumn (index.js:661)
    at Array.map (<anonymous>)
    at makePadRow (index.js:694)
    at Array.map (<anonymous>)
    at makeTable (index.js:800)
    at ReactTable.render (index.js:822)
    at finishClassComponent (react-dom.development.js:7873)
    at updateClassComponent (react-dom.development.js:7850)
    at beginWork (react-dom.development.js:8225)
    at performUnitOfWork (react-dom.development.js:10224)
    at workLoop (react-dom.development.js:10288)
    at HTMLUnknownElement.callCallback (react-dom.development.js:542)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:581)
    at invokeGuardedCallback (react-dom.development.js:438)
    at renderRoot (react-dom.development.js:10366)
    at performWorkOnRoot (react-dom.development.js:11014)
    at performWork (react-dom.development.js:10967)
    at requestWork (react-dom.development.js:10878)
    at scheduleWorkImpl (react-dom.development.js:10732)
    at scheduleWork (react-dom.development.js:10689)
    at scheduleTopLevelUpdate (react-dom.development.js:11193)
    at Object.updateContainer (react-dom.development.js:11231)
    at react-dom.development.js:15226
    at Object.unbatchedUpdates (react-dom.development.js:11102)
    at renderSubtreeIntoContainer (react-dom.development.js:15225)
    at Object.render (react-dom.development.js:15290)
    at Object../src/index.js (index.js:7)
    at __webpack_require__ (bootstrap a8e5e606f2c87ac29357:678)
    at fn (bootstrap a8e5e606f2c87ac29357:88)
    at Object.0 (registerServiceWorker.js:108)
    at __webpack_require__ (bootstrap a8e5e606f2c87ac29357:678)
    at ./node_modules/ansi-regex/index.js.module.exports (bootstrap a8e5e606f2c87ac29357:724)
    at bootstrap a8e5e606f2c87ac29357:724
getProps @ allbmj.js:117
makePadColumn @ index.js:661
makePadRow @ index.js:694
makeTable @ index.js:800
render @ index.js:822
finishClassComponent @ react-dom.development.js:7873
updateClassComponent @ react-dom.development.js:7850
beginWork @ react-dom.development.js:8225
performUnitOfWork @ react-dom.development.js:10224
workLoop @ react-dom.development.js:10288
callCallback @ react-dom.development.js:542
invokeGuardedCallbackDev @ react-dom.development.js:581
invokeGuardedCallback @ react-dom.development.js:438
renderRoot @ react-dom.development.js:10366
performWorkOnRoot @ react-dom.development.js:11014
performWork @ react-dom.development.js:10967
requestWork @ react-dom.development.js:10878
scheduleWorkImpl @ react-dom.development.js:10732
scheduleWork @ react-dom.development.js:10689
scheduleTopLevelUpdate @ react-dom.development.js:11193
updateContainer @ react-dom.development.js:11231
(anonymous) @ react-dom.development.js:15226
unbatchedUpdates @ react-dom.development.js:11102
renderSubtreeIntoContainer @ react-dom.development.js:15225
render @ react-dom.development.js:15290
./src/index.js @ index.js:7
__webpack_require__ @ bootstrap a8e5e606f2c87ac29357:678
fn @ bootstrap a8e5e606f2c87ac29357:88
0 @ registerServiceWorker.js:108
__webpack_require__ @ bootstrap a8e5e606f2c87ac29357:678
./node_modules/ansi-regex/index.js.module.exports @ bootstrap a8e5e606f2c87ac29357:724
(anonymous) @ bootstrap a8e5e606f2c87ac29357:724
index.js:2177 The above error occurred in the <ReactTable> component:
    in ReactTable (at allbmj.js:132)
    in App (created by Route)
    in Route (at App.js:19)
    in Switch (at App.js:17)
    in div (at App.js:15)
    in Router (created by BrowserRouter)
    in BrowserRouter (at App.js:14)
    in App (at index.js:7)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
__stack_frame_overlay_proxy_console__ @ index.js:2177
logCapturedError @ react-dom.development.js:9747
captureError @ react-dom.development.js:10540
renderRoot @ react-dom.development.js:10391
performWorkOnRoot @ react-dom.development.js:11014
performWork @ react-dom.development.js:10967
requestWork @ react-dom.development.js:10878
scheduleWorkImpl @ react-dom.development.js:10732
scheduleWork @ react-dom.development.js:10689
scheduleTopLevelUpdate @ react-dom.development.js:11193
updateContainer @ react-dom.development.js:11231
(anonymous) @ react-dom.development.js:15226
unbatchedUpdates @ react-dom.development.js:11102
renderSubtreeIntoContainer @ react-dom.development.js:15225
render @ react-dom.development.js:15290
./src/index.js @ index.js:7
__webpack_require__ @ bootstrap a8e5e606f2c87ac29357:678
fn @ bootstrap a8e5e606f2c87ac29357:88
0 @ registerServiceWorker.js:108
__webpack_require__ @ bootstrap a8e5e606f2c87ac29357:678
./node_modules/ansi-regex/index.js.module.exports @ bootstrap a8e5e606f2c87ac29357:724
(anonymous) @ bootstrap a8e5e606f2c87ac29357:724
allbmj.js:117 Uncaught TypeError: Cannot read property 'row' of undefined
    at Object.getProps (allbmj.js:117)
    at makePadColumn (index.js:661)
    at Array.map (<anonymous>)
    at makePadRow (index.js:694)
    at Array.map (<anonymous>)
    at makeTable (index.js:800)
    at ReactTable.render (index.js:822)
    at finishClassComponent (react-dom.development.js:7873)
    at updateClassComponent (react-dom.development.js:7850)
    at beginWork (react-dom.development.js:8225)
    at performUnitOfWork (react-dom.development.js:10224)
    at workLoop (react-dom.development.js:10288)
    at HTMLUnknownElement.callCallback (react-dom.development.js:542)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:581)
    at invokeGuardedCallback (react-dom.development.js:438)
    at renderRoot (react-dom.development.js:10366)
    at performWorkOnRoot (react-dom.development.js:11014)
    at performWork (react-dom.development.js:10967)
    at requestWork (react-dom.development.js:10878)
    at scheduleWorkImpl (react-dom.development.js:10732)
    at scheduleWork (react-dom.development.js:10689)
    at scheduleTopLevelUpdate (react-dom.development.js:11193)
    at Object.updateContainer (react-dom.development.js:11231)
    at react-dom.development.js:15226
    at Object.unbatchedUpdates (react-dom.development.js:11102)
    at renderSubtreeIntoContainer (react-dom.development.js:15225)
    at Object.render (react-dom.development.js:15290)
    at Object../src/index.js (index.js:7)
    at __webpack_require__ (bootstrap a8e5e606f2c87ac29357:678)
    at fn (bootstrap a8e5e606f2c87ac29357:88)
    at Object.0 (registerServiceWorker.js:108)
    at __webpack_require__ (bootstrap a8e5e606f2c87ac29357:678)
    at ./node_modules/ansi-regex/index.js.module.exports (bootstrap a8e5e606f2c87ac29357:724)
    at bootstrap a8e5e606f2c87ac29357:724

**Comment by gary-menzel** [comment]
ReactTable is a normal React component. It can be used anywhere a React component can (including create-react-app). In fact, all the examples on codesandbox are basically sitting on top of create-react-app.

That error is saying that `rowInfo` is undefined but I can't begin to say why that would be without seeing a lot more code.

**Comment by gary-menzel** [comment]
Aside from that - the code you have shown above would break as `getProps` needs to return an object (even an empty object) or that will cause an error.

**Comment by dberhane** [comment]
Thank you @gary-menzel for your prompt response. It seems all of the react-tools functionality work for me except the component decorators.  I was able to view via console.log(rowInfo) the property, "rowInfo.row.comment_count" successfully but the code snippet below still fails with the error, "TypeError: Cannot read property 'row' of undefined" if I uncomment the styling background directive and access the property directly, "rowInfo.row.comment_count" as detailed:

{
  getProps: (state, rowInfo, column) => {
    console.log(rowInfo)

    return {
      style: {
//        background: rowInfo.row.comment_count === 5 ? 'red' : null
      }
    }
  }
}

The full code snippet of my app which runs on create-react-app:

import React, { Component } from "react"
import queryString from "query-string"

import "../node_modules/bootstrap/dist/css/bootstrap.min.css"
import ReactTable from "react-table"
import "../node_modules/react-table/react-table.css"

class App extends Component {
  constructor(props) {
    super(props)
    this.state = {
      data: [],
      channel: ""
    }
  }

  componentDidMount() {
    const { pathname } = this.props.location

    const { description = null } = queryString.parse(this.props.location.search)

    const feedUrl = description
      ? `http://localhost:2002${pathname}/?description=${description}`
      : `http://localhost:2002${pathname}`

    fetch(feedUrl, { method: "get" })
      .then(result => {
        const feeds = result.json()
        console.log(feeds)
        return feeds
      })
      .then(feeds => {
        pathname === "/podcasts"
          ? this.setState({ data: feeds.tracks, channel: feeds.title })
          : this.setState({ data: feeds })
      })
      .catch(err => {
        console.log(err)
      })
  }

  render() {
    const { data, channel } = this.state

    const columns = [
      {
        Header: "Podcast ID",
        accessor: "id", 
        maxWidth: 120
      },
      {
        Header: "Created",
        accessor: "created_at",
        maxWidth: 220
      },
      {
        Header: "Downloads",
        accessor: "download_count",
        maxWidth: 100
      },
      {
        Header: "Favoritings",
        accessor: "favoritings_count",
        maxWidth: 100
      },
      {
        Header: "Title",
        accessor: "title"
      },
      {
        Header: "Description",
        accessor: "description"
      },
      {
        Header: "Comments",
        accessor: "comment_count",
        maxWidth: 80
      },
      {
        getProps: (state, rowInfo, column) => {
          console.log(rowInfo)

          return {
            style: {
         //     background: rowInfo.row.comment_count === 5 ? "red" : null
            }
          }
        }
      }
    ]

    return (
      <ReactTable
        data={data}
        columns={columns}
        defaultPageSize={100}
        filterable={true}
        className="-striped -highlight"
      />
    )
  }
}

export default App

**Comment by gary-menzel** [comment]
I think the problem is probably that you have the `getProps` on a column definition that is incomplete. It appears you want to decorate a row and not a column. You should use `getTrProps` on the ReactTable instance itself (and not `getProps` on an empty column definition).

There are two different sets of props handlers.  A few on the `column` definition and then the rest on the ReactTable instance.

ALSO NOTE: all columns should have at least an `accessor` to operate correctly.

**Comment by gary-menzel** [comment]
So, for example, if you moved the `getProps` into the column definition with the 'comment_count' accessor you may find it works (you want to highlight that cell). But if you want to highlight the row, then you'll need to put it in the ReactTable instance as `getTrProps` instead.

**Comment by dberhane** [comment]
I've moved the getProps in the column definition and still getting the same error message, "Uncaught TypeError: Cannot read property 'row' of undefined"

`      {
        Header: "Comments",
        accessor: "comment_count",
        maxWidth: 80,
        getProps: (state, rowInfo, column) => {
          console.log(rowInfo)

          return {
            style: {
              background: rowInfo.row.comment_count === 5 ? "red" : null
            }
          }
        }
      },
`

**Comment by dberhane** [comment]
Could this be create-react-app Webpack issue as Decorators are not supported? I could see some error stack on my create react app:

./src/index.js
http://localhost:3000/static/js/bundle.js:44076:51
  44073 | 
  44074 | 
  44075 | 
> 44076 | __WEBPACK_IMPORTED_MODULE_1_react_dom___default.a.render(__WEBPACK_IMPORTED_MODULE_0_react___default.a.createElement(__WEBPACK_IMPORTED_MODULE_3__App__["a" /* default */], {
        |                                                   ^  44077 |   __source: {
  44078 |     fileName: _jsxFileName,
  44079 |     lineNumber: 7

**Comment by gary-menzel** [comment]
I don't know what you mean by "Decorators" in this context. If you mean @ symbols that instruct various enhancements - ReactTable does not use those. The series of `get*` overrides are simple function calls to get an object to pass as props to the various components.

This example (taken from the basic example in the docs - and with a `getProps` added to the Age column) works: https://codesandbox.io/s/0o717rq9ol

Make sure you got rid of the `getProps` that was sitting in the incomplete column definition (because it will still fail and then you will never get to see if the real one worked).

**Comment by dberhane** [comment]
Finally, I was able to resolve the problem which was not directly related to the react-table.js. My react app was interacting with a remote RESTful service and that the state data (this.state.data) for the first milliseconds being empty was the cause of the TypeError. I was able to put a simple if condition to stop this happening just before react render return statement:

  if (this.state.data.length === 0) return <div><h2>Waiting for RealTime interaction with a Remote Service</h2></div>
