### ISSUE TITLE
Resetting filters with minimal adjustments to the default filter method

### ISSUE THREAD

**Issue by boriskogan81** [react-tools/react-table#718]
I'm using React-Table 6.7.6, and want to reset all filters programatically.

Right now, I've got this code:

```
		return (
			<div>
				<ReactTable
					className="-striped -highlight"
					data={data}
					columns={columns}
					filterable={true}
					defaultFilterMethod={(filter, row, column) => {
						const id = filter.pivotId || filter.id;
						return row[id] !== undefined
							? String(row[id]).includes(filter.value)
							: true;
					}}
				/>
			</div>
		);
```

Is there a way to reset the filter values without digging into the guts of this thing too much?

**Comment by gary-menzel** [comment]
Check the doco on the `filtered` property (and you might want to also consider the `onFilteredChange` handler).

This is an implementation question. For any further assistance please use the #react-table Slack channel (badge at the top of the README in the doco). The github issues are for bugs and feature requests.  Thanks.
