### ISSUE TITLE
[Question] data from redux state, how to refresh?

### ISSUE THREAD

**Issue by lcapriotti** [react-tools/react-table#719]
## What version of React-Table are you using?
6.7.5

## What bug are you experiencing, or what feature are you proposing?
the data is passed to ReactTable as array from redux state, and updated with external logic. 
The ReactTable component does not update unless the length of the data array changes.

Is there anything to do to have automatic update of the table content even when a "data field" in a row changes?

**Comment by gary-menzel** [comment]
Nothing special required just normal Redux wiring around the component. Check this basic Redux example: https://codesandbox.io/s/r5q81w4wwq

This is an implementation issue and not a bug with ReactTable.  For implementation help, please use the #react-table Slack channel (badge at the top of the README in the doco). Thanks.
