### ISSUE TITLE
Is  this Component support IE 11?

### ISSUE THREAD

**Issue by jdx2014** [react-tools/react-table#722]
## What version of React-Table are you using?
Your bug may already be fixed in the latest release. Run `yarn upgrade react-table`!
Place your version here...
the react-table version is 6.7.6

## What bug are you experiencing, or what feature are you proposing?
Please include a detailed explanation here...

## Use https://codesandbox.io/s/X6npLXPRW (by clicking the "Fork" button) to reproduce the issue.
Then paste a link to your newly forked codesandbox here...

## What are the steps to reproduce the issue?
1. list the steps
2. to reproduce
3. the issue

**Comment by gary-menzel** [comment]
Yes - If you are having display issues, make sure you have the correct DOCTYPE. There is an FAQ in the Wiki here.

**Comment by jdx2014** [comment]
Thanks to the response,the IE don't supprt method of Array.find ,which is used in the source code  of method.js (line 40+),and then i resolve this by import baby.polyfill . why not import this polyfill in the source solution.

**Comment by gary-menzel** [comment]
It is not included as it uses ES2015 standards for Javascript.  It is the developers responsibility to add the correct support.  Array.find is a very common construct in modern Javascript so you will require it for a lot of other component libraries that work with arrays.

**Comment by jdx2014** [comment]
Thanks ,it's sure the responsibility of developers.
 anothet question is the demo  https://react-table.js.org/#/story/simple-table can't display anythind in IE 11.

**Comment by gary-menzel** [comment]
I've tested it with a Windows 8.1 and IE11 virtual machine and it does work. So I am not sure what would be happening.

**Comment by jdx2014** [comment]
ok,i test it with a Windows 10 home edition and IE 11.125,and the reason i find is about Array.find

**Comment by gary-menzel** [comment]
I am saying I tested the demo simple-table - and it works.  As far as your build environment is concerned, you need to ensure your build/execution environment is ES2015 (and up) compatible. I don't think there is any issue with React Table so will close this now.

If you need additional implementation help please join the #react-table Slack channel (badge at the top of the README in the doco) as the github issues are for bugs and feature requests.
