### ISSUE TITLE
support for rowspan | question

### ISSUE THREAD

**Issue by seeden** [react-tools/react-table#723]
Is there any support for rowspan?
Thank you

**Comment by gary-menzel** [comment]
No support for any type of span (row or column).  However, the following examples show how a rowSpan can be "faked" (if it is a simple one)....

https://codesandbox.io/s/k0kvql3jr

https://codesandbox.io/s/p2wy5zlowx

**Comment by lmannering** [comment]
Both those links are broken, is there a working demo of this available please?

**Comment by gary-menzel** [comment]
Those examples are gone because codesandbox has a limit on how many free sandboxes can exist.

I also don't have any time available to recreate them.

**Comment by lmannering** [comment]
Ah ok, no worries! I've found a way round it :)

**Comment by sireeshav** [comment]
@seeden @lmannering Pls help me with this issue
