### ISSUE TITLE
Unexpected behaviour when changing amount of rows in table

### ISSUE THREAD

**Issue by meeoh** [react-tools/react-table#724]
## What version of React-Table are you using?
Your bug may already be fixed in the latest release. Run `yarn upgrade react-table`!
6.6.0

## What bug are you experiencing, or what feature are you proposing?
When having a table say of 5 items. I want to be able to delete one of the items in the table. I can trigger a rerender where that item will no longer be in my data-set, but the item is still there.

My table looks something like this: 
![image](https://user-images.githubusercontent.com/5509365/34618662-7524c170-f20d-11e7-82a7-6dbd1f756ad8.png)
When I change the quantity of the first item to 0, the table rerenders and the first item no longer shows like so: 
![image](https://user-images.githubusercontent.com/5509365/34618880-33885708-f20e-11e7-878c-73dec47a3f5b.png)

 However, the second items quantity will dropdown to zero, and when you increase the second items quantity, the first item comes back! I feel like this has something to do with the index of the rows not updating. I know this isnt feature technically isnt supported, but was looking for a workaround for this.

**Comment by gary-menzel** [comment]
Screenshot don't provide enough information.  Please provide a mockup of the code in codesandbox as it is much easier to see how you have constructed the table and the logic behind the functionality you are trying to provide.

There are many factors that could cause the behaviour you are seeing (e.g. having a sort enable would mean that changes to the data will automatically re-sort, or an active filter could do similar, or it may just be that you don't have the data wired up correctly or that your quantity component isn't written to understand individual rows correctly).

As far as the numbers changing, that sounds like you may not have the quantity component written correctly.

So, a codesandbox simplified mockup will help narrow the possibilities.

**Comment by meeoh** [comment]
Thank you for your reply @gary-menzel, it was a bit complicated to recreate the issue in a codesandbox, so I just did some debugging with the information you gave me. I found out that adding a `key` to the table would make it remount when the items changed, and that solved the issue
