### ISSUE TITLE
access data that has been filtered down

### ISSUE THREAD

**Issue by reboryan** [react-tools/react-table#726]
I am trying to find a way to access the filtered down data when `filterable` is enabled. I have all the rows as JSON stored in state initially, but when I start to filter down, I can't find a way to either (a) update the state with the now filtered down rows, or (b) simple access the filtered down data as JSON (or other) and store in a var or something that I can then use for my specific need:

My specific application is we need to be able to save a CSV of the _**filtered data**_. Is this currently possible?

Thanks in advance, love this tool.

**Comment by gary-menzel** [comment]
There's an FAQ for that in the Wiki....

https://github.com/react-tools/react-table/wiki/FAQ#how-do-i-get-at-the-internal-data-so-i-can-do-things-like-exporting-to-a-file

NOTE: you don't want to update the state with the filtered data - this should remain your "raw" data for that table.
