### ISSUE TITLE
yarn run watch hangs on Windows 10

### ISSUE THREAD

**Issue by dumptruckman** [react-tools/react-table#727]
## What bug are you experiencing, or what feature are you proposing?
When attempting to run `yar run watch` on Windows 10 or even bash on Ubuntu on Windows, the process hangs after showing `src/utils.js -> lib/utils.js`. The process works fine on my Linux Mint laptop. Here's a paste of the output https://hastebin.com/otoviyobom.tex

## What are the steps to reproduce the issue?
1. clone git repo
2. run `yarn`
3. run `yarn run watch`

**Comment by gary-menzel** [comment]
I had this when I first installed the repo on my Macbook Pro.  I made sure everything was at the latest versions (even though I thought they were) and then it all ran fine.

However, I am not running on a Windows machine (so can't really help out much).

**Comment by dumptruckman** [comment]
I just tried updating to the latest everything. yarn 1.3.2, node 8.9.4, npm 5.6.0. Unfortunately I'm still encountering the same issue.

**Comment by gary-menzel** [comment]
Do you have webpack installed globally or did it just install for the package ?

I think that was another thing I had to do (I uninstalled webpack globally and installed it again).

It's been about 4 months since I first did it.

It is frustrating because there is no error message that I could find - it just seems to not do anything.

**Comment by dumptruckman** [comment]
Globally uninstall webpack and reinstalling it locally for react-table did the trick. Thanks!

**Comment by dumptruckman** [comment]
Turns out I did not actually resolve my issue. It seems to have fixed the problem when running `yarn run docs` but *not* `yarn run watch`. Any other thoughts?

**Comment by dumptruckman** [comment]
Specifically, it seems to be having a problem with `npm run watch:node`

**Comment by dumptruckman** [comment]
Nevermind. I just don't understand what I'm doing. It does seem to be detecting file changes. I was under the impression that `yarn run watch` was suppose to start a nodejs instance with some sort of demo site.

**Comment by gary-menzel** [comment]
`yarn run watch` only rebuilds the code when there are changes. You need to use the docs site to actually run up any pages with your changed code.  That is basically what the the bottom of the README says. So, essentially, you run both. The `docs` one is what gives you a website and it uses the built files that are produced by the `yarn run watch`.
