### ISSUE TITLE
Edited Value end with BR-Tag, even if linebreak in cell was removed via edit

### ISSUE THREAD

**Issue by matthiaw** [react-tools/react-table#728]
## What version of React-Table are you using?
react-table ^6.7.6

## What bug are you experiencing, or what feature are you proposing?
An edited cell has a html-linebreak-tag as postfix, if a value had a linebreak before. Even if it was deleted.

## See Codesandbox-Issue
See https://codesandbox.io/s/3q8y8jy135

## What are the steps to reproduce the issue?
1. Edit Cell and add LineBreak
2. Delete Linebreak in Cell
3. Watch Console at Web-Developer-View. Every Value ends with <br>.

This seems not right, so my question is, why is this happening. This produces in my App errors because the line-break-tag leads to errors, so i need to do text-replacement and the end of the line. Could i force the cell to be a single-line?

**Comment by gary-menzel** [comment]
The editing example (only an example - not part of the core library) uses direct editing of a `<div/>` to avoid using a controlled `<input/>` that would cause refreshes to happen (unless it was in it's own stateful component) so, technically, you are editing HTML.  As a result you have to deal with that and it includes some type of conversion.

You can do anything you like to edit the cell content - this is a developer provided piece of functionality.  You could still use the `<div/>` and provide a key handler to filter out the ENTER key (for example) or you could replace the `<div/>` with your own input component that calls back to your wrapper code when the content is change (like an `onBlur`) - but it is really outside the scope of ReactTable.
