### ISSUE TITLE
Bug or missleading docs

### ISSUE THREAD

**Issue by code-beans** [react-tools/react-table#729]
## What version of React-Table are you using?
v6.7.6

## What bug are you experiencing, or what feature are you proposing?
I can only access fields in a custom Cell Style which are also exposed as a column somewhere in my table. The docs are also not clear on this, see chapter **Custom Cell, Header and Footer Rendering**    

`row` - Original row from your data (is what I expect)
`row` - The post-accessed values from the original row (is what I get)

I should either have full access to my row, or an index to look up in my original data

## Reproduce
https://codesandbox.io/s/vn3n9rnmo0 l.26

## What are the steps to reproduce the issue?
1. define custom Cell Style
2. Access any row attribute which is in your original data, but not exposed as a column

**Comment by gary-menzel** [comment]
Where it says "original" in the description it should say "original" on the left hand side. It contains your original row.

"row" is the rendered data.

It is just a documentation error which is low on the list of fix priorities.  A console log reveals this information.  There is already a an issue in to fix the documentation so this will be closed.
