### ISSUE TITLE
Conditionally coloring a cell (not row) based on its value

### ISSUE THREAD

**Issue by veeral-patel** [react-tools/react-table#736]
## What version of React-Table are you using?
6.7.6

## What bug are you experiencing, or what feature are you proposing?
I don't know how to conditionally color a CELL based on it's value. I've read the README, and can conditionally color a row like this:

```
            getTdProps={(state, rowInfo, column, instance) => {
                return {
                    style: {
                        background: rowInfo.row.severity == "HIGH" ? "green" : null
                    }
                };
            }}
```
Here, if the cell's value is "HIGH", the entire ROW is green. What I'd like is for just that cell to be green. How do I do that? A simple example would be nice.

Thanks!

## Use https://codesandbox.io/s/X6npLXPRW (by clicking the "Fork" button) to reproduce the issue.
https://codesandbox.io/s/4jo143r80w

**Comment by gary-menzel** [comment]
Move your code to `getProps` in the column definition where you want the background colour to be. `getTdProps` is global for the row (you'd have to check the columns and only do it for the correct column).

**Comment by veeral-patel** [comment]
Got it!
For future reference - https://codesandbox.io/s/4jo143r80w

**Comment by mendesfelipe87** [comment]
@veeral-patel Hi, your code in sandbox is broken

**Comment by mendesfelipe87** [comment]
fixed! for future references

https://codesandbox.io/s/744n0nmvl0

**Comment by efrenmarin45** [comment]
How would we go about doing this in v7?

**Comment by LoriaDenzell** [comment]
Currently not working in V7
