### ISSUE TITLE
pageJump input toggle arrows don't change the page

### ISSUE THREAD

**Issue by pigeontoe** [react-tools/react-table#742]
Toggling the pageJump input doesn't cause any change other than the number displayed. I would expect manipulating the up and down arrows to actually change the current page. Currently, I have to manually hit enter from inside the input box to affect any change which seems clunky. Is there an onChange event or something that I can hook into and change pages somehow?

**Comment by gary-menzel** [comment]
No - there is no exposure of the internals of the pagination control. You'd need to replace it with your own version if you want to change the functionality. The current pagination control is about 140 lines long. You could copy that and just modify the parts you want to change and then install it your ReactTable via the `PaginationComponent`. You just have to make sure that you maintain the function (the component uses callbacks to talk to ReactTable).

It's not "clunky" - just not what you expected.  Imagine if you had 500 pages - you wouldn't want to be using arrow keys on the keyboard to get there.  It just uses a "default" input box.

**Comment by pigeontoe** [comment]
I just looked at it in chrome on my macbook and it seems a lot less "clunky". Incrementing or decrementing the input moves the cursor to the input and hitting enter takes you to that page in the table. I would still personally like for it to change the page, but maybe that's just me.

At work I use a pc and design in firefox, and in that environment incrementing or decrementing the pageJump input does nothing unless you then click inside the input, then hit enter (which I find not at all intuitive). Unfortunately, this is the environment that our main client uses exclusively when using our software, so I will look into this solution for sure. Thanks a lot for the tip!

**Comment by gary-menzel** [comment]
It's probably also me as well. Although I did not build the pagination control, I never use those increment/decrement techniques.  I prefer to type my numbers and probably would find the page jumping around when I type higher numbers a little disconcerting (e.g if I wanted to get to page 123 I would type 1, then page 1 would appear, 2 then page 12 would appear, 3 then page 123 would appear).  So, at minimum, it would have to be debounced.

NOTE: a lot of people (on the #react-table Slack channel - badge at the top of the README) have been totally removing the pagination control (there is a flag to turn it off) and implementing a completely different type of paging outside of the ReactTable instance with the list of page buttons approach.

**Comment by pigeontoe** [comment]
That makes a lot of sense when you think about actually typing numbers in manually. I'll keep that in mind, and I'll look into the solutions you suggested. Thanks a lot!
