### ISSUE TITLE
CSS Espcificity for input inside the filter

### ISSUE THREAD

**Issue by rorofino** [react-tools/react-table#743]
## What version of React-Table are you using?
Latest

## What bug are you experiencing, or what feature are you proposing?
The input inside the filter cant be easy customized because of css especificity.

.ReactTable .rt-thead.-filters input,
.ReactTable .rt-thead.-filters select {
    border: 1px solid rgba(0, 0, 0, 0.1);
    background: #fff;
    padding: 5px 7px;
    font-size: inherit;
    border-radius: 3px;
    font-weight: normal;
    outline: none
}

Would be nice to have an simple class that style the input. Right now, all ui libs that i tried to use broke when the field was added to the table.

**Comment by gary-menzel** [comment]
The specificity won't be changed in the current release as it is critical to the operation of the component and all the existing users of the component.  Which components have you tried to use?  Please provide a codesandbox.io example demonstrating the issue and there might be a way to provide assistance.

Also, please consider asking on the #react-table Slack channel (badge at the top of the README) as there is a wider range of users there who may also be able to help.

The github issues are for bugs and feature requests.

Thanks.

**Comment by pavlos256** [comment]
Workaround that overrides the Thead component to rename "-filters" to "x-filters":

```js
import { ReactTableDefaults } from "react-table";

function TheadComponent({ children, className, ...rest }) {
	className = className.replace(/-filters/g, "x-filters");

	return (
		<div className={classNames("rt-thead", className)} {...rest}>
			{children}
		</div>
	);
}

Object.assign(ReactTableDefaults, {
	TheadComponent
});
```

```css
.ReactTable {
	.x-filters {
		border-bottom: 1px solid rgba(0, 0, 0, 0.05);

		.rt-th {
			border-right: 1px solid rgba(0, 0, 0, 0.02);
		}
	}
}
```
