### ISSUE TITLE
Custom Pagination Bar

### ISSUE THREAD

**Issue by EinsamerHirte** [react-tools/react-table#745]
Is there any way to custom Top/Bottom Pagination, over show/hide them. Can I use a custom component for them?

Thanks!

**Comment by gary-menzel** [comment]
Please read the documentation. There are overrides for almost every component.

Also, the github issues are not for general enquiries - please join the #react-table Slack channel (badge at the top of the README). Thanks.

**Comment by bpb27** [comment]
```jsx
<ReactTable data={data} columns={columns} PaginationComponent={Pagination} />
```

**Comment by ajay1008** [comment]
How to add select option range feature, for selecting 5,10,15 records
