### ISSUE TITLE
Does not display boolean values

### ISSUE THREAD

**Issue by guyisra** [react-tools/react-table#746]
if the data, via the accessor, return a boolean value, they are not displayed in the table.

Is this a known issue, or should I use some option to convert them to string?

**Comment by gary-menzel** [comment]
The main purpose of the `accessor` is to provide values for correct sorting and filtering comparisons and should return raw data (like a boolean). An attempt is made to convert that into something that can be displayed.  However, the correct way to display non-string or non-numeric data is to use a `Cell` handler and convert your data there.

**Comment by Omortis** [comment]
This seems to happen with string values of "False" and "'False'" as well - these are not raw booleans. Is this expected behavior? They are already a string - do I need to use a Cell handler to cast them to a string again?

**Comment by Waqar-Ul-Khaf** [comment]
> This seems to happen with string values of "False" and "'False'" as well - these are not raw booleans. Is this expected behavior? They are already a string - do I need to use a Cell handler to cast them to a string again?
> 
> (Ignore, not a react-table issue, sorry for the static...)

How you target that problem  ?

**Comment by anantl05** [comment]
You can do value.toString() to display boolean values in data table.

**Comment by debmaj2** [comment]
> The main purpose of the `accessor` is to provide values for correct sorting and filtering comparisons and should return raw data (like a boolean). An attempt is made to convert that into something that can be displayed. However, the correct way to display non-string or non-numeric data is to use a `Cell` handler and convert your data there.

Is there a supporting example?
