### ISSUE TITLE
Column width to adjust to cell contents

### ISSUE THREAD

**Issue by bernatfortet** [react-tools/react-table#748]
Hi, I understand how to use minWidth, maxWidth to adjust the width of a column.
How can I make sure that the minWidth of a column adjusts to the width of the biggest element in its cells?

thanks

**Comment by gary-menzel** [comment]
This is not directly supported in ReactTable.

**Comment by mecampbellsoup** [comment]
Is it not possible to use e.g. `width: 'fit-content'` in column props?

**Comment by tannerlinsley** [comment]
I'm not sure what you mean. By rendering using html table elements you are already getting that. Can you explain more?
