### ISSUE TITLE
Can't seem to find the 'isExpanded' state.

### ISSUE THREAD

**Issue by Romyeo** [react-tools/react-table#749]
I've been trying to figure out how to know if a row is expanded, i've read the documentation and it said its on 'Cells-level props' but i don't know which get * Props should i use to access this table state, i've used getTdProps and also getTrProps but the 'isExpanded' state is not there.

**Comment by gary-menzel** [comment]
If you have a `Cell` renderer in a column, then the object passed to that contains the `isExpanded`.
