### ISSUE TITLE
Not really an issue. Just a question on how to grab filtered data?

### ISSUE THREAD

**Issue by exztinct01** [react-tools/react-table#750]
I would just like to ask how I can grab the filtered data. For example, I fetched data containing 2174 rows, after filtering only 1900 rows passed the filter. I now need to send to backend api an array containing the filtered data's first column values.
My question is how do I get that data?

**Comment by gary-menzel** [comment]
This is in the FAQ in the Wiki on github.....

https://github.com/react-tools/react-table/wiki/FAQ#how-do-i-get-at-the-internal-data-so-i-can-do-things-like-exporting-to-a-file

**Comment by Ali-Aref** [comment]
> This is in the FAQ in the Wiki on github.....
> 
> https://github.com/react-tools/react-table/wiki/FAQ#how-do-i-get-at-the-internal-data-so-i-can-do-things-like-exporting-to-a-file

the wiki page is removed. any update link ? 
I searched and found solutions on getting data from `<ReactTable ...>` but I hadn't use that. I implemented as the basic example.
