### ISSUE TITLE
How to render two attributes of the data object in a single column?

### ISSUE THREAD

**Issue by carlosmjimenez** [react-tools/react-table#752]
React-table 5.6.0

How to render two attributes of the data object in a single column?

for example:

`const data = [
  {
    title:'React', 
    url: 'https://facebook.github.io/react/',
    author: 'Jordan Walke',
    num_comments: 3,
    points: 4,
    objectID: 0,
  }]`

I want it to be rendered in this way:

`<a href={data.url}>{data.title}</a>`

**Comment by midnightcodr** [comment]
Use `Cell` and `row.original`._attribute_, for example:
```javascript
                  accessor: 'url'
                  Cell: row => {
                      return <a href={row.value}>{row.original.title}</a>
                  }
```
Btw your `data` is the whole data set and the only entry in the data array should be considered one of the data rows when you use `react-table`.

**Comment by carlosmjimenez** [comment]
Thank you so much, It works perfectly!
