### ISSUE TITLE
Filtering on press Enter

### ISSUE THREAD

**Issue by Pasichnyk** [react-tools/react-table#753]
Need to change filters launching event. I'm using server-side data. And it sends request after every button's click in filters.... that does not fit to server-side data. 

How to make filters launching on pressing **Enter**, not on any buttons.

**Comment by gary-menzel** [comment]
Create your own `Filter` component for the column (or columns) you want to filter.

There is an example in the doco "Custom Filtering". It uses a `<select />` but you can put any component in there to filter however you want.

**Comment by Pasichnyk** [comment]
Ok. 
Next question: can I affect few filters from one select ?
 ```javascript
onChange({
   fieldA: fieldAValue,
  fieldB: fieldBValue
})
```

**Comment by Pasichnyk** [comment]
As I understand filterMethod is not applied to server-side data.

**Comment by Pasichnyk** [comment]
off topic: When I set parameters "filtered" or "sorted" on table, it starts endless looping of changing states and sending requests.
Am I doing smth wrong or is it a bug ?

**Comment by lc-stevenzhang** [comment]
` 
columns: [
          {
            Header: 'LC_Class',
            accessor: 'class_name',
            Filter: ({ filter, onChange }) => {
                 return (
                    <Input
                         onKeyPress={event => {
                             if (event.keyCode === 13 || event.which === 13) {
                                    onChange(event.target.value)
                            }
                        }}
      />
    )
  },
          },`

**Comment by starrybleu** [comment]
After I followed @lc-stevenzhang 's code, I found it doesn't keep `filtered` state. So there is an unexpected behavior that the last entered input filter only works. Is there a workaround?
When I call `onChange`, I cannot stop fireFetchData. If I could stop fireFetchData along with `onChange`, it will be great!
