### ISSUE TITLE
Event listeners is really slow in example

### ISSUE THREAD

**Issue by rmv125** [react-tools/react-table#755]
## What version of React-Table are you using?
Version used in example
## What bug are you experiencing, or what feature are you proposing?
I looked through the examples, and found, that event listeners added by custom props example is slow on case with large number of records in the table.

## Use https://codesandbox.io/s/X6npLXPRW (by clicking the "Fork" button) to reproduce the issue.
https://react-table.js.org/#/story/custom-component-props

## What are the steps to reproduce the issue?
1. Open the example
2. Open performance analysis tab in dev tools.
3. Start record, and hover table row. Then stop record after a few seconds.
4. Look on results.
On my machine, it took more than 3 seconds to handle the event (the event handler, is just console.log). During that time, the page fps is 0.
![img](http://storage6.static.itmages.com/i/18/0117/h_1516203102_3339940_a6a3055bd6.png)

I looked into that issue, and looks like it happens because of logging table state and instance.
I think the example with 3 seconds lags is not the great example, and it should be fixed.

**Comment by gary-menzel** [comment]
Happy to accept a suggestion to fix it.

**Comment by rmv125** [comment]
You just need to remove logging of table state and instance, and probably add the comment saying that it's possible to access that.

**Comment by gary-menzel** [comment]
Except - that is the whole point of the example (to show that it works). You'd do something more sensible if you required this for an actual feature.
