### ISSUE TITLE
Render table without TrGroupComponent

### ISSUE THREAD

**Issue by BaranovNikita** [react-tools/react-table#756]
## What version of React-Table are you using?
6.7.6

## What bug are you experiencing, or what feature are you proposing?
I try render default HTML table. but every row wpapped to TrGroupingComponent

## Use https://codesandbox.io/s/X6npLXPRW (by clicking the "Fork" button) to reproduce the issue.
https://codesandbox.io/s/q9nm9rmk3w

Can I render table without TrGroupComponent?

**Comment by gary-menzel** [comment]
No. This is critical to the layering of ReactTable.  You cannot render a "traditional" HTML table with ReactTable.
