### ISSUE TITLE
[help] Render HTML in cell

### ISSUE THREAD

**Issue by zzeebbii** [react-tools/react-table#757]
Actually I'm stuck on two things.
First I'm using server side filtering, sorting and pagination and it's working absolutely fine. Now I want one column to be filtered on frontend only, I mean when I filter it should just filter loaded data in browser and shouldn't send AJAX request. I've define the `filterMethod ` on column but still it's sending AJAX request while I just want to filter already present rows. Is it possible to use server side filtering along with client side filtering on different columngs.

Secondly, I'm getting JSON response from my server. I'm also sending some HTML in that JSON which render two buttons. Now when I'm setting `accessor `equals to key in collection, it just prints the HTML in text format and button is not rendered. What should I do to render HTML in cell, not text.

Any help is appreciated.

**Comment by gary-menzel** [comment]
This is a React question.  React has a "dangerouslySetInnerHTML" mechanism. However, there are multiple solutions to rendering HTML (including converting it to a React component).

This is not really a ReactTable issue. Please ask others over on the #react-table Slack channel (badge at the top of the README). Thanks.
