### ISSUE TITLE
Reset filters when doing server-side filtering

### ISSUE THREAD

**Issue by pierrickbena** [react-tools/react-table#760]
## What version of React-Table are you using?
6.7.6

## What bug are you experiencing, or what feature are you proposing?
Hi, 
I am doing server-side filtering with my react-table. I have several tabs, and I am looking for a way to reset the filters when I change the current tab. 

If I add 

`filtered={this.state.filtered}
 onFilteredChange={filtered => this.setState({ filtered })}` 

it works, but in that case the backend is called twice each time a character is typed in a filter area, because I have the manual prop.

## What are the steps to reproduce the issue?
1)Type a character in a filter area
2)Click on the other tab
3) Notice the value typed in the filter area is still there

Thanks for your help !

**Comment by bdell** [comment]
clear and reinitiate a timeout call to your backend when you need to update your table data

```js
myDataUpdateFunction(options) {
    clearTimeout(this.myTimeout);
    this.myTimeout = setTimeout(() => {
        MyAPI.getNewData(options).then(data => this.setState({ tableData: data }))
    }, 500);
}
```

**Comment by ScottAHoward** [comment]
We are having the same issue.  We used similar code to get the filter to clear under a similar scenario and would like to limit the number of calls to the API.

**Comment by gary-menzel** [comment]
It is called twice because it is once for the typed character and then (because of the controlled input) it triggers again.  You can set up a debounce to avoid this (either by setting a flag in your own component or using a debounce function from something like lodash).

**Comment by pierrickbena** [comment]
If I add ` this.fetchData = _.debounce(this.fetchData.bind(this),100)`; in the constructor , it works as expected. Thanks @gary-menzel
