### ISSUE TITLE
Getting started - table with header column and row

### ISSUE THREAD

**Issue by iehdk** [react-tools/react-table#762]
How can I create a table like below?

![table](https://user-images.githubusercontent.com/29797781/35154592-0f698be4-fd2b-11e7-8792-036bd0eac2f3.png)

**Comment by gary-menzel** [comment]
ReactTable is not a "spreadsheet" (which is what your picture looks like). It also does not support fixed columns (which is also what your picture looks like for the column containing A/B).

If you require that type of functionality then you need to find a different component.

[Also - just posting a picture is very vague.  I could easily make a table that looks like that just with a normal Table/Th/Td - or just about any React Table component.  But I doubt it would be what you want.]

**Comment by iehdk** [comment]
I need a table where I can update the entire content easily using props - which you can with react-table AFAICT. Also, I will be needing the [select table](https://react-table.js.org/#/story/select-table-hoc) which looks super nice. The question is; can you style the first column like the first row and also make the data unselectable?

A picture says more than a 1000 words? :o|

**Comment by gary-menzel** [comment]
I think what you need to do is consume all the documentation and play around with the library on codesandbox.io (which lets you write in an IDE like environment in real time).

There is a LOT you can do with styling.  There is a LOT you can do with columns and there are a LOT of props and components that can be overridden.

It is what the picture doesn't say that is needed to answer the question :)

You could display nothing in the header for the first column.  You could set `style` on the first column that is different to the other columns.  You could also style the other headers (there is a `headerStyle` for a column - in the doco) to make it be the same styling as the first column.

That is all simple to do.  But, if you then expect the first column to behave like a frozen column in a spreadsheet, ReactTable does not (cannot currently) do that.
