### ISSUE TITLE
[Question] What would be the best method to render the FilterComponent in the place where PaginationComponent should be?

### ISSUE THREAD

**Issue by zomars** [react-tools/react-table#763]
So, basically I need to render the filter component at the bottom at the table. I would like to know if there a way to easy "swapping" these components or any suggestions would be greatly appreciated.

Cheers.

**Comment by gary-menzel** [comment]
There is no facility to do this.

**Comment by zomars** [comment]
I've solved it using flexbox, it's not exactly what I was looking for but it's close enough:

```js
<ReactTable
  data={clients}
  columns={columns}
  getTheadFilterProps={() => {
    return {
      style: {
        order: '1'
      }
    }
  }}
/>
```
