### ISSUE TITLE
Bad variable type checking inside documentation for `defaultSortMethod`

### ISSUE THREAD

**Issue by WojtekWernicki** [react-tools/react-table#764]
## What version of React-Table are you using?
6.7.6

## What bug are you experiencing, or what feature are you proposing?
Fix for documentation (`defaultSortMethod`)

## Reproduction
Please check README.md file

## What are the steps to reproduce the issue?
Inside documentation for default sorting method, there is missing checking variable type. Current code:
```
a = a === 'string' ? a.toLowerCase() : a
b = b === 'string' ? b.toLowerCase() : b
```
will compare variable to provided "string", not to the type. Here's how code should look:
```
a = typeof a === 'string' ? a.toLowerCase() : a
b = typeof b === 'string' ? b.toLowerCase() : b
```

**Comment by tannerlinsley** [comment]
Please submit a PR to fix this if you can :)
