### ISSUE TITLE
Align component in cell

### ISSUE THREAD

**Issue by M1chaelChen** [react-tools/react-table#769]
## What version of React-Table are you using?
6.7.6

## What bug are you experiencing, or what feature are you proposing?
Can not align component within the cell.

**Comment by DamianFekete** [comment]
Check this out: https://codesandbox.io/s/ojyx80ljo5
I've added the property `className` and defined the CSS class in index.css.

**`index.js:`**
```Javascript
                {
                  Header: "Last Name",
                  id: "lastName",
                  accessor: d => d.lastName,
                  className: "right"
                }
```
**`index.css:`**
```css
.right {
  text-align: right;
}
```

**Comment by parwat08** [comment]
This one too works fine. Add the css in main css file and use it

```
Header: () => (
    <div style={{
        textAlign: "right"
    }}>
        Actions
      </div>
)
```

**Comment by robertvasile** [comment]
@DamianFekete @parwat08 both your solutions align the text in the table header,
i'd bet @M1chaelChen was referring to aligning the values

**Comment by DamianFekete** [comment]
@robertvasile, my change works OK. I've colored in the following example the background for the column **values** to see that they are right aligned: https://codesandbox.io/s/ryj15q8wyq

@parwat08 already said that her/his change it is for the column name, not the value. That may be useful if you want to align everything, not only values.

**Comment by parwat08** [comment]
@DamianFekete Thanks mate

@robertvasile Mine solution might be useful if someone wants to align the column name. I already have mentioned it.

**Comment by mbenhalima** [comment]
I found this very helpful to align the components within all the cells in the table:
      getTdProps={() => ({
          style: {
              textAlign: 'right'
          }
      })}
