### ISSUE TITLE
Cannot read property 'columns' of undefined

### ISSUE THREAD

**Issue by johnnyignatov** [react-tools/react-table#770]
Uncaught (in promise) TypeError: Cannot read property 'columns' of undefined
    at methods.js:74
    at Array.forEach (<anonymous>)
    at ReactTable.getDataModel (methods.js:73)
    at ReactTable.componentWillMount (lifecycle.js:28)
    at vendor.js:39404
    at measureLifeCyclePerf (vendor.js:39132)
    at ReactCompositeComponentWrapper.performInitialMount (vendor.js:39403)
    at ReactCompositeComponentWrapper.mountComponent (vendor.js:39314)
    at Object.mountComponent (vendor.js:14969)
    at ReactDOMComponent.mountChildren (vendor.js:43793)
3vendor.js:14986 Uncaught (in promise) TypeError: Cannot read property 'getHostNode' of null
    at Object.getHostNode (vendor.js:14986)
    at ReactCompositeComponentWrapper.getHostNode (vendor.js:39440)
    at Object.getHostNode (vendor.js:14986)
    at Object.updateChildren (vendor.js:38978)
    at ReactDOMComponent._reconcilerUpdateChildren (vendor.js:43763)
    at ReactDOMComponent._updateChildren (vendor.js:43867)
    at ReactDOMComponent.updateChildren (vendor.js:43854)
    at ReactDOMComponent._updateDOMChildren (vendor.js:41020)
    at ReactDOMComponent.updateComponent (vendor.js:40838)
    at ReactDOMComponent.receiveComponent (vendor.js:40800)

version: ^6.5.3

This Error appeared suddenly, without any changes in my code

**Comment by TomFaulkner** [comment]
Would you be able to post the relevant code? I think I am having similar problems. The first row seems to have an undefined index. I've put in some checks to prevent crashes on an undefined column index in my example.

I've kind of worked the editable rows into the pivoting table with aggregation examples.

When this renders the aggregation math has been calculated correctly, but the first row doesn't have an index, so it won't have any values (other than the '---' I included) and changes aren't used in further calculations.

`import React from 'react';
import ReactTable from 'react-table';
import 'react-table/react-table.css';

const data = [{
  category: 'Cash and Equivalents',
  name: 'Cash',
  balanced: 64.02,
  baseValue: 26,
},
{
  category: 'Cash and Equivalents',
  name: 'Marketable Securities',
  balanced: 21.05,
  baseValue: 5,
},
{
  category: 'Cash and Equivalents',
  name: 'Marketable Securities',
  balanced: 121.05,
  baseValue: 9,
},
{
  category: 'Net Trade Receivables',
  balanced: 32.01,
  baseValue: 26,
}];

class ExcelObj extends React.Component {
  constructor(props) {
    super(props);
    this.renderEditable = this.renderEditable.bind(this);
    this.state = {
      data,
    };
  }

  renderEditable(cellInfo) {
    console.log('render editable: ', cellInfo);
    console.log('cellinfo', cellInfo.index, cellInfo.column.id);
    return (
      <div
        style={{ backgroundColor: '#fafafa' }}
        contentEditable
        suppressContentEditableWarning
        onBlur={(e) => {
          if (cellInfo.index) {
            console.log('successful blur cell', cellInfo);
            const dataCopy = [...this.state.data];
            dataCopy[cellInfo.index][cellInfo.column.id] = e.target.innerHTML;
            console.log('inner ', e.target.innerHTML);
            this.setState({ data: dataCopy });
            console.log('state:', this.state);
            // console.log('blur', e);
          }
          else {
            console.log('blur cell', cellInfo);
          }
        }}
        dangerouslySetInnerHTML={
          cellInfo.index
            ? { __html: this.state.data[cellInfo.index][cellInfo.column.id] }
            : { __html: '---' }
        }

      />
    );
  }

  render() {
    const columns = [
      {
        Header: 'Select',
      },
      {
        accessor: 'category',
      },
      {
        accessor: 'name',
      },
      {
        Header: 'Balanced',
        accessor: 'balanced',
        aggregate: balanced => balanced.reduce((a, b) => {
          console.log(a, b);
          return parseFloat(a) + parseFloat(b);
        }),
        Aggregated: row => <span><strong>{row.value}</strong></span>,
        Cell: this.renderEditable,
      },
      {
        Header: '% Base Value',
        accessor: 'baseValue',
        editable: true,
        Cell: this.renderEditable,
      },
    ];

    return (<ReactTable
      pivotBy={['category']}
      columns={columns}
      data={this.state.data}
    />);
  }
}
`

**Comment by TomFaulkner** [comment]
Would you be able to post the relevant code? I think I am having similar problems. The first row seems to have an undefined index. I've put in some checks to prevent crashes on an undefined column index in my example.

I've kind of worked the editable rows into the pivoting table with aggregation examples.

When this renders the aggregation math has been calculated correctly, but the first row doesn't have an index, so it won't have any values (other than the '---' I included) and changes aren't used in further calculations.


[index.txt](https://github.com/react-tools/react-table/files/1660984/index.txt)

**Comment by johnnyignatov** [comment]
@TomFaulkner can you please show me this part of your code?

**Comment by TomFaulkner** [comment]
@johnnyignatov Sure, here you go. I've edited a bit more, removing the dangerouslySetInnerHTML as well, so it will be somewhat different from the examples.

Also, you may have to remove the Semantic UI and Redux imports. But, it should be easy enough to strip those out.

[index.txt](https://github.com/react-tools/react-table/files/1664628/index.txt)

**Comment by gary-menzel** [comment]
FYI: Aggregated rows have no index because they are not real rows so cannot reference an index in the original data.
