### ISSUE TITLE
Question:  regarding Save/Restore of Expansions and Sorting

### ISSUE THREAD

**Issue by aldensc** [react-tools/react-table#771]
## What version of React-Table are you using?
Your bug may already be fixed in the latest release. Run `yarn upgrade react-table`!
6.7.4

## What bug are you experiencing, or what feature are you proposing?
We are looking at saving off the current expansions and sort order for tables.  To accomplish this, we need to look at the react-table's state.sorted, state.sortedData, and state.expanded.  I don't see methods provided to get at these.  These all contain indexed/keyed values, so we need to lookup the actual value to save/restore them.  It is possible that the index/keys could be altered when leaving and returning to the table (like adding/removing pivot data), so we need to use the actual data.  

- Is it safe to interrogate the mentioned state objects?  Some of the needed items under sortedData are prefixed with _ (like _subRows), which typically means it is private.  
- How subject to change are these?  
- Any thoughts of providing this type of functionality in the future?

Regards,
Scott Alden (IQVIA)i
scott.alden@quintilesims.com

## Use https://codesandbox.io/s/X6npLXPRW (by clicking the "Fork" button) to reproduce the issue.
N/A

## What are the steps to reproduce the issue?
N/A

**Comment by aldensc** [comment]
Clarification...

By saving the actual value, I mean for the pivot.  We can't save [0].  [0] may not point to the same expanded item if we add or delete certain data rows.  We need to save the text value of the expanded item.  For the sorts, we just need to save the state.sorted info, which is pretty straight forward.

**Comment by gary-menzel** [comment]
Yes - the _ variables are notiionally private but it is OK to consider them to be "read only".

Yes, the values are indexes to lines on the current page - if you want to save them you will have to translate them yourself as ReactTable does not know about external indexes.

**Comment by aldensc** [comment]
Thanks Gary.  Would be nice to have methods for accessing this data so any state format changes would not affect users using the data.  Regards.

**Comment by tannerlinsley** [comment]
Since this is a question of implementation we invite you to continue the conversation in the react tools slack organization. Thanks! https://react-chat-signup.herokuapp.com/
