### ISSUE TITLE
Don't pass illegal props to input component on selectTable HOC

### ISSUE THREAD

**Issue by nlucero** [react-tools/react-table#773]
I'm using a custom `Checkbox` component on my app that basically wraps the HTML checkbox input and adds some custom markup/CSS:

```
const Checkbox = ({ label, ...rest }) => (
  <label className="some-custom-style" htmlFor={rest.id}>
    <input type="checkbox" className="more-custom-style" {...rest} />
    {label}
  </label>
);
```

If I use that component as the `SelectInputComponent` on my table, it receives a `selectType` prop as you can see [here](https://github.com/react-tools/react-table/blob/f70d453caa81b263794b5e31329b5d1850882ba1/src/hoc/selectTable/index.js#L37).
Since my `Checkbox` component passes its props to the native `input` element, I get an error from React:

`Warning: React does not recognize the 'selectType' prop on a DOM element.`

Obvious solutions are:

1. Filter the `selectType` prop from the pass-through props
2. Don't pass the `selectType` prop to the component

I think this a very common use case and since `selectType` is a very `React-Table`-specific prop, it should not pass such prop if the `SelectInputComponent` is a custom component.

**Comment by gary-menzel** [comment]
3. remove the prop yourself and don't pass it in with lazy props (which is exactly what the `defaultSelectInputComponent` does in the code
