### ISSUE TITLE
Inconsistent parameters received on toggleSelection handler of selectTable HOC

### ISSUE THREAD

**Issue by nlucero** [react-tools/react-table#774]
Right now, if you use the default `input` component, the `toggleSelection` handler gets called with these parameters:

```
onClick={(e)=>{
  const { shiftKey } = e;
  e.stopPropagation();
  props.onClick(props.id, shiftKey, props.row);
}}
```

If you use a custom `SelectInputComponent`, the `toggleSelection` receives the `SyntheticEvent` object from `React`. So it makes it impossible to know, for example, which row was clicked.

I think both methods should receive the same arguments.

**Comment by nlucero** [comment]
One possible solution:

Wrap the call to `toggleSelection` [in this line](https://github.com/react-tools/react-table/blob/f70d453caa81b263794b5e31329b5d1850882ba1/src/hoc/selectTable/index.js#L36) with another function that passes the correct arguments in (same way it is being done on the default input component).

**Comment by gary-menzel** [comment]
Please read up on synthetic events in React. If you are building your own component you can turn it into a concrete event.  The Default input/checkbox uses the members directly (which are resolve to real values).

From the React doco:

> Note:
> 
> If you want to access the event properties in an asynchronous way, you should call event.persist() on the event, which will remove the synthetic event from the pool and allow references to the event to be retained by user code.
> 
>

**Comment by nlucero** [comment]
How do I access the row being clicked from the `SyntethicEvent` object then? If I use the default input component, the `row` prop comes in the third param: `props.onClick(props.id, shiftKey, props.row);` but I don't think you have access to that prop on the `SyntheticEvent`.

**Comment by gary-menzel** [comment]
You'll need to provide a mocked up example of your code.

This is the code that passes the props to the SelectInputComponent:
```
    rowSelector(row) {
      if(!row || !row.hasOwnProperty(this.props.keyField)) return null;
      const { toggleSelection, selectType, keyField } = this.props;
      const checked = this.props.isSelected(row[this.props.keyField]);
      const inputProps = 
      {
        checked,
        onClick: toggleSelection,
        selectType,
        id: row[keyField],
        row,
      }
      return React.createElement(this.props.SelectInputComponent,inputProps);
    }

```
Then, if you are building something else inside of that, then handling the event is something you have to do yourself.  The `row` is passed in the props to that component.

**Comment by nlucero** [comment]
I forked the codesandbox demo of the SelectTable HOC [here](https://codesandbox.io/s/740oxwvvvx)

I've added a render of the current selection at the bottom. As you can see it does not work, because on line 147 I'm passing in a custom Input component and then the `toggleSelection` handler stops receiving the expected parameters.

What I want to able to do is to access the same data `toggleSelection` when I'm using a custom Input component.

As you mentioned, the `row` prop is passed to the Input component. But is not useful in this scenario, as the `onClick` is handled on `toggleSelection` and not on the Input component.

**Comment by gary-menzel** [comment]
you get the data you are asking for in the `props`.

Add this line to your `render` just before you return and you will see the props there....

```
    console.log('props',this.props);
```
You have to replicate the functionality of the default component.  Here is the source code pasted (it is in the code)....
```
const defaultSelectInputComponent = (props) => {
  return (
    <input 
      type={props.selectType || 'checkbox'} 
      checked={props.checked} 
      onClick={(e)=>{
        const { shiftKey } = e;
        e.stopPropagation();
        props.onClick(props.id, shiftKey, props.row);
      }} 
      onChange={()=>{}}  
    />
  )
}
```

**Comment by nlucero** [comment]
Yeah, that works 👍 

Just as an opinion, it would be nice if the user wouldn't need to know how the HOC internally works in order to implement a custom Select Input component. Regardless of the Select Input component used on the table, the `toggleSelection` handler should receive the same parameters.

I will close this issue. Thanks for your help!
