### ISSUE TITLE
How to display the total amount of table data？

### ISSUE THREAD

**Issue by phypor** [react-tools/react-table#775]
## What version of React-Table are you using?
Your bug may already be fixed in the latest release. Run `yarn upgrade react-table`!
Place your version here...

## What bug are you experiencing, or what feature are you proposing?
Please include a detailed explanation here...

## Use https://codesandbox.io/s/X6npLXPRW (by clicking the "Fork" button) to reproduce the issue.
Then paste a link to your newly forked codesandbox here...

## What are the steps to reproduce the issue?
1. list the steps
2. to reproduce
3. the issue

**Comment by gary-menzel** [comment]
Your question is not clear.  You pass the data in so you have full control over it and would already know how many rows and columns there are.  If you mean you want a count of what is filtered then please look at the FAQ section in the Wiki here. There is an item regarding accessing the internal data state (read only).
