### ISSUE TITLE
Pivot Aggregate row below expanded contents

### ISSUE THREAD

**Issue by TomFaulkner** [react-tools/react-table#777]
## What version of React-Table are you using?
6.7.6

Really happy with React-Table so far. Our team is likely to use it quite a bit for our project. Thank you for this wonderful library.

How would I go about having the pivot expansion expand upwards instead of downwards?

That is, in expanded state, row 1 and row 2 would be above the aggregate row.

**Comment by gary-menzel** [comment]
I know we spoke about this on the #react-table Slack channel.

As discussed, ReactTable doesn't provide that functionality (at least not in this version or in the near future - and even then only if there was a big demand for it).

So, I'll close this for now.
