### ISSUE TITLE
highlight a full row

### ISSUE THREAD

**Issue by Lisss13** [react-tools/react-table#781]
How can I highlight a full row if a certain cell has been changed using react table?

**Comment by gary-menzel** [comment]
Provide a `getTrProps` handler and use your change detection to set a `style` or a `className`.

There's an example in the doco.

As far as detecting the change - that is really up to you as to how that happens.

While it is not highlighting a row, this example shows something similar in highlighting a cell....

https://codesandbox.io/s/wkxolyrpo5

**Comment by Lisss13** [comment]
Am i able to detect that using state, comparing previous and current state, similarly to shouldComponentUpdate()?

**Comment by gary-menzel** [comment]
I am not sure what you mean.  If your data is changing and you need to highlight a line, the simplest way is to do what that example does and add some type of mechanism to each row to show that it has changed.  It's really not related to `shouldComponentUpdate`.

Some external factor will happen that will change a row in your table.  To be able to change the row colour the row needs to know about the change. In the example I posted, it is a "cell" that looks for the change and returns an appropriate style change.  You can work that into changing the colour for a "row" instead.  The controlling factor in the example is a change in the current price against the previous price.  Maybe in your code you set a flag.

You could also have some other state that used a row ID (from your data) and told you if something was different.

But ReactTable doesn't have any callback that says "this row has changed" - it doesn't really care as React decides what to refresh based on the keys generated for the rows and cells.
