### ISSUE TITLE
how does minWidth work exactly?

### ISSUE THREAD

**Issue by hex-fire** [react-tools/react-table#783]
## What version of React-Table are you using?
6.5.1

## What bug are you experiencing, or what feature are you proposing?
When I set minWidth to a column, I expect it is really the minimum width for this column but it's not. I could still resize this column to any width less than the value of minWidth.

https://codesandbox.io/s/6z6qyjrpxr

## What are the steps to reproduce the issue?
1. resize the first name column
2. the column can be resized to a very small width while its minWidth is set to 200

**Comment by DamianFekete** [comment]
The width won't go less than 200px if you resize the browser window (or the container of the react-table), not if you manually resize one column.

**Comment by gary-menzel** [comment]
@DamianFekete is correct.  Closing now.

**Comment by jaybahuguna** [comment]
how to remove element.sty;e {min-width: 900px;} from "react-table": "6.10.0",
