### ISSUE TITLE
way to filter multiple columns?

### ISSUE THREAD

**Issue by iamglenbacs** [react-tools/react-table#784]
on the https://react-table.js.org/#/story/custom-filtering sample, the search is below each header, we want to implement a search feature, but the input type will be outside of the table, and will filter on each header, have no idea how to start, help?

**Comment by gary-menzel** [comment]
Use the `filtered` prop. There is a clear example of what it looks like in the doco....
```
  filtered={[{ // the current filters model
    id: 'lastName',
    value: 'linsley'
  }]}
```
`id` will be the same as the `accessor` if you are just using plain strings for the accessor - otherwise whatever `id` you give your columns.
