### ISSUE TITLE
Tree Table (HOC) incorrect rendering

### ISSUE THREAD

**Issue by xxdeveloper** [react-tools/react-table#787]
## What version of React-Table are you using?
v6.7.6

## What bug are you experiencing, or what feature are you proposing?
Incorrect css rendering of table rows. 

## What are the steps to reproduce the issue?
1. Reproduced even by the example https://react-table.js.org/#/story/tree-table-hoc

Reproduced when the screen width is less than the length of the table row
(red square on the image)
![screen shot 2018-02-03 at 15 48 26](https://user-images.githubusercontent.com/7071125/35767296-c465ba42-08fa-11e8-95ab-52fac4b5bf7e.png)

**Comment by xxdeveloper** [comment]
Update: 
It seems this is a good temporary solution for me, but tests are needed.
```
.ReactTable .rt-tbody {
  overflow-x: hidden! Important;
  width: 100%;
  display: inline-table;
}

.ReactTable .rt-thead .rt-tr {
  display: flex;
}

.ReactTable .rt-thead {
  display: inline-table;
  width: 100%;
}
```

**Comment by tannerlinsley** [comment]
We invite you to reopen this issue with more information or continue the conversation in the react tools slack organization. Thanks! https://react-chat-signup.herokuapp.com/
