### ISSUE TITLE
freeze column(s) while scrolling horizontally

### ISSUE THREAD

**Issue by jacaetevha** [react-tools/react-table#788]
Would you be able to add a property to freeze a column or columns on the left while scrolling horizontally? I'd be happy to take a crack at it, but not really quite sure where to start.

**Comment by gary-menzel** [comment]
Several people have have attempted this (it is spread throughout the closed issue here). It has been determined that ReactTable needs a re-write to accomplish this feature.

PRs are welcome - but must maintain backwards compatibility with the current version.  Any significant changes would have to be rolled into a brand new major version.
