### ISSUE TITLE
Question: Way to do filterable header

### ISSUE THREAD

**Issue by NadavGab** [react-tools/react-table#789]
Is there a way to make the header to be header AND filter?
Explanation: I want to have a header that have magnifying glass icon, with onClick event on it. when clicking on the magnifying glass the header will replaced with a filter field.

![image](https://user-images.githubusercontent.com/31407663/35776475-e86adf98-09a5-11e8-8f4b-72082c715a7a.png)

![image](https://user-images.githubusercontent.com/31407663/35776554-6efb93a8-09a7-11e8-89e6-2130faff7398.png)

**Comment by gary-menzel** [comment]
You can do anything you like if you override the components.

However, the filter row is under the header row and there is an example in documentation around a customer filter that has a drop-down list.

https://react-table.js.org/#/story/custom-filtering

**Comment by NadavGab** [comment]
Thanks Gary, but maybe I didn't explained my self well..
I don't have problem to to a drop-down to the column header, my problem starts when I am trying to connect between the Header drop-down to the custom filter I made.

This is my code I have to the column:
```
 {
    Header: 'Platform',
    accessor: 'platformName',
    maxWidth: 200,
    filterable: true,
    filterMethod: (selected, row) => {
      if (selected.value.indexOf('') > -1) {
        return true;
      }

      return selected.value.indexOf(row[selected.id]) > -1;
    },
    Filter: ({ filter, onChange }) => (
      <FilterInnerComponent
        onChange={(event) => onChange(event.filterType)}
        style={{ width: '100%', color: filter ? '#b08c8c' : null }}
        value={filter ? filter.value : ''}
      >
        <MenuItem value={''} primaryText="All" />
        {createSelectItems(data, 'platformName')}
      </FilterInnerComponent>
    ),
  }
```

But if I'll do something like that:
```
 {
    Header: ({ filter, onChange }) => (
      <FilterInnerComponent
        onChange={(event) => onChange(event.filterType)}
        style={{ width: '100%', color: filter ? '#b08c8c' : null }}
        value={filter ? filter.value : ''}
      >
        <MenuItem value={''} primaryText="All" />
        {createSelectItems(data, 'platformName')}
      </FilterInnerComponent>
    ),
    accessor: 'platformName',
    maxWidth: 200,
    filterable: true,
    filterMethod: (selected, row) => {
      if (selected.value.indexOf('') > -1) {
        return true;
      }

      return selected.value.indexOf(row[selected.id]) > -1;
    },
  }
```

The filter and onChange parameters obviously are not passed to the Header, and also the filterMethod is not "talikng" with the Header.

**Comment by gary-menzel** [comment]
ReactTable is not set up that way.  If you want to do something along those lines then you will need to find a different way to pass information.  The layout architecture is that the Filter is rendered underneath the Header in it's own row.  To change that you will need to completely replace the `TheadComponent` (as well as a number of other related components) and I don't think the effort will be worth it.

You can check on the #react-table Slack channel (badge on the README in the doco) but I am fairly sure no-one else has done anything like that.

**Comment by NadavGab** [comment]
Thank you Gary, I'll try to rewrite the TheadComponent.
