### ISSUE TITLE
How to fully encapsulate a filter in a separated Component?

### ISSUE THREAD

**Issue by brunodymios** [react-tools/react-table#790]
According to https://react-table.js.org/#/story/custom-filtering, in order to have a custom filter (both UI and logic) it is necessary to:

- specify the `Filter `attribute for the column that will have the custom filter
- specify for the same column the `filterMethod `attribute, with the function containing the filtering logic

The UI from the component specified in Filter must call the onChange function passed as a prop in order to let ReactTable perform the filtering.

The question is: how to create a component that includes **both UI and filterMethod logic outside the ReactTable**? I'm thinking about the definition of some utility filters to be re-used whenever they are needed, such as "NumberRangeFilter" or "DateRangeFilter".

Without such possibility, the only way that I see to reuse code is to copy&paste it for each target column.

**Comment by gary-menzel** [comment]
Firstly, the examples are trying to compact everything into one place so it is easy to see how all the options behave.  They are not "best practice" or even "good" React coding (as such).  They are meant to teach how the API passes params and props around.

So...

One way is to have a function that returns an object with the `Filter` and `filterMethod` as members and then use the spread operator to inject those into each column definition where you want to reuse that pair.
```
function sharedFilter() {
  return {
    Filter: YourReactFilterComponent,
    filterMethod: yourFilterMethod,
    // any other relevant props you might need - e.g. style
  }
}
// then....
columns = [
  {
    // column definition gets the props from the object from the function
    ...sharedFilter()
  }
]
```
Or you could simply just put calls to the `Component` and `function` in by hand...
```
columns = [
  {
    // column definition gets the props from the object from the function
    Filter: YourReactFilterComponent,
    filterMethod: sharedFilter,
  }
]
```
The only downside of the 2nd suggestion is that you could possibly mix in the wrong `Filter` and `filterMethod`.  However, if you name them correctly, it is likely to be obvious.

**Comment by tannerlinsley** [comment]
Since this is a question of implementation we invite you to continue the conversation in the react tools slack organization. Thanks! https://react-chat-signup.herokuapp.com/
