### ISSUE TITLE
Subcomponent example is wrong

### ISSUE THREAD

**Issue by hamdibayhan** [react-tools/react-table#793]
I am trying subcomponent feature example in [here link](https://react-table.js.org/#/story/sub-components) but subcomponent is not containing the children from Utils, subcomponent is containing the first `defaultPageSize` amount of data. Why? I think this is wrong.

**Comment by hamdibayhan** [comment]
I think subcomponent's data should be like the below:

`data={data[row.index].children}`

**Comment by gary-menzel** [comment]
I don't really understand what you mean.  I cannot see any reference to Utils in the subcomponent in that example.

I am using SubComponent extensively and it works as expected (the rowInfo property is sent in as the props and I can then further process or use the data from that row).

NOTE: it is only an example of how props are passed and consumed, it is not a "real world" example of how it might be used.

**Comment by hamdibayhan** [comment]
@gary-menzel Actually this is just a suggest. Title is wrong, it is my mistake because I wanted to access the children data but I understood how to I access the children data later. I think subcomponents should shown the children in this example.
