### ISSUE TITLE
Tree view with parent column

### ISSUE THREAD

**Issue by torava** [react-tools/react-table#794]
React-table is missing one important feature. I would like to present my flat data in a tree view similar to file managers. Each row has a parent column from which the component could tell how to present data in a tree. If react-table can be configured to this it should be mentioned in documentation. Data could be also prepared to have nested children if it helps the implementation.

**Comment by gary-menzel** [comment]
Did you check the doco for `treeTableHOC` ?

Also, it is possible to use the pivot functionality with an `Aggregated` component to make it work more like a Tree.

**Comment by gary-menzel** [comment]
make sure you are using V 6.7.6

**Comment by torava** [comment]
I have checked documentation and it doesn't answer how tree can be infinitely nested by one parent column.

Data like this

[
  {
    id: 1,
    name: 'Robert Darwin',
    parent: null
  },
  {
    id: 2,
    name: 'Erasmus Darwin',
    parent: 1
  },
  {
    id: 3,
    name: 'Anne Darwin',
    parent: 1
  },
  {
    id: 4,
    name: 'Robert Waring Darwin',
    parent: 2
  },
  {
    id: 5,
    name: 'Charles Robert Darwin',
    parent: 4
  }
]

Will be presented like this.

- Robert Darwin
-- Erasmus Darwin
--- Robet Waring Darwin
---- Charles Robert Darwin
-- Anne Darwin
