### ISSUE TITLE
Please allow developer to overwrite styles

### ISSUE THREAD

**Issue by S3ak** [react-tools/react-table#795]
In react-table/src/index.js
```
      return (
        <ThComponent
          key={`${i}-${column.id}`}
          className={classnames(classes)}
          style={{
            ...styles,
            ...flexStyles,
          }}
          {...rest}
        >
          {_.normalizeComponent(column.Header, {
            data: sortedData,
            column,
          })}
        </ThComponent>
      )
```
Please put the *styles* spread after the *flexStyles* spread so that the developer can style flex css property. I trying to make the columns responsive but cannot overwrite the flex property

**Comment by gary-menzel** [comment]
This is core to the way ReactTable works.  It won't be changed in the current version because then there would be a lot of broken table layout.  Sorry.

**Comment by tannerlinsley** [comment]
Correct. This would allow the developer to break the core functionality of the table. We'll keep this in mind for the next version though.
