### ISSUE TITLE
State Bleedthrough with multiple ReactTable components

### ISSUE THREAD

**Issue by nkrul** [react-tools/react-table#796]
React-Table v. 6.7.6 :
With multiple ReactTable components defined, but only one visible at a time there is state bleedthrough.

Worked Example:
https://codesandbox.io/s/n39jj77nlj

Original project:
`git clone https://github.com/kncept/junit-reporter && cd junit-reporter && ./gradlew reportOnTestData`
View the generated html (file location is output as text)

With multiple ReactTable components defined, but hidden in a tab, there is... interesting... state bleedthrough.

Observed bugs:

- switching to a tab with a subcomponent defined adds the subcomponent toggle, but the toggle stays when changing tabs again, even if it was previously absent from a table. The presence/absence of the expander remapping in the headers doesn't change the toggle being present, but only changes the style for the table its defined for.
- The width of columns sharing the same name stays between tables as well.

**Comment by nkrul** [comment]
Bleed through also happens with pageSizeOptions and defaultPageSize... I suspect its a fair chunk of state.

**Comment by tannerlinsley** [comment]
Very interesting. I'll look into this. Probably needs some cleanup in the componentWillRecieveProps area.

**Comment by tannerlinsley** [comment]
Closing due to issue age. If you think this issue needs to be reopened, please check the latest version of React-Table for the issue once more and reopen if appropriate. Thanks!

**Comment by nkrul** [comment]
Hi.
Updated https://codesandbox.io/s/r0x89pkjro with the latest versions of react and react-table.
The state bleedthrough is unchanged.
