### ISSUE TITLE
Pivot with objects

### ISSUE THREAD

**Issue by Goatfried** [react-tools/react-table#798]
Hello together,
I would like to use the pivot feature on a column of objects. As far as I see, this is only possible for scalar values currently, but I think it would be a nice addition without to much trouble.

In my case data looks roughly like this
```javascript
[ {
	id: 1,
	itemId: 123,
	quantiy: 5,
	order: {
		id: 1,
		buyer: "Some customer",
		priority: 1
	}
},
{
	id: 3,
	itemId: 456
	seller: 2,
	order: {
		id: 1,
		buyer: "Some customer",
		priority: 9
	}
}]
```

Now, I'd like to setup a column like this:
```javascript
{
	accessor: "order",
	Cell: ({value}) => <Order order={value} />,
}
```

This works fine as long as no pivoting is done by column order. If pivoting is done, the object will be cast to a string and don't receive the proper value anymore.

I haven't looked into the code yet, how pivoting is done exactly, but I'd assume, that the usage of a Map could allow pivoting by any type of value. The other way would be to allow a custom function that return a value to pivot by.

To solve my issue, I'll connect some store and pass the id down, but it seems a bit bloated.

**Comment by gary-menzel** [comment]
The pivot implementation is not that simple to change.  There is a notional plan to extract it as a separate layer in a future version.

I am not totally sure what you are trying to do but, you can use a function as an accessor to return anything you like from a "data" perspective.

**Comment by tannerlinsley** [comment]
We'll keep this in mind for future versions.
