### ISSUE TITLE
Is there a localization API for the Next/Previous buttons? 

### ISSUE THREAD

**Issue by SigalGivati** [react-tools/react-table#802]
## What version of React-Table are you using?
Your bug may already be fixed in the latest release. Run `yarn upgrade react-table`!
6.6.0

## What bug are you experiencing, or what feature are you proposing?
Localization API for all text in the elements. 

I'm looking for an API to localize the text on the different elements. Is there any, or should I implement it myself by targeting the elements?

**Comment by mikdatdogru** [comment]
+1

**Comment by gary-menzel** [comment]
It's in the doco....
```
  // Text
  previousText: 'Previous',
  nextText: 'Next',
  loadingText: 'Loading...',
  noDataText: 'No rows found',
  pageText: 'Page',
  ofText: 'of',
  rowsText: 'rows',
```

**Comment by timothydowd** [comment]
how to get to button style?
