### ISSUE TITLE
How to  an "Export to csv/xls" button to react-table?

### ISSUE THREAD

**Issue by AjayZinngg** [react-tools/react-table#804]
## What version of React-Table are you using?
Your bug may already be fixed in the latest release. Run `yarn upgrade react-table`!

## What bug are you experiencing, or what feature are you proposing?
An export to csv/xls button
## Use https://codesandbox.io/s/X6npLXPRW (by clicking the "Fork" button) to reproduce the issue.
Then paste a link to your newly forked codesandbox here...

## What are the steps to reproduce the issue?
1.Create a react table in your component and add an export to csv /xls button.

**Comment by gary-menzel** [comment]
Please read the FAQ here in github. There is an item in there. You have to read the data and export it yourself.  There is no built in functionality for this.

**Comment by AjayZinngg** [comment]
Alright

**Comment by nicogreenarry** [comment]
> Please read the FAQ here in github

Where is that? I don't see an FAQs section.
