### ISSUE TITLE
getTrProps rowInfo.index

### ISSUE THREAD

**Issue by junbinku** [react-tools/react-table#805]
While I was implementing some hard coded dataset to the table I realised there were some issues or maybe was implemented that way for the use of rowInfo.index in getTrProps.

Issue:
- rowInfo.index will show up an issue quoted 'index is undefined', if only two rows of data is implemented or less than 10
- Dataset in the table has to be exact 10 rows to not get the error 

```

  var tempObj = [{time: '09:22:10', id: '1', event: 30}, {time: '09:22:10', id: '1', event: 30},
                    {time: '09:22:10', id: '1', event: 30}, {time: '09:22:10', id: '1', event: 30},
                    {time: '09:22:10', id: '1', event: 30}, {time: '09:22:10', id: '1', event: 30},
                    {time: '09:22:10', id: '1', event: 30}, {time: '09:22:10', id: '1', event: 30},
                    {time: '09:22:10', id: '1', event: 30}, {time: '09:22:10', id: '1', event: 30}
                  ]

    var labelObj = [{Header: 'Time', accessor: 'time'},
                  {Header: 'Account ID', accessor: 'id'},
                {Header: 'Events', accessor: 'event'}]
```

This above is the dataset I had which I ran in the constructor. 

Conclusion:
- react table could require a full set row of data or a change in defaultPageSize may be an option

**Comment by gary-menzel** [comment]
You need to check for the existence of `rowInfo` it is also used in the header and footer (which don't have rows).

**Comment by junbinku** [comment]
@gary-menzel I don't think it has to do with the header and footer. 

if you do a console.log(rowInfo.index), you will be expected to get a list from 0 to 9 printed separately. I had 10 rows set as default page size. So it didn't count the header nor the footer.

**Comment by gary-menzel** [comment]
If you think there is an issue, please submit a codesandbox.io or stackblitz.com example of the issue so the code can be properly reviewed.

ReactTable is used by a lot of people I do know that the `rowInfo` can be sometimes `null` so you have to check it before trying to use it (as I already explained).
