### ISSUE TITLE
how to add hide and show column like in ui-grid have ? 

### ISSUE THREAD

**Issue by gowthamdev** [react-tools/react-table#807]
## What version of React-Table are you using?
Your bug may already be fixed in the latest release. Run `yarn upgrade react-table`!
Place your version here...

## What bug are you experiencing, or what feature are you proposing?
Please include a detailed explanation here...

## Use https://codesandbox.io/s/X6npLXPRW (by clicking the "Fork" button) to reproduce the issue.
Then paste a link to your newly forked codesandbox here...

## What are the steps to reproduce the issue?
1. list the steps
2. to reproduce
3. the issue

**Comment by gary-menzel** [comment]
The column definitions have a flag.  You have to implement this yourself.  Please check the documentation. If you have implementation questions please take them to #react-table on Slack (badge at the top of the README in the doco). Thanks.
