### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by atanasster** [react-tools/react-table#810]
Hi guys,
Great component, very flexible.

I am adapting it for https://github.com/grommet/grommet v2 with styled-components and also added some keyboard handling (Home/End, PageUp/PageDown, Arrows) - still testing it out.
Would be happy to contribute back, but not sure if this is in your plans as it uses another UI library that already has flex box. 
Source code: https://github.com/atanasster/crypto-grommet/tree/master/src/components/table
Some running examples of ReactTable: 
https://crypto-grommet.herokuapp.com/exchanges
https://crypto-grommet.herokuapp.com/coins

Thanks again for the great job and let me know what I should do.

**Comment by gary-menzel** [comment]
I think you have managed to understand the "power" of ReactTable.  It can be used stand-alone but the best way to use it is to extend it using React mechanisms to take advantage of the underlying lightweight architecture.

I think, for now, that is probably the best way to leave it.  However, there has been discussion about a re-write of ReactTable using the types of techniques you have employed so I hope you will keep watching the ReactTable repo and maybe contribute.  I am sure @tannerlinsley would be interested in seeing these ideas.

I'll close this (but only to keep the issue register clean).
