### ISSUE TITLE
Full cell info on hover

### ISSUE THREAD

**Issue by yannickneemaa** [react-tools/react-table#813]
version of React-Table are you using : 6.7.6

Is it possible, if some of my cells have long content, to use a fixed column width, and to have the full content on hover (with a tooltip or something else...).

Or if you have this use case, how do you solve it ?

Thanks !

**Comment by amlcodes** [comment]
Did you get this going? I'm working on this now

**Comment by mrruby** [comment]
Any updates?

**Comment by mrubin** [comment]
This would be great. Along the same lines, is there any way to have cell content not get truncated (with a "...") but go multi-line or somehow show the full content?

**Comment by amlcodes** [comment]
So I am already working with React.Semantic UI so their Popup on React Tables column definitions ```Cell: props => {
                      return (
                        <Popup
                          trigger={<div>{props.original.Name}</div>}
                          content={props.original.Name}
                          inverted
                        />
                      );
                    }``` 
like that is working for me. I would mess with overflow on tr div in css, I removed overflow ellipsis already

**Comment by JonathanKolnik** [comment]
+1

**Comment by vmengh** [comment]
In reacttable tooltip or hover text on a particular column or cell can also be achieved using the span tag with title attribute.
example below -
const columns = [
 {
        Header: "Message",
        accessor: "message",
        Cell: row => <div><span title={row.value}>{row.value}</span></div>
      }
];

**Comment by ivanchoff** [comment]
title is an option but what if it is required add more complex information in tooltip?, that is my case :(

**Comment by c-cognizant-nchittur** [comment]
Can we get ellipses working for situation like this ? Can anyone help on ellipses code.

**Comment by ariel262626** [comment]
> In reacttable tooltip or hover text on a particular column or cell can also be achieved using the span tag with title attribute.
> example below -
> 
> ```
> const columns = [
>  {
>         Header: "Message",
>         accessor: "message",
>         Cell: row => <div><span title={row.value}>{row.value}</span></div>
>       }
> ];
> ```

hi thanks, works for me. 
how can i design that tooltip?

**Comment by javed24** [comment]
> In reacttable tooltip or hover text on a particular column or cell can also be achieved using the span tag with title attribute.
> example below -
> 
> ```
> const columns = [
>  {
>         Header: "Message",
>         accessor: "message",
>         Cell: row => <div><span title={row.value}>{row.value}</span></div>
>       }
> ];
> ```

does this still work? I'm doing the following to get a tooltip when hovering over the entire row, but it's not rendering the tooltip.

```
Cell: (row) => <div><span title={row.value}>{row.value}</span></div>
```

**Comment by richewinqred** [comment]
Anyone get a tooltip to render in cell working?
