### ISSUE TITLE
Async table mockup link is dead

### ISSUE THREAD

**Issue by poohsen** [react-tools/react-table#815]
## What version of React-Table are you using?
Your bug may already be fixed in the latest release. Run `yarn upgrade react-table`!
Place your version here...

## What bug are you experiencing, or what feature are you proposing?
Async table mockup link in the readme.md is dead and I couldn't find the `ServerSide.js` file anywhere else I would've submitted a PR.

## Use https://codesandbox.io/s/X6npLXPRW (by clicking the "Fork" button) to reproduce the issue.
Then paste a link to your newly forked codesandbox here...

## What are the steps to reproduce the issue?
Click on "async table mockup" in the readme.md.

**Comment by gary-menzel** [comment]
But the link in the sidebar to a similar example is not (it's a low priority to fix the docs).
