### ISSUE TITLE
Using custom cell with custom props produces "Unknown prop `someFunc` on <div> tag"

### ISSUE THREAD

**Issue by keirlawson** [react-tools/react-table#816]
## What version of React-Table are you using?
6.7.6

## What bug are you experiencing, or what feature are you proposing?
I am trying to combine a custom cell component with custom props, per the documentation here: https://react-table.js.org/#custom-props. Whilst the code works when first rendering I see a warning from React, `Unknown prop 'someFunc' on <div> tag`

## Use https://codesandbox.io/s/X6npLXPRW (by clicking the "Fork" button) to reproduce the issue.
https://codesandbox.io/s/r5n96yvwnm

## What are the steps to reproduce the issue?
1. Create a custom cell
2. pass custom prop to the cell that is not a standard DOM attribute
3. note warning in the console

**Comment by gary-menzel** [comment]
That is because the props are applied (lazy ...)  to a `div` that is wrapped around what your `Cell` component produces (that is the "cell" is the content inside the "grid").  You can either wear the warning or you can provide a `TdComponent` (which is actually when the props are applied) to extra the unknown prop.

This is not a ReactTable but a React thing (doing type checking on the `div` props).

**Comment by gary-menzel** [comment]
In other words, it looks more like this.....
```
<div {...allTheProps}>
  <MyCell ... />
</div>
```

**Comment by gary-menzel** [comment]
The `div` is generated by the `TdComponent` function (which is made from a call to `makeTemplateComponent` in the utilities package - which in turn is just a very light wrapped to constrain the grid).

**Comment by keirlawson** [comment]
Ok, it feels like this is probably an issue which react-table could solve, ie by using a non-native component wrapping a div rather than a div directly in `makeTemplateComponent`?

**Comment by gary-menzel** [comment]
Probably not.  It needs to be "something" and a `div` is the most common block element.

You can always write the `Cell` handler as a function that returns your custom component....
```
Cell: (rowInfo) => <MyCell rowInfo={rowInfo} someFunction={ () => alert("clicked") } />
```
And then you don't need to implement a `getProps` at all.

Your custom function is really meant for your custom cell renderer (and not for the wrapping component - whatever that happens to be).

**Comment by gary-menzel** [comment]
Could it be written a different way?  Yes, probably.  But that is how Tanner designed it.  There's been talk over a complete rewrite - maybe it will work different in the next major update.  However, it would be too big a change for the current major version.
