### ISSUE TITLE
Expected scroll to be moved to top on click of next, but still they are not.

### ISSUE THREAD

**Issue by srininmkl** [react-tools/react-table#821]
## What version of React-Table are you using?
Your bug may already be fixed in the latest release. Run `yarn upgrade react-table`!
6.7.4

## What bug are you experiencing, or what feature are you proposing?
I have 100 rows, i have chose 25 rows per page, now I have scrolled down to end of 1st page, now clicking next, expected the scroll will be moved to top to 26th element but it is not.
 

## What are the steps to reproduce the issue?
1. render table with 100 rows
2. choose 25 rows pr page
3. scroll down to end of 1st page
4. click next

**Comment by gary-menzel** [comment]
The vertical scroll was a late add-on and not strongly supported.  If you want that behaviour you will have to look into a way to implement it.

**Comment by srininmkl** [comment]
i have achieved it by adding these following lines 
//For Next button 
document.getElementsByClassName("-next")[0].getElementsByClassName("-btn")[0].addEventListener("click", function () {
      document.getElementsByClassName("rt-tbody")[0].scrollTop = 0;
    });
//For Previous button 
    document.getElementsByClassName("-previous")[0].getElementsByClassName("-btn")[0].addEventListener("click", function () {
      document.getElementsByClassName("rt-tbody")[0].scrollTop = 0;
    });
