### ISSUE TITLE
Ids for filtering

### ISSUE THREAD

**Issue by harkinj** [react-tools/react-table#823]
Is there a way to specify unique ids for the filtering fields? We are trying to use Codecept for acceptance testing which allows us to specify a unique id for a field we want to fill in - e.g I.fillField('#NameID', 'SearchName').

**Comment by gary-menzel** [comment]
No. There is no support for something like this.  In general React doesn't really use and `id` for any elements.  You could re-write the filter components to be something you generate yourself but then you would be adding the effort of re-writing things just to support the testing.

**Comment by harkinj** [comment]
Thanks for the info and the quick response.
