### ISSUE TITLE
Documentation regarding striping and highlighting

### ISSUE THREAD

**Issue by cerealcoder** [react-tools/react-table#825]
## What version of React-Table are you using?
`6.7.6`

## What bug are you experiencing, or what feature are you proposing?
The documentation regarding [striping and highlighting](https://www.npmjs.com/package/react-table#classes) of rows is very thin; are you willing to provide some guidance in this area? That is, in order to introduce striping and/or hover-over highlighting, what is the developer responsible for doing?

**Comment by gary-menzel** [comment]
```
<ReactTable className="-striped -highlight" .... />
```
There's not much else to say.  If you mean the CSS itself - you can just override that to be whatever you want (just follow how it is done in the provided .css file).

**Comment by cerealcoder** [comment]
Ah, I see now. It was the indefinite article "a" that appears in this sentence that was fooling me:
> Adding a -striped className to ReactTable will slightly color odd numbered rows for legibility

I thought I had to create a class named `someClass-striped` in order to implement this feature.
