### ISSUE TITLE
Duplicate row keys in causing problems with preact

### ISSUE THREAD

**Issue by rantecki** [react-tools/react-table#827]
## What version of React-Table are you using?
6.7.6

## What bug are you experiencing, or what feature are you proposing?
Initial render on page load is fine, but after any data updates the table goes crazy.  I spent quite some time trying to narrow this down, and it appears to be related to my use of Preact and the presence of duplicate key props in table rows.

Pad rows seem to use integer indexed keys, as do regular page rows.  The first data row will have a key of "0" and the first pad row will also have a key of "0".  I'm not sure if this situation is considered valid in standard React, but React certainly appears to handle this situation a bit more elegantly than does Preact.

## Use https://codesandbox.io/s/X6npLXPRW (by clicking the "Fork" button) to reproduce the issue.
Example at https://codesandbox.io/s/3qw8knlr7p

## What are the steps to reproduce the issue?
1. Click the "Add a dummy task" button in the example above.  The problem will be obvious.

A trivial workaround to fix this problem is to simply prepend a prefix to the key used in `makePadRow()`.  I've verified that this does indeed fix the problem.

E.g.

``` js
    const makePadRow = (row, i) => {
    ...
      return (
        <TrGroupComponent key={`pad-${i}`} {...trGroupProps}>
        ...
        </TrGroupComponent>
      )
    }
```

**Comment by gary-menzel** [comment]
I don't think any of the contributors who have worked on the tool use Preact.

However, if you are prepared to submit a PR then I am sure Tanner would be happy to review and merge it as long as it is backward compatible with the existing React behaviour.

**Comment by tannerlinsley** [comment]
Closing due to issue age. If you think this issue needs to be reopened, please check the latest version of React-Table for the issue once more and reopen if appropriate. Thanks!

**Comment by rheajt** [comment]
I think this is the same issue I am having. Using preact with react-table v6.8.6. Sadly, the shared sandbox above is no longer working so I can't verify that I am having the same trouble. Should I open a new issue?
