### ISSUE TITLE
sub component to right side

### ISSUE THREAD

**Issue by ssad9985** [react-tools/react-table#829]
I am using react table version 6.8.0.

I am using subcomponent property of react table. I want to have the subcomponent arrow as the last column of each row in table. By default it is coming as first. 

Please help me

**Comment by gary-menzel** [comment]
There is an example in the doco of moving the Expander into a different column (titled "Custom Expander Position").

Please re-check the doco. If you have any implementation issues take them to the #react-table Slack channel (badge at the top of the README in the doco). Thanks.
