### ISSUE TITLE
Fixed columns as an option

### ISSUE THREAD

**Issue by LittleHendrix** [react-tools/react-table#830]
## What version of React-Table are you using?
v6.7.6

## What bug are you experiencing, or what feature are you proposing?
Not a bug, a feature request maybe?

Hi there,

Great table solution first of all. I'm just wondering if there's an official way to set columns as fixed (to left or right)? I've managed to pin the 1st column using `position: sticky; left: 0;`. However, when using this method to add a 2nd fixed column, I would have to give a static value for the `left` property. It is okay until I resize the 'fixed' columns, and everything gets messed up. 

I assume this is not currently supported. Is there a way to tap into column resize event so maybe somehow I can update the 2nd 'fixed' columns positions?

Thanks!

Regards

**Comment by gary-menzel** [comment]
There is no support for this in the current version and there are no plans for a major version upgrade in the near future. Several people have tried to implement this in the current architecture but were never able to overcome all the issues.

If this is a requirement for your use-case then you will need a different package.

**Comment by LittleHendrix** [comment]
@gary-menzel  thanks for the quickly reply Gary. Totally understand that is not a supported feature currently. Just wondering if you could help me on the `onColumnResize` event at all? I think I could get a workaround that would fix my current issue, albeit not a 'real' solution. Thanks again!

**Comment by gary-menzel** [comment]
The doco lists `onResizedChange` - that is the only place where there is a resize event - but it is triggered by the user.

**Comment by LittleHendrix** [comment]
@gary-menzel  yes, I want to update some CSS values when a user resizes a particular column for example. I will look into this. Thanks again!
