### ISSUE TITLE
Highlight Row on checkbox selection

### ISSUE THREAD

**Issue by ssad9985** [react-tools/react-table#832]
version of table 6.8.0

Hi,

I am using react table as checkbox table to have checkbox in every row. I want to highlight the row when the corresponding checkbox is checked, and revert back to original color when unchecked. 

Also is it possible to change the checkbox UI to some 'tick' image on selecting and revert on deselecting

Please help me

**Comment by gary-menzel** [comment]
The selectTableHOC is just an example.  You can copy it and change it in your code as much as you like.  To change highlight or any prop on a row use `getTrProps`.
