### ISSUE TITLE
How to specify colspan in a row ?

### ISSUE THREAD

**Issue by ViswanathLekshmanan** [react-tools/react-table#833]
## What version of React-Table are you using?
Your bug may already be fixed in the latest release. Run `yarn upgrade react-table`!
v6.7.6

## What bug are you experiencing, or what feature are you proposing?
Unable to specify colspan in a row. Need to specify a colspan of 4 in a 7 column row.

## What are the steps to reproduce the issue?
NA

**Comment by gary-menzel** [comment]
Sorry - you can't. ReactTable is not a "normal" table and has no support for `colspan` or `rowspan`.

**Comment by djfried** [comment]
I was able to get this effect by using the getTdProps prop on the table by passing it this function and hiding the columns that I wanted:
  customTdProps = (state, rowInfo, column, instance) => {
      let className = 'meeting__td'
      const columnsNotHidden = ["col0", "col6", "col7", "col8", "col9" ]
      if (rowInfo && rowInfo.original && this.isTopic(rowInfo.original) && columnsNotHidden.indexOf(column.id) === -1 ) {
          className = `${className} hide-me`;
      }

      return {className};
  };
