### ISSUE TITLE
Examples in codesandbox load without view

### ISSUE THREAD

**Issue by maxfrigge** [react-tools/react-table#834]
In the docs examples are loaded in codesandbox, but codesandbox initialises without a view. The reason for this is the query param `&view=split`. Removing the query param will fix it and load codesandbox in split view.

Example in docs:
https://react-table.js.org/#/story/server-side-data

Loads this in iframe (not working):
https://codesandbox.io/embed/wjrn8wy3R?autoresize=1&hidenavigation=1&view=split

Should load without view param:
https://codesandbox.io/embed/wjrn8wy3R?autoresize=1&hidenavigation=1

That's all.

**Comment by gary-menzel** [comment]
Closing.  This seems as though it may have been related to breaking changes in codesandbox that seem to be resolved.  If the problem still exists, please open another issue.

NOTE: Ives is in a fairly quick release cycle for changes and there are no resources available for ReactTable to keep pace
