### ISSUE TITLE
Server-side: When page is set to x, next should be lead to  page + 1 and previous page - 1

### ISSUE THREAD

**Issue by mschipperheyn** [react-tools/react-table#835]
## What version of React-Table are you using? 6.8.0

Currently when you use server-side fetching, the fetchData fires on load with the current page.

I need to be able to load a table set at a specific page. However, when I set page to x and click Next or Previous, the fetchData always fires with the current page index without indicating forward or backward.

I read in another comment that you should use state. How is that supposed to work?

```
class Table extends React.PureComponent{
  state = {
    page: 0
  };

  componentDidUpdate(){
    const { items } = this.props;
    console.log('server', items.page);
  }

  handlePageChange = page => {
    const { items } = this.props;
    console.log('client', page);
    this.setState(
      {
        page
      });
  };

  handleFetchData = props => {
    const { pageSize, sorted, filtered } = props;
    const { page } = this.state;
    console.log('fetch', page, props.page);
    this.props.listReviews(`&page=${page}&pageSize=${pageSize}`);
  };

  render() {
    const { items, loading } = this.props;
    const { page } = this.state;
    if (!items) return <Loading />;

    const { rows, limit, count } = items;

    return (
                <ReactTable
                  manual
                  data={rows}
                  pages={Math.ceil(count / limit)}
                  page={page}
                  defaultPageSize={limit}
                  pageSize={limit}
                  loading={loading}
                  onPageChange={this.handlePageChange}
                  onFetchData={this.handleFetchData}
                />
    );
  }
}
```
If I set the state `onPageChange`, the page changes, ok. But if want to make sure that what comes back from the server is in line with the front end, I need to set the page on componentDidUpdate. So I see the following cycle:

**load**
fetch 0 0
server 0
**Click next**
client 1
fetch 0 0
server 0
server 0

I played around with loading stuff in onPageChange, but it's hard to get it right and this should be a piece of cake. Why doesn't the handleFetchData receive a page and nextPage when Next of Previous is clicked? 

Perhaps I'm not getting it or misunderstanding some basic concepts here. Please enlighten me if this is the case. 

The way imho it should work is
when Next is clicked, the handleFetchData receives a `page`attribute (current page) and a `nextPage` attributes. These will be the same on initial load. 

This way, we can manage this purely on props and don't have to deal with async aspects.

**Comment by mschipperheyn** [comment]
I realized that since I'm using redux, the best way to deal with server side fetching is to ignore onFetchData completely. I'm just using componentDidMount and handlePageChange now. All state is maintained in the reducer.

**Comment by gary-menzel** [comment]
Generally, you should ignore `onFetchData` (as you have indicated).  It is mostly not required for any modern React-based solution.  The only place where I think it may be useful (my opinion) is if you just have a very light front end piece of code with no other React infrastructure and need to get some data into a table.  Even so, the data still needs to be maintained in the component state.

In terms of your question with regard to why a page instead of next/prev... simply because most backend DBs provide a "start" and "limit" - not a "next" or "previous".

I'll close this now since you have a solution.
