### ISSUE TITLE
`onExpandedChange`: event.target is always null

### ISSUE THREAD

**Issue by obsoke** [react-tools/react-table#836]
## What version of React-Table are you using?
6.8.0

## What bug are you experiencing, or what feature are you proposing?
I'm trying to use the `onExpandedChange` callback property on `ReactTable`. The documentation says that the function signature looks like this: `onExpandedChange={(newExpanded, index, event) => {...}}`. However, the `event.target` property is always returning as `null` for me.

I see a warning in the developer console suggesting I use `event.persist()` to keep event objects from being nullified after being used but even putting that function call at the top of the callback doesn't seem to change anything.

## Use https://codesandbox.io/s/X6npLXPRW (by clicking the "Fork" button) to reproduce the issue.
https://codesandbox.io/s/nkl45jxkwj

## What are the steps to reproduce the issue?
1. Set a column to have its `expander` property to `true`, enabling expanded rows on the table.
2. Set your `SubComponent` to something.
3. Give `ReactTable` a `onExpandedChange` callback function with all three arguments.
4. Use `event.persist()`.
5. `console.log(event.target)`
6. See `null` in the console when we expected to see the event target.

**Comment by tusharneve** [comment]
I am also facing same problem please help.

**Comment by stahlmanDesign** [comment]
I would also like to access the event so I can detect if the `alt` key was pressed and open/close all
```jsx
  handleOnExpandedChange = (newExpanded, index, e)=>{
    if(e && e.nativeEvent && e.nativeEvent.altKey){
      // TODO open/close all
      // bug: e is null, React warns to e.persist() but that only works if you have access to e before it is null
    }
```

**Comment by gary-menzel** [comment]
I've had a look through the code and I cannot see where anything is happening to the event - it is basically just passed straight through all the calls until it hits the `onExpandedChange`.

I also attempted to hijack the even in an `onClick` handler in the `getTdProps` and persist it there (because it is the `onClick` handler that calls the `onExpandedChange` - and that does not work (i.e. the event seems to have been removed from the Synthetic Even Pool even before there).  So I am unsure as to what is happening.

**Comment by gary-menzel** [comment]
I can't be sure but I suspect the event has to be persisted before the first usage of it. It would be a code change to ReactTable that would need to be tested.

**Comment by tannerlinsley** [comment]
Closing due to issue age. If you think this issue needs to be reopened or if it should be turned into a pull-request, please check the latest version of React-Table for the issue or feature once more and reopen or create a PR if appropriate. Thanks!
