### ISSUE TITLE
ReactTable/MobX: data update not reflected in table

### ISSUE THREAD

**Issue by github-account-because-they-want-it** [react-tools/react-table#839]
## What version of React-Table are you using?
6.8.0

## What bug are you experiencing, or what feature are you proposing?
Table is not updating custom cell contents when data changes. I'm not sure if this is an issue with ReactTable or my code. Please help

## Use https://codesandbox.io/s/X6npLXPRW (by clicking the "Fork" button) to reproduce the issue.
https://codesandbox.io/s/jp882l3m2w

## What are the steps to reproduce the issue?
1. Edit text areas in the table Price column.
2. You'll see in the console that the `onChange()` handler is being triggered and the store items are updated.
3. Table cells are not updated

**Comment by gary-menzel** [comment]
This is a very basic MobX example with ReactTable.  It does not have an editable field in it but the buttons at the Add a record and Update with a random string.

Maybe that will help.  I don't have anything more complex as I don't use MobX.

https://codesandbox.io/s/kkmxl8moq5

**Comment by github-account-because-they-want-it** [comment]
Thank you @gary-menzel . I see that there's an issue with ReactTable not playing well with ObservableArray so I modified my example above to resemble you example as much as possible (cloning the observable array data and extracting the custom cell into it's own observable) but the results are the same and the change is again not picked up by the table. I'm really baffled as to why this is not working.

**Comment by github-account-because-they-want-it** [comment]
I also modified your example to add an update column with a text editor cell. The result is the same. Here https://codesandbox.io/s/p98vqqyy27

**Comment by gary-menzel** [comment]
It's working now.....

https://codesandbox.io/s/z2v7m0kvml

You were adding a member called `newTask` to the object rather than changing the `task` member.  I found it by enabling the `console.log` that prints out the state at the top of the render before ReactTable.  It was changing but the value was not changing the `text` field.

**Comment by github-account-because-they-want-it** [comment]
Thank you @gary-menzel . So in my case it all comes down to the difference between reassigning a new object `this.todos[index] = { ...this.todos[index], task }` than modifying the existing one `this.todos[index].price = newPrice`. The former works and latter doesn't. Pretty interesting :thinking:

**Comment by gary-menzel** [comment]
This is pretty common in tools like Redux and MobX - even though I don't use them, I have adopted the habit of updating in that way in normal Javascript (and I really don't think about it now).  The idea is you don't change an object you create a new one.  That gives you immutability even without using `immutable.js`. However, it means you have to commit to using it everywhere.

Glad it is working now.

**Comment by thomaszdxsn** [comment]
it doesn't work for expand mode, use subrows field
