### ISSUE TITLE
deselect all selected rows command

### ISSUE THREAD

**Issue by ssad9985** [react-tools/react-table#841]
Version 6.8.0

I want to cancel/deselect all the selected rows on a button click, say CANCEL. How to achieve this?

**Comment by gary-menzel** [comment]
If you are talking about the selectTableHOC example in the docs - it already does clear all the selected rows using the global checkbox in the header - so there is example code already there.

I'll close this ticket now. If you have other questions, please discuss this on the #react-table Slack channel (button at the top of the README in the doco).  Thanks.

**Comment by ravisojitra** [comment]
How can i deselect all rows with external button which is placed inside other component than table? You can check below example where i have exported toggleAllPageRowsSelected with clearAll alias to use it with ref in parent component. But it's always undefined.

```
const { getTableProps, getTableBodyProps, headerGroups, rows, prepareRow, selectedFlatRows, toggleAllPageRowsSelected } = useTable(
    {
      columns: primaryColumns,
      data,
    },
    useRowSelect,
    hooks => {
      hooks.visibleColumns.push((columns) => [
        {
          id: 'selection',
          Header: ({ getToggleAllRowsSelectedProps }) => (
            <IndeterminateCheckbox
              isHeader={true}
              {...getToggleAllRowsSelectedProps()}
            />
          ),
          Cell: ({ row }) => (
            <IndeterminateCheckbox
              row={row.original}
              {...row.getToggleRowSelectedProps()}
            />
          ),
        },
        ...columns,
      ])
    }
  )
    console.log('toggleAllPageRowsSelected => ',toggleAllPageRowsSelected)
  useImperativeHandle(ref, () => ({ clearAll: toggleAllPageRowsSelected }))
```

**Comment by nitishnivedan** [comment]
@ravisojitra - were u able to reset the selected checkbox from oustide component (not in react table) by click of a button.

**Comment by AnushHakobyan** [comment]
@ravisojitra @nitishnivedan use `toggleAllRowsSelected` returned by `useTable` hook to reset selected rows' state outside of the table rows.

**Comment by nitishnivedan** [comment]
@AnushHakobyan - yes, I had posted this question long back and achieved then by using toggleAllRowsSelected only. thanks anyways for commenting. Its much appreciated.

**Comment by handhikadj** [comment]
@AnushHakobyan  @nitishnivedan any code snippet / codesandbox example for that?

**Comment by uooopss** [comment]
@handhikadj - my solution is to use the method `useImperativeHandle` from React and `toggleAllRowsSelected` from react-table.
`
import { FC, forwardRef, useImperativeHandle, useRef } from 'react'
import { useRowSelect, useTable } from 'react-table'

Parent.jsx

const Parent: FC = () => {
  const tableRef = useRef<any>(null)
  return (
    <div onClick={() => tableRef?.current?.resetSelectedRows()}>
      Reset
    </div>
    <Table 
      ref={tableRef}
      columns={[]} // your table columns
      data={[]} // your table data
    />
  )
}

Table.tsx

const Table: FC = forwardRef(({ data, columns }: any, ref: any) => {
  const {
    getTableProps,
    getTableBodyProps,
    headerGroups,
    footerGroups,
    rows,
    prepareRow,
    // @ts-ignore
    toggleAllRowsSelected, // Method for set/reset all rows. toggleAllRowsSelected: Function(?set: Bool) => void
    // @ts-ignore
    state: { selectedRowIds },
  } = useTable(
    {
      columns,
      data,
    },
    useRowSelect
  )
  
  useImperativeHandle(
    ref,
    () => ({
      resetSelectedRows: toggleAllRowsSelected,
    }), // you can just use ({toggleAllRowsSelected}) and in Parent call tableRef.current.toggleAllRowsSelected() with ?bool param
    []
  )
  
  return (
    <table {...getTableProps()} className="min-w-full">...</table>
  )
})
` 
Links for more information:
1) `useImperativeHandle`: [](https://react.dev/reference/react/useImperativeHandle)
2) `toggleAllRowsSelected`: [](https://react-table-v7.tanstack.com/docs/api/useRowSelect#instance-properties)

**Comment by fahadsaleem020** [comment]
@ssad9985

**Comment by fahadsaleem020** [comment]
@ssad9985

**Comment by fahadsaleem020** [comment]
@ssad9985    `table.resetRowSelection();`

**Comment by mdodge-ecgrow** [comment]
Thank you fahadsaleem020, that worked beautifully!
For whatever reason, the `toggleAllRowsSelected(false)` method from uooopss was no longer working for me.  It was leaving an `undefined` in the selected rows array.

**Comment by MESSELMIyahya** [comment]
I think this will help

Use this method
```ts
const { setRowSelection } = useTable(...);

const handleUnselectAll = ()=>{
   setRowSelection({})
}
```

**Comment by codeto0516** [comment]
```ts
<Checkbox
  checked={row.getIsSelected()}
  disabled={!row.getCanSelect()}
  indeterminate={row.getIsSomeSelected()}
  onChange={row.getToggleSelectedHandler()}
/>
```
