### ISSUE TITLE
Tabindex needs to be added to header columns for sorting

### ISSUE THREAD

**Issue by gward35** [react-tools/react-table#842]
## What version of React-Table are you using?
"react-table": "^6.7.6",

## What bug are you experiencing, or what feature are you proposing?
Add tabindex to react table column headers so keyboard users can navigate to the column headers and sort columns on keypress 

Please consider implementing this feature so this tool can become 508 compliant. 

In the meantime what is the best way to replicate this behavior? Could I user headerProps to inject a tabindex=0 to focus the header columns ?

**Comment by gary-menzel** [comment]
This is all up to the user.  You may be able to use headerProps or possible getTheadThProps (from memory - don't have the docs handy right now).

**Comment by louismrose** [comment]
Not quite what is needed here, but I'm using the following to remove the "tabIndex=-1" from columns that aren't sortable:

```jsx
<ReactTable
            getTheadThProps={(state, rowInfo, column) => {
                // NB: when sortable is undefined we don't wish to unset tab index and so
                // we do a strict equality check for false
                return column.sortable === false ? {tabIndex:null} : {};
            }}
/>
```

You might be able to do something with `state` and `column` to determine the index of the column for which this `<th>` is being rendered, and then return an appropriate tabIndex.

**Comment by gward35** [comment]
Thanks so much for the replies I have my focus and keydown events set up
using getProps how can I toggle the sort function/method? Is there
something I can call that's baked in?

**Comment by gward35** [comment]
One more addition. . . 
I was looking at the ThComponent which is defined featuring a toggleSort prop

`return (
        <ThComponent
          key={`${i}-${column.id}`}
          className={classnames(
            classes,
            isResizable && 'rt-resizable-header',
            sort ? (sort.desc ? '-sort-desc' : '-sort-asc') : '',
            isSortable && '-cursor-pointer',
            !show && '-hidden',
            pivotBy &&
              pivotBy.slice(0, -1).includes(column.id) &&
              'rt-header-pivot',
          )}
          style={{
            ...styles,
            flex: `${width} 0 auto`,
            width: _.asPx(width),
            maxWidth: _.asPx(maxWidth),
          }}
          toggleSort={e => {
            if (isSortable) this.sortColumn(column, multiSort ? e.shiftKey : false)
          }}
          {...rest}
        >
          <div className={classnames(isResizable && 'rt-resizable-header-content')}>
            {_.normalizeComponent(column.Header, {
              data: sortedData,
              column,
            })}
          </div>
          {resizer}
        </ThComponent>
      )
    }`

And that component is used in your index.js  and calls toggleSort onClick

`ThComponent: ({ toggleSort, className, children, ...rest }) => (
    <div
      className={classnames('rt-th', className)}
      onClick={e => (
        toggleSort && toggleSort(e)
      )}
      role="columnheader"
      tabIndex="-1" // Resolves eslint issues without implementing keyboard navigation incorrectly
      {...rest}
    >
      {children}
    </div>
  ),`

Would it not just be a matter of adding an onKeyPress handler to the component for keyboard (enter) ability to sort the table?

If so what is the best way to add this prop to the component? getTheadProps and getTheadThProps dont seem to do it. 

Alternatively if this is not the case my above post still is open. How can I call the sort function once the th component is focused? 

Thanks so much for any responses and time.

**Comment by tannerlinsley** [comment]
Closing due to issue age. If you think this issue needs to be reopened or if it should be turned into a pull-request, please check the latest version of React-Table for the issue or feature once more and reopen or create a PR if appropriate. Thanks!
