### ISSUE TITLE
Server side rendering: onFetchData does not get triggered when I navigate back and forth from any other app from other than 0th Page

### ISSUE THREAD

**Issue by swp44744** [react-tools/react-table#849]
## What version of React-Table are you using?
Your bug may already be fixed in the latest release. Run `yarn upgrade react-table`!
Place your version here...
"react-table": "6.8.0"

## What bug are you experiencing, or what feature are you proposing?
Please include a detailed explanation here...
I am using server side pagination and data rendering and it works great... from my react table one of the column is a link(react-router: LInk) to other app. 
once you click on the text link in a column it will take you to the new app and on hitting cancel(which is again a react router Link back to the react table) on new app takes you back to react table component. This works great when I am on page: 0, ReactTable triggers onFetchData and makes server call and renders the data in react table, awesome. but If I paginate to the next page(Anything but 0th page) go to the new app and try to comeback to react table page by clicking cancel then react table does not trigger onFetchData callback method.

## Use https://codesandbox.io/s/X6npLXPRW (by clicking the "Fork" button) to reproduce the issue.
Then paste a link to your newly forked codesandbox here...
I cant put my code on sand box sorry about that...

## What are the steps to reproduce the issue?
1. list the steps
2. to reproduce
3. the issue

**Comment by cordoval** [comment]
where is your code? you did not offer a forked version on codesandbox.io

**Comment by tannerlinsley** [comment]
Closing due to issue age. If this issue was a question, please ask it again on https://spectrum.chat/react-table. If you think this issue needs to be reopened or if it should be turned into a pull-request, please check the latest version of React-Table for the issue or feature once more and reopen or create a PR if appropriate. Thanks!
