### ISSUE TITLE
Custom table row colors that change based on data / use

### ISSUE THREAD

**Issue by katzman** [react-tools/react-table#851]
I'm not having an issue, i'm asking about extra functionality, i dug through the docs and messed with the CSS but i can't find what i'm looking for. We have expandable rows, they need to be a different color then the rows that they will reveal. The revealed rows can be the standard stripped but the parent row needs to be a different color. So based on the datatype i want to be able to set a different classname for that row. 

I messed with using custom cells, but the background color doesn't cover the entire row. 

Thoughts, ideas, i'm doing it all wrong?

Thanks!

**Comment by tannerlinsley** [comment]
Closing due to issue age. If you think this issue needs to be reopened or if it should be turned into a pull-request, please check the latest version of React-Table for the issue or feature once more and reopen or create a PR if appropriate. Thanks!
