### ISSUE TITLE
Page number displayed doesn't reset 

### ISSUE THREAD

**Issue by MRLmic** [react-tools/react-table#854]
## What version of React-Table are you using?
Your bug may already be fixed in the latest release. Run `yarn upgrade react-table`!
Version 6.8.0

## What bug are you experiencing, or what feature are you proposing?
I have a function to refresh my table. The data refreshes but the page number doesn't.

## Use https://codesandbox.io/s/X6npLXPRW (by clicking the "Fork" button) to reproduce the issue.
I can't use sandbox, but here is my code:

`fetchData(state, refreshData=false) {
    this.setState({ loading: true });
    if (refreshData) {
      // this.setState({page: 0})
      pageIndex => this.setState({page: pageIndex})
      this.getNumPages()
    }
    var currentPageNumber = state.page;
    var numEventsNeeded = currentPageNumber * this.state.pageSize + 1;
    if (this.state.data.length < numEventsNeeded || refreshData) {
      var api = "/api/v1/tools/events/"+this.props.eventType+"/"+this.state.pageSize+"/"+currentPageNumber;
      $.get(api, (newData) => {
        var data = this.state.data.concat(newData);
        var curData = newData;
        this.setNewData(data, curData);
      }).fail((e) => {
        console.log(e);`...etc.

In the ReactTable:
`
  <ReactTable
              manual
              data={this.state.curData}
              noDataText="No event data available"
              page={this.state.page}
              pages={this.state.numPages}
              loading={this.state.loading}
              onFetchData={this.fetchData}
              columns={columns}
              defaultPageSize={5}
              className="-striped -highlight"
              showPageSizeOptions={false}
              showPageJump={false}
              onPageChange={pageIndex => this.setState({page: pageIndex})}`

The onClick function for refresh table is:
`  this.fetchData({page: 0}, true);`
## What are the steps to reproduce the issue?
1. Change pages
2. Click Refresh Table button

**Comment by tannerlinsley** [comment]
Closing due to issue age. If you think this issue needs to be reopened or if it should be turned into a pull-request, please check the latest version of React-Table for the issue or feature once more and reopen or create a PR if appropriate. Thanks!
