### ISSUE TITLE
Global Filter

### ISSUE THREAD

**Issue by sushmit-oodles** [react-tools/react-table#855]
Is there way to have a global filter right on top of table where we can filter the table regardless of data in any cell or row ?

**Comment by M4RTO** [comment]
I agree with you, we need a global filter  for react-table

**Comment by gary-menzel** [comment]
ReactTable is a toolbox (albeit with a default mode of operation). You can build the global filter yourself...

Here is an example: https://codesandbox.io/s/r74mokr5x4

**Comment by dimaqq** [comment]
I would be awesome if this snippet made it to the docs!

**Comment by skube** [comment]
Is there an example how to do this with v7 of React Table?
