### ISSUE TITLE
filter input styling

### ISSUE THREAD

**Issue by sushmit-oodles** [react-tools/react-table#856]
i have 6 columns out of which the second one is filterable. So, i there is an input field in sencond column.
How do i style that input field ? input fields is rendered automatically when i explicitly declared:
filterable:false on all columns except the 2nd one.

**Comment by tannerlinsley** [comment]
Closing due to issue age. If you think this issue needs to be reopened or if it should be turned into a pull-request, please check the latest version of React-Table for the issue or feature once more and reopen or create a PR if appropriate. Thanks!
