### ISSUE TITLE
Ability to set tabindex per row to allow accessibility to screen readers

### ISSUE THREAD

**Issue by erichwelz** [react-tools/react-table#858]
## What version of React-Table are you using?
Your bug may already be fixed in the latest release. Run `yarn upgrade react-table`!
6.8.0

## What bug are you experiencing, or what feature are you proposing?
I'd like to add tabIndex=0 per row so that a user may tab through each row of a table.
I've read the documentation, hopefully not well enough, as I haven't found a way to modify React-Table on a per row basis

Default sandbox has no tabbing per row.
https://codesandbox.io/s/X6npLXPRW 

## What are the steps to reproduce the issue?
Go to sandbox
Try tabbing

**Comment by tannerlinsley** [comment]
Closing due to issue age. If you think this issue needs to be reopened or if it should be turned into a pull-request, please check the latest version of React-Table for the issue or feature once more and reopen or create a PR if appropriate. Thanks!
