### ISSUE TITLE
Edit arrow icon for the pagination function

### ISSUE THREAD

**Issue by JH-Baek** [react-tools/react-table#867]
Am I able to edit the arrow icon for the pagination function at the bottom of the table?
![image](https://user-images.githubusercontent.com/20623279/37635126-ba8c00ee-2c5e-11e8-9493-c9be097c8b74.png)

**Comment by gary-menzel** [comment]
You have to replace the whole pagination component (check the docs - the source for the original is a separate component of 140 lines long - so you can just copy it into your own code and then do what you like and pass that as the new pagination component) - none of the individual pieces of the pagination component can be configured other than the text.

**Comment by JH-Baek** [comment]
Oh, OK. Thanks for your response. I will try what you told me to do.
