### ISSUE TITLE
Editable Table - change default behavior of pressing "enter" - key

### ISSUE THREAD

**Issue by Anirie** [react-tools/react-table#869]
@react-table: ^6.8.0

Is it possible to change the default behavior of editing a table-cell?
In particular, how can I prevent jumping into a new line of the cell, when I hit the enter-key?

I would like to update my edited data in the database by hitting the enter-key and lose focus of the just edited cell, rather than jump into the next line.

## What are the steps to reproduce the issue?
1. Go to https://react-table.js.org/#/story/editable-table
2. Edit a cell
3. Press "Enter"

Thank you for your help.

**Comment by gary-menzel** [comment]
The example in the docs is just an example and probably not "complete" for production use.  You need to build your own as all the requirements are different from project to project.  I built my own so it navigates with the up and down arrow keys and tab, it also saves data back to my database.  But it is specific to my needs and can't really be made generic for anyone to use.

**Comment by cosydney** [comment]
Did you managed to do what you wanted @Anirie ?
Best
