### ISSUE TITLE
I am no able to hide the footer of a hidden column

### ISSUE THREAD

**Issue by Fabitosoft** [react-tools/react-table#879]
I am using React-Table 6.7.6.

I have been trying to use show disable on the column. It works properly, but, when I try to used it on a column that includes footer, the footer is still there. How can I get hidden the column its footer?

**Comment by gary-menzel** [comment]
I am closing this ticket as it does not provide an example.  If you still have the issue and can provide an example of the breaking code then please open another ticket.
