### ISSUE TITLE
Is it possible to disable the checkboxes in the checkboxHOC ?

### ISSUE THREAD

**Issue by stefanoborini** [react-tools/react-table#883]
We need to disable the checkboxes in response to a specific state of the application. Is it possible to do so?

disable as in "make them unchangeable", not "untoggle".

**Comment by gary-menzel** [comment]
You are able to supply your own component for the checkbox.  In any case, the checkbox HOC is an example and is a fairly short piece of code that was meant to be hacked.  Feel free to.

**Comment by GodAlmighty990** [comment]
can you provide example of how to disable/ hide checkbox from one row in react-table?
