### ISSUE TITLE
Reordering table rows via drag and drop

### ISSUE THREAD

**Issue by MarissaMC** [react-tools/react-table#884]
## What version of React-Table are you using?
6.7

## What bug are you experiencing, or what feature are you proposing?
I saw there's feature of reordering columns via drag, but no same feature for rows.
Could we have custom order for rows via drag and drop? Thanks!

**Comment by gary-menzel** [comment]
Not currently possible.

**Comment by gioce90** [comment]
There is a way for obtain this?

**Comment by mattiagecchele** [comment]
+1

**Comment by kotromeo** [comment]
+1

**Comment by aruniverse** [comment]
ive been using react-beautiful-dnd, kinda works, not the best though...
