### ISSUE TITLE
Limit Number of Expanded Rows

### ISSUE THREAD

**Issue by tsteele2013** [react-tools/react-table#887]
## What version of React-Table are you using?

6.8.0

## What bug are you experiencing, or what feature are you proposing?

It would be nice if there was a way to programmatically close one or multiple expanded rows, or in my specific case I would like to enable only one expanded row at a time.

Functionality similar to bootstrap accordions, for example. https://getbootstrap.com/docs/4.0/components/collapse/#accordion-example

**Comment by tsteele2013** [comment]
@gary-menzel Thank you, this was rather helpful! Migrating to react-table from v0.x griddle-react, and am getting a few wires crossed.

**Comment by CaitlinWeb** [comment]
I was also looking for how to create an accordion effect with the expander option. There aren't many details in the documentation, and since I'm not too familiar with the library yet it took me awhile to figure out how to only have one row open at once.

For anyone else looking to do this, it's as simple as this: 
```jsx
onExpandedChange={(expanded, currentInd) => {
  for (const ind in Object.keys(expanded)) {
    expanded[ind] = currentInd === ind;
  }
}}
```

This works because the object passed first, `expanded`, is the same mapping you use for the prop `expanded`. From the documentation:
```jsx
expanded={{ // The nested row indexes on the current page that should appear expanded
    1: true,
    4: true,
    5: {
      2: true,
      3: true
    }
  }}
```

**Comment by gary-menzel** [comment]
NOTE: It is necessary to `this.setState({ expanded })` and not the one passed in the call (this is breaking the React model).  It might work (if the `expanded` being passed is the EXACT one used in ReactTable) but that is a side effect that may not be there in the future. Also, it will still only work for the top level if you have a pivot table.

**Comment by CaitlinWeb** [comment]
Good to know, thank you. It did work but it sounds like it might break later... I'm using a stateless component and didn't want to add state just for this, though. It'd be nice to have this as an optional prop. I don't know why you'd want to have an accordion effect on anything but the top level, so the implementation should be very simple.

**Comment by Valerika** [comment]
HI! @CaitlinWeb not working for me(
```
<Table
          minRows={0}
          resizable={false}
          sortable={true}
          data={data}
          page={0}
          pageSize={totalItemsPage}
          defaultPageSize={10}
          showPageSizeOptions={false}
          columns={columns}
          expanded={this.state.expanded}
          getTdProps={(state, rowInfo, column, instance) => {
            return {
              onClick: e => {
                this.expand_row(rowInfo);
              }
            };
          }}
          onExpandedChange={(expanded, currentInd) => {
            for (const ind in Object.keys(expanded)) {
              expanded[ind] = currentInd === ind;
            }
          }}
/>

**Comment by CaitlinWeb** [comment]
@Valerika Try removing the `expanded` property, as that probably takes precedence over `onExpandedChange`. Or if you're already using a stateful component with an `expanded` value (of one row) you don't need to do anything special.

**Comment by Valerika** [comment]
@CaitlinWeb thanks for the answer! I deleted the `expanded` but it did not help. Please help me. I needed an accordion effect in table  Here is my code. Thank you!

```
constructor(props) {
    super(props);
    this.state = {
      expanded: null
    };
  }



  expand_row = row => {
    globalIdCode = row.row.code;

    let expanded = { ...this.state.expanded };
    if (expanded[row.viewIndex]) {
      expanded[row.viewIndex] = !expanded[row.viewIndex];
    } else {
      expanded[row.viewIndex] = true;
    }
    this.setState({
      expanded: expanded
    });
  };



<Table
          minRows={0}
          resizable={false}
          sortable={true}
          data={data}
          page={0}
          pageSize={totalItemsPage}
          defaultPageSize={10}
          showPageSizeOptions={false}
          columns={columns}
          expanded={this.state.expanded}
          getTdProps={(state, rowInfo, column, instance) => {
            return {
              onClick: e => {
                this.expand_row(rowInfo);
              }
            };
          }}
          onExpandedChange={(expanded, currentInd) => {
            for (const ind in Object.keys(expanded)) {
              expanded[ind] = currentInd === ind;
            }
          }}
/>

**Comment by CaitlinWeb** [comment]
@Valerika Try something like this. You'll likely need to play around with it, I haven't tried it out myself.

> ```
> constructor(props) {
>     super(props);
>     this.state = {
>       expanded: null
>     };
>   }
> 
> <Table
>           minRows={0}
>           resizable={false}
>           sortable={true}
>           data={data}
>           page={0}
>           pageSize={totalItemsPage}
>           defaultPageSize={10}
>           showPageSizeOptions={false}
>           columns={columns}
>           expanded={this.state.expanded}
>           onExpandedChange={(expanded, currentInd) => {
>               const expandedValue = {};
>               expandedValue[currentInd] = expanded[currentInd];
>               this.setState({ expanded: expandedValue });
>           }}
> />
> ```

What this does is implicitly sets all rows to false except for the one clicked, thus creating an accordion effect with only one expanded at once. It uses `onExpandedChange`, but if you want the whole row clickable like in your code you can use `getTdProps` to set `onClick`.

---

Reference:
> onExpandedChange={(newExpanded, index, event) => {...}} // Called when an expander is clicked. Use this to manage `expanded`

**Comment by muellermarkus** [comment]
@Valerika This code works for me: 

```ts
  constructor(props) {
    super(props);

    this.state = {
      expanded: {},
    };
  }

                    // Props for <ReactTable> component
                    expanded={this.state.expanded}
                    onExpandedChange={(expanded, currentInd) => {
                      this.setState({
                        expanded: {
                          [currentInd[0]]: expanded[currentInd[0]] !== false,
                        },
                      });
                    }}
                    onPageChange={() => {
                      this.setState({
                        expanded: {},
                      });
                    }}
```

**Comment by joyahmed** [comment]
I've used useEffect and setPageSize(n)
