### ISSUE TITLE
Help - TreeTable blank - Works on codesandbox but not inside my project

### ISSUE THREAD

**Issue by ranrao** [react-tools/react-table#891]
TreeTable works in codesandbox - https://codesandbox.io/s/xv6yozp4vp. But, when the same code is embedded in my project, the table is blank.

My package settings used similar versions on codesandbox. And, the it works without the pivot and accessor attributes ... The moment I use accessor, the table becomes blank.

Also, in my project, the return it as a component, so that it can be used by other components.
export default ReportData;

Helpful feedback highly appreciated. Thanks much in advance!

**Comment by gary-menzel** [comment]
@ranrao your example doesn't even run - it has errors that are not even related to ReactTable.

**Comment by ChampionRoy** [comment]
change treeTableHOC.js code and finally the data is shown.
`const extra = {
      columns: columns.map((col) => {
        let column = col;
        if (rest.pivotBy && rest.pivotBy.includes(col.accessor)) {
          column = {
            accessor: col.accessor,
            width: `${componentProps.treeTableIndent}px`,
            show: false,
            Header: '',
          }
        }
        return column;
      }),
      TrComponent,
      getTrProps,
    };`
change "show" from "false" to "true".
But I still confused why the default configuration is false.

**Comment by gary-menzel** [comment]
@ChampionRoy It hides the column to be able to get rid of the "pivoty" nature and creates an "indent" similar to a Tree Table.  If you want the column from the original 'pivotBy' then you don't want to be using the treeTableHOC.  In other words, the `treeTableHOC` is MEANT to hide the pivot columns.

BUT NOTE - both you and @ranrao  - it ONLY works with a string-based accessor.  It will NOT work with a function-based accessor.

Finally - it is only an EXAMPLE of how to build a HOC for ReactTable and is not considered "production" ready.  There were so many people who were just unable to grasp the concept so I built a few examples.  They are there for people to hack about in true Open Source fashion (just as is ReactTable itself).

**Comment by AntoineBenard** [comment]
Same problem
version info:
react-table 6.8.2
react 16.3.1
react-dom 16.3.1

Changing like @ChampionRoy did, solved the data displaying issue but the pivotBy column also appears...

**Comment by darksheik** [comment]
I was wrestling with this myself for a bit.  It properly adds the `hidden` class to the cell in the expandable data.  However, the pivot cell _also_ has a `hidden` class, which more universally means that something should be hidden.  Possible a Bootstrap theme is doing this.

The pivot cell should remove the `hidden` class.
