### ISSUE TITLE
Invalid Prop Type warning - renders fine though

### ISSUE THREAD

**Issue by pmonty** [react-tools/react-table#894]
**Version** 
`"react-table": "^6.8.0"`

**Bug Info**
I am getting a message in the console that reads:
`Warning: Failed prop type: Invalid prop `data` of type `object` supplied to `ReactTable`, expected `array`.

**Code**
```
export class SortableTable extends React.Component<ISortableTableProps, {}> {
    @observable
    private rows: number;

    constructor(props: ISortableTableProps) {
        super(props);
        this.rows = this.props.rows;
    } 

    public render(): JSX.Element {
        return (
            <ReactTable
                data={this.props.data}
                columns={this.props.columns}
                defaultPageSize={this.getNumberOfRows()}
                className="-striped -highlight"
            />
        );
    }

    private getNumberOfRows(): number {
        return this.rows < 10 ?
            this.rows : 10
    }
}
```

this.props.data is definitely an array of objects.

**Result**
It renders the data fine but gives this warning for some reason.

**Comment by gary-menzel** [comment]
It gives a warning because the data from an observable may not a true Array. You should convert the Observable Array to a normal array to be sure it will work correctly.  In some cases (like sorting) it will give a real error.

**Comment by gary-menzel** [comment]
NOTE: warnings should go away in the PRODUCTION build of React.

While the goal is to remove warnings, the version of React has a big impact on what warnings are presented.  So this is low on priority but part of the general checking done and fixed in code reviews.
