### ISSUE TITLE
Pagination 'Next' button click custom event handler

### ISSUE THREAD

**Issue by germiya** [react-tools/react-table#897]
## What version of React-Table are you using?
"react-table": "^6.7.6"

## What feature are you proposing?
Is it possible to add a custom event handler for 'Next' and 'Previous' buttons in the pagination.
I have to load more than 20K rows , so, instead of loading everything at once, I wanted to make axios call and get data on click of these buttons and reload the table.

Thanks

**Comment by gary-menzel** [comment]
There is no hook into the button click.  You can hook into `onPageChange` or you can use `onFetchData`. Don't hook into both - if you are going to do a backend call then `onFetchData` is the most appropriate - but you are then responsible for filtering and sorting on the backend as well.

Check the docs - there is an `onFetchData` example that uses axios.
