### ISSUE TITLE
Documentation examples don't load

### ISSUE THREAD

**Issue by jrpharis** [react-tools/react-table#898]
Trying to view any of the examples on the [documentation](https://react-table.js.org/?_sm_au_=iVV7nf2TB7Qrmv5q#/story/readme) results in the message 

```
Not Found
We could not find the sandbox you're looking for.
```

**Comment by gary-menzel** [comment]
I've just checked a handful of the links in the document and don't get that error.

**Comment by tannerlinsley** [comment]
Closing due to issue age. If you think this issue needs to be reopened or if it should be turned into a pull-request, please check the latest version of React-Table for the issue or feature once more and reopen or create a PR if appropriate. Thanks!
