### ISSUE TITLE
optimization

### ISSUE THREAD

**Issue by Lisss13** [react-tools/react-table#901]
## What version of React-Table are you using?
"react-table": "6.7.6"

## What bug are you experiencing, or what feature are you proposing?
In the array of objects, I change some values, but the entire table is redrawn

Are there any ways to optimize?

**Comment by tannerlinsley** [comment]
Closing due to issue age. If you think this issue needs to be reopened or if it should be turned into a pull-request, please check the latest version of React-Table for the issue or feature once more and reopen or create a PR if appropriate. Thanks!
