### ISSUE TITLE
Table missing rows from the datasource after doing a react component refresh....might be problem with pagination

### ISSUE THREAD

**Issue by TickleKitty** [react-tools/react-table#902]
## What version of React-Table are you using?
6.8.0

## What bug are you experiencing, or what feature are you proposing?
This is hard to explain as it does not happen consistent for us.  Basic problem is this:  Table datasource has 20 rows of data but the resulting table will only show 10.  This is a basic example.

This seems to happen after the parent react component reloads.  So the user makes some changes to our filters (these are all separate controls) we do an api fetch to get new data.  I can see that the data is coming back correctly from the server (all 20 rows are returned as expected) but the grid will not show them.

Sample codesanbox:
https://codesandbox.io/s/n3v1q2y52m

In my codesandbox example you'll see that I'm just trying to turn pagination off completely.  I just don't need it or want it for what I'm doing.  Maybe I'm just doing it correctly?  Am I missing an option to just turn all pagination features off and show all rows?

## What are the steps to reproduce the issue?
1. Initial table renders
2. User makes changes to filters (these are separate controls elsewhere in react page)
3. Server fetches the new data
4. React table doesn't show the correct data.

Thanks for the help!

**Comment by gary-menzel** [comment]
You don't need to use `minRows` if you are setting the page size - however, the `defaultPageSize` won't change after the initial rendering.  You should probably set `pageSize` instead.

**Comment by TickleKitty** [comment]
@gary-menzel that was the problem! Thanks so much!!
