### ISSUE TITLE
Displaying cells under pivot column group

### ISSUE THREAD

**Issue by pnaw94** [react-tools/react-table#905]
Hey there!
My problem is kind of similar to https://github.com/react-tools/react-table/issues/882, though it is slightly more complex and after doing some research I'm pretty much certain there's currently no workaround for it.

The issue:
I have a set of records, each record represents some data for particular province within a country (so it has country name and province name properties, among others). What I want to do is to group these records by country name, but I don't want to have another column for province name, since that's kind of redundant - I'd like to have my province names displayed within the same column as country, when I expand it.

So basically what I want to have is to replace this
![current](https://user-images.githubusercontent.com/10995919/38621670-a34fd802-3da1-11e8-87b0-c790dea22bb8.jpg)

with this 
![expected](https://user-images.githubusercontent.com/10995919/38621687-a7c390cc-3da1-11e8-99e3-e1db36a615cb.png)

...and I've actually done that, using the trick from the issue mentioned before, but besides that, I'd like to have my provinces sorted within the group, so that when I choose to sort this column, the groups are sorted by country name, but inside each group, records are sorted by province name.

And that's the real issue, as it seems it can't be achieved, because to group the values properly, I need my accessor property to return the country name, but then sorting method receives only the country name (cell value), while it should also have province name. On the other hand, when I set my accessor to return the whole item (containing both province and country), then column grouping breaks.

Wrapping up, this problem could be resolved actually in many ways. There could be a property like "pivot by" for column, that would be something similar to accessor, or enable the sorting method to also receive original objects instead of cell values. Those would be the quickest solutions, though I'm not sure if those wouldn't be just workarounds for a bigger problem, and some additional design is needed?

Please let me know what you think about this and maybe if I'm missing something.

**Comment by gary-menzel** [comment]
The pivot model only works for simple cases and needs to be removed completely from ReactTable so that more complex situations can be accomplished.  This will not happen until the next major upgrade - which is not even planned at this point.

I don't fully understand your requirement but you could look at implementing a custom sort function (either for the columns involved or at the table level) and see if that resolves the issue.  The pivot mechanism first sorts the data and then moves those sorted pivot columns to the front of the column list.  It might get you by.

Also not that the `accessor` result is what is used for sorting and filtering.  The `Cell` result is only used to display on the screen. So, if you build a custom sort, the "value" being tested comes from the `accessor` - which could be an object (as long as your `Cell` returns something that can be rendered).

**Comment by pnaw94** [comment]
@gary-menzel my point is following:
My object for each row is (simplified): `{ country: "Canada", province: "Ontario" }`
I'd like to have country and province disabled in one column (like on image I've attached before).

1. When I choose accessor `obj => obj.country`, then I get my data properly pivoted by country, but then also the grouped rows (meant to be provinces) are being sorted by accessor's property (country), and I need them to be sorted by province prop. I also can't achieve anything by overriding sortBy, as it is being passed the result of accessor method, so I always get two country names to compare (while I'd rather need entire object there).

2. When I choose accessor `obj => obj`, then I'm able to override all that sorting and stuff, but pivoting simple doesn't work, as it takes accessor's result for grouping.

**Comment by gary-menzel** [comment]
I think you are just fighting against what has been built for the pivot functionality.  You'll either have to look at forking the code and adjusting it or abandoning ReactTable for a different solution.  The pivot facility really does not have very much configurability in the current version of ReactTable (and is likely to be removed and migrated to a HOC or some other function as renderer mechanism in the next major version).

**Comment by pnaw94** [comment]
Got it, thanks for your feedback then!
