### ISSUE TITLE
how can I remove the expand icon of the non-data rows ?

### ISSUE THREAD

**Issue by mikdatdogru** [react-tools/react-table#907]
## What version of React-Table are you using?
v6.8.0

https://codesandbox.io/s/jp640jzlv5

codesandbox example's the child data in row 2 is empty but it can be expandable.
how can I remove the expand icon of the non-data rows ?

**Comment by pnaw94** [comment]
You should be able to pass `Expander` property to column definition, and then render it based on your preferences.
Please look at https://react-table.js.org/#/story/readme section Column.
It should look like `Expander: props => condition ? null : <default expander>`

**Comment by mikdatdogru** [comment]
@pnaw94 thanks your answer. 

I did this way.


 `
{
    expander: true,
    width: 65,
    Expander: ({ isExpanded, ...rest }) =>{
      if(rest.original.hareketler.length > 0){
        return (
          <div>
            {isExpanded
              ? <i className="fa fa-minus c-red"/>
              : <i className="fa fa-plus c-green"/>}
          </div>
        )
      }
      return (
        <div>
          <i className="fa fa-plus disabled" style={{color:'#e8e8e8'}}/>
        </div>
      )
    }
  }
`

**Comment by krishna63** [comment]
@mikdatdogru : could you update the example with the fix you had. I also had same issue

**Comment by mikdatdogru** [comment]
@krishna63 
working demo here:
https://codesandbox.io/s/8l464jrm19
