### ISSUE TITLE
100k rows demo triggers potential infinite loop error

### ISSUE THREAD

**Issue by Yahtze** [react-tools/react-table#909]
## What version of React-Table are you using?
Your bug may already be fixed in the latest release. Run `yarn upgrade react-table`!
N/A

## What bug are you experiencing, or what feature are you proposing?
Just a bug with your demo [here](https://react-table.js.org/#/story/100k-rows-w-pivoting-sub-components)

## Use https://codesandbox.io/s/X6npLXPRW (by clicking the "Fork" button) to reproduce the issue.
https://react-table.js.org/#/story/100k-rows-w-pivoting-sub-components

## What are the steps to reproduce the issue?
1. Open the demo
2. Click Run
3. Receive error for 10001+ iterations

The error says it can be fixed if you add a sandbox.config.json file.

**Comment by ryota-murakami** [comment]
i fixed it by `sandbox.config.json` & `infiniteLoopProtection: false`.

**[Docs](https://codesandbox.io/docs/configuration/#sandbox-configuration)**

such as following

[![Edit React-Table - 100k Rows + Aggregation](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/04612qw080?module=%2Fsandbox.config.json)

**Comment by gary-menzel** [comment]
This is known about but requires the author of the original codesandbox to make the changes.

There is no intention to change the link at this point in time.  Thanks for the information though.

We suggest people just fork the breaking example into their own codesandbox and make the necessary changes.

**Comment by togakangaroo** [comment]
Why leave the top example on your npm page broken? Just point it to a different sandbox which fixes things...

**Comment by tannerlinsley** [comment]
The latest version of that example link should be fixed, since it now includes a sandbox config file that removes the loop protection.

**Comment by togakangaroo** [comment]
@tannerlinsley I came here because I clicked the first example link on the npm main page and got this error. This is the link listed in npm https://codesandbox.io/s/github/tannerlinsley/react-table/tree/master/archives/v6-examples/react-table-100k-rows-aggregation
