### ISSUE TITLE
RangeError on demo

### ISSUE THREAD

**Issue by cordoval** [react-tools/react-table#916]
Potential infinite loop: exceeded 10001 iterations. You can disable this check by creating a sandbox.config.json file.

when looking at https://react-table.js.org/#/story/100k-rows-w-pivoting-sub-components

**Comment by gary-menzel** [comment]
This is an issue with changes on codesandbox and the examples have not been updated.  Given that there is a new version of ReactTable under consideration, this is unlikely to be fixed until that release is finished.
