### ISSUE TITLE
Missing rt-resizable-header-content div in 6.8.1

### ISSUE THREAD

**Issue by Morasta** [react-tools/react-table#918]
## What version of React-Table are you using?
6.8.1

## What bug are you experiencing, or what feature are you proposing?
Resizable headers (.rt-th.rt-resizable-header) columns used to have two child divs, ".rt-resizable-header-content" and ".rt-resizer". As of 6.8.1 the former div is no longer present which necessitates a bunch of CSS rewrites (e.g. codepens, other issues, etc.). Would be nice to have that div back...

## What are the steps to reproduce the issue?

Build any example using 6.7.x (e.g. https://codesandbox.io/s/1ojwxxp253):
```
<div class=" rt-resizable-header -cursor-pointer rt-th" style="flex: 100 0 auto; width: 100px;"> 
    <div class="rt-resizable-header-content">First Name</div>
    <div class="rt-resizer"></div>
</div>
```

Build using 6.8.x (e.g. https://codesandbox.io/s/rln1mr0o4p):
```
<div class="rt-th  rt-resizable-header -cursor-pointer" role="columnheader" tabindex="-1" style="flex: 100 0 auto; width: 100px;">
    <!-- react-text: 12 -->First Name<!-- /react-text -->
    <div class="rt-resizer"></div>
</div>
```

**Comment by gary-menzel** [comment]
@tannerlinsley There were questions about this change almost as soon as it was released.

**Comment by tannerlinsley** [comment]
Reverted.
