### ISSUE TITLE
Problem in Re-fetch the data from the server

### ISSUE THREAD

**Issue by patwapro** [react-tools/react-table#922]
I want to trigger the fetchData but got an error. 
 I know this is not good way to call function but how to 
 recall the onFetch data.

export default class BillPayment extends Component {
    constructor(props) {
        super(props);
        this.state = {
            data: [],
            recharge:[],
            pages: null,
            loading: true,
            error:null,
            isLoaded: false,
            splitButtonOpen: false,
            startDate: moment(),
            changedate:moment().format('YYYY-MM-DD'),
        }
        this.requestData = this.requestData.bind(this);
        this.fetchData = this.fetchData.bind(this);
        this.toggleSplit = this.toggleSplit.bind(this);
        this.handleChange = this.handleChange.bind(this);
      }

    requestData(pageSize, page, sorted, filtered) {
      return new Promise((resolve, reject) => {
        const start =  page * pageSize;
        axios({
          method: 'get',
          url: 'http://localhost:3000/transaction/usertransactionbyuser?trans_id=671030003&page='+start+'&pageSize='+pageSize+'&date='+this.state.changedate, 
        }).then(response => {
          let filteredData = response.data.transaction
          if (filtered.length) {
            filteredData = filtered.reduce((filteredSoFar, nextFilter) => {
              return filteredSoFar.filter(row => {
                return (row[nextFilter.id] + "").includes(nextFilter.value);
              });
            }, filteredData);
          }
      
          const sortedData = _.orderBy(
            filteredData,
            sorted.map(sort => {
              return row => {
                if (row[sort.id] === null || row[sort.id] === undefined) {
                  return -Infinity;
                }
                return typeof row[sort.id] === "string"
                  ? row[sort.id].toLowerCase()
                  : row[sort.id];
              };
            }),
            sorted.map(d => (d.desc ? "desc" : "asc"))
          );
      
          const res = {
            rows: sortedData,
            pages: Math.ceil(response.data.count / pageSize)
          };
      
          setTimeout(() => resolve(res), 500);
        }).catch(error => {
          console.log(error);
        });
    
      });
    };
 
      fetchData(state, instance) {
        this.setState({ loading: true });
       this.requestData(
          state.pageSize,
          state.page,
          state.sorted,
          state.filtered
        ).then(res => {
          this.setState({
            data: res.rows,
            pages: res.pages,
            loading: false
          });
        });
      }
    
      toggleSplit() {
        this.setState({
          splitButtonOpen: !this.state.splitButtonOpen
        });
      }

      handleChange(date) {
        this.setState({
          startDate: date,
          changedate:date.format('YYYY-MM-DD'),
        });
        this.fetchData(); // I want to trigger the fetchData but got an error. I know this is not good way to call function but how to recall the onFetch data.
      }
    

    render() {
        const { changedate, rows, data, pages, loading, error, isLoaded } = this.state;
            return (                               
                <div>           
                    <Row className="mb-40">
                        <Col sm="12" md="12" lg="12">
                        <ReactTable                         
                            columns={
                              [{                                          
                                Header: "Date",
                                accessor: "req_dt"
                                },{
                                  Header: "Mobile",
                                  accessor: "customer_id"
                                },{
                                  Header: "Service Name",
                                  accessor: "service_name"
                                },{
                                  Header: "Amount",
                                  accessor: "trans_amt"
                                },{
                                  Header: "Status",
                                  accessor: "status"
                                }                               
                            ]
                          }
                            manual 
                            data={data}
                            pages={pages} 
                            loading={loading} 
                            onFetchData={this.fetchData} 
                            defaultPageSize={5}
                            className="-striped -highlight"                                              
                          />
                        </Col>
                    </Row>                                                                                             
                </div>                                                                                           
            );
        }
}

**Comment by gary-menzel** [comment]
You almost have it right:

- when your `onFetchData` is called - save the state props in your own component state somewhere before calling your `requestData` (use the callback on `setState` to make sure it is stored in your component state and use that instead of what is passed in the props
- in your `handleChange` don't call `fetchData` directly (because you don't have the right props for it) but call your `requestData`... if you want different `state` then you should use `setState` again and call `requestData` on the `setState` callback (so you know it has been saved)

**Comment by patwapro** [comment]
**thank you sir,
can i do it right, this is my code**

fetchData(state, instance) {
        this.setState({ 
          loading: true,
          draw:state **// here i am set state**
         });
        this.requestData(
          state.pageSize,
          state.page,
          state.sorted,
          state.filtered
        ).then(res => {
          this.setState({
            data: res.rows,
            pages: res.pages,
            loading: false
          });
        });
      }

handleChange(date) {
        this.setState({
          startDate: date,
          changedate:date.format('YYYY-MM-DD'),
          loading: true,
        });
        console.log(this.state.draw)
        this.requestData(
          this.state.draw.pageSize,
          this.state.draw.page,
          this.state.draw.sorted,
          this.state.draw.filtered,
          date.format('YYYY-MM-DD')
        ).then(res => {
          this.setState({
            data: res.rows,
            pages: res.pages,
            loading: false
          });
        });
      }

**this is right or want improvement.
Thank you for your help.**

**Comment by tannerlinsley** [comment]
Closing due to issue age. If this issue was a question, please ask it again on https://spectrum.chat/react-table. If you think this issue needs to be reopened or if it should be turned into a pull-request, please check the latest version of React-Table for the issue or feature once more and reopen or create a PR if appropriate. Thanks!
