### ISSUE TITLE
TreeTable blank - Works on codesandbox but not inside my project

### ISSUE THREAD

**Issue by AntoineBenard** [react-tools/react-table#930]
This is a reopen request of issue #891

version info:
react-table 6.8.2
react 16.3.1
react-dom 16.3.1

The same code works on :
https://codesandbox.io/s/6x8kpkxlwr
but not inside my project

Modifying show: false to true in : 
`var extra = {
          columns: columns.map(function (col) {
            var column = col;
            if (rest.pivotBy && rest.pivotBy.includes(col.accessor)) {
              column = {
                accessor: col.accessor,
                width: treeTableIndent + 'px',
                show: true,
                Header: ''
              };
            }
            return column;
          }),
          TrComponent: TrComponent,
          getTrProps: getTrProps
        };`

display the data in my project but the pivotBy column also appear :  
![image](https://user-images.githubusercontent.com/6001360/39313018-39710fe2-4971-11e8-8a81-a66163ccde77.png)

With hot module replacement from Webpack activated, the pivot column is not appearing, but with a page refreshing (F5) the column always reappear.

**Comment by gary-menzel** [comment]
The TreeTable does not support a function-based accessor.  This is why the pivot columns will still be displaying.

**Comment by AntoineBenard** [comment]
Actually the accessor is not function based: 

`{
              accessor: "state"
            },`

**Comment by tannerlinsley** [comment]
Closing due to issue age. If this issue was a question, please ask it again on https://spectrum.chat/react-table. If you think this issue needs to be reopened or if it should be turned into a pull-request, please check the latest version of React-Table for the issue or feature once more and reopen or create a PR if appropriate. Thanks!
