### ISSUE TITLE
React table not getting fetched by google bot/chrome v41

### ISSUE THREAD

**Issue by maddy25** [react-tools/react-table#931]
## What version of React-Table are you using?
"react-table": "^6.7.0-alpha-0"

## What bug are you experiencing, or what feature are you proposing?

I am using react table to build my app. It is displaying fine in latest chrome browser, but fails for chrome v41 and when google bot tries to fetch.

<img width="575" alt="screen shot 2018-04-24 at 8 44 55 pm" src="https://user-images.githubusercontent.com/6854007/39317463-a642f1bc-4949-11e8-8a23-71886b068ce1.png">

<img width="647" alt="screen shot 2018-04-25 at 2 00 21 pm" src="https://user-images.githubusercontent.com/6854007/39317478-ad2f6b36-4949-11e8-92f0-0cb136d50080.png">

So it is more of a question, if react table works in old chrome versions? Also I am using react-scripts, so I was hoping the transpiler works fine.

Here is package.json
{
  "name": "react-table-simple-table",
  "description": null,
  "version": "0.0.0",
  "dependencies": {
    "bootstrap": "^4.1.0",
    "jquery": "^3.3.1",
    "lodash": "^4.17.5",
    "match-sorter": "^2.2.1",
    "popper.js": "^1.14.3",
    "react": "^15.6.2",
    "react-bootstrap": "^0.32.1",
    "react-dom": "^15.6.2",
    "react-icons": "^2.2.7",
    "react-responsive-modal": "^2.0.3",
    "react-table": "^6.7.0-alpha-0"
  },
  "devDependencies": {
    "babel-cli": "^6.26.0",
    "babel-preset-react-app": "^3.1.1",
    "react-scripts": "^1.1.4"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
  }
}

**Comment by gary-menzel** [comment]
This is probably more a question for @tannerlinsley.

You might need a polyfill for the `find` method.

But you should also update to 6.7.6 - which is probably the most recent stable version.

**Comment by gary-menzel** [comment]
I went and looked this up.  Chrome only added support for `find` in V 45 + (and even then only basic support).  So, to work on Chrome 41 it would need every instance of the `Array.find` method to be changed to something else or you need to add some type of polyfill to get it working.

Here's a polyfill site (which also shows that before 45 - well 46 - that Chrome did not support it natively).  However, the polyfill javascript library does.

https://polyfill.io/v2/docs/features/#Array_prototype_find

**Comment by maddy25** [comment]
Thanks Gary. I had added https://cdn.polyfill.io/v2/polyfill.min.js  before in the app but it didn't work. 
May be this didn't have polyfill for find? I need to check.

**Comment by maddy25** [comment]
<script src="https://cdn.polyfill.io/v2/polyfill.js?features=es6"></script> this worked!
Googlebot is now able to fetch and render. I did not test in chrome41 but I think it should work. This was my goal. 
I tested in chrome 41 because googlebot uses chrome version 41.

Thank you for pointing me to the documentation! I thought I had added the polyfill required but it required features = es6 to add all es6 features.

**Comment by tannerlinsley** [comment]
Closing due to issue age. If this issue was a question, please ask it again on https://spectrum.chat/react-table. If you think this issue needs to be reopened or if it should be turned into a pull-request, please check the latest version of React-Table for the issue or feature once more and reopen or create a PR if appropriate. Thanks!
