### ISSUE TITLE
Initial Filtered State in Manual Mode?

### ISSUE THREAD

**Issue by ma-matterhorn** [react-tools/react-table#933]
## What version of React-Table are you using?
6.6.0

## What bug are you experiencing, or what feature are you proposing?
Is there a way to have the table initial render with a set of filtered key/values when in manual mode?  Calling setState on the component with *filtered* keys seems to cause some issues (maybe, perhaps because it then it in turn calls the onFetchData callback and maybe something isn't copacetic there).  Wondering if it's possible to set the filtered state on init but *not* have it call fetchData until after the user interacts with the component. 

Example: I have a query string parameter in the URL bar -- which in turn maps to a set of filters which I pass as props down to the table.  Once the user interacts with the table's filtering, it becomes the source of truth or it emits an action to keep it synced in a redux store.

**Comment by gary-menzel** [comment]
Please provide a codesandbox.io example of the problem you are experiencing. It should be possible to set the `filtered` parameter but maybe your implementation is causing an infinite loop.

**Comment by ma-matterhorn** [comment]
@gary-menzel I can try and put together a code pen -- but I think my only issue is that I can't disable the onFetchData from firing until a user physically interacts with the table.  If this was an option my issues would be resolved 100%.  Do you know if there is a way currently with the code for this to happen, or would this be a feature request?

**Comment by learningassistant** [comment]
Believe i have the exact same issue, setting 'filtered' with a default array causes onFetchData to go into an infinite loop - https://pastebin.com/Q8g77ybJ

**Comment by tannerlinsley** [comment]
Closing due to issue age. If this issue was a question, please ask it again on https://spectrum.chat/react-table. If you think this issue needs to be reopened or if it should be turned into a pull-request, please check the latest version of React-Table for the issue or feature once more and reopen or create a PR if appropriate. Thanks!

**Comment by AbhaysinghBhosale** [comment]
You keep your filter stored in state and pass that on each re-render as follows

take a initial state
filtered: [],

pass this as a props to table
filtered={this.state.filtered}

add onChange event to table
onFilteredChange = {filtered => {this.setState({ filtered });}}

So now once you filter anything it will be set to filtered state and then passed to table

**Comment by bryanstrader** [comment]
> Believe i have the exact same issue, setting 'filtered' with a default array causes onFetchData to go into an infinite loop - https://pastebin.com/Q8g77ybJ

Having this same exact issue, table uses manual mode, onFetchData continues to fire in infinite loop when I try to set the filtered prop of the table...any advice is appreciated! Thank you!
