### ISSUE TITLE
React 16.3 doesn't like componentWillMount lifecycle hook

### ISSUE THREAD

**Issue by IceSentry** [react-tools/react-table#934]
## What version of React-Table are you using?

6.8.2

## What bug are you experiencing, or what feature are you proposing?

I am using React 16.3 and they are going to deprecate the componentWillMount lifecycle hook in favor of either UNSAFE_componentWillMount or the new lifecycle methods. This creates arrors in the console saying to stop using componentWillMount, but I'm not using it outside of this library.

## What are the steps to reproduce the issue?

1.  make a basic app wih react 16.3 and react-table
2.  look at the console errors

more info here:
https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html

**Comment by gary-menzel** [comment]
We are aware of the changes and there are no current plans to retro fit the existing version.  @tannerlinsley is looking at a full refactor of ReactTable and it will happen during that process.

**Comment by tannerlinsley** [comment]
Closing due to issue age. If this issue was a question, please ask it again on https://spectrum.chat/react-table. If you think this issue needs to be reopened or if it should be turned into a pull-request, please check the latest version of React-Table for the issue or feature once more and reopen or create a PR if appropriate. Thanks!

**Comment by ashnur** [comment]
https://fb.me/react-strict-mode-warnings

**Comment by tannerlinsley** [comment]
React Table doesn't use classes or lifecycles anymore. If you're using an older version that does, then you'll need to either upgrade or fork and fix

**Comment by tm1000** [comment]
@tannerlinsley do you mean 7.0 (which is in alpha) doesn't use lifecycles? Because 6.10 definitely uses lifecycles.

**Comment by ashnur** [comment]
https://github.com/tannerlinsley/react-table/blob/v6/src/lifecycle.js

**Comment by tannerlinsley** [comment]
Correct. V6 is EOL

**Comment by tm1000** [comment]
Thanks @tannerlinsley! :-)
