### ISSUE TITLE
server side filtering using mysql join problem

### ISSUE THREAD

**Issue by midnightcodr** [react-tools/react-table#936]
Hi, I am running into an issue with server-side filtering using mysql (with joins). Take the following scenario for example,
I have two related tables:

```
employee {
    id,
    name,
    departmentId
}

department {
    id,
    name
}
```

Query:
```select e.employeeId, e.name, d.name as departmentName from employee e left join department d on (d.id = e.departmentId) ...```

```
const columns = [
    {
        Header: 'Employee Name',
        accessor: 'name'
    },
    {
        Header: 'Department Name',
        accessor: 'departmentName'
    },
    ...
]
```
Displaying the data is not an issue, however it's impossible to filter by `departmentName` (due to the fact that column alias doesn't work in mysql where condition, changing to `d.name` won't work either because the dot has a special meaning in react-table). I would propose adding an additional attribute to Column definition so it would become 
```
    {
        Header: 'Department Name',
        accessor: 'departmentName',
        filterAccessor: 'd.name'
    }
```

by default `filterAccessor` is the same as `accessor` and it can be overwritten when necessary, and it instead of `accessor` will be used in `filtered` array.

Edit: I should point out changing the column name in `department` table is NOT possible due to the fact that it's already being used by many internal programs.

**Comment by gary-menzel** [comment]
This is not a ReactTable issue.  The developer is responsible for translating from the front-end to back-end.  When you are supplied the `filter` information in the `onFetchData` you can translate it before calling your back end.

ReactTable is deliberately light weight - if we keep adding all the small specific implementation request it will become bloated.

**Comment by midnightcodr** [comment]
Makes sense. Will try it out. Thanks @gary-menzel!

**Comment by tannerlinsley** [comment]
Closing due to issue age. If this issue was a question, please ask it again on https://spectrum.chat/react-table. If you think this issue needs to be reopened or if it should be turned into a pull-request, please check the latest version of React-Table for the issue or feature once more and reopen or create a PR if appropriate. Thanks!
