### ISSUE TITLE
Style table cells without a custom component?

### ISSUE THREAD

**Issue by SelaO** [react-tools/react-table#942]
Is there a way to style cells without making a special component for them?

For example: these are not centered in the cell, and I want to center them. 
![image](https://user-images.githubusercontent.com/21977571/39526180-acc62fcc-4e26-11e8-92ae-27a879ebdbfa.png)

And that's how they look in the column object: 

        columns={[
          {
            Header: 'Customer Name',
            accessor: 'name',
          }]

**Comment by gary-menzel** [comment]
Did you check the documentation for the `style` and `className` props for columns ?

**Comment by SelaO** [comment]
There's very little mention of styling in the docs and I don't see an example on how to use it, just that it's there. 

![image](https://user-images.githubusercontent.com/21977571/39531092-1885caa4-4e33-11e8-9fd1-798fc13600ac.png)

And it doesn't work if I add my css selector to the table: ` className="foo"`.

**Comment by gary-menzel** [comment]
You asked about styling columns.... I said it was in the doco on the props for columns......
```
columns: [{
  Header: 'etc...',
  style: { /* normal javascript type of style object */ },
  className: 'your-class-name-here',
}];
```
Search the doco for 'style'....
```
    // Cells only
    className: '',
    style: {},
```

**Comment by SelaO** [comment]
It doesn't work exactly like it should, for example if I add: `className: 'foo',`

```
.foo{
    display: flex;
    align-items: center;
    height: 100%;
}
```

Doesn't behave like:

```
  makeRoutesNumberCell(row) {
    const { routes } = row.original;
    return (
      <div className="foo">
        <span>
          {routes}
        </span>
      </div>
    )
  }
```

The first one doesn't center the contents in the cell.

**Comment by gary-menzel** [comment]
That is because the style is applied to the container - if you want to do what you have shown above then you have to have a `Cell` renderer.

You have to understand that ReactTable uses `flex` itself to style the cells - so your flex parameters are going to be overridden by those required by ReactTable.  The rows and cells are already a flex grid with specific settings.
