### ISSUE TITLE
default sort method mixes zeroes and nulls/undefineds (and doesn't match doco)

### ISSUE THREAD

**Issue by bobisageek** [react-tools/react-table#948]
## What version of React-Table are you using?
6.8.1

## What bug are you experiencing, or what feature are you proposing?

Disclaimer: I don't write a lot of JS, so this might all be totally wrong...

defaultSortMethod forces null and undefined to the empty string, which is neither greater than nor less than 0, so when trying to sort a numeric field, nulls are not differentiated from zeroes. This is different than indicated in the readme, which says that defaultSortMethod forces nulls and undefineds to -Infinity.

https://codesandbox.io/s/ly98145xkl: sort this list by age, and the blanks and zeroes do not sort separately.

Using -Infinity would (I think) move the problem to strings, e.g. strings won't be greater than or less than -Infinity. Perhaps a way to address this for arbitrary types would be some guards in the sort... something along the lines of:
if a is null/undefined && b is null/undefined return 0
if a is null/undefined return -1
if b is null/undefined return 1

## What are the steps to reproduce the issue?

1.  sort a table on a column with zeroes and nulls - expected outcome: nulls are separated from zeroes; actual outcome: nulls are mixed in with zeroes (dependent on subsequent sorts/index)

**Comment by gary-menzel** [comment]
You can replace the default sort method if it does not meet your needs.

**Comment by bobisageek** [comment]
That's what I ended up doing - I just wanted to bring it up in case there was a desire to make defaultSortMethod do what I imagine would be the generally expected behavior in more circumstances.

**Comment by CWSites** [comment]
@bobisageek can you share how you got around this?

**Comment by bobisageek** [comment]
@CWSites I just overrode the default sort method on that column to sort the way that made sense for my values

**Comment by CWSites** [comment]
Can you share @bobisageek?

**Comment by bobisageek** [comment]
I'm not sure what you're asking for... if you just want the sort method I used, I took the one that's in the documentation and changed the null/undefined ternary to return -Infinity instead of a blank space:
```js
{
    // force null and undefined to the bottom
    a = a === null || a === undefined ? -Infinity : a
    b = b === null || b === undefined ? -Infinity : b
    // force any string values to lowercase
    a = typeof a === 'string' ? a.toLowerCase() : a
    b = typeof b === 'string' ? b.toLowerCase() : b
    // Return either 1 or -1 to indicate a sort priority
    if (a > b) {
      return 1
    }
    if (a < b) {
      return -1
    }
    // returning 0, undefined or any falsey value will use subsequent sorts or
    // the index as a tiebreaker
    return 0
  }
```

If you're looking for the extra guards around null/undefined, I didn't actually sit down and write it. My specific situation only had the null/undefined issue on numeric values, and I don't write a lot of JS, so I didn't put the time in to try and solve a problem I didn't have.
