### ISSUE TITLE
getThProps  doens't return any values... 

### ISSUE THREAD

**Issue by gadi246** [react-tools/react-table#951]
## What version of React-Table are you using?

Your bug may already be fixed in the latest release. Run `yarn upgrade react-table`!
Place your version here...

## What bug are you experiencing, or what feature are you proposing?

Please include a detailed explanation here...

## Use https://codesandbox.io/s/X6npLXPRW (by clicking the "Fork" button) to reproduce the issue.

Then paste a link to your newly forked codesandbox here...

## What are the steps to reproduce the issue?

1.  list the steps
2.  to reproduce
3.  the issue

**Comment by tannerlinsley** [comment]
Closing due to issue age. If you think this issue needs to be reopened, please check the latest version of React-Table for the issue once more and reopen if appropriate. Thanks!
