### ISSUE TITLE
doesn't work with node 10

### ISSUE THREAD

**Issue by maikelmclauflin** [react-tools/react-table#952]
## What version of React-Table are you using?

Your bug may already be fixed in the latest release. Run `yarn upgrade react-table`!
latest

## What bug are you experiencing, or what feature are you proposing?

increase the node range in the package.json

## Use https://codesandbox.io/s/X6npLXPRW (by clicking the "Fork" button) to reproduce the issue.

Then paste a link to your newly forked codesandbox here...

## What are the steps to reproduce the issue?

install the package with node 10+

**Comment by tannerlinsley** [comment]
Closing due to issue age. If you think this issue needs to be reopened, please check the latest version of React-Table for the issue once more and reopen if appropriate. Thanks!
