### ISSUE TITLE
Make row selection field editable

### ISSUE THREAD

**Issue by dbMundada** [react-tools/react-table#953]
## What version of React-Table are you using?
v6.7.4

## What bug are you experiencing, or what feature are you proposing?

Related to the Pagination row-selection component 
- Can we make the row selection component editable.
- As we are not auto detecting the height & adjusting the number of rows this necessarily needed for our component. (https://github.com/react-tools/react-table/issues/921)

**Comment by tannerlinsley** [comment]
Closing due to issue age. If you think this issue needs to be reopened, please check the latest version of React-Table for the issue once more and reopen if appropriate. Thanks!
