### ISSUE TITLE
dynamic sort order

### ISSUE THREAD

**Issue by jackbarantee** [react-tools/react-table#959]
We are using react table and table has 5 column(id,name,age,add1,add2)(index.js). by default we set sort order on id column and id column has link that route to new page(id.js).  But when we get back from route page(id.js) to home page(index.js) sort order change back to default sort defined . however we want to keep the last sorted order selected when we get back to index,js from id.js.  I tried saving state as shown in controlled property but it does not work. Is there any solution that helps.

**Comment by gary-menzel** [comment]
Not really - if you want to maintain the state of ReactTable (or mostly any component) after navigating away from the page it is defined on) you have to save that state in a global store (e.g. Redux, MobX, LocalStorage, SessionStorage - or a back end database) and load it again when the component is re-rendered on the page.

**Comment by ivanisko** [comment]
Hello Gary,
I saved sort state in localStorage, then in componentDidMount I get saved sort, then set saved sort to state and in callback call onFetchData. There I set state.sorted to saved sort and make request to server. 
Data are sorted but table is without graphical sign(black line in header). Can you please help me, where I can make mistake?
Thank you

**Comment by gary-menzel** [comment]
Not without seeing the code on `codesandbox.io` as per the request in the github template here for raising an issue.

**Comment by ivanisko** [comment]
Ok. How I get state of ReactTable and load it again? State of my component doesn't have some variable with ReactTable. 
Thank you for answer

**Comment by tannerlinsley** [comment]
Closing due to issue age. If this issue was a question, please ask it again on https://spectrum.chat/react-table. If you think this issue needs to be reopened or if it should be turned into a pull-request, please check the latest version of React-Table for the issue or feature once more and reopen or create a PR if appropriate. Thanks!
