### ISSUE TITLE
this. checkboxTable is not a property of the component (trying out the selectTable)

### ISSUE THREAD

**Issue by juriwulff** [react-tools/react-table#965]
When trying to implement the selectTable in my React+Typescript project it says `Property 'checkboxTable' does not exist on type 'MyComponentNameHere'.`

In the demo: [select-table](https://react-table.js.org/#/story/select-table-hoc), it says `(property) App.checkboxTable: any` when hovering on the `this.checkboxTable` where the `CheckboxTable` component is rendered.

Have I missed anything?

**Comment by gary-menzel** [comment]
The ReactTable team does not support Typescript. You'll need to discuss that with the team that created the Typescript definitions.

I built the `selectTableHOC` and have no experience with (or knowledge of) Typescript.  It is only supported for ES6 JavaScript.

**Comment by juriwulff** [comment]
Hi @gary-menzel 

Thank you for the quick response and for your contributions to this lib. We have used it in react projects before with great pleasure. 

I just tried the `selectTable` in a clean react project and it works great. I will try to pursuit a fix another place.

**Comment by itavq** [comment]
> Hi @juriwulff
> Could you kindly share your successful remedy for that one? assuming you managed to work with the HOC with typescript.
> 
> Thanks

for the record, check out https://codepen.io/aaronschwartz/pen/WOOPRw.
That's one way to get the checkbox selection functionality while working around the afford mentioned issue.
