### ISSUE TITLE
ReactTable column refresh by selecting with "" dropdown value

### ISSUE THREAD

**Issue by PavelAlexDev** [react-tools/react-table#977]
Hi, everyone.
Please let me know kindly about my issue.
I am using custom dropdown for reacttable filtering.(every colum has own filter method.)
All are working correctly, but not working to show original column list with setting "all" item in select.
I was set as like following.
- colume setting
       {
        Header: translations['cocom'],
        accessor: 'cocom',
        Filter: ({ filter, onChange }) =>
                    <FilterDropdown dropdownData={(value)=> 
                  {onChange({filterValue:value}); console.log(value);}} value={this.state.filterValue}/>
      }
- FilterDorpdown

       renderItems() {
        return this.state.dropdownItems.map(function(data, key){  
            if(data.label == "All"){
                return ( <option key={key} value="">{data.label}</option>) ;
            } else {
                return (<option key={key} value={data.label}>{data.label}</option> );
            }
        })
      }

      handleChange = (e) => {
          const { name, value } = e.target;
          const { selectedDropDownValue } = this.state;
          this.setState({
            selectedDropDownValue: value
          }, () =>{
             this.props.dropdownData(this.state.selectedDropDownValue);
          });
      }

       render() {
          let key = this.props.id || 0;
          return (
            <div>
                 <select name={key} onChange={this.handleChange}>
                      {this.renderItems()}
                 </select>
             </div>
           );
      }
But in this https://react-table.js.org/#/story/custom-filtering, I was setting as like following attached image
http://prntscr.com/jk03y4
Mean's to set filter value with "", then working to show original list.
What is my fault using this?
Hope to get kindly teaching.
Regards.

**Comment by tannerlinsley** [comment]
Closing as part of our long-overdue issue cleanup. If this issue was a question, please ask it again on https://spectrum.chat/react-table. If you think this issue needs to be reopened or if it should be turned into a pull-request, please check the latest version of React-Table for the issue or feature once more and reopen or create a PR if appropriate. Thanks!
