### ISSUE TITLE
Using native html table elements

### ISSUE THREAD

**Issue by igodorogea** [react-tools/react-table#978]
Does that library support the usage of native html elements?
Like:
- `<table />`
- `<thead />`
- `<tbody />`
- `<tfoot />`
- `<tr />`
- `<td />`
- `<th />`

I need it mainly for table's column autowidth support.
I tried to override the above specific components, got the desired markup to be render, but the style is off on first render(after page load, column widths are broken), and it comes to normal after rerender.

![storybook - opera](https://user-images.githubusercontent.com/4079076/40311445-72c66214-5d18-11e8-95bf-c9b3a9efc6d8.jpg)

**Comment by gary-menzel** [comment]
No.  It relies heavily on the non-table nature of `div` elements to control the grid with `flexbox`.

If you require that support you will need to select a different package.
