### ISSUE TITLE
React Table - is not working on IE edge.

### ISSUE THREAD

**Issue by Dhineshtyr** [react-tools/react-table#979]
I'm using "react table" version 6.7.5. It is not supporting for IE edge. 

Im getting error like "**Object doesn't support property or method 'find'**". 

Can anyone help me to resolve this ?

![image](https://user-images.githubusercontent.com/9817854/40424196-7d2cdb48-5eb2-11e8-84c0-e251fc64aa8b.png)

**Comment by gary-menzel** [comment]
You will most likely need a polyfill for the Array object.

**Comment by tannerlinsley** [comment]
Please use a polyfill for older browsers. This is outside the scope of react-table currently. If you think this issue needs to be reopened, please check the latest version of React-Table for the issue once more and reopen if appropriate. Thanks!
