### ISSUE TITLE
Keys from subcomponent tables

### ISSUE THREAD

**Issue by ivanthemeh** [react-tools/react-table#980]
## What version of React-Table are you using?
Latest

## What bug are you experiencing, or what feature are you proposing?

I am trying to access a key in a react table in a subcomponent a couple levels deep and have not been able to, Is this possible to do? What Im trying to accomplish is to be able to filter the data in a table in a subcomponent a couple levels deep by using a main searchbar on the first table. Any help would be appreciated. Thanks!

**Comment by gary-menzel** [comment]
You will need to provide a mocked-up example on codesandbox as per the instructions for submitting an issue.

**Comment by tannerlinsley** [comment]
Closing due to issue age. If you think this issue needs to be reopened, please check the latest version of React-Table for the issue once more and reopen if appropriate. Thanks!
