### ISSUE TITLE
Hide columns header row

### ISSUE THREAD

**Issue by geogikk92** [react-tools/react-table#984]
I have table without header of columns. How to hide empty header div in my table?

![dasda](https://user-images.githubusercontent.com/14110861/40541673-6cf7a90a-6025-11e8-8f61-25dee8632f44.png)

**Comment by tannerlinsley** [comment]
This looks to be a question of implemention. Please repost this question on our support community:

<a href="https://spectrum.chat/react-table">
  <img alt="Join the community on Spectrum" src="https://withspectrum.github.io/badge/badge.svg" />
</a>
