### ISSUE TITLE
Q: Setting default sort column & ordering

### ISSUE THREAD

**Issue by amivag** [react-tools/react-table#987]
I want to present a table, sorted by a specific column, in a specific order (e.g. ASC/DESC). Is this possible, without affecting the input data?

Thanks

**Comment by tannerlinsley** [comment]
This looks to be a question of implemention. Please repost this question on our support community:

<a href="https://spectrum.chat/react-table">
  <img alt="Join the community on Spectrum" src="https://withspectrum.github.io/badge/badge.svg" />
</a>
