### ISSUE TITLE
Is it possible to give a color to a row onClick

### ISSUE THREAD

**Issue by germiya** [react-tools/react-table#990]
## What version of React-Table are you using?

"react-table": "^6.7.6"

## What bug are you experiencing, or what feature are you proposing?

I have a click event on a cell in react -table and onClick of that cell i need to change the color of the entire row.

Thanks,
Germiya

**Comment by tannerlinsley** [comment]
This looks to be a question of implementation (as mentioned in the issue template). Please repost this question on our support community:

<a href="https://spectrum.chat/react-table">
  <img alt="Join the community on Spectrum" src="https://withspectrum.github.io/badge/badge.svg" />
</a>
