### ISSUE TITLE
How to setState inside onHover event

### ISSUE THREAD

**Issue by BharatKalluri** [react-tools/react-table#993]
## What version of React-Table are you using?

Your bug may already be fixed in the latest release. Run `yarn upgrade react-table`!
6.8.4

## What bug are you experiencing, or what feature are you proposing?

It is more of a support question which I am struggling to find an answer. I have a tree table and depending on the value in the table, I am drawing graphs in another component. So, onHover the graph changes. But if I try to setState inside getTdProps , the table gets to its initial state.
How can I prevent that from happening?

### URL

https://codesandbox.io/embed/3rxl3kpkqq?codemirror=1

**Comment by tannerlinsley** [comment]
This looks to be a question of implementation (as mentioned in the issue template). Please repost this question on our support community:

<a href="https://spectrum.chat/react-table">
  <img alt="Join the community on Spectrum" src="https://withspectrum.github.io/badge/badge.svg" />
</a>
