### ISSUE TITLE
Change Pagination Layout

### ISSUE THREAD

**Issue by kunalvirk** [react-tools/react-table#999]
Thanks for the great plugin!!!
I just made my default table with react (previously using jquery DataTable), everything is fine, but i just want to change the pagination template. Please help here as I'm kinda new to react :).....

Thanks in advance....

**Comment by vish0910** [comment]
@kunalvirk : Hi, coincidentally I was looking for the same feature. Try the solution posted here. 
https://github.com/react-tools/react-table/issues/745 . Hope it helps!

**Comment by tannerlinsley** [comment]
This is an implementation question and should be asked on https://spectrum.chat/react-table. Thanks!
